### ISSUE TITLE
顶栏文章标题居中对齐

### ISSUE THREAD

**Issue by aeuicey** [mirai-mamori/Sakurairo#1004]
**这是什么方面的想法？**

UI 界面 

**这个想法具体是要实现什么？**

标题居中对齐，目前测试版本是靠左对齐，不是很美观。

**这个想法实现后有什么帮助？**

帮助主题更加美观

**补充信息：**
![事发图片](https://img.picgo.net/2024/12/01/msedge_dwqopDA1Ez44128ca81e326e0b.png)
![版本信息](https://img.picgo.net/2024/12/01/msedge_ajmTVmBytV8f0e6fcb4b210908.png)

**Comment by mirai-mamori** [comment]
已调整
