### ISSUE TITLE
出现无法进入写文章界面，切换其他主题是好的

### ISSUE THREAD

**Issue by shizhishikongzhijie** [mirai-mamori/Sakurairo#1005]
# **问题出处：**

几天前就出现了无法进入写文章界面，之后的今天直接无法进入后台。
直接在数据库切换主题后，能进入后台，切换会原本的主题，进入后台的异常消失。
但仍然无法写文章。
我看到有其他人提过了类似的问题。
#980 
无法进入写文章的问题是否与无法进入后台的问题有关联呢？
我注意到数据库显示连接被终止，是否与数据库有关系？

# **配置与环境：**

- PHP 版本：8.0.26
- 数据库类型 / 版本：mysql 5.7
- WordPress 版本：6.7.1
- 主题版本：Sakurairo 主题版本 2.7.2 | 内部版本 19.2.0 | 

# **截图：**

## php日志：
![dbc27a13f7bdf55e7bd446e17f1dcfbf](https://github.com/user-attachments/assets/e2d80d3e-9bd7-47ef-8899-f031625acdae)

## 项目日志：
![2b0614315f86d967020c9945289f4440](https://github.com/user-attachments/assets/3f35bf37-74d8-46b9-a140-11653c6df779)
![27e2839fc0c77df8065275069f3759ea](https://github.com/user-attachments/assets/facac2eb-f30e-4474-ba2b-c1882286758e)

## 数据库日志：进入写文章界面
![image](https://github.com/user-attachments/assets/9ee23b70-4fe1-4aa4-8415-e4f0fb81f5e3)

## 浏览器显示
![797f7693547580e8f117bdfe1eb811fd](https://github.com/user-attachments/assets/3ae0b701-12aa-4852-90e0-39c127d6b596)

**Comment by KotoriK** [comment]
日志里有`message: PHP Warning: Undefined array key "dark" in /www/wwwroot/www.shizhishi.cn/wp-content/themes/sakura-3.x/functions.php on line 681"`
看起来是`sakura`的问题？

**Comment by shizhishikongzhijie** [comment]
> 日志里有`message: PHP Warning: Undefined array key "dark" in /www/wwwroot/www.shizhishi.cn/wp-content/themes/sakura-3.x/functions.php on line 681"` 看起来是`sakura`的问题？

这是由于无法进入后台界面，所以我从数据库里更改主题为sakura-3.x（sakura主题原本就有这个问题），这时就能进入后台界面，然后我在后台界面切换主题为Sakurairo。这时，无法进入后台界面的情况消失。

**Comment by mirai-mamori** [comment]
关闭Chatgpt功能即可

**Comment by shizhishikongzhijie** [comment]
> 关闭Chatgpt功能即可

看来确实是这个的问题，早上是好的，晚上又无法进入，关闭ChatGPT功能后可以进了。
可能是ChatGPT 访问地址或秘钥的问题
在更换了新的秘钥和访问地址后，问题消失，可以在开启ChatGPT功能的情况下进入文章发布。

**Comment by zsanjin-p** [comment]
原来是这样
