### ISSUE TITLE
主题中前台背景模糊的功能是不是有点问题？功能开启后GPU占用很高！

### ISSUE THREAD

**Issue by ShowUNow** [mirai-mamori/Sakurairo#1008]
**我的站点**： [我的博客](https://tingyun.top/)

**具体表现**

当页面停留在封面图界面时，GPU占用正常。当页面下滑到含有前台背景模糊的区域时，GPU占用骤增！
![image](https://github.com/user-attachments/assets/a0685219-bff1-47c5-b695-40d1e17c7f34)

**我的本地配置是什么？**

是最新版本的主题。
由于我的笔记本设计比较逆天，不能独显直连。所以对于浏览器的硬件加速只能用核显。
我的CPU是i7-11800H，打开该页面之后，风扇狂转，并伴随着页面滑动、鼠标点击和拖尾特效卡顿。
每次我打开包含背景模糊的页面时，我的CPU：
![photo_2024-12-06_23-04-43](https://github.com/user-attachments/assets/8590d5fb-76ae-4f28-b534-9769e2581079)

**为什么我会觉得是bug？**

感觉只是一个背景模糊的话，不至于系统占用增加这么多吧，而且把背景模糊关掉的话就没事了。

**我希望开发者做些什么？**

可否提供一下关于前台背景模糊功能代码的具体位置？我简单地看了看没找到-.-

**Comment by mirai-mamori** [comment]
u1s1 你加的特效可能比模糊本身更严重
