### ISSUE TITLE
分类查找

### ISSUE THREAD

**Issue by GavinIves** [mirai-mamori/Sakurairo#101]
**具体行为描述：**
没有分类查找 后台虽然有分类标签 但在前台点击分类是无内容

你的问题具体是什么？
是没有这样的设计 还是需要一些设置 希望能请教一下

**尝试：**
我设置了标签和分类 但在前台都无法找到只显示这个分类的内容的方法

**Comment by mirai-mamori** [comment]
请提供截图辅助说明，我暂时没能理解你想说的是什么

**Comment by GavinIves** [comment]
[cid:image001.png@01D68D21.67064670]
这里的开心分类 点击并不会跳转到开心分类 而是404 后台有这个设置吗

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 染川 瞳<mailto:notifications@github.com>
发送时间: 2020年9月17日 18:34
收件人: mirai-mamori/Sakurairo<mailto:Sakurairo@noreply.github.com>
抄送: IVES<mailto:ives852751153@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [mirai-mamori/Sakurairo] 分类查找 (#101)


请提供截图辅助说明，我暂时没能理解你想说的是什么

―
