### ISSUE TITLE
夜间模式封面图片背景对比度问题

### ISSUE THREAD

**Issue by leaphy-dev** [mirai-mamori/Sakurairo#1013]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**
夜间模式
这个问题出在程序的哪一个具体功能？
夜间模式
**实际行为描述：**

触发问题后造成了什么效果及影响？

**预期的行为：**

这个功能应该有怎样的效果和影响？
正常显示图片
**复现步骤：**

怎样才能再次触发这个问题？
关闭前台背景一体化，打开夜间模式。只有夜间模式才有这个问题
**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.3
- 数据库类型 / 版本：mysql8.4
- WordPress 版本：6.7.1
- 主题版本：（Release 标注的版本号）2.7.2
- 
使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）
在edge和via上测试过
**截图（若有）**
![Screenshot_2024-12-10-22-38-28-878_com microsoft emmx](https://github.com/user-attachments/assets/26090f8a-14c5-4531-a575-3a9a9fb7311f)
![Screenshot_2024-12-10-22-38-37-353_com microsoft emmx](https://github.com/user-attachments/assets/f22fde57-4948-4adb-ad0f-f53899ab4bc5)

如图，夜间模式图片对比度明显不同

**补充信息：**

提供尽可能多的相关信息。

**Comment by leaphy-dev** [comment]
补充：在开启前台背景一体化的情况下无此问题

**Comment by nicocatxzc** [comment]
```
body.dark .centerbg {
    background-blend-mode: hard-light;
    background-color: #333333;
}
```
在根目录的css中，自行删掉即可
