### ISSUE TITLE
主题图片等所有视觉资源无法加载

### ISSUE THREAD

**Issue by Deepsea-CN** [mirai-mamori/Sakurairo#1016]
**问题出处：**

全部界面中主题自带的图像，包括仪表盘中主题设置内的各种图标，news，logo

**实际行为描述：**

今天突发，原因未知，所有ui图像和logo无法显示，控制台报错诸如
GET https://s.nmxc.ltd/sakurairo_vision/@2.7/basic/friendlink.jpg net::ERR_CERT_DATE_INVALID
GET https://s.nmxc.ltd/sakurairo_vision/@2.7/options/update_source_iro.webp net::ERR_CERT_DATE_INVALID
        
       

**预期的行为：**

正常工作显示

**复现步骤：**

原因未知怀疑cdn或视觉资源地址失效

**配置与环境：**

略
**截图（若有）**
![image](https://github.com/user-attachments/assets/9579142a-61f4-4011-bd15-7e75d0440eb2)

**补充信息：**

全部视觉资源地址未响应

**Comment by RainMz** [comment]
+1
