### ISSUE TITLE
建议点击图片有放大的功能

### ISSUE THREAD

**Issue by Ubanillx** [mirai-mamori/Sakurairo#1027]
建议点击图片有放大的功能
有些图片虽然清晰度已经很高了，但是因为不能放大导致不管是pc端还是手机端都看不清楚图片中的内容，希望能够改进

**Comment by Deepsea-CN** [comment]
有灯箱功能啊，你可以设置一下，就能点击放大图像了

**Comment by nicocatxzc** [comment]
使用灯箱功能即可，建议使用lightgallery，另外两个貌似有问题
