### ISSUE TITLE
主题不能兼容 WP Editor.md 插件

### ISSUE THREAD

**Issue by smireshang** [mirai-mamori/Sakurairo#103]
启用WP Editor.md（最新版）后，主页会一直处于加载动画的状态。禁用该插件后，主页正常加载。

- PHP 版本：7.2.7
- 数据库类型 / 版本：5.5.60 - MySQL
- Worldpress 版本：5.5.1
- 主题版本：1.20.10
- 使用的插件：WP Editor.md
- 浏览器：Google Chrome 85.0.4183.102

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
此原因是因为本主题前身Sakura主题预置的部分功能产生冲突，上游暂时无兼容的想法，但上游有提供成熟的解决方案，请加群询问。
