### ISSUE TITLE
区块编辑器 / 插件 / 浏览器

### ISSUE THREAD

**Issue by INXEKI** [mirai-mamori/Sakurairo#104]
* 【常见】从别的主题切换到该主题后的文章 / 使用可视化编辑器（区块编辑器）编辑新文章时，对正斜杠符号（/）等符号的识别逻辑混乱，主要体现在如下情况：
    * 【频繁】使用软回车（Shift+Enter）进行文章换行时，不被正确识别。换行不会出现在预览或者实际输出网页，但是在可视化编辑器中，换行却是实际存在的。可能是由于主题对于br的处理逻辑有问题。有趣的是，如果切换到代码编辑器在HTML代码中把br改成错误的/br，主题会自动换行。但是这样会导致再度进入编辑器后，WordPress 报错未能预料的区块。
    * 【常见】在文章中使用较多代码区块，自定义文本区块，诗句区块或Markdown 区块，亦或是连续的单行段落区块与代码区块交错时，会在网页预览和实际输出中出现一大段HTML文本，无法正确识别，或自定义文本区块或诗句区块也被识别成代码，黑底黑字表示，可阅读性大大降低，macOS风格的代码框标题处不显示代码语言。
    * 【偶见】在一些较长篇或区块繁杂的文章中，多页之后会出现文本没有被上色的状态——Github格式应当为黑色字体，但在数页后失效，变成粉色文字。
    * 【偶见】在一些较长篇或区块复杂的文章中，多页之后会出现代码区块显示为自定义文本区块一样的情况。代码仍被高亮显示，但是非macOS样式，为自定义文本区块的黄色背景块。
    * 【偶见】代码区块中的反斜杠符号莫名其妙消失。例如C语言中的 \n 自动变成了 n
* 加载网站时，对某些插件或浏览器兼容性较差。
    * 【偶见】在新设备或从未加载过该插件的设备上第一次加载带有数学公式的LaTeX时，WordPress 插件 LaTeX 转 HTML 部分时候显示为原始 markdown 文本，需要再次刷新才能显示数学公式。
    * 【频繁】使用 iPad Pro 11-inch 中的 Safari 浏览器时，下方前一文章和后一文章并非居中显示，而是左对齐显示。
    * 【频繁】Github风格的文章页面中，进入深色模式标题仍为深色。
    * 【频繁】JetPack 的 预约表单等功能性区块中，确认内容的按钮颜色为黑色，与文字颜色冲突，可阅读性较低。

**配置与环境：**

- PHP 版本：5.6.40
- 数据库类型 / 版本：MySQL 5.5
- WorldPress 版本：5.4.2
- 主题版本：1.20.10
- 使用的插件：Autoptimize，JetPack，LaTeX转HTML，WP super cache
- 浏览器：Safari，Edge，Chrome

**Comment by INXEKI** [comment]
更正发现：
在使用 LaTeX2HTML 时，必须在网页加载后再次刷新才可正常显示公式。
若使用 autoptimize 对 JavaScript 进行全项目优化，则 LaTex2HTML 可正常工作（初次加载网站时便可使用），但整个主题的粉色字体改黑色，GitHub风格样式，macOS风格代码块等全部失效。

**Comment by mirai-mamori** [comment]
1/逻辑混乱问题是上游Sakura遗留下的BUG，已经和上游反馈联系修复。
2.1/主题自带代码高亮插件对其他插件的冲突，暂无最佳解决方案。
2.2/不是Bug，是对 iPad 尺寸的分辨率适配。
2.3/是在暗黑模式适配问题，将在下个版本修复。
2.4/主题不会主动对插件适配，如果有使用率高的插件，将会考虑适配。现阶段你可以自己写入CSS来进行修正。
