### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by INXEKI** [mirai-mamori/Sakurairo#105]
* 建议允许设置主题色强调色，方便 WordPress 自带主题用户转 Sakuraito 主题。
* 建议允许设置仅在文章和起始页启动樱花等特效，在页面中不显示。如果可以设置对某些文章单独关闭则更好。（同样包括 live2D，音乐，页脚毒鸡汤。）
* 建议增加页尾网站已经运行xxx天，这样不需要额外配置主题内容。
* 建议允许设置默认为Github风格，以避免文字在较慢的网络环境中加载时先显示为默认主题的粉色字体再变成黑色。
* （如果上一个不可以）建议将页脚那个漂亮的小樱花从主题颜色中分离出来，不然选择黑色樱花也变成黑色。
* 建议在可视化编辑器中增加列表区块之后的行距。列表区块和新段落区块行距过短，如同软回车换行，整体美观度下降，建议额外再换一行。
* 强烈建议前一文章和后一文章可以设置为子主题内的前一后一文章，而非整个时间戳的前一后一文章。

**Comment by mirai-mamori** [comment]
1/主题色强调色是指？
2/可以考虑在前台添加选项，将根据实际需求考虑是否添加。
3/不考虑添加，每个博客运行时间没有好的方案获取。
4/默认设置不会进行调整，你可以自行在后台切换到Github风格。
5/分离没有意义，不考虑。
6/WordPress 可视化编辑器相关的问题请和 WordPress 团队反馈。
7/将根据实际需求考虑是否添加此设置。
