### ISSUE TITLE
网站的404页面的搜索图标无法加载

### ISSUE THREAD

**Issue by freeflights** [mirai-mamori/Sakurairo#106]
这是哪一方面的问题？你是否知道问题所牵连到的文件以及在文件的哪一行？

404错误页面的搜索图标无法加载

你的问题具体是什么？

404错误页面的搜索图标无法加载，显示为一个框

你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了

没有

- 问题页面：https://www.lalala.zone/hello
- 浏览器：Google Chrome | 86.0.4240.75 (正式版本) （64 位） (cohort: Stable)

![image](https://user-images.githubusercontent.com/58329305/96241280-82fc7a80-0fd4-11eb-8797-a6dc577a836b.png)

提供一个此问题触发的截图或报错信息。若没有，则留空。

![image](https://user-images.githubusercontent.com/58329305/96241371-a7585700-0fd4-11eb-94eb-f6c141037add.png)

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
已修复
