### ISSUE TITLE
Pjax + Hermit-X 与主题 APlayer 设置不兼容

### ISSUE THREAD

**Issue by MakiseVon** [mirai-mamori/Sakurairo#108]
**问题出处：**

Pjax + Hermit-X 与主题中 `cdn/js/lib.js` 的 APlayer 设置不兼容

**实际行为描述：**

开启 Pjax，使用 Hermit-X 在页面插入播放器。
在有播放器的页面切换到其他页面再切换回来，浏览器报错：

lib.js:32 Uncaught TypeError: Cannot read property 'classList' of undefined
    at e.value (lib.js:32)
    at e.value (lib.js:32)
    at lib.js:32

**复现步骤：**

同实际行为描述。

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：MySql 5.6
- WorldPress 版本：5.53
- 主题版本：1.20.11
- 使用的插件：Hermit-X
- 浏览器：Chrome

**截图（若有）**

![1.png](https://i.loli.net/2020/11/06/94ziOFcBuUfWKle.png)

**补充信息：**

应该是 APlayer 遗留问题<在其他平台上使用 Pjax + APlayer 时也有。
删除 `APlayer.min.js` 中 `this.audio.src=""` 这一句可解决。
主题的 `cdn/js/lib.js` 包含了 `APlayer.min.js` 的这部分内容

```javascript
this.container.innerHTML="",this.audio.src="",this.timer.destroy()
```

**Comment by mirai-mamori** [comment]
暂不考虑对第三方插件进行PJAX适配。如果你有好的解决方案，欢迎提交PR给本项目。
