### ISSUE TITLE
【2.0.0】后台主题设置 重做

### ISSUE THREAD

**Issue by mirai-mamori** [mirai-mamori/Sakurairo#109]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**

现有内容的优化 / 新增功能 / UI 界面 / 用户体验

**这个想法具体是要实现什么？**

**这个想法实现后有什么帮助？**

**是否有具体的实现思路？**

**补充信息：**

**Comment by YJ2CS** [comment]
页脚播放器的 音量 选项在增强选项卡。而其余的选项都在前台选项卡。我认为它们应当放在一起，更方便用户寻找。

此外，页脚播放器关闭后，aplayer.js还会被加载。因为它被包含在lib.js

**Comment by yche2990** [comment]
我很喜欢这个主题，这几天都在捣鼓中，对页脚播放器有些建议：

页脚播放器希望能加入可以host自己服务器歌曲的功能和选项，而不仅仅只是调用外部比如网易api。我知道hermit x插件可以实现上传自己的歌曲，但是现在的侧边栏界面无法支持这个功能。
