### ISSUE TITLE
网易云音乐播放器无法打开

### ISSUE THREAD

**Issue by yuanyuannetwork** [mirai-mamori/Sakurairo#11]
首先非常感谢各位能够将这么优秀的主题开源，在使用过程中我发现网易云音乐播放器无法打开，勾选了也不行，不勾选也不行，小部件不显示，希望能够看一下

**Comment by mirai-mamori** [comment]
麻烦说明一下问题的复现过程和使用的主题版本。谢谢！

**Comment by yuanyuannetwork** [comment]
我使用的是1.10版本，在后台主题——》功能——》页脚悬浮播放器无法显示

**Comment by mirai-mamori** [comment]
你好，感谢你的反馈，这边暂时（1.11.0版本）没能复现以下问题：
页脚悬浮播放器无法显示。
请尝试清除缓存，重置主题设置，或者重新安装主题来解决问题。
如果问题依旧存在，可以留下你的网站地址以便进一步解决。
谢谢你的支持！
