### ISSUE TITLE
首页下拉箭头监听滚轮动作

### ISSUE THREAD

**Issue by RJCooLEST** [mirai-mamori/Sakurairo#110]
**这是什么方面的想法？**

这是现有内容的优化

**这个想法具体是要实现什么？**

简单来说，就是在首页的下拉箭头在原有的鼠标左键下拉功能下，增加一个滚轮下滑触发。

**这个想法实现后有什么帮助？**

能够从图片框快速移动到文章页。

**是否有具体的实现思路？**
否

**补充信息：**
本人技术力无法实现···，之前看到过实例，抱着试一试的心情提交了一个建议，希望能收获一些建议。

**Comment by mirai-mamori** [comment]
暂不认为滚轮下滑立刻触发是一个让大多数人能够觉得合理的设置。
