### ISSUE TITLE
视频不会自动停止

### ISSUE THREAD

**Issue by GavinIves** [mirai-mamori/Sakurairo#116]
**问题出处：**

文章里有视频内容 播放后 切换至下一个文章时不会自动停止上一个视频的播放 依然在后台播放 有声音

**Comment by mirai-mamori** [comment]
请具体说明情况，并说明视频内容的使用方式、PJAX相关设置、复现方法。

**Comment by GavinIves** [comment]
视频使用的阿里云oss配合cdn调用的，启用了pjax，我在文章里播放了视频 切换至别的页面例如下一个文章 前进或者后退 之前的视频不会停止 会重新播放 虽然页面已经是新的页面 但是声音依然在播放而且是从头开始的

**Comment by mirai-mamori** [comment]
提供一下网站链接

**Comment by GavinIves** [comment]
https://love.ivesgo.fun/index.php/2019/12/13/2019-12-13-%e5%8d%97%e4%ba%ac/
看一看我的这个页面 视频我设置了自动播放 点击最下面的下一篇文章 视频声音依然在 麻烦了

**Comment by mirai-mamori** [comment]
尝试关闭自动播放视频或者关闭PJAX以解决问题，此问题初步认为是PJAX的兼容性问题。

**Comment by GavinIves** [comment]
尝试过这两种解决方案 均无效

**Comment by mirai-mamori** [comment]
在最新主题（1.20.20）的环境中，在现有的描述情况下无法复现此问题，请更具体的说明你的生产环境配置以便进一步判断，另外建议可以去README中提供的QQ群中需求帮助以更快速的解决你的问题。issue回复可能存在不及时的问题。

**Comment by GavinIves** [comment]
已找到原因 关闭插件Autoptimize 这里面的js优化会让他无法停止
