### ISSUE TITLE
重置密码过程中图标显示不全表格错位、其次登录不上

### ISSUE THREAD

**Issue by samondlee** [mirai-mamori/Sakurairo#12]
浏览器：新edge正式版

问题1：密码重置过程中，出现选项框图标错位，返回页无返回
![dsa](https://user-images.githubusercontent.com/8521327/79193661-aeec4700-7e5d-11ea-8cf7-9e9ec752260b.PNG)
![捕获](https://user-images.githubusercontent.com/8521327/79193685-b4499180-7e5d-11ea-89cc-e4f00ac9d33f.PNG)

问题2：在评论https://asuhe.jp/daily/sakurairo-user-manual/ 文章时如果选择 在评论框处点击登录，则返回文章页时 始终显示未登录，实际是登录成功的；但是如果从https://asuhe.jp/wp-login.php 登录，再返回文章页 会显示成功登录

问题3：当前Sakurairo主题版本是否是1.9.3，是否在wordpress仍然识别sakura版本号，目前 提示最新版本为1.11.0 是否应该更新
![捕获](https://user-images.githubusercontent.com/8521327/79194811-ce846f00-7e5f-11ea-98e5-3fb63c602a12.PNG)

**Comment by mirai-mamori** [comment]
你好，感谢你的反馈。问题在此做出解答：

①密码重置过程中，出现选项框图标错位，返回页无返回。
选择框错位，经过测试，可以复现，请等待修复。返回页是因为原Sakura主题设计的时候就没有进行返回。

②登录问题。
这个问题可以复现，定性为BUG，请等待修复。

③主题版本问题
这是因为1.10.0版本开始，设置不再与Sakura主题共享。
请尝试清除缓存，重置主题设置（推荐），或者重新安装主题来解决问题。
同时，我们也不推荐和Sakura主题共同安装，可能仍有部分资源与Sakura主题有冲突。
如果问题依旧存在，可以留下你的网站地址以便进一步解决。

谢谢你的支持！

**Comment by mirai-mamori** [comment]
你的问题已经在1.11.4中得到部分修复。
