### ISSUE TITLE
左下角播放器使用网易云的歌单时，无论歌单里有多少歌曲，只显示前3首

### ISSUE THREAD

**Issue by Iseason2000** [mirai-mamori/Sakurairo#122]
![image](https://user-images.githubusercontent.com/65019366/103437767-91b70d00-4c66-11eb-98a9-8f9faa43869a.png)
![image](https://user-images.githubusercontent.com/65019366/103437772-9da2cf00-4c66-11eb-8b58-05ba7415c017.png)

**Comment by mirai-mamori** [comment]
收到，下个版本将进行修复
