### ISSUE TITLE
主页文章封面无法显示 API 随机图片

### ISSUE THREAD

**Issue by WindLeaf233** [mirai-mamori/Sakurairo#134]
**问题出处：**

首页的文章区域

**实际行为描述：**

首页的文章封面不显示或显示无法找到 url 的图片，src 指向的是 “http://域名/index.php?rest_route=/sakura/v1/image/feature?453”。

**预期的行为：**

封面应为外部 API 随机图片，src 应指向 “https://api.iro.tw/webp_mb.php”，可以正常加载外部 API 图片。

**复现步骤：**

我设置 iro 主题设置>>主页设置>>文章区域设置>>文章区域装饰特色图片选项 为 “外部API随机图片”，
然后设置 “文章区域装饰特色图片外部API随机图片地址” 为 ”https://api.iro.tw/webp_mb.php“（API），
清除缓存并刷新网页，文章的封面仍然是无法找到 url 的图片

**配置与环境：**

- PHP 版本：7.2
- 数据库类型 / 版本：mysql / 5.7.21
- WorldPress 版本：5.6
- 主题版本：2.0.0.2
- 使用的插件：Akismet反垃圾评论，你好多莉（这两个是自带的）
- 浏览器：Microsoft Edge 88.0.705.53 (官方内部版本) (64 位)

顺带提一下，上面的 WordPress 误写为了 WorldPress...

**截图（若有）**

![1](https://user-images.githubusercontent.com/58383985/106364413-ca332f00-6369-11eb-8da7-d7054c77f7a9.png)
![2](https://user-images.githubusercontent.com/58383985/106364416-d0291000-6369-11eb-8ce7-d14fa2b81988.png)
如图，第一个是封面指向的 src，第二个是 iro 主题设置

**补充信息：**

已经清除过缓存，重启过 http 服务，换过浏览器。

**Comment by mirai-mamori** [comment]
请先尝试更换随机图片API地址

**Comment by WindLeaf233** [comment]
> 请先尝试更换随机图片API地址

更换过好几个了

**Comment by mirai-mamori** [comment]
请提供你的 网站

**Comment by WindLeaf233** [comment]
> 请提供你的 网站

http://l.woc.ink:20001/

**Comment by mirai-mamori** [comment]
请尝试使用正常的网页端口进行配置，目前在我们的测试环境下未能复现此问题

**Comment by WindLeaf233** [comment]
> 请尝试使用正常的网页端口进行配置，目前在我们的测试环境下未能复现此问题

http://47.111.230.116/
重装了一下 WordPress，端口是 80，但是，还是不行...

**Comment by mirai-mamori** [comment]
请使用域名解析你的IP，并且在正确配置了SSL的情况下进行测试，另外请说明你的服务器环境，包括是否使用面板类软件如宝塔等。

**Comment by WindLeaf233** [comment]
已解决，感谢回复

**Comment by lululus** [comment]
> 已解决，感谢回复

请问您是怎么解决的？我也遇到了移动端无法调用图片api的问题
