### ISSUE TITLE
保存错误：function(){return u(n),r.apply(this,arguments)}

### ISSUE THREAD

**Issue by iSteveyang** [mirai-mamori/Sakurairo#136]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码。**

**问题出处：**

这个问题出在程序的哪一个具体功能？

从上一个版本，更新2.01后
设置中调整设置，无法保存
报错显示 `function(){return u(n),r.apply(this,arguments)}`

**实际行为描述：**
进行设置恢复默认后
更改随便一项设置，也报错显示这个提示

触发问题后造成了什么效果及影响？
无法更改设置
**预期的行为：**

这个功能应该有怎样的效果和影响？
正常保存

**复现步骤：**
function(){return u(n),r.apply(this,arguments)}

怎样才能再次触发这个问题？
更改设置并保存

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：mysql
- WordPress 版本：
- 主题版本：（Release 标注的版本号）2.0.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）禁用全部插件问题依旧存在
- 浏览器：（浏览器名称及版本号）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
请不要使用宝塔面板的Nginx防火墙

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: iSteveyang <notifications@github.com>
发送时间: Tuesday, February 2, 2021 9:52:04 AM
收件人: mirai-mamori/Sakurairo <Sakurairo@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [mirai-mamori/Sakurairo] 保存错误：function(){return u(n),r.apply(this,arguments)} (#136)


注意，在报告之前请先确认：你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码。

问题出处：

这个问题出在程序的哪一个具体功能？

从上一个版本，更新2.01后
设置中调整设置，无法保存
报错显示 function(){return u(n),r.apply(this,arguments)}

实际行为描述：
进行设置恢复默认后
更改随便一项设置，也报错显示这个提示

触发问题后造成了什么效果及影响？
无法更改设置
预期的行为：

这个功能应该有怎样的效果和影响？
正常保存

复现步骤：
function(){return u(n),r.apply(this,arguments)}

怎样才能再次触发这个问题？
更改设置并保存

配置与环境：

  *   问题页面：（如果有，请提供一个触发此问题的页面链接）
  *   PHP 版本：7.4
  *   数据库类型 / 版本：mysql
  *   WordPress 版本：
  *   主题版本：（Release 标注的版本号）2.0.1
  *   使用的插件：（所有使用中的的插件，以便判断兼容性问题）禁用全部插件问题依旧存在
  *   浏览器：（浏览器名称及版本号）

截图（若有）

提供一个此问题触发的截图或报错信息。若没有，则留空。

补充信息：

提供尽可能多的相关信息。

―

**Comment by iSteveyang** [comment]
好的，谢谢。
