### ISSUE TITLE
保存失败

### ISSUE THREAD

**Issue by MomentQYC** [mirai-mamori/Sakurairo#138]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**
WordPress
这个问题出在程序的哪一个具体功能？
保存
**实际行为描述：**
保存
触发问题后造成了什么效果及影响？
无法保存
**预期的行为：**
成功保存
这个功能应该有怎样的效果和影响？
见下方
**复现步骤：**
见下方
怎样才能再次触发这个问题？
部分情况下点保存
**配置与环境：**
LNMP
- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.3
- 数据库类型 / 版本：5.7.30
- WordPress 版本：5.6.1
- 主题版本：（Release 标注的版本号）最新版
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）无问题
- 浏览器：（浏览器名称及版本号）Chrome 75

**截图（若有）**
见下方
提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。
![image](https://user-images.githubusercontent.com/62551256/106829704-a2c0c700-66c7-11eb-8031-e9d1195df463.png)

**Comment by mirai-mamori** [comment]
#136 请参考此issue

**Comment by MomentQYC** [comment]
我没有执行该issue的操作 @mirai-mamori
