### ISSUE TITLE
菜单是中文时有时会出现Bug

### ISSUE THREAD

**Issue by IcyFeather233** [mirai-mamori/Sakurairo#139]
**问题出处：**

问题出在菜单上面

**实际行为描述：**

我换成这个主题后，有的分类如果是中文的话，从导航菜单点进分类就会出现404 not found，即有的分类可以正常点进去，有的不行

**预期的行为：**

正常的话点分类应该进入分类的界面，显示该分类的文章

**复现步骤：**

菜单名字为中文有几率触发

ps.  把所有分类名字改成英文之后就没问题了

**Comment by mirai-mamori** [comment]
请提供更多信息
