### ISSUE TITLE
雪花特效bug反馈

### ISSUE THREAD

**Issue by SkipM4** [mirai-mamori/Sakurairo#140]
设置入口: iro主题设置-全局设置-额外设置-特效及动画-飘落特效-雪花 二分之一数量
具体问题: 雪花粒子飘落效果未覆盖页尾及上方区域
预期效果: 应整页都有雪花粒子飘落效果
复现步骤: 安装主题
问题页面: http://0309.lite0.com/
PHP版本: 7.3.4nts
数据库版本: Mysql8.0.12
WordPress版本: 5.6.1
主题版本: 2.0.1.1
未使用插件
浏览器版本: Microsoft Edge 88.0.705.56

**Comment by mirai-mamori** [comment]
后续版本将会更换实现方式
