### ISSUE TITLE
古登堡插件格式错乱

### ISSUE THREAD

**Issue by CircleCrop** [mirai-mamori/Sakurairo#142]
**问题出处：**文章古登堡区块样式错乱

这个问题出在程序的哪一个具体功能？

**实际行为描述：** https://ccrop.xyz/1613061343-678c31e8b371bddc10ee6439d9839e84  格式错乱

触发问题后造成了什么效果及影响？

**预期的行为：** 格式错乱

这个功能应该有怎样的效果和影响？

**复现步骤：**

安装古登堡插件，然后新建文章，加入按钮区块或是以下html代码
<div class="wp-block-buttons is-content-justification-center">
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" style="border-radius:2px;background-color:#ba0c49;color:#fffffa">立即下载</a></div>

<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color" style="border-radius:2px;color:#ba0c49">关于塞万提斯</a></div>
</div>

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：mysql5.6
- WordPress 版本：5.6.1
- 主题版本：（Release 标注的版本号）2.0.1.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
Allow Webp Image

This is a short description of what the plugin does. It's displayed in the WordPress admin area.

1.0.0版本  作者：Top Infosoft  
Autoptimize	
Autoptimize
  
通过优化 CSS, JS, 图像, Google字体等来使您的网站更快。

2.8.1版本  作者：Frank Goossens (futtta)  
Disable "BIG image" Threshold	
Disable "BIG image" Threshold

Disables the "BIG image" threshold added in WordPress 5.3.

1.0版本  作者：Jonathan Desrosiers  
Easy FancyBox	
Easy FancyBox
  
Easily enable the FancyBox jQuery extension on all image, SWF, PDF, YouTube, Dailymotion and Vimeo links. Also supports iFrame and inline content.

1.8.18版本  作者：RavanH  
Elementor	
Elementor
  
The Elementor Website Builder has it all: drag and drop page builder, pixel perfect design, mobile responsive editing, and more. Get started now!

3.1.1版本  作者：Elementor.com  
Gutenberg	
Gutenberg

自1440年开始印刷。这是核心中新区块编辑器的开发插件。

9.9.2版本  作者：Gutenberg 团队  
MailPoet 3 (New)	
MailPoet 3 (New)

Create and send newsletters, post notifications and welcome emails from your WordPress.

3.59.2版本  作者：MailPoet  
MailPoet 3 Premium (New)	
MailPoet 3 Premium (New)

This plugin adds Premium features to the free version of MailPoet and unlocks the limit of 1,000 subscribers. Enjoy!

3.59.0版本  作者：MailPoet  访问插件主页
OSS Upload	
OSS Upload
  
使用阿里云 OSS 作为媒体库附件存储空间，支持原创增强的 OSS 协议包装和全原生图像编辑及衍生功能。

4.8.9版本  作者：Link  
SiteOrigin Widgets Bundle	
SiteOrigin Widgets Bundle
  
A collection of all widgets, neatly bundled into a single plugin. It's also a framework to code your own widgets on top of.

1.17.11版本  作者：SiteOrigin  
WP Statistics	
WP Statistics
  
This plugin gives you the complete information on your website's visitors.

13.0.5版本  作者：VeronaLabs    访问 WordPress.org 页面  评价此插件
WP Super Cache	
WP Super Cache
  
WordPress的快速缓存插件。

1.7.1版本  作者：Automattic  
WP-SynHighlight	
WP-SynHighlight

Source code Syntax highlighting plugin with full GUI support. Please see README.txt and screenshots for more information. I'd love to get feature sugesstions and bug reports to my email. Plugin settings  Support forum

2.4.3版本  作者：Vladislav "FractalizeR" Rastrusny  
WPJAM BASIC	
WPJAM BASIC

WPJAM 常用的函数和接口，屏蔽所有 WordPress 不常用的功能。

5.6.1版本  作者：Denis  
Yoast SEO	
Yoast SEO
获取高级版  常见问题    
第一个真正意义上的 WordPress 全能SEO解决方案！包含了页面内容分析、XML站点地图和更多功能。

15.8版本  作者：Yoast团队  
终极简码	
终极简码
简码    
WordPress的视觉组件的所有集合

5.9.7版本  作者：Vladimir Anokhin  
经典编辑器	
- 浏览器：（浏览器名称及版本号）chrome 88.0.4324.104

**截图（若有）** https://ccrop.xyz/1613061343-678c31e8b371bddc10ee6439d9839e84

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**
原主题Sakura可正常工作。
提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
请提供截图
