### ISSUE TITLE
文章页面“上一篇/下一篇”区域出错

### ISSUE THREAD

**Issue by InternetBugs** [mirai-mamori/Sakurairo#144]
**问题出处：文章页面

这个问题出在程序的哪一个具体功能？

**实际行为描述：丑化页面

触发问题后造成了什么效果及影响？

**预期的行为：不应该显示这段代码

这个功能应该有怎样的效果和影响？

**复现步骤：打开最新的文章，翻到底下的“下一篇/上一篇”区域就能看到

怎样才能再次触发这个问题？

- PHP 版本：8.0
- 数据库类型 / 版本：MySQL 5.6.50
- WordPress 版本：5.6.1
- 主题版本：（Release 标注的版本号）2.0.1.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）https://ae01.alicdn.com/kf/U5c6e9e6e916046f2b905baee48009d0eA.jpg

- 浏览器：（浏览器名称及版本号）via浏览器v4.1.6

截图（若有）：https://ae01.alicdn.com/kf/U4370c42749214375a9933f69756b5def0.jpg

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：切换到php8.0后出现的问题，php7.4时没有的问题，仅限于最新发布的文章，其他文章没有这个问题

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
切换PHP版本到80环境需要重新安装配置WP
