### ISSUE TITLE
视频尺寸大小异常

### ISSUE THREAD

**Issue by guomaimang** [mirai-mamori/Sakurairo#145]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

更换主题前视频尺寸正常，更换sakuraio之后，视频就变成了原尺寸，不能适应页面的宽度要求了。之前在用樱花庄白猫的主题，是没问题的。已经尝试过还原，确定就是主题的问题。

这严重影响了美观和可用性以及体验效果。

下图是异常视频尺寸约束

![image](https://user-images.githubusercontent.com/47519540/107984362-bd1d6d80-7002-11eb-83e9-b31afe8c8131.png)

下图是正常视频尺寸约束

![image](https://user-images.githubusercontent.com/47519540/107984430-e3dba400-7002-11eb-9aa4-61c4e79417be.png)

尝试使用 width = 100% ，但一个一个调很不方便

**Comment by mirai-mamori** [comment]
提供你的网站地址
