### ISSUE TITLE
评论的时区显示异常

### ISSUE THREAD

**Issue by Kchenyuhang** [mirai-mamori/Sakurairo#146]
**问题bug**：评论区显示的评论时间有时候（偶尔）会显示异常，会相差8个小时；尝试在仪表盘中修改时区，但是有时还是会显示异常。
最近一次遇到这个情况是在今天，距离我上次打开博客，测试评论的时间相差近半个月。我的WordPress博客也是刚创建不久。

**Comment by mirai-mamori** [comment]
请使用主题设置中的时区调整功能
