### ISSUE TITLE
多作者头像显示错误

### ISSUE THREAD

**Issue by laoxong** [mirai-mamori/Sakurairo#147]
**问题出处：作者博文界面

这个问题出在程序的哪一个具体功能？

**实际行为描述：多作者头像显示错误,均显示管理员的头像
触发问题后造成了什么效果及影响？

**预期的行为：对应的作者显示对应的头像

这个功能应该有怎样的效果和影响？

**复现步骤：**访问非管理员的作者页面

怎样才能再次触发这个问题？

**配置与环境：**Centos8 + PHP7.4 +MySql +Litespeed

- 问题页面：https://www.moec.top/archives/author/intel2333/  https://www.moec.top/archives/author/laoxong/  
- PHP 版本：7.4
- 数据库类型 / 版本：MySql
- WordPress 版本：5.6.2
- 主题版本：2.0.1.1 
- 使用的插件：
![image](https://user-images.githubusercontent.com/31268830/108794179-4236f280-75c0-11eb-8a0a-0d28108830c7.png)

- 浏览器：Chrome 88.0.4324.182

**截图**
![image](https://user-images.githubusercontent.com/31268830/108795394-60e9b900-75c1-11eb-8a14-ace9dd55cab1.png)
![image](https://user-images.githubusercontent.com/31268830/108793915-9db4b080-75bf-11eb-8945-d7b6c82b08bc.png)

**补充信息：**
头像显示错误,另一个作者的头像显示为管理员的头像,而非作者的头像

**Comment by BambooMC** [comment]
我也是这个问题，建议现在主题常规设置里面把个人头像删了，然后多作者好了，再去footer.php把自带的头像改一下就行了，这样个人头像显示不会出问题，然后其他作者也会显示他自己的头像了

**Comment by laoxong** [comment]
> 我也是这个问题，建议现在主题常规设置里面把个人头像删了，然后多作者好了，再去footer.php把自带的头像改一下就行了，这样个人头像显示不会出问题，然后其他作者也会显示他自己的头像了

嗯嗯,谢谢
