### ISSUE TITLE
问题：错误报告2021/2/27

### ISSUE THREAD

**Issue by 615303619** [mirai-mamori/Sakurairo#149]
**问题出处：**
页面编辑
这个问题出在程序的哪一个具体功能？
页面、文章[与插件的兼容度]
**实际行为描述：**
iro主题似乎并不去Elementor插件相兼容，每次在Elementor中编辑好的文章，发布后在页面中打开就发现格式全乱套了。

**预期的行为：**

应该和Elementor插件兼容，毕竟这个插件使用频率还是蛮高的

**复现步骤：**

用Elementor插件发布页面后，在网站打开

**配置与环境：**

- 问题页面：[https://www.tdogmc.top/index.php/fuwuqijieshao/](https://www.tdogmc.top/index.php/fuwuqijieshao/)
- PHP 版本：7.3.7吧？（不大确定）
- 数据库类型 / 版本：phpMyAdmin3.5.8.2
- WordPress 版本：5.6.1
- 主题版本：2.0.1.1
- 使用的插件：Akismet反垃圾评论、bbPress、**Elementor**、Elementor - Header, Footer & Blocks、Essential Addons for Elementor、Gutenberg、Jetpack 、Pinyin Slugs、Really Simple SSL、Smush、WordPress 导入工具、WP SMTP、WP Statistics、Yoast SEO
- 浏览器：Google Chrome 88.0.4324.150
**截图（若有）**
见上方网页
提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**
其实就是希望作者能够支持Elementor插件

提供尽可能多的相关信息。
![image](https://user-images.githubusercontent.com/71170887/109387649-92ee7880-793d-11eb-9d10-a9ef294f895b.png)
   这是插件的一些设定

![@$ TN@X_V6U%G8A`D(G}QMY](https://user-images.githubusercontent.com/71170887/109388102-009ba400-7940-11eb-966e-0ec0d3cd65f7.png)
这是插件编辑中的格式

**Comment by mirai-mamori** [comment]
暂无适配第三方插件计划
