### ISSUE TITLE
求助function(){return u(n),r.apply(this,arguments)}

### ISSUE THREAD

**Issue by Mtoly** [mirai-mamori/Sakurairo#157]
**大致范围：后台主题设置出现问题

这是哪一方面的问题？你是否知道问题所牵连到的文件以及在文件的哪一行？

**具体行为描述：更新主题后后台主题设置点保存出现function(){return u(n),r.apply(this,arguments)}

你的问题具体是什么？

**尝试：重装主题

你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了

**配置与环境：nginx/centoos

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.3
- 数据库类型 / 版本：Mysql5.6.47
- WordPress 版本：5.7
- 主题版本：2.0.1.1（Release 标注的版本号）
- 使用的插件：无插件（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：Chrome 88.0.4324.182（正式版本） （64 位）（浏览器名称及版本号）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
参考Issue136

**Comment by RenMu-V** [comment]
> **大致范围：后台主题设置出现问题
> 
> 这是什么问题？
> 
> **具体行为描述：更新主题后后台主题设置点保存出现function(){return u(n),r.apply(this,arguments)}
> 
> 你的问题具体是什么？
> 
> **试题：重装主题
> 
> 如果有，你的解决方法和过程失败了吗？
> 
> **配置与环境：nginx/centoos
> 
> * 页：（如果有，请提供问题触发此页的链接）
> * PHP版本：7.3
> * 数据库类型/版本：Mysql5.6.47
> * WordPress版本：5.7
> * 主题版本：2.0.1.1（发布标注的版本号）
> * 使用的插件：无使用中的插件，以便判断所有使用中的问题
> * 浏览器：Chrome 88.0.4324.182（正式版本）（64位）（浏览器名称及版本号）
> 
> **截图（若有）**
> 
> 提供此问题触发的截图或报错信息。如果没有，则留空。
> 
> **补充信息：**
> 
> 提供更多的相关信息。
关闭宝塔的Nginx防火墙实测已解决！调试主题请暂时关闭任何防御机制程序。
