### ISSUE TITLE
页脚播放器报错

### ISSUE THREAD

**Issue by Jony6688** [mirai-mamori/Sakurairo#165]
正确设置音乐播放器后报错
![image](https://user-images.githubusercontent.com/65661177/112741846-9d8f4280-8fbb-11eb-8b97-ad8fcee1ad26.png)

**Comment by KotoriK** [comment]
本主题的音乐播放器使用的是APlayer
这个应该是播放器内部的错误 请提交给Aplayer那边

**Comment by KotoriK** [comment]
固定链接设置为“朴素”时可能会产生这个问题
参见 #156
