### ISSUE TITLE
手机端文章页面回复某一条子评论，点击回复按钮后头像位置错位。

### ISSUE THREAD

**Issue by NyaDoo** [mirai-mamori/Sakurairo#168]
**问题出处：**

2.0.3.5（寻找iro.tw所列博客测试，有同样问题）
https://www.nyadoo.com/2021/04/04/1/

**实际行为描述：**

1、手机端点击某条子评论右侧回复按钮后，头像位置错位，具体见图。
![Screenshot_2021-04-07-16-11-09-169_com android chrome](https://user-images.githubusercontent.com/65238336/113834993-12cdf500-97be-11eb-8972-49306d963f1d.jpg)
![Screenshot_2021-04-07-16-13-05-088_com android chrome](https://user-images.githubusercontent.com/65238336/113835000-1497b880-97be-11eb-9756-88df1eec344f.jpg)

2、有一定概率，在点击某条子评论右侧回复按钮后，会完全刷新页面，重新下滑展开评论后可见取消回复按钮上方有红色文字“正在回复给xxxx”（xxxx为用户昵称）。

**Comment by bymoye** [comment]
已在commit 9cc5a6a 修复
