### ISSUE TITLE
关于移动端访问的一点疑惑

### ISSUE THREAD

**Issue by KyonCN** [mirai-mamori/Sakurairo#17]
貌似在iOS端打不开侧边栏，首页打开直接是文章列表，不是首页头图，右下角的主题切换按钮也没有。
我试了ios的safari和chrome都是这种情况，但是使用桌面端chromeF12调试时移动端都一切功能正常，是啥问题啊，是我没设置对吗，谢谢大佬。

**Comment by mirai-mamori** [comment]
请更加详细的说明你遇到的情况，或者查看【主题设置】-基础-页面顶部提示的帮助渠道，联系到我们。

**Comment by KyonCN** [comment]
> 请更加详细的说明你遇到的情况，或者查看【主题设置】-基础-页面顶部提示的帮助渠道，联系到我们。

好的 我去加群了 谢谢
