### ISSUE TITLE
全天开启深色模式功能

### ISSUE THREAD

**Issue by Mtoly** [mirai-mamori/Sakurairo#176]
**这是什么方面的想法？**

想新增全天开启深色模式功能

**这个想法具体是要实现什么？**
实现全天开启深色模式

**Comment by KotoriK** [comment]
右下角的小工具中有开启深色模式的选项 这个选项是全天可用的

**Comment by Mtoly** [comment]
我的意思是在wp后台设置里调的默认深色模式，一访问网站就是深色模式，不用访问网站时点右下角小工具设置

**Comment by AriharaShirone** [comment]
选项确实是全天可用的，但是刷新页面之后会自动变回白天模式QAQ

**Comment by Mtoly** [comment]
> 选项确实是全天可用的，但是刷新页面之后会自动变回白天模式QAQ
所以我是想要刷新了不变的
我也不知道代码在哪里改

**Comment by Mtoly** [comment]
> 右下角的小工具中有开启深色模式的选项这个选项是全天可用的

我的意思是在wp后台设置里调的替代深色模式，一访问网站就是深色模式，不用访问网站时点右下角小工具设置

**Comment by KotoriK** [comment]
> 选项确实是全天可用的，但是刷新页面之后会自动变回白天模式QAQ

你用的是哪个版本的主题

**Comment by AriharaShirone** [comment]
> > 选项确实是全天可用的，但是刷新页面之后会自动变回白天模式QAQ
> 
> 你用的是哪个版本的主题

2.0.1.1

**Comment by KotoriK** [comment]
> > > 选项确实是全天可用的，但是刷新页面之后会自动变回白天模式QAQ
> > 
> > 
> > 你用的是哪个版本的主题
> 
> 2.0.1.1

这个选项是在cookie中存储的 你有没有允许cookie

**Comment by AriharaShirone** [comment]
> > > > 选项确实是全天可用的，但是刷新页面之后会自动变回白天模式QAQ
> > > 
> > > 
> > > 你用的是哪个版本的主题
> > 
> > 
> > 2.0.1.1
> 
> 这个选项是在cookie中存储的 你有没有允许cookie
我应该允许了所有Cookie
![屏幕截图 2021-04-16 212436](https://user-images.githubusercontent.com/30365341/115030891-2d107d00-9efa-11eb-8354-df9415d43c22.png)

**Comment by KotoriK** [comment]
> > > > > 选项确实是全天可用的，但是刷新页面之后会自动变回白天模式QAQ
> > > > 
> > > > 
> > > > 你用的是哪个版本的主题
> > > 
> > > 
> > > 2.0.1.1
> > 
> > 
> > 这个选项是在cookie中存储的 你有没有允许cookie
> > 我应该允许了所有Cookie
> > ![屏幕截图 2021-04-16 212436](https://user-images.githubusercontent.com/30365341/115030891-2d107d00-9efa-11eb-8354-df9415d43c22.png)
你可以检查一下所有cookie里你的站点的数据 深色模式的设置会在dark那一项里边

重点检查一下过期时间

**Comment by Mtoly** [comment]
> > > > > > 选项确实是全天可用的，但是刷新页面之后会自动变回白天模式QAQ
> > > > > 
> > > > > 
> > > > > 你用的是哪个版本的主题
> > > > 
> > > > 
> > > > 2.0.1.1
> > > 
> > > 
> > > 这个选项是在cookie中存储的你有没有允许cookie
> > > 我应该允许了所有Cookie
> > > ![屏幕截图2021-04-16 212436](https://user-images.githubusercontent.com/30365341/115030891-2d107d00-9efa-11eb-8354-df9415d43c22.png)
> 
> 你可以检查一下所有cookie里你的站点的数据深色模式的设置会在暗那一个里边
> 重点检查一下过期时间

我允许了cookie存储也是那样
