### ISSUE TITLE
文章页面启用特定区块会导致页面显示错误信息

### ISSUE THREAD

**Issue by AriharaShirone** [mirai-mamori/Sakurairo#177]
**问题出处：**

文章的编辑与发布

**实际行为描述：**

在想要发布的文章中启用特色图像和/或表格时，出现错误。（目前仅这两者已知，未能确定添加其他区块造成的影响）将
在页面上将显示：

Warning: strpos(): Empty needle in /[installation_directory]/wordpress/wp-content/themes/Sakurairo/inc/theme_plus.php on line XXX

**预期的行为：**

应当展示页面内容而不应在页面上显示错误或警告信息。

**复现步骤：**

怎样才能再次触发这个问题？

**配置与环境：**

- 问题页面：
- http://shirone.moe/
- http://shirone.moe/2021/04/15/ubuntu-21-04-beta%e6%9d%a5%e5%8a%9b%ef%bc%81/
- PHP 版本：7.3.15
- 数据库类型 / 版本：MariaDB 10.3.22
- WordPress 版本：5.7.1
- 使用的插件：未启用任何插件
- 浏览器：Microsoft Edge 版本 89.0.774.77 

**截图（若有）**

![屏幕截图 2021-04-16 181830](https://user-images.githubusercontent.com/30365341/115010623-35f45500-9ee0-11eb-8169-bb9d2c1c4943.png)

**Comment by KotoriK** [comment]
你用的是哪个版本的主题？

**Comment by AriharaShirone** [comment]
就是2.0.1.1

**Comment by AriharaShirone** [comment]
> 你用的是哪个版本的主题？

是2.0.1.1
我好像忘记写版本了QAQ

**Comment by AriharaShirone** [comment]
> 你用的是哪个版本的主题？

是2.0.1.1
我好像忘记写版本了QAQ

**Comment by KotoriK** [comment]
是使用古腾堡编辑器还是

**Comment by AriharaShirone** [comment]
> 是使用古腾堡编辑器还是

是Wordpress自带的那个，应该是古腾堡吧

**Comment by KotoriK** [comment]
在2.0.1.1版本 古腾堡编辑器内 尝试添加表格、添加特色图像
未能复现错误

**Comment by AriharaShirone** [comment]
> 在2.0.1.1版本 古腾堡编辑器内 尝试添加表格、添加特色图像
> 未能复现错误

如果这样的话可能是我个人其他软件的兼容性问题，我会在尝试更新所有软件后重新测试。

**Comment by AriharaShirone** [comment]
> 在2.0.1.1版本 古腾堡编辑器内 尝试添加表格、添加特色图像
> 未能复现错误

如果可能的话，能否告诉我你使用的数据库等的版本信息以及系统环境？

**Comment by AriharaShirone** [comment]
> 在2.0.1.1版本 古腾堡编辑器内 尝试添加表格、添加特色图像
> 未能复现错误

emm，我认为可能是腾讯服务器部署的Wordpress中一些不兼容的配置导致该问题的发生。我想可以关闭这条issue了。如果重新独自搭建Wordpress环境之后仍然有此问题，我会reopen这条issue。对于造成的不便，敬请包涵。

**Comment by KotoriK** [comment]
> > 在2.0.1.1版本 古腾堡编辑器内 尝试添加表格、添加特色图像
> > 未能复现错误
> 
> 如果可能的话，能否告诉我你使用的数据库等的版本信息以及系统环境？谢谢。

### 环境
PHP 8.0.3
IIS 10
MySQL 8

好的
