### ISSUE TITLE
打字栏特效

### ISSUE THREAD

**Issue by kanxingxin** [mirai-mamori/Sakurairo#179]
**问题出处：封面栏打字特效

**实际行为描述：没有出现这个功能 不管改为什么文字，都显示为疯狂造句中

我在别人网站上打开，别人的可以正常显示 ，浏览器为谷歌浏览器

**Comment by KotoriK** [comment]
请贴一下控制台报错或网站网址

**Comment by kanxingxin** [comment]
http://www.jiuzui.xyz/
报错的
Uncaught ReferenceError: 人生若只如初见 is not defined
    at VM24:1337

**Comment by KotoriK** [comment]
你的主题版本是？

**Comment by kanxingxin** [comment]
正在使用 iro 主题 版本 2.0.1.1 | 主题文档 | 源码地址
重新安装了也没用。

**Comment by KotoriK** [comment]
主题设置“封面签名栏打字特效文本”项有说明：
填写打字特效文本部分，文本外必须使用英文双引号，二句话之间使用英文逗号隔开

请检查。
