### ISSUE TITLE
使用宝塔面板无法保存设置

### ISSUE THREAD

**Issue by weiyongzenqi** [mirai-mamori/Sakurairo#181]
使用宝塔面板部署wordpress装完主题后主题设置无法保存
提示:function(){return u(n),r.apply(this,arguments)}

问题页面：在管理后台iro主题设置
PHP 版本：7.4
数据库类型 / 版本：mysql5.6.50
WordPress 版本：最新版
主题版本：2.0.1.1
使用的插件：Akismet反垃圾评论;Redis Object Cache
浏览器：Microsoft Edge 版本 90.0.818.46 (官方内部版本) (64 位)
![image](https://user-images.githubusercontent.com/67868002/115994819-2d4ffd00-a60b-11eb-814a-afc87451b245.png)

**Comment by mirai-mamori** [comment]
参考issue136
