### ISSUE TITLE
首页封面图无法显示

### ISSUE THREAD

**Issue by baicuya** [mirai-mamori/Sakurairo#182]
封面图无论是本地还是外部API都无法显示，确认外部API没有问题、而且前两天用过mashior的3.9.9版本也是同样的问题
**大致范围：**

这是哪一方面的问题？你是否知道问题所牵连到的文件以及在文件的哪一行？
manifest/gallary

**具体行为描述：**

你的问题具体是什么？
想显示封面图、但是无法显示

**尝试：**

你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了
找群里的用同样主题的朋友登陆后台也没解决、当时用的是mashiro的版本，他推荐的你这款用了还是封面不显示

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）123.57.194.212
阿里云服务器
ubantu系统
nigix
- PHP 版本：7.2.4
- 数据库类型 / 版本：mysql
- WordPress 版本：5.7.1
- 主题版本：（Release 标注的版本号）2.0.1.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）无插件使用
- 浏览器：（浏览器名称及版本号）谷歌浏览器、手机各种浏览器

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。![image](https://user-images.githubusercontent.com/81811911/116003938-fab9fa80-a632-11eb-8471-2e04e15e7558.png)

**补充信息：**

提供尽可能多的相关信息。页面不显示封面图.

**Comment by KotoriK** [comment]
请提供问题发生时的F12控制台的报错截图

**Comment by baicuya** [comment]
> 请提供问题发生时的F12控制台的报错截图
pc断可显示了、但是移动端还是无法显示移动端的api但是在关闭多端显示、移动端可以显示pc端api的图片，开了则移动端什么都不显示

**Comment by KotoriK** [comment]
> > 请提供问题发生时的F12控制台的报错截图
> 
> pc断可显示了、但是移动端还是无法显示移动端的api但是在关闭多端显示、移动端可以显示pc端api的图片，开了则移动端什么都不显示

请开启伪静态，并把“固定链接”调整至“朴素”以外的选项

issue里边搜索应该能看到类似的问题

**Comment by lululus** [comment]
#156
