### ISSUE TITLE
关闭文章评论后会重复显示文章名

### ISSUE THREAD

**Issue by Dracl** [mirai-mamori/Sakurairo#186]
**具体行为描述：**
你的问题具体是什么？
关闭文章评论后会重复显示文章名。

**尝试：**
你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了
在主题所有.php文件搜索过了，没有这个class。

**配置与环境：**
问题页面：dracl.cn
腾讯云服务器
Windows Server 2019
nigix
PHP 版本：7.4
数据库类型 / 版本：mysql
WordPress 版本：5.7.1
主题版本：2.0.1.1
使用的插件：无插件使用
浏览器：谷歌浏览器

**截图**
提供一个此问题触发的截图或报错信息。若没有，则留空。
![Snipaste_2021-05-04_22-01-13](https://user-images.githubusercontent.com/44107571/117016449-4f413200-ad25-11eb-8c19-5080a7c924e0.jpg)
![Snipaste_2021-05-04_22-10-17](https://user-images.githubusercontent.com/44107571/117016767-9af3db80-ad25-11eb-855f-841a7d4a0197.jpg)

**Comment by KotoriK** [comment]
你是指 screen-readedr-text是重复显示吗？
如果你不使用屏幕阅读器的话应该不会受到影响

**Comment by Dracl** [comment]
> 你是指screen-readedr-text是重复显示吗？
> 如果你不使用屏幕阅读器的话应该不会受到影响

是的，重复显示，笨笨群主染川 瞳说这本来不应该重复，叫我来发个issue~
