### ISSUE TITLE
iro设置保存时无法保存

### ISSUE THREAD

**Issue by SECRET-2** [mirai-mamori/Sakurairo#189]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

保存iro主题设置时

**实际行为描述：**

无法保存，会卡在保存页面

**预期的行为：**

无法更改iro主题设置

**复现步骤：**

尝试修改iro主题设置

**配置与环境：**

- 问题页面：https://[网站名称]/wp-admin/admin.php?page=iro_options
- PHP 版本：PHP7.4
- 数据库类型 / 版本：MySQL5.7
- WordPress 版本：Wordpress5.7.1
- 主题版本：2.0.1.1
- 使用的插件：无
- 浏览器：Edge 90.0.818.56（64位）

**截图（若有）**

![sakurairo2](https://user-images.githubusercontent.com/62282935/117821691-6ab8b980-b29e-11eb-96d5-c0fe72e15c57.png)
![sakurairo1](https://user-images.githubusercontent.com/62282935/117821711-6f7d6d80-b29e-11eb-865a-08a624e8257b.png)

**补充信息：**

当我试图修改iro主题设置时，它将返回错误，同时永久停留在正在保存界面，无法保存。

**Comment by KotoriK** [comment]
#136
