### ISSUE TITLE
希望能够关闭“文章区域装饰特色图片”功能;“评论上传图片”功能关闭后仍然有上传入口

### ISSUE THREAD

**Issue by BlueRoseSL** [mirai-mamori/Sakurairo#193]
**大致范围：**

具体使用的问题

**具体行为描述：**

能否关闭“文章区域装饰特色图片”这个功能呢，我希望显示文章的第一张图片，但找不到相应的选项

**尝试：**

已经看过配置iro.tw/guide了，但也没找到方法

**补充信息：**

另外，关于评论上传图片功能，我关闭了选项后，虽然确实无法上传图片了，但上传图标却没有消失，如下
![1](https://user-images.githubusercontent.com/84373235/118611971-ed39ff80-b7ef-11eb-96fa-fcd843cb3ce5.png)
![2](https://user-images.githubusercontent.com/84373235/118612018-f62ad100-b7ef-11eb-89ff-71c5131b41cb.png)
虽然鼠标显示为禁止，但是确实可以弹出上传窗口的，只是上传了也没用，这种情况是不是什么地方出了问题……？

**Comment by KotoriK** [comment]
请确认你使用的主题版本是否是2.0.1.1

**Comment by BlueRoseSL** [comment]
> 请确认你使用的主题版本是否是2.0.1.1

![无标题](https://user-images.githubusercontent.com/84373235/118744895-bc0d0e00-b887-11eb-93ef-f2d28ff343f1.png)

**Comment by KotoriK** [comment]
特色图片这个问题 建议你手动设置文章的特色图像
