### ISSUE TITLE
不知道什么原因，文章封面图片加载不出来

### ISSUE THREAD

**Issue by 503611908** [mirai-mamori/Sakurairo#200]
图片链接打开后显示
{"code":"rest_no_route","message":"\u672a\u627e\u5230\u5339\u914dURL\u548c\u8bf7\u6c42\u65b9\u5f0f\u7684\u8def\u7531\u3002","data":{"status":404}}

**Comment by KotoriK** [comment]
请注明主题版本号、图片链接

**Comment by 503611908** [comment]
主题是最新的2.1，图片是封面随机图片,域名/index.php/wp-json/sakura/v1/image/feature&826

**Comment by KotoriK** [comment]
参见#156
