### ISSUE TITLE
当 Pjax 和 Ajax 加载 同时打开时网站主页文章加载异常的问题

### ISSUE THREAD

**Issue by aquausora** [mirai-mamori/Sakurairo#201]
**问题出处：**

![微信图片_20210521132028](https://user-images.githubusercontent.com/57339353/119086010-62e3dc80-ba37-11eb-998e-dc55d4ff17c6.png)

**实际行为描述：**

![微信图片_20210521132024](https://user-images.githubusercontent.com/57339353/119086022-6b3c1780-ba37-11eb-823a-d6518b3d94d7.png)

当 Pjax 和 Ajax 加载 同时打开时会出现此问题，此时在主页点击 `Previous` 无法正常加载文章封面图。

![微信图片_20210521132703](https://user-images.githubusercontent.com/57339353/119086598-4a27f680-ba38-11eb-8dbd-55752c2b8af3.png)

关闭 Pjax 或在 Pjax 打开的状态下主页文章使用上下页加载则不会出现此问题。

**配置与环境：**

- PHP 版本：7.4
- 数据库类型 / 版本：MySQL 5.6.49
- WordPress 版本：5.7.2
- 主题版本：2.1.0

- 使用的插件：

-![微信图片_20210521132527](https://user-images.githubusercontent.com/57339353/119086402-0503c480-ba38-11eb-8100-b13f77919b88.png)

**Comment by KotoriK** [comment]
问题已修复 感谢你的支持
