### ISSUE TITLE
特定情况下暗色模式显示不完整

### ISSUE THREAD

**Issue by KotoriK** [mirai-mamori/Sakurairo#204]
**问题出处：**

文章页面

**实际行为描述：**

#### 排版设置默认时（sakura.css）

```<h3>```不会跟随深色模式变色。事实上所有标题中只有```<h3>```跟随了sakura.css里边原本设置的颜色#737373

#### 排版设置为Github时

所有标题（指h1-h5）都不会跟随深色模式变色。

**配置与环境：**
- 主题版本：2.1.0.1

查了下相关代码好复杂，等一个有缘人修。

**Comment by mirai-mamori** [comment]
修了
