### ISSUE TITLE
启用2.1主题后后台速度变慢

### ISSUE THREAD

**Issue by BlueRoseSL** [mirai-mamori/Sakurairo#205]
**问题出处：**

优化时出现错误

**实际行为描述：**

网站后台速度很慢，主题中是否使用了谷歌字体？

**复现步骤：**

更新到2.1出现

**截图（若有）**

![无标题](https://user-images.githubusercontent.com/84373235/119213201-07295a00-baf0-11eb-901a-eb8d82e89f0e.png)
其他主题没有报错，是否需要特殊的版本？

**补充信息：**

速度慢可能是编辑器的原因，启用经典编辑器后速度恢复正常，但error仍然存在。

**Comment by KotoriK** [comment]
具体是哪个页面速度很慢？

**Comment by KotoriK** [comment]
数据库报错应当是MySQL版本过低的问题 请报告你正在使用的版本

**Comment by BlueRoseSL** [comment]
> MySQL版本

版本5.6.41-84.1
页面速度主要是文章编辑器，平均两秒才能打开，换成经典编辑器就没问题了。
此外主题升级在继承设定方面也有问题，我没有开启验证码，但升级之后登录需要验证码，我反复查了其他地方都没有问题，最后把主题的验证码选项开启再关闭后才解决问题，不知道其他设置会不会有同样的问题？

**Comment by KotoriK** [comment]
> > MySQL版本
> 
> 
> 
> 版本5.6.41-84.1
> 
> 页面速度主要是文章编辑器，平均两秒才能打开，换成经典编辑器就没问题了。
> 
> 此外主题升级在继承设定方面也有问题，我没有开启验证码，但升级之后登录需要验证码，我反复查了其他地方都没有问题，最后把主题的验证码选项开启再关闭后才解决问题，不知道其他设置会不会有同样的问题？
> 
> 


后台问题一般与主题无关
可以尝试通过插件安装最新版本的古腾堡

**Comment by BlueRoseSL** [comment]
> > > MySQL版本
> > 
> > 
> > 版本5.6.41-84.1
> > 页面速度主要是文章编辑器，平均两秒才能打开，换成经典编辑器就没问题了。
> > 此外主题升级在继承设定方面也有问题，我没有开启验证码，但升级之后登录需要验证码，我反复查了其他地方都没有问题，最后把主题的验证码选项开启再关闭后才解决问题，不知道其他设置会不会有同样的问题？
> 
> 后台问题一般与主题无关
> 可以尝试通过插件安装最新版本的古腾堡

区块编辑器正是卡顿的原因，可能是因为使用了谷歌字体？
报错很确定是主题与MySQL冲突，如果不是MySQL版本的问题那就必定是主题的问题，其他主题不会报错。

**Comment by KotoriK** [comment]
SQL语句报错是因为主题使用了新版本的SQL语句
请升级MySQL
