### ISSUE TITLE
评论B站和贴吧表情点击无效

### ISSUE THREAD

**Issue by Wapriaily** [mirai-mamori/Sakurairo#206]
**问题出处：**

页面评论区域哔哩哔哩表情包

**实际行为描述：**

点击无效

**预期的行为：**

点击后出现表情

**复现步骤：**

更新后一直点击无效

**配置与环境：**

- 问题页面：https://www.wapriaily.com/bug-1/
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL 5.6.50
- WordPress 版本：5.7.2
- 主题版本：Version: 2.1.0
- 使用的插件：Akismet；Jetpack；Login LockDown；tencentcloud-cdn；WP Mail SMTP；WP Statistics；Yoast SEO；健康检查和故障排除；超级缓存
- 浏览器：Google Chrome 90.0.4430.212

**截图（若有）**

![image](https://user-images.githubusercontent.com/52833112/119216912-1e287600-bb09-11eb-903b-d4afae6005e2.png)

**补充信息：**

提供尽可能多的相关信息。

**Comment by Wapriaily** [comment]
> **问题出处：**
> 
> 页面评论区域哔哩哔哩表情包
> 
> **实际行为描述：**
> 
> 点击无效
> 
> **预期的行为：**
> 
> 点击后出现表情
> 
> **复现步骤：**
> 
> 更新后一直点击无效
> 
> **配置与环境：**
> 
> * 问题页面：https://www.wapriaily.com/bug-1/
> * PHP 版本：7.4
> * 数据库类型 / 版本：MySQL 5.6.50
> * WordPress 版本：5.7.2
> * 主题版本：Version: 2.1.0
> * 使用的插件：Akismet；Jetpack；Login LockDown；tencentcloud-cdn；WP Mail SMTP；WP Statistics；Yoast SEO；健康检查和故障排除；超级缓存
> * 浏览器：Google Chrome 90.0.4430.212
> 
> **截图（若有）**
> 
> 提供一个此问题触发的截图或报错信息。若没有，则留空。
> 
> **补充信息：**
> 
> 提供尽可能多的相关信息。

**Comment by Wapriaily** [comment]
![image](https://user-images.githubusercontent.com/52833112/119216869-cb4ebe80-bb08-11eb-9fd3-d24197296e21.png)

**Comment by KotoriK** [comment]
已修复(Sakurairo_Script 65f45d2)
