### ISSUE TITLE
【2.1.0.1移动端】增加 侧边栏居中

### ISSUE THREAD

**Issue by Slmie** [mirai-mamori/Sakurairo#209]
侧边栏不会居中，望加个开关 或 默认就开启
![Screenshot_20210523-130816](https://user-images.githubusercontent.com/54428353/119249495-8b044480-bbcb-11eb-80ef-5b953f8a2192.png)

**Comment by bymoye** [comment]
可修改 style.css下

**Comment by Slmie** [comment]
好的，谢谢
