### ISSUE TITLE
在纪念模式下移动端菜单栏的内容无法正常显示

### ISSUE THREAD

**Issue by aquausora** [mirai-mamori/Sakurairo#212]
**问题出处：**

移动端菜单栏

**实际行为描述：**

![微信图片_20210523202642](https://user-images.githubusercontent.com/57339353/119260444-5f9e4b80-bc05-11eb-9a42-97d749f23999.jpg)

在浅色模式下菜单栏显示为全白

![微信图片_20210523202414](https://user-images.githubusercontent.com/57339353/119260464-7644a280-bc05-11eb-9a71-d12a58541741.jpg)

在深色模式下菜单栏则显示为全灰

**复现步骤：**

将打开主题的纪念模式即可复现。

**配置与环境：**

- 主题版本：2.1.0.1

**Comment by KotoriK** [comment]
请报告浏览器版本

**Comment by bymoye** [comment]
下一版本修复

**Comment by aquausora** [comment]
> 请报告浏览器版本

Chrome 90.0.4430.210 Android
