### ISSUE TITLE
关于追番模版的功能增加

### ISSUE THREAD

**Issue by qingzinai** [mirai-mamori/Sakurairo#215]
现在的追番模版只有显示正在追的番剧,
希望能像b站一样按照想看，正在看，已经看过做成tabs展示的模版,将数据显示全
![E4FE147D2D75047D071BBDAF226B8273](https://user-images.githubusercontent.com/34832141/119749508-ceabc680-bec9-11eb-9fad-5b8f03a14672.jpg)

**Comment by mirai-mamori** [comment]
暂不确定B站接口是否支持，若支持，将考虑添加
