### ISSUE TITLE
字体切换按钮表意不清

### ISSUE THREAD

**Issue by Dracl** [mirai-mamori/Sakurairo#216]
具体行为描述：
你的问题具体是什么？
网页端和移动端字体不一致

尝试：
你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了
似乎摸不着头脑……不知道怎么解决……

配置与环境：
问题页面：dracl.cn
腾讯云服务器
Windows Server 2019
nigix
PHP 版本：7.4
数据库类型 / 版本：mysql
WordPress 版本：5.7.1
主题版本：2.0.1.1
使用的插件：无插件使用
浏览器：谷歌浏览器、移动端也是谷歌浏览器
![XVW~ @MMWKRCSWS(_6J _$X](https://user-images.githubusercontent.com/44107571/119818856-4dcce900-bf22-11eb-9720-39dc5e97f903.png)
字体调用正常

截图
![O_0R3(3_S3PCGLT4T)4 IQR](https://user-images.githubusercontent.com/44107571/119818832-44dc1780-bf22-11eb-9c85-8f397bb7b022.png)
正常情况：A=PingFang SC B=Noto Serif SC

![K7RKX{V(8F}OH@W$XSMXVBD](https://user-images.githubusercontent.com/44107571/119848333-50d5d280-bf3e-11eb-8ba8-0a26aa1ce2e8.png)
移动端错误情况：A=Noto Serif SC B=PingFang SC

补充：
![7VF561D`%JE528U_`9_2PIQ](https://user-images.githubusercontent.com/44107571/119849891-9ba41a00-bf3f-11eb-9ee3-c5efdda0b2c9.jpg)
修改为：A=Noto Sans SC B=Noto Serif SC （谷歌字体库没苹方，其实一直调用的是默认Noto Sans SC）
移动端桌面模式下一切正常……

**Comment by mirai-mamori** [comment]
手机端有个锤子苹方字体

**Comment by KotoriK** [comment]
在本地有苹方字体的手机端与电脑端的Safari测试，上述两种字体在两边的表现没有区别。
然而，测试中发现，点击A按钮、B按钮本应当切换到A、B两种字体，但实际上两个按钮功能相同，都是“在A、B两种字体间切换”


另外谷歌字体API上应该没有苹方...

**Comment by Dracl** [comment]
> 在本地有苹方字体的手机端与电脑端的Safari测试中，上述两种字体在两边的表现没有区别。
> 然而，测试中发现，点击A按钮，B按钮本可以切换到A，B两个字体，但两个两个按钮功能相同，都是“在A，B两个字体间切换”
> 
> 另外谷歌字体API上应该没有苹方...

那……我调用的是默认字体……？不过也误打误发现了个BUG，不亏！
