### ISSUE TITLE
文章页面上下文切换bug

### ISSUE THREAD

**Issue by happy2h** [mirai-mamori/Sakurairo#217]
**问题出处：**

iro主题设置 - 页面设置 - 文章页面设置 - 开启文章页面上下文切换

**实际行为描述：**

只有两篇博客，第二篇博客的上下文切换有问题，如图
![image](https://user-images.githubusercontent.com/29790236/119923748-d8eec300-bfa4-11eb-8581-46e7f7b9b44f.png)

**预期的行为：**

应该不显示下一篇，因为当前博文就是最后一篇。

**复现步骤：**

两篇博客，开启文章页面上下文切换

**配置与环境：**

- 问题页面：https://nickxie.top/index.php/2021/05/27/%e4%bd%bf%e7%94%a8%e9%98%bf%e9%87%8c%e4%ba%91ecs%e6%90%ad%e5%bb%bawordpress/
- PHP 版本：8.0
- 数据库类型 / 版本：mysql 5.6
- WordPress 版本：最新
- 主题版本：最新的
- 使用的插件：
- 
![image](https://user-images.githubusercontent.com/29790236/119923955-4e5a9380-bfa5-11eb-9ea3-4a2572dd52bc.png)

- 浏览器：edge 最新

**Comment by KotoriK** [comment]
已在commit 62677b0修复
