### ISSUE TITLE
希望增加文章内插入音乐的接口

### ISSUE THREAD

**Issue by Dracl** [mirai-mamori/Sakurairo#218]
具体行为描述：
在樱花庄那看到有在文章用Aplayer插入音乐的功能，而主题似乎本身就有Aplayer模块(首页网易云)，何不提供一个接口呢~

尝试：
你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了
我试着用插件来解决这个需求，但是找到了两个，一个是用文章ID来存储歌曲信息……说实话很蠢，会产生大量没用ID，
第二个是由于长期没人维护，导致疯狂报错，樱花庄那也报错了2333，但是第二个是用数据库来存储歌曲信息，聪明多了。

配置与环境：
问题页面：dracl.cn
腾讯云服务器
Windows Server 2019
nigix
PHP 版本：7.4
数据库类型 / 版本：mysql
WordPress 版本：5.7.1
主题版本：2.0.1.1
使用的插件：无插件使用
浏览器：谷歌浏览器

截图：
![Snipaste_2021-05-30_17-00-11](https://user-images.githubusercontent.com/44107571/120098445-94ac2000-c168-11eb-81d1-d1c4102603d8.jpg)
插件调用的效果

**Comment by mirai-mamori** [comment]
快给我去升级主题

**Comment by Dracl** [comment]
> 快给我去升级主题

今晚立刻升级！

**Comment by KotoriK** [comment]
这句话应该是WordPress的内部翻译
也就是说用翻译修改的相关插件就能改了

**Comment by Dracl** [comment]
> 这句话应该是WordPress的内部翻译
> 也就是说用翻译修改的相关插件就能改了

好的感谢~

**Comment by mirai-mamori** [comment]
HermitX，请
