### ISSUE TITLE
关于页尾播放器的问题

### ISSUE THREAD

**Issue by ThreeDada** [mirai-mamori/Sakurairo#224]
大佬，我这边页尾的播放器的设置打开了但是一直不显示，不知道是怎么回事
萌新请大佬赐教~~
wordpress版本：5.7.1
PHP版本：7.4
![屏幕截图 2021-06-01 205451](https://user-images.githubusercontent.com/56024731/120326821-b6013d80-c31b-11eb-95b5-598d80dd1152.png)
![屏幕截图 2021-06-01 210608](https://user-images.githubusercontent.com/56024731/120328463-691e6680-c31d-11eb-8b1b-ef3ba2fe3787.png)

**Comment by ThreeDada** [comment]
> 大佬，我这边页尾的播放器的设置打开了但是一直不显示，不知道是怎么回事
> 萌新请大佬赐教~~
> wordpress版本：5.7.1
> PHP版本：7.4
> ![屏幕截图 2021-06-01 205451](https://user-images.githubusercontent.com/56024731/120326821-b6013d80-c31b-11eb-95b5-598d80dd1152.png)
> ![屏幕截图 2021-06-01 210608](https://user-images.githubusercontent.com/56024731/120328463-691e6680-c31d-11eb-8b1b-ef3ba2fe3787.png)



> 大佬，我这边页尾的播放器的设置打开了但是一直不显示，不知道是怎么回事
> 萌新请大佬赐教~~
> wordpress版本：5.7.1
> PHP版本：7.4
> ![屏幕截图 2021-06-01 205451](https://user-images.githubusercontent.com/56024731/120326821-b6013d80-c31b-11eb-95b5-598d80dd1152.png)
> ![屏幕截图 2021-06-01 210608](https://user-images.githubusercontent.com/56024731/120328463-691e6680-c31d-11eb-8b1b-ef3ba2fe3787.png)

**Comment by KotoriK** [comment]
问题解决了吗
没有的话可以发一下网站地址
