### ISSUE TITLE
希望可以去除文章页面顶部的白边

### ISSUE THREAD

**Issue by smmya** [mirai-mamori/Sakurairo#227]
我的博客首页（maomao.ml），上边的白边无法去除，如果将75px改成0px将会是很好的体验，但是

从f12可知问题在  <div class="blank" style="padding-top: 75px;"></div>

我找遍相关css文件并修改，也无法修复该问题
**具体行为描述：**

你的问题具体是什么？

**尝试：**
寻找相关css

**配置与环境：**

- 问题页面：主页和联系页
- PHP 版本：7.4
- 数据库类型 / 版本：mysql
- WordPress 版本：5.7.2
- 主题版本：（Release 标注的版本号）2.1.1.1
- 使用的插件：Hermit X，古德堡，，ProfilePress，WP Githuber MD
- 浏览器：谷歌

**截图（若有）**
https://ftp.0u0.ltd/2021/06/07/cf7950607114344.png

https://ftp.0u0.ltd/2021/06/07/8eb9b0607114344.png

**补充信息：**

**Comment by smmya** [comment]
今天看了一下，我认为是除了博客页，其他的新建页面都会出现白边的问题，现在我要修改我的博客，所以我将要去掉首页和联系这两个页面，如果你要修复的话应该可以通过新建页面复现问题，或者我提供我这里的备份给你 @KotoriK

**Comment by mirai-mamori** [comment]
下个版本实装
