### ISSUE TITLE
关于该主题的一些问题

### ISSUE THREAD

**Issue by smmya** [mirai-mamori/Sakurairo#229]
我的博客所用编辑器为WP Githuber MD
1：文章的字体颜色过淡，且无可以设置字体颜色的地方，建议将主题颜色默认设置为黑色
2：评论区有报错：Markdown Supported while  Forbidden
不知道是因为什么问题，检查了，检查不出
博客地址：https://maomao.ml

**Comment by bymoye** [comment]
颜色过淡是否考虑是屏幕色准问题..?
要修改颜色可以通过F12开发者工具 查看style 在主题下style.css/sakura.css并在对应的行数进行修改

**Comment by AriharaShirone** [comment]
> 我的博客所用编辑器为WP Githuber MD
> 1：文章的字体颜色过淡，且无可以设置字体颜色的地方，建议将主题颜色默认设置为黑色
> 2：评论区有报错：Markdown Supported while Forbidden
> 不知道是因为什么问题，检查了，检查不出
> 博客地址：https://maomao.ml

那个Markdown supported while </> forbidden是给用户的提示并非错误报告；
另外如果你的屏幕是HDR的，另外如果可能的话请说一下屏幕的色域，我自己的博客在高色域HDR显示器上并没有出现类似问题

**Comment by huang-chip** [comment]
评论区上方的"Markdown supported while </> forbidden", 其实际意思是"当</>被禁止时, 支持markdown"
也就是说, **你在评论区可以用markdown语句写评论, 但是不可以在其中嵌入</>(即HTML语句)**
这个功能真的爱了, 超级奈斯(°∀°)ﾉ
