### ISSUE TITLE
修改字体资源的地址

### ISSUE THREAD

**Issue by smmya** [mirai-mamori/Sakurairo#230]
建议更改为jsdriver，这个资源在主题表现为
https://fonts.loli.net/css?family=Noto+SerifMerriweather|Merriweather+Sans|Source+Code+Pro|Ubuntu:400,700|Noto+Serif+SC

从pagespeed测试可以看到这个资源比较影响博客的打开，加载这个资源花费了1秒以上

**Comment by mirai-mamori** [comment]
你来搞一个？

**Comment by smmya** [comment]
> 你来搞一个？

我也想，可是我不会.jpg

**Comment by mirai-mamori** [comment]
那你出钱买服务器和CDN？

**Comment by smmya** [comment]
> 那你出钱买服务器和CDN？

不能白嫖jsdriver吗

**Comment by mirai-mamori** [comment]
你嫖一个给我看看

**Comment by smmya** [comment]
> 你嫖一个给我看看

那我去爬……
