### ISSUE TITLE
在php8.0下使用登录模板创建页面报错

### ISSUE THREAD

**Issue by kawhicurry** [mirai-mamori/Sakurairo#231]
![issue](https://user-images.githubusercontent.com/68467656/121885182-70466b00-cd46-11eb-80c2-13c042f592a2.jpg)
其他使用环境：
服务器：centos8.3.2011
wordpress：5.7.2
主题版本：2.1.1.1

解决方案：将php版本更换为7.4后可正常使用

**Comment by bymoye** [comment]
可以尝试以下 b058dbb
