### ISSUE TITLE
使用FancyBox灯箱，文章无故刷新

### ISSUE THREAD

**Issue by Dracl** [mirai-mamori/Sakurairo#232]
具体行为描述：
使用FancyBox灯箱的时候，点开图片再返回，网站会刷新或者往上滑动一下

尝试：
你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了
毫无头绪

配置与环境：
腾讯云服务器
Windows Server 2019
nigix
PHP 版本：7.4
数据库类型 / 版本：mysql
WordPress 版本：5.7.1
主题版本：2.1.1.1 
使用的插件：无插件使用
浏览器：谷歌浏览器
问题页面：dracl.cn/3

![IJ%KX)QW{K7BK%FS4XNBPSY](https://user-images.githubusercontent.com/44107571/121935141-b1f10900-cd7a-11eb-98dd-73c731cd846a.png)
使用主题的自定义css

![S~Q8ALUPK ~H0{2RS9`C3{S](https://user-images.githubusercontent.com/44107571/121935179-bc130780-cd7a-11eb-8c23-49e3da19eb18.png)
文章内使用Html模块调用

https://user-images.githubusercontent.com/44107571/121936320-1496d480-cd7c-11eb-98a1-99af304db1ce.mp4

iPad Pro上复现成功

**Comment by Dracl** [comment]
已解决，关闭PJAX局部刷新就不会出现这个问题，但是不知道为什么会冲突

**Comment by Dracl** [comment]
![{10MX}%4%UN X I2H7@%Q6Q](https://user-images.githubusercontent.com/44107571/122652923-11cd2280-d174-11eb-8b29-e6c88af5b1fb.png)
点击旁边的章节，地址栏就会添加一段信息来定位，
但是你这个时候点开FancyBox，再点空白的地方返回，
他会就跳回到刚刚点章节的地方，关闭pjax后不会刷新文章了，
但是还是会跳一段，感觉属于bug了
问题页面：dracl.cn/3

**Comment by bymoye** [comment]
看样子应该是锚点跳转的问题 @KotoriK
