### ISSUE TITLE
页尾设置-页尾一言跨域无法使用问题

### ISSUE THREAD

**Issue by tanmantang** [mirai-mamori/Sakurairo#239]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**  页尾设置-页尾一言

这个问题出在程序的哪一个具体功能？
页尾设置-页尾一言

**实际行为描述：** 
当打开页尾一言后，网站没有出现一言，多次清空缓存刷新也不行，自己手动访问api地址又是可以的

触发问题后造成了什么效果及影响？
一言无法使用

**预期的行为：** 

这个功能应该有怎样的效果和影响？

**复现步骤：** 
打开一言功能刷新页面

怎样才能再次触发这个问题？
打开一言功能刷新页面
**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：（Release 标注的版本号）  2.1.1.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）未使用插件
- 浏览器：（浏览器名称及版本号）

**截图（若有）**
![](https://p.pstatp.com/origin/pgc-image/c606dcd758834f79aa25f2e670583e60)
提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**  应该是跨域的问题，建议更换成一言官方api 试试，或者能在后台设置里面添加一个自定义的地址输入框
感谢大大们

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
近期主题相关CDN被恶意攻击，属于正常情况，正在解决中
