### ISSUE TITLE
关于新增PJAX回调函数设置的想法

### ISSUE THREAD

**Issue by aquausora** [mirai-mamori/Sakurairo#240]
**这是什么方面的想法？**

新增功能

**这个想法具体是要实现什么？**

添加PJAX回调函数设置

**这个想法实现后有什么帮助？**

可以手动添加PJAX回调函数，进而能让一些JS资源自动重载。还可以使诸如利用HermitX之类的插件插入页面中的JS无需刷新页面即可加载。

**是否有具体的实现思路？**

主题JS部分的代码压缩了，找放PJAX回调函数的位置结果实在没找到，如果能在主题设置里PJAX开关那加一个PJAX回调函数设置就好啦。

**Comment by KotoriK** [comment]
下个版本即将增加相关功能 相关api文档也会进行补充
目前有关实现在[Fuukei/Sakurairo_Scripts /src/sakura-app/sakurairo_global.ts](https://github.com/Fuukei/Sakurairo_Scripts/blob/master/src/sakura-app/sakurairo_global.ts)
