### ISSUE TITLE
后台社交网络添加一个显示开关按钮

### ISSUE THREAD

**Issue by tanmantang** [mirai-mamori/Sakurairo#242]
**这是什么方面的想法？**
在后台社交网络处，给添加一个是否显示的按钮或开关，能自定义显示

现象描述：我发现 在社交网络模块下面，只要是填入了链接比如QQ，就会在主页显示出来，但是，我现在不想让QQ显示出来
按照现在的逻辑就要吧链接删除了，这样做，我下次想让他显示出来就又要去重新填入这个链接，就很麻烦

现有内容的优化 / 新增功能 / UI 界面 / 用户体验

**这个想法具体是要实现什么？**
给社交网络主页会出现的图标添加一个开关，能自定义显示

**这个想法实现后有什么帮助？**
能够自定义显示主页社交，而不用删除后台填入的链接

**是否有具体的实现思路？**
能否加入一个开关？

**补充信息：**

**Comment by mirai-mamori** [comment]
不考虑添加，这个麻烦根本谈不上麻烦，反而添加了用户的使用成本
