### ISSUE TITLE
文章短码，[download]下载链接[/download] 自定义显示文字

### ISSUE THREAD

**Issue by tanmantang** [mirai-mamori/Sakurairo#243]
**这是什么方面的想法？**
要是能够将下载链接短码自定义文字就好了，不然像下图那种，有多个下载链接感觉就有点不和谐了

**这个想法具体是要实现什么？**
文章短码，[download]下载链接[/download] 自定义显示文字

**这个想法实现后有什么帮助？**
可以自定义下载按钮的文字

**是否有具体的实现思路？**
不清楚

**补充信息：**
[![RIjlnS.png](https://z3.ax1x.com/2021/07/06/RIjlnS.png)](https://imgtu.com/i/RIjlnS)

**Comment by KotoriK** [comment]
你是想替换掉下载按钮中的文字吗？

**Comment by tanmantang** [comment]
> 你是想替换掉下载按钮中的文字吗？

是的，不知道这个可不可以

**Comment by mirai-mamori** [comment]
如果使用区块编辑器生成的请手动自行修改，如果是第三方插件的话请确保翻译文件正确
