### ISSUE TITLE
翻页重复

### ISSUE THREAD

**Issue by laoxong** [mirai-mamori/Sakurairo#246]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**
主页的翻页

**实际行为描述：**

在第三,四次翻页会重复显示第二页的内容

**预期的行为：**

第三,四次翻页显示相应的内容

**复现步骤：**

点击下一页

**配置与环境：**

- 问题页面：主页
- PHP 版本：7.4.13
- 数据库类型 / 版本：MySQL 5.7.32
- WordPress 版本：
- 主题版本：2.1.2.1
- 使用的插件：
  ![image9c80fd14770821f2.png](https://imgs.2002000.xyz/images/2021/07/12/image9c80fd14770821f2.png)
- 浏览器:Chrome 91.0.4472.124
**截图（若有）**

![K5Q11MN2_UDR6V38cc16b961a39861.png](https://imgs.2002000.xyz/images/2021/07/12/K5Q11MN2_UDR6V38cc16b961a39861.png)
**补充信息：**

提供尽可能多的相关信息。

**Comment by bymoye** [comment]
无法复现

**Comment by laoxong** [comment]
可能是缓存插件的原因

**Comment by laoxong** [comment]
狂点下一页就会导致
![image58ee6423ab629b72.png](https://imgs.2002000.xyz/images/2021/07/29/image58ee6423ab629b72.png)
