### ISSUE TITLE
关于侧边栏的两个小建议

### ISSUE THREAD

**Issue by ytandxx** [mirai-mamori/Sakurairo#249]
1，在浏览内容的时候点击侧边栏吗，滚动条会自动回到顶部而不是停留在浏览的内容上。
2，打开侧边栏的时候能否加上点击旁白部分收起侧边栏，而不是点击顶上的叉号，这在移动端上的体验完全是两码事。
![image](https://user-images.githubusercontent.com/44430201/125943004-026f7ef0-6afb-4cd5-942d-fa82776d6ce5.png)

**Comment by ytandxx** [comment]
还有一个问题就是当背景是图片的时候，刷新时由于封面和主题是分开的，再加上加载时往下移上移的动画，没有content的透明度遮盖会显得很尴尬，如图，这是在加载时截的。如果能用一个大div做背景遮罩（毛玻璃效果），就会好很多。

![image](https://user-images.githubusercontent.com/44430201/125947788-b6bb5f3b-8f42-4a7c-9334-a3dd01fc07d4.png)

**Comment by KotoriK** [comment]
> 还有一个问题就是当背景是图片的时候，刷新时由于封面和主题是分开的，再加上加载时往下移上移的动画，没有content的透明度遮盖会显得很尴尬，如图，这是在加载时截的。如果能用一个大div做背景遮罩（毛玻璃效果），就会好很多。
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/44430201/125947788-b6bb5f3b-8f42-4a7c-9334-a3dd01fc07d4.png)
> 
> 


不同的问题最好不要放在一个issue里边

**Comment by KotoriK** [comment]
移动端侧边栏的问题因为侧边栏的实现方式比较难下手一直在搁置 近期会再想想办法

如果说能帮忙改好就最好了~
