### ISSUE TITLE
封面背景一体化且处于深色模式时打开侧边栏，背景图会变黑

### ISSUE THREAD

**Issue by ytandxx** [mirai-mamori/Sakurairo#251]
封面背景一体化且处于深色模式时打开侧边栏，背景图会变黑

![image](https://user-images.githubusercontent.com/44430201/125963432-e0908d78-4c16-4e81-9e9c-db6674bf9b50.png)

浏览器内核： Chromium 86.0.4240.198  +  IE (Trident 7~11)

**Comment by KotoriK** [comment]
来个网址看看

**Comment by KotoriK** [comment]
与#249 第一条相关

**Comment by ytandxx** [comment]
> 来个网址看看

www.lorre.top
