### ISSUE TITLE
能否在后台添加一个 自定义js代码 的功能

### ISSUE THREAD

**Issue by tanmantang** [mirai-mamori/Sakurairo#252]
**这是什么方面的想法？**
能否在后台添加一个 自定义js代码 的功能
现在后台有自定义css的功能，很方便,也很实用
但是有时候想添加一些自定义的js ,就需要去更改主题文件，要是下一次更新，一下更新了就又要重新去改，感觉有点麻烦

**这个想法具体是要实现什么？**
在后台设置添加一个自定义js代码 的功能

**这个想法实现后有什么帮助？**
可以自定义添加一些js代码

**是否有具体的实现思路？**
无

**补充信息：**

**Comment by KotoriK** [comment]
可以考虑使用页尾信息添加相关代码

**Comment by tanmantang** [comment]
> 可以考虑使用页尾信息添加相关代码

试过了。不行，那个百度统计和CNZZ统计（试过添加到谷歌统计的哪里，不行qaq）还有自己写的一个js 也不行（在footer.php里面可以）

**Comment by tanmantang** [comment]
试过了。不行，那个百度统计和CNZZ统计（试过添加到谷歌统计的哪里，不行qaq）还有自己写的一个js 也不行（在footer.php里面可以）
