### ISSUE TITLE
页尾在线播放器无法加载

### ISSUE THREAD

**Issue by Dep0s1t** [mirai-mamori/Sakurairo#253]
**大致范围：**

页尾在线播放器

**具体行为描述：**

网易云音乐播放器无法显示

**尝试：**

重置设置, 隐私模式打开

**配置与环境：**

- PHP 版本：7.4
- 数据库类型 / 版本：MySQL 5.6.50
- WordPress 版本：5.7.2
- 主题版本：2.1.1.1
- 使用的插件：UpdraftPlus - Backup/Restore, Wenprise Pinyin Slug, WP Force SSL
- 浏览器：Google Chrome 91.0.4472.164

**补充信息：**

页尾一言也无法显示

**Comment by comwasemo** [comment]
网易云web 未登录无法加载[我喜欢]歌曲。

网易云web 未登录只能加载此歌单的10首歌曲。

**Comment by Dep0s1t** [comment]
> 网易云web 未登录无法加载[我喜欢]歌曲。
> 
> 网易云web 未登录只能加载此歌单的10首歌曲。

但是他连一首都加载不出，而且我没法看到播放器。我也没有用我喜欢的歌单。

**Comment by KotoriK** [comment]
目前受api限制 后台设置中要设置网易云cookie
未设置aplayer会直接加载失败并且不会有提示

**Comment by Dep0s1t** [comment]
> 目前受api限制 后台设置中要设置网易云cookie
> 若未设置该项 aplayer会直接加载失败并且不会有直接提示

谢谢，结果我发现机器是海外的大多数音乐都放不了。可以在设置里加下。。。

**Comment by KotoriK** [comment]
> > 目前受api限制 后台设置中要设置网易云cookie
> 
> > 若未设置该项 aplayer会直接加载失败并且不会有直接提示
> 
> 
> 
> 谢谢，结果我发现机器是海外的大多数音乐都放不了。可以在设置里加下。。。

可以提供相关api文档

**Comment by Dep0s1t** [comment]
> > > 目前受api限制 后台设置中要设置网易云cookie
> > 
> > 
> > > 若未设置该项 aplayer会直接加载失败并且不会有直接提示
> > 
> > 
> > 谢谢，结果我发现机器是海外的大多数音乐都放不了。可以在设置里加下。。。
> 
> 可以提供相关api文档

我意思是可以在设置里加下提示海外机器可能无法使用，就像其他的一样。
或者也可以直接在设置里加功能让网易云流量走解锁代理
