### ISSUE TITLE
请问友链模板的格式是什么啊

### ISSUE THREAD

**Issue by whtry** [mirai-mamori/Sakurairo#254]
就是页面模板友链中如何编辑添加示例网站中的那种友链，就是这种
![image](https://user-images.githubusercontent.com/69187424/126773971-5374a6d9-ecce-4bc0-b9bf-4b38bf6a232e.png)

**Comment by beixibaobao** [comment]
友情链接请新建页面之后，再worpress左侧选择链接，添加，模板类型有2款，加油再iro主题设置页面模板里面去找然后选择/更换。
