### ISSUE TITLE
评论文章后出错

### ISSUE THREAD

**Issue by starlighteternal** [mirai-mamori/Sakurairo#258]
大致范围：

页尾的评论
具体行为描述：

评论后提示信息：

Warning: Trying to access array offset on value of type null in /www/wwwroot/wordpress/wp-content/themes/Sakurairo-master/functions.php on line 344

Warning: Trying to access array offset on value of type null in /www/wwwroot/wordpress/wp-content/themes/Sakurairo-master/functions.php on line 344

Warning: Trying to access array offset on value of type null in /www/wwwroot/wordpress/wp-content/themes/Sakurairo-master/functions.php on line 345

Warning: Trying to access array offset on value of type null in /www/wwwroot/wordpress/wp-content/themes/Sakurairo-master/functions.php on line 345

尝试：

重置设置, 禁用插件

配置与环境：

PHP 版本：8.0
数据库类型 / 版本：MySQL 5.6.50
WordPress 版本：5.7.2
主题版本：2.1.1.1
使用的插件：无
浏览器：QQ浏览器

**Comment by mirai-mamori** [comment]
已修复，在下个版本会实装
