### ISSUE TITLE
开启PJAX情况下，当首次进入页面非主页时，首页封面图片不会被加载

### ISSUE THREAD

**Issue by NyaDoo** [mirai-mamori/Sakurairo#260]
**实际行为描述：**

开启PJAX情况下，当首次进入页面非主页时，通过导航菜单进入主页后首页封面图片不会被加载，同时控制台无报错，无web请求生成。

**配置与环境：**

- 问题页面：https://www.nyadoo.com/
- PHP 版本：PHP7.4
- 数据库类型 / 版本：MySQL 8.0
- WordPress 版本：WP5.8
- 主题版本：Release2.1.1.1（Dev2.1.5.0）
- 使用的插件：Akismet反垃圾评论和表单提交、tencentcloud-captcha、tencentcloud-cdn、tencentcloud-cos、经典编辑器
- 浏览器：Edge 92.0.902.55 基于 Chromium 

**截图（若有）**
![image](https://user-images.githubusercontent.com/65238336/127155684-16caa4d3-50af-4683-be6b-57b82b0cb7e6.png)

**Comment by KotoriK** [comment]
Fix Fuukei/Sakurairo_Scripts d182b49a01c762ff6002fa7586f65e4f347cce74
