### ISSUE TITLE
封面与前台背景一体化 能否提供开关设置为仅首页生效

### ISSUE THREAD

**Issue by NyaDoo** [mirai-mamori/Sakurairo#262]
**这是什么方面的想法？**

UI 界面优化

**这个想法具体是要实现什么？**

请问能否实现 封面与前台背景一体化 提供一个开关设置为仅首页生效，其他页面仍然保持为“白色背景”状态。
（或者针对首页和其他页面提供两个不同的透明度设置选项）

**这个想法实现后有什么帮助？**

部分页面或者文章会有插入封面图或者文章中有插入图片。
在这种情况下，插入的图片（包括封面图）与背景图是没有过渡的，故实际效果体验会很差，观感会很突兀。

**Comment by mirai-mamori** [comment]
意义不大

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: NyaDoo ***@***.***>
发送时间: Tuesday, July 27, 2021 9:56:29 PM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mirai-mamori/Sakurairo] 封面与前台背景一体化 能否提供开关设置为仅首页生效 (#262)


这是什么方面的想法？

UI 界面优化

这个想法具体是要实现什么？

请问能否实现 封面与前台背景一体化 提供一个开关设置为仅首页生效，其他页面仍然保持为“白色背景”状态。
（或者针对首页和其他页面提供两个不同的透明度设置选项）

这个想法实现后有什么帮助？

部分页面或者文章会有插入封面图或者文章中有插入图片。
在这种情况下，插入的图片（包括封面图）与背景图是没有过渡的，故实际效果体验会很差，观感会很突兀。

―
