### ISSUE TITLE
针对首页导航栏的自适应优化

### ISSUE THREAD

**Issue by NyaDoo** [mirai-mamori/Sakurairo#263]
**这是什么方面的想法？**

UI 界面

**这个想法具体是要实现什么？**
首页导航栏按照设备（浏览器）宽度自适应调整展现效果。

目前当导航栏内容较长，且页面宽度不够的情况下（例如在900px宽度下浏览：https://www.nyadoo.com/），会出现导航栏跑到下面的情况，观感较差，是否可以进行自适应调整呢？
Spirit大佬博客的效果我感觉就很完美。
（悄咪咪的，如果可以实现导航栏居中（靠左）的位置设置调整就更好了）

**Comment by mirai-mamori** [comment]
将在Next 版本中进行重构

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: NyaDoo ***@***.***>
发送时间: Tuesday, July 27, 2021 10:03:22 PM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mirai-mamori/Sakurairo] 针对首页导航栏的自适应优化 (#263)


这是什么方面的想法？

UI 界面

这个想法具体是要实现什么？
首页导航栏按照设备（浏览器）宽度自适应调整展现效果。

目前当导航栏内容较长，且页面宽度不够的情况下（例如在900px宽度下浏览：https://www.nyadoo.com/），会出现导航栏跑到下面的情况，观感较差，是否可以进行自适应调整呢？<https://www.nyadoo.com/%EF%BC%89%EF%BC%8C%E4%BC%9A%E5%87%BA%E7%8E%B0%E5%AF%BC%E8%88%AA%E6%A0%8F%E8%B7%91%E5%88%B0%E4%B8%8B%E9%9D%A2%E7%9A%84%E6%83%85%E5%86%B5%EF%BC%8C%E8%A7%82%E6%84%9F%E8%BE%83%E5%B7%AE%EF%BC%8C%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E8%BF%9B%E8%A1%8C%E8%87%AA%E9%80%82%E5%BA%94%E8%B0%83%E6%95%B4%E5%91%A2%EF%BC%9F>
Spirit大佬博客的效果我感觉就很完美。
（悄咪咪的，如果可以实现导航栏居中（靠左）的位置设置调整就更好了）

―
