### ISSUE TITLE
开启 封面与前台背景一体化 情况下，前台打开暗黑模式，首页封面图不显示。

### ISSUE THREAD

**Issue by NyaDoo** [mirai-mamori/Sakurairo#264]
** 实际行为描述： **

开启 封面与前台背景一体化 情况下，若在前台打开暗黑模式，则首页封面图不会显示。
检查控制台封面图片有被加载，且在前台关闭暗黑模式后封面图可以马上正常显示。
应该是 封面与前台背景一体化 和 暗黑模式 的样式冲突。
** 配置与环境： **

PHP 版本：PHP7.4
数据库类型 / 版本：MySQL 8.0
WordPress 版本：WP5.8
主题版本：Release2.1.1.1（Dev2.1.5.0）
使用的插件：Akismet反垃圾评论和表单提交、tencentcloud-captcha、tencentcloud-cdn、tencentcloud-cos、经典编辑器
浏览器：Edge 92.0.902.55 基于 Chromium

**Comment by KotoriK** [comment]
这是受深色模式背景透明度控制的 请检查相关选项
