### ISSUE TITLE
Dev2.1.5.0 页尾附加代码JavaScript无法引入

### ISSUE THREAD

**Issue by NyaDoo** [mirai-mamori/Sakurairo#265]
通过页尾附加代码依旧无法正常引入JavaScript。
引入CNZZ统计代码被转义为普通文字并显示如下：
![image](https://user-images.githubusercontent.com/65238336/127183230-a5292fe1-e819-4327-a331-c068700e7364.png)
测试引入今日诗句api，html部分成功引入，但JavaScript部分直接被丢弃了，控制台检查没有加载改js。
![image](https://user-images.githubusercontent.com/65238336/127183494-24c1fbd8-af86-4d93-9d6d-cbc89280c5e5.png)
![image](https://user-images.githubusercontent.com/65238336/127183568-ead093c3-d29b-4a43-8449-446e49abc705.png)

Dev2.1.5.0
WP5.8

**Comment by KotoriK** [comment]
估计是设置框架在保存设置时处理了<script>标签 @mirai-mamori

**Comment by mirai-mamori** [comment]
> 估计是设置框架在保存设置时处理了<script>标签 @mirai-mamori

你得在Footer里面提前加个标签

**Comment by KotoriK** [comment]
Fix a77e16b
