### ISSUE TITLE
百度统计API

### ISSUE THREAD

**Issue by huxinfeng** [mirai-mamori/Sakurairo#273]
> iro内置主题是谷歌统计，但是国内访问谷歌根本登录不上，所以建议设置选项可以搞成百度统计。**
> 百度统计地址：https://tongji.baidu.com/

API接口：

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?a7c13acbe83b16ebb8eba576336a174c";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

**Comment by ddmt0000** [comment]
这个倒没必要主题专门适配，你也可以在footer中引入baidu tongji的js也可以达到同样的目的。

**Comment by KotoriK** [comment]
> 这个倒没必要主题专门适配，你也可以在footer中引入baidu tongji的js也可以达到同样的目的。

主要是Pjax加载页面后，统计那边需要手动更新pageview的问题

确实，到时可以把相关的接口文档开放出来
