### ISSUE TITLE
主题使用之后原页面图片不能自动加载，需要手动更新才显示

### ISSUE THREAD

**Issue by peterxu2002** [mirai-mamori/Sakurairo#281]
**问题出处：**
网页页面显示

**实际行为描述：**

页面图片不能正常加载，只有刷新浏览器才可以加载图片，代码部分显示正常。

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**

怎样才能再次触发这个问题？

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：
- 数据库类型 / 版本：
- WordPress 版本：7.8
- 主题版本：（Release 标注的版本号）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**
[image](https://user-images.githubusercontent.com/84840224/129014680-0c79f69f-fa51-452e-af10-3bff47083c53.png)

 #@
提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
说明版本号和服务器环境
