### ISSUE TITLE
文章评论显示顺序改为最新评论在前

### ISSUE THREAD

**Issue by AnimatorBullet** [mirai-mamori/Sakurairo#283]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**

现有内容的优化

**这个想法具体是要实现什么？**

评论倒序，新评论显示在前面
**这个想法实现后有什么帮助？**

浏览起来方便
**是否有具体的实现思路？**

无
**补充信息：**

**Comment by AnimatorBullet** [comment]
网页相关0基础。单纯使用者角度...

**Comment by mirai-mamori** [comment]
之后版本将考虑加入切换评论展示相关功能

**Comment by mirai-mamori** [comment]
还有你网站封面随机图炸了

**Comment by AnimatorBullet** [comment]
> 还有你网站封面随机图炸了

确实，不过我按正常的设置返回404,之前Sakura显示正常...回家了再试试。感谢~

**Comment by AnimatorBullet** [comment]
> 还有你网站封面随机图炸了

{"code":"rest_no_route","message":"\u672a\u627e\u5230\u5339\u914dURL\u548c\u8bf7\u6c42\u65b9\u5f0f\u7684\u8def\u7531\u3002","data":{"status":404}}

**Comment by AnimatorBullet** [comment]
我知道了，重新用这个主题的文件生成一下试试~谢谢提醒

**Comment by AnimatorBullet** [comment]
https://cdn.jsdelivr.net/gh/AnimatorBullet/Blog-cdn2@main/
重新建了个仓库，直接进能进，填的时候也没加最后的 / 
但是还是前面的一串报错

**Comment by mirai-mamori** [comment]
建议使用外部API的方式（创建一个子域名，在网站服务器下新建一个API）进行展示，本主题对本地相关的随机图进行了改进，可能不适用旧有方案。

**Comment by AnimatorBullet** [comment]
> 建议使用外部API的方式（创建一个子域名，在网站服务器下新建一个API）进行展示，本主题对本地相关的随机图进行了改进，可能不适用旧有方案。

好的，我去搜下教程，谢谢

**Comment by AnimatorBullet** [comment]
> 建议使用外部API的方式（创建一个子域名，在网站服务器下新建一个API）进行展示，本主题对本地相关的随机图进行了改进，可能不适用旧有方案。

api搞定了，但是有跨域问题报错= =
有啥帮助链接么，nginx怎么改呢...查了没成功。
https://api.anibullet.com/webp.php
随机api能正常打开了

**Comment by AnimatorBullet** [comment]
> 关闭缓存封面图功能即可

好的~

**Comment by mirai-mamori** [comment]
2.2.2版本中会实装相关选项

**Comment by yuk7-0v0** [comment]
Wordpress>>设置>>其他评论设置>>在每个页面顶部显示【新的】评论
俺这样就可以实现，你可以试试
