### ISSUE TITLE
移动端界面签名栏文本无法显示完整

### ISSUE THREAD

**Issue by Abraham511** [mirai-mamori/Sakurairo#292]
在移动端查看首页时，签名栏文本过长，无法完整显示

**这是什么方面的想法？**

现有的UI 界面优化  /  用户体验

**这个想法具体是要实现什么？**

希望能设置签名栏换行，或者签名过长时移动端会自动扩宽签名栏显示第二行

**这个想法实现后有什么帮助？**

提升用户体验

**是否有具体的实现思路？**

暂无
![Screenshot_20210815-211427_WeChat](https://user-images.githubusercontent.com/52842852/129479852-6f18e92d-da1e-4559-b5de-de365c962fda.jpg)

**补充信息：**

**Comment by mirai-mamori** [comment]
不考虑此方式，后期可能使用滚动的方式进行排版
