### ISSUE TITLE
保存失败 function(){return u(n),r.apply(this,arguments)}

### ISSUE THREAD

**Issue by dedede121** [mirai-mamori/Sakurairo#301]
**问题出处：**

点击保存后弹出 function(){return u(n),r.apply(this,arguments)}

**实际行为描述：**

没有使用宝塔面板的Nginx防火墙，按照正常步骤安装后保存设置时弹出

触发问题后造成了什么效果及影响？

保存失败

**预期的行为：**

保存成功

**复现步骤：**

按照正常步骤部署WordPress并安装主题，然后保存设置

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4.22
- 数据库类型 / 版本：MySQL
- WordPress 版本：5.8
- 主题版本：2.2.1
- 使用的插件：无
- 浏览器：Chrome

**截图（若有）**

> 
![Desktop Screenshot 2021 08 20 - 17 49 41 61 (2)](https://user-images.githubusercontent.com/41088044/130215564-a56a0ae8-057e-4774-a9f4-ec574d0fc484.png)

> 

**补充信息：**

**Comment by mirai-mamori** [comment]
参考#136
