### ISSUE TITLE
希望文章内的图片能点击查看大图以及支持右键点击点击

### ISSUE THREAD

**Issue by KoishiStudio** [mirai-mamori/Sakurairo#302]
**这是什么方面的想法？**

 用户体验

**这个想法具体是要实现什么？**

* 文章正文中的图片，点击后能查看大图
* 右键点击/移动端长按图片能出现菜单(此处指浏览器自带的菜单，并不是要主题自己做一个菜单出来)

**这个想法实现后有什么帮助？**

* 部分图片尺寸较大，且不方便裁剪，在正文中会被缩小显示导致看不清楚细节，能查看大图有利于解决这一问题
* 允许右键/长按菜单可以便于使用常用的图片操作，例如复制、保存等

**是否有具体的实现思路？**

对于查看大图那个，我觉得较为直接的方法就是，点击后直接跳转到图片原始链接；右键菜单无思路

**补充信息：**

无

**Comment by mirai-mamori** [comment]
主题有内置灯箱
