### ISSUE TITLE
注册功能开启无效

### ISSUE THREAD

**Issue by AdeSpike** [mirai-mamori/Sakurairo#304]
**大致范围：**

登录模板无法启动注册功能

**具体行为描述：**

在主题设置中开启了注册功能，但登录页面没有显示注册的位置

**尝试：**

尝试关闭了其它插件，只保留单独的主题，开启注册功能后依然显示目前不允许注册
我尝试将wp-login.php后添加？action=register后，返回的内容为wp-login.php?registration=disabled，页面出现弹窗显示目前不允许用户注册
相关代码在wp-login文件中，个人观察是执行了
if ( ! get_option( 'users_can_register' ) ) {
			wp_redirect( site_url( 'wp-login.php?registration=disabled' ) );
			exit;
		}
这段函数，但我已经在模板设置里打开了允许登录页面注册，不知道为什么登录页面依然没有注册入口
**配置与环境：**

- 问题页面：目前域名还在备案，服务器无法访问，暂时不能提供链接
- PHP 版本：php7.3.4nts
- 数据库类型 / 版本：mysql5.7.26
- WordPress 版本：5.8
- 主题版本：2.2.1
- 使用的插件：Hotlink File Prevention2.0.0, Login LockDown1.8.1, Wordfence安全7.5.5,WP Editor.md10.2.1,WPS隐藏登录1.8.5
- 浏览器：Microsoft Edge  92.0.902.78

**截图（若有）**

![image](https://user-images.githubusercontent.com/46109115/130450137-600883cb-d575-43bf-b6c0-b37bff4b3da9.png)
![image](https://user-images.githubusercontent.com/46109115/130450298-2d37dda1-a08d-4fa6-93e8-a01f945e0556.png)
![image](https://user-images.githubusercontent.com/46109115/130450483-9c473aa2-d239-4115-93cd-1da12825cab4.png)

**补充信息：**

提供尽可能多的相关信息。

**Comment by beixibaobao** [comment]
wordpress自带一个是否允许用户注册，那个功能打开了吗（仪表盘-常规-设置）

**Comment by AdeSpike** [comment]
> wordpress自带一个是否允许用户注册，那个功能打开了吗（仪表盘-常规-设置）
现在设置完成了，成功解决了。
但还有一件事，音乐播放器没有加载出来，我已经填上我账号的cookies了，设置也完成了，但网页左下角没有播放器，而且控制台报错，无法加载APIplayer。这个也是设置的问题吗？
![image](https://user-images.githubusercontent.com/46109115/130611984-41337cf1-7261-4a17-b7f4-8d0c34bcd254.png)

**Comment by beixibaobao** [comment]
> > wordpress自带一个是否允许用户注册，那个功能打开了吗（仪表盘-常规-设置）
> > 现在设置完成了，成功解决了。
> > 但还有一件事，音乐播放器没有加载出来，我已经填上我账号的cookies了，设置也完成了，但网页左下角没有播放器，而且控制台报错，无法加载APIplayer。这个也是设置的问题吗？
> > ![image](https://user-images.githubusercontent.com/46109115/130611984-41337cf1-7261-4a17-b7f4-8d0c34bcd254.png)

确定cookies正确吗，_ntes_nnid=388887*********，这样或者是其他的，您可以给我打码部分，然后看看你输入的什么吗？或者是尝试把cookies编辑成文件发到contact@beixibaobao.com我的邮箱，我这边帮您查看也行。（cookies为敏感内容，别直接不打码发在公屏上）

**Comment by AdeSpike** [comment]
> > > wordpress自带一个是否允许用户注册，那个功能打开了吗（仪表盘-常规-设置）
> > > 现在设置完成了，成功解决了。
> > > 但还有一件事，音乐播放器没有加载出来，我已经填上我账号的cookies了，设置也完成了，但网页左下角没有播放器，而且控制台报错，无法加载APIplayer。这个也是设置的问题吗？
> > > ![image](https://user-images.githubusercontent.com/46109115/130611984-41337cf1-7261-4a17-b7f4-8d0c34bcd254.png)
> 
> 确定cookies正确吗，_ntes_nnid=388887*********，这样或者是其他的，您可以给我打码部分，然后看看你输入的什么吗？或者是尝试把cookies编辑成文件发到[contact@beixibaobao.com](mailto:contact@beixibaobao.com)我的邮箱，我这边帮您查看也行。（cookies为敏感内容，别直接不打码发在公屏上）


感谢您的回复，现在网页直接提取的cookie与帮助文档内的描述不太一样，可能导致无法识别，我已经按照您的提示完成了相关设置。真诚感谢您的解答
