### ISSUE TITLE
追剧模板bug

### ISSUE THREAD

**Issue by CrazyGirlish** [mirai-mamori/Sakurairo#305]
**问题出处：**

追剧模板出现bug

**实际行为描述：**

前端报错显示一行代码

**预期的行为：**

目前知道的是只影响观感

**复现步骤：**

启动B站追剧模板

**配置与环境：**
 CentOS 7.6，宝塔最新版
- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：mysql 5.6
- WordPress 版本：5.8zn-ch
- 主题版本：（Release 标注的版本号）2.2.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- Akismet 反垃圾评论 ，Easy WP SMTP，  Elementor，Elementor Pro，Essential Addons for Elementor，Sync QCloud COS，TablePress，Templately，WP User Avatars，WPForms Lite，WPJAM BASIC，你好多莉，百度站长SEO合集(支持百度/360/Bing/头条推送)
- 浏览器：（浏览器名称及版本号）微软最新版EDGE

**截图（若有）**

![QQ截图20210823234625](https://user-images.githubusercontent.com/48341841/130477500-99368c48-cf3d-4da3-bac8-cf2fce3b14b1.png)

**补充信息：**

提供尽可能多的相关信息。

**Comment by bymoye** [comment]
除数为0(

**Comment by CrazyGirlish** [comment]
![131](https://user-images.githubusercontent.com/48341841/130790924-da3820ba-2cf3-4629-8f74-dc7ff13d9b47.png)
B站的剧我确实没有完整的追过？是这个原因导致的除数为零？

**Comment by KotoriK** [comment]
> ![131](https://user-images.githubusercontent.com/48341841/130790924-da3820ba-2cf3-4629-8f74-dc7ff13d9b47.png)
> 
> B站的剧我确实没有完整的追过？是这个原因导致的除数为零？

追剧进度是分子不是分母
可以看一下commit里的注释
基本是电影这些分母为0的导致的

**Comment by CrazyGirlish** [comment]
好的，谢谢&nbsp;


SummerNight
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月25日(星期三) 晚上11:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mirai-mamori/Sakurairo] 追剧模板bug (#305)





  

 
B站的剧我确实没有完整的追过？是这个原因导致的除数为零？
  
追剧进度是分子不是分母
 可以看一下commit里的注释
 基本是电影这些分母为0的导致的
