### ISSUE TITLE
文章无法评论（不显示评论框）

### ISSUE THREAD

**Issue by wicecoffery** [mirai-mamori/Sakurairo#309]
**问题出处：**
文章下面没有评论框

**实际行为描述：**
文章下面的评论选项开启；
设置里面 的评论也开启
切基本关闭插件后依然没有出现
切换其他主题（sakura）文章出现评论框

**预期的行为：**

文章下面出现评论框

- 问题页面：
![P0 `P~3XCZN)VF3RXWP$TB6](https://user-images.githubusercontent.com/65485003/130635077-d0bdbaba-201e-487e-a4ec-f1e108bc3529.png)

- PHP 版本：72
- WordPress 版本：当前版本：5.8
- 主题版本：版本：2.2.1
- 使用的插件：
![`M ~M 4YVVF7ZD)Y6FUHF2](https://user-images.githubusercontent.com/65485003/130634596-6b622c70-6ed6-49a8-8543-bbe9776bda4e.png)

- 浏览器：Edge

**截图（若有）**
![~V2I3 3%LSOB9RBHRHCP295](https://user-images.githubusercontent.com/65485003/130634415-04ac0629-d95c-4572-be65-036ec3c49a78.png)
![KHBRAL1QIJO(18_%LH(QPQ3](https://user-images.githubusercontent.com/65485003/130634425-1ad2a6a3-e896-4da9-80da-f5b403364333.png)

**补充信息：**

根据大佬切换宝塔里面伪静态和文章里面的固定链接，关闭插件，全部不显示；

**Comment by bymoye** [comment]
多西爹哟

**Comment by wicecoffery** [comment]
> @KotoriK

www.icecoffee.ltd
https://www.icecoffee.ltd/archives/417
感谢

**Comment by KotoriK** [comment]
> 多西爹哟 @KotoriK
> 发一下地址哦

一开口就知道是老太君了
