### ISSUE TITLE
登入验证码不会自动刷新

### ISSUE THREAD

**Issue by bin2024** [mirai-mamori/Sakurairo#323]
**问题出处：**登入界面验证码

这个问题出在程序的哪一个具体功能？

**实际行为描述：****登入页面验证码
触发问题后造成了什么效果及影响？

**预期的行为：**当未安装登入限制插件时存在爆破风险

这个功能应该有怎样的效果和影响？

**复现步骤：**当登入密码或账号输错时自动刷新验证码
怎样才能再次触发这个问题？

**配置与环境：**all

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：（Release 标注的版本号）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by bymoye** [comment]
是的 但是验证码的有效期是一分钟
