### ISSUE TITLE
文章区域装饰特色图片对齐方向失效

### ISSUE THREAD

**Issue by dogsking** [mirai-mamori/Sakurairo#328]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

这个问题出在程序的哪一个具体功能？

文章区域装饰特色图片对齐方向

**实际行为描述：**

触发问题后造成了什么效果及影响？
仅选择左右交替时样式还是会跟随上一次的设置靠左或者靠右，或者说是保存了但是没有生效，我无法确认

**预期的行为：**

这个功能应该有怎样的效果和影响？
设置左右交替后字与图片会在不同的文章区域有交替的布局
**复现步骤：**

怎样才能再次触发这个问题？
一直存在
**配置与环境：**

- 问题页面： mimohan.top
- PHP 版本：7.4
- 数据库类型 / 版本：
- WordPress 版本：5.8.1
- 主题版本：
- 使用的插件：无
- 浏览器： chrome 、360浏览器

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
请检查是否是缓存问题使致主题输出的样式未能更新
相关问题在最新版本的主题中无法复现
