### ISSUE TITLE
PC开屏封面视频分辨率显示问题

### ISSUE THREAD

**Issue by beixibaobao** [mirai-mamori/Sakurairo#329]
**问题出处：**

PC端首页封面视频

**实际行为描述：**

插入1920*1080P视频及以上视频，会出现尺寸不符

**预期的行为：**

画面明显感觉被放大

**复现步骤：**

你插入个视频被，或者是试试我给的临时视频源：https://blog.beixibaobao.com/rand/video/videos/Drama-%E3%80%8AThe%20Last%20Flash%E3%80%8B.mp4

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.0
- 数据库类型 / 版本：5.7.34
- WordPress 版本：5.8.1
- 主题版本：2.2.6.1
- 使用的插件：Wechat Social+WP Githuber MD
- 浏览器：chrome NEW

**补充信息：**

【虽然知道一般没啥人会存1080P视频在那儿，所以不抱期待会短时间有修/doge】

**Comment by KotoriK** [comment]
为啥我这现在是视频播放器的大小根本不随屏幕大小变化

**Comment by beixibaobao** [comment]
> 为啥我这现在是视频播放器的大小根本不随屏幕大小变化

吃惊，封面视频和视频播放器啥关系【虽然文章内视频播放器大小不随屏幕大小变化确实有，我一直以为是我自己的问题。】
-----
发issues是存档，为啥不直接私我（草）
