### ISSUE TITLE
启动主题报错

### ISSUE THREAD

**Issue by beyondmydreamm** [mirai-mamori/Sakurairo#332]
启动主题报错

Parse error: syntax error, unexpected ':', expecting '{' in /www/wwwroot/hannibal.cc/wordpress/wp-content/themes/Sakurairo/functions.php on line 528

您的站点遇到了致命错误。

**Comment by KotoriK** [comment]
请检查php版本 本主题仅支持7以上的版本

提问前请多看看文档，并参考模板提问，能为我们减少很多查找问题的时间
