### ISSUE TITLE
FancyBox灯箱的markdown语法无法正常使用

### ISSUE THREAD

**Issue by WankkoRee** [mirai-mamori/Sakurairo#334]
**问题出处：**

FancyBox灯箱

**实际行为描述：**

直接显示了原始代码，并且图片地址会被渲染成`<a>`标签

**预期的行为：**

正常显示灯箱

**复现步骤：**

启用`Githuber MD`插件，在文章页写个`!{flowchart}(https://i.loli.net/2020/05/21/PJTQ2dbipD1yaf9.png)`

**配置与环境：**

- PHP 版本：7.2.33
- WordPress 版本：5.8.1
- 主题版本：2.2.7
- 使用的插件：`Githuber MD`

**截图（若有）**

![image](https://user-images.githubusercontent.com/21287731/133793060-49add440-8b68-4bf5-a9b6-a2a088f206b9.png)

**补充信息：**

推测是与`Githuber MD`冲突，因为`Githuber MD`并不认这个markdown语法，所以会当成普通文本处理，而文本中含有url，导致url被渲染，造成FancyBox正则无法成功匹配。

如果直接使用灯箱的html代码则一切正常。

如果使用`` `!{flowchart}(https://i.loli.net/2020/05/21/PJTQ2dbipD1yaf9.png)` ``则可以显示灯箱但文章页的图片底部会有`code`标签的渲染样式。

**Comment by KotoriK** [comment]
请与GitHub MD插件作者联系
