### ISSUE TITLE
希望在评论设置中添加一个自定义上传图片地址的功能

### ISSUE THREAD

**Issue by UtopiaXC** [mirai-mamori/Sakurairo#338]
**这是什么方面的想法？**

用户体验

**这个想法具体是要实现什么？**
目前上传图片图床只支持那三个，但是我用的是我基于Lsky Pro的自建图床，希望能添加一个自定义上传接口和token设置

**这个想法实现后有什么帮助？**
可以自定义评论上传图片的图床

**Comment by KotoriK** [comment]
请提供相关接口

有能力的话欢迎自己实现！相关的代码在 https://github.com/mirai-mamori/Sakurairo/blob/16900802a2441acf7c6f6f9a4ee6431fdf209f8c/inc/api.php#L88

**Comment by mirai-mamori** [comment]
已添加
