### ISSUE TITLE
让前台背景和封面随机图片选项以及文章区域装饰特色图片设定分离

### ISSUE THREAD

**Issue by h3tsya** [mirai-mamori/Sakurairo#340]
**自定义功能优化**

**请让让前台背景和封面随机图片选项以及文章区域装饰特色图片的设定进行分离**

目前存在的问题是，因为我是4k显示屏，

所以无法使用外链api来当我的图片，我只能全部本地化

而当我上传4k壁纸作为前台背景时

封面随机图片api的1080p会让我的封面非常糊，

但是，当我上传4k高清壁纸到本地作为封面随机图片时

网页载入速度过慢，文章封面加载时间过长

目前的办法只有舍去前台背景的设定，只让封面图片随机打开（因为无法取消封面图片随机）

让我在设定自定义图片时感到很吃力

目前我的希望是

**让前台背景，封面图片，文章封面图片三个功能能够分开设定**

目前封面图片，文章封面图片使用的是同一个本地图片库，且无法取消显示

如果前台背景，封面图片，文章封面图片三个功能能够分开设定

这样，我的背景可以使用4k分辨率以上的图片，封面可以选择关闭，或者设定为其他和主题相符的图片

文章封面可以选择分辨率较小，更加符合文章内容的封面图片

**这个想法实现后，使用者能够更加高度自定义自己  _各式各样的主题背景_，_封面图片_，_更加符合文章的封面_**

**可以通过分别设定背景（取消\wp-content\themes\Sakurairo\manifest\gallary），或者将\wp-content\themes\Sakurairo\manifest\gallary的本地随机图片库，仅仅链接至封面图片，或者文章封面**

我没有学过网页设计，作为小白不知提议是否实行起来比较容易，仅仅作为建议

如果上述要求实现起来比较困难，那么我希望能够添加一个      取消随机封面      的选项

**Comment by KotoriK** [comment]
请查看主题设置中“文章区域装饰特色图片选项”，将其更改为"外部API随机图片"后，在下方出现的文本框填入api即可
相关api可以自建，主题不再另外提供
