### ISSUE TITLE
文章页面无法正常打开

### ISSUE THREAD

**Issue by StarOnTheSky** [mirai-mamori/Sakurairo#342]
**问题出处：**

主页正常，文章页面无法打开

**实际行为描述：**

页面报错，无法正常打开
![IMG_20211001_144916](https://user-images.githubusercontent.com/51866924/135580290-2d73b99b-1518-4cb6-a1a1-0742b867e12a.jpg)

**复现步骤：**

未知

**配置与环境：**

- 问题页面：https://service-3g7a9p0h-1306227824.sh.apigw.tencentcs.com/2021/09/22/mmotee%e6%a8%a1%e5%bc%8f/
- PHP 版本：7.2.34
- 数据库类型 / 版本：腾讯云 CynosDB (MySQL 5.7)
- WordPress 版本：5.8.1
- 主题版本：2.2.7
- 使用的插件：Orbit Fox
- 浏览器：Firefox Android 92.1.1

**截图（若有）**

见上

**补充信息：**

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
请启用mbstring php扩展
详情百度
