### ISSUE TITLE
live2D

### ISSUE THREAD

**Issue by fon11731** [mirai-mamori/Sakurairo#343]
请问，那个live2D怎么自定义呢

**配置与环境：**

- PHP 版本：7.4
- 数据库类型 / 版本：phpMyAdmin
- WordPress 版本：5.8.1
- 主题版本：2.2.7

**Comment by mirai-mamori** [comment]
仔细阅读Readme和主题相关设置介绍

**Comment by always1314** [comment]
我想说readme和主题相关设置介绍并没有自定义的那些东西
