### ISSUE TITLE
[新增功能]请求添加“回复可见”、“登录可见”、“链接按钮”

### ISSUE THREAD

**Issue by NickPikachu** [mirai-mamori/Sakurairo#351]
1.使用户浏览文章时，部分内容需要回复（登录网站）后才可以查看。
2.用户在博客中的文章有个小按钮（如“点击跳转”或者按钮名字可以自定义等）可以直接跳转网站，而不是像Wordpress一样长长的一条蓝色链接。

1.这个功能可以有效杜绝网站爬虫，还有不尊重作者成果的用户等。
2.方便用户浏览，提升观感体验（用户体验至上才是主题的初衷吧？）

暂无（Wordpress插件商店有类似插件Easy2Hide，不过没用中文而且会导致风格不统一等，按钮功能在CorePress主题内有差不多的，包括回复可见也有，不过风格不是我喜欢的类型了）

也没啥可说的了 =w=

**Comment by mirai-mamori** [comment]
区块编辑器可以自己进行跳转按钮的配置

**Comment by Lfhsheng** [comment]
设置某些内容评论可见，希望能加上
