### ISSUE TITLE
在线音乐播放器无法加载网易云的我喜欢的音乐列表

### ISSUE THREAD

**Issue by lvzhenbo** [mirai-mamori/Sakurairo#353]
**问题出处：**

在线音乐播放器

**实际行为描述：**

无法加载，控制台报这个错误
![image](https://user-images.githubusercontent.com/32427677/137676549-91237269-cba6-4723-b676-779e0290fb72.png)

**预期的行为：**

能够加载

**复现步骤：**

按照文档中描述的正常配置，包括cookies

**配置与环境：**

- 问题页面：https://www.lvzhenbo.xyz
- PHP 版本：8.0.8
- 数据库类型 / 版本：MariaDB 10.4.19
- WordPress 版本：5.8.1
- 主题版本：2.2.12
- 使用的插件：Akismet Anti-Spam     UpdraftPlus - Backup/Restore
- 浏览器：Google Chrome v94.0.4606.81

**截图（若有）**

![image](https://user-images.githubusercontent.com/32427677/137676549-91237269-cba6-4723-b676-779e0290fb72.png)

**补充信息：**

我估计和歌单内的歌的数量有关，我这个已经达到1000+

**Comment by KotoriK** [comment]
未能复现 不过由于网易云限制只能返回前20首

**Comment by KotoriK** [comment]
> > > 未能复现 不过由于网易云限制只能返回前20首
> > 
> > 
> > 主题2.2.7可以通过抓取登录cookie可以加载"我喜欢"这个歌单全部。 ![Screenshot_2021-10-20-18-10-53-415_cn.nr19.mbrowser.png](https://user-images.githubusercontent.com/85409617/138074595-cf198d10-63e8-4ab2-938a-ccc09f33af35.png) 现在我点不开列表了。
> 
> 确认一下2.2.7现在还能访问整个歌单？（还是说是只有自己的号能访问）

可能确实是需要歌单创建者本人的cookie，在2.2.12上能访问100首的完整歌单

**Comment by lvzhenbo** [comment]
对的是空的，但是我改成其他的歌单是可以的

**Comment by KotoriK** [comment]
我看看怎么让源代码把错误报出来

**Comment by lvzhenbo** [comment]
![image](https://user-images.githubusercontent.com/32427677/138115080-c268e589-b906-4c8c-986e-3c08ca3de63c.png)
我换了一个10首的歌单就行

**Comment by KotoriK** [comment]
比较麻烦 需要知道你那边调用网易云的api到底返回了什么才能解决问题
主题是使用 metowolf/Meting 获取歌单信息的
https://github.com/mirai-mamori/Sakurairo/blob/c3491ce5c7cae9fe1b095355efc0564cc8be1b4d/inc/classes/Meting.php
你可以在本地代入参数运行一下看看到底返回什么

**Comment by lvzhenbo** [comment]
目前我无法复现了，现在打开突然可以显示并且播放了

**Comment by lvzhenbo** [comment]
啊。。不是。。我说的是2.2.12，当我现在打开我的博客想备份主题设置的时候发现突然有音乐播放器了并且能播放
