### ISSUE TITLE
关于扩大内容显示区域宽度、调整导航栏排列、相册显示异常的求助

### ISSUE THREAD

**Issue by GowanOAtta** [mirai-mamori/Sakurairo#361]
1、显示宽度问题
我的显示器是15寸的，阅读文章时候两边留白太多了，屏幕空间空了一半左右
![图片](https://user-images.githubusercontent.com/24862657/139570110-0c810f93-f4ce-49e3-bd8f-c946056858bd.png)
我还用嵌入网站做了一个网址收藏，但是宽度不够排版有些乱了
![图片](https://user-images.githubusercontent.com/24862657/139573323-bcb6b2e2-2603-4bfc-b019-383c57a52f16.png)
请问如何扩大文章内容显示区域的宽度？

2、导航栏排列问题
上方导航栏有遮挡到内容了，导航栏是否可以调为竖直排列？

3、相册显示“未上传图片或图片设置异常”
代码按如下添加了
![图片](https://user-images.githubusercontent.com/24862657/139573643-4554f0fe-d5a9-4411-8011-8e3944ad08d6.png)
然而无论代码添加与否都显示如下
![图片](https://user-images.githubusercontent.com/24862657/139573622-4ad2d29c-a069-4dcb-80e6-3244951f4491.png)
请问如何上传或设置图片？

**Comment by KotoriK** [comment]
1. 可以修改#content 或.site-content的宽度
2. 不可以
3. 诸如```&lt;```是转义字符。你应该输入的是\<img>这样的并且要把板块改成自定义html
4. 下次这类问题可以发到Discussion

**Comment by GowanOAtta** [comment]
> 
> 
>     1. 可以修改#content 或.site-content的宽度
> 
>     2. 不可以
> 
>     3. 诸如`&lt;`是转义字符。你应该输入的是<img>这样的并且要把板块改成自定义html
> 
>     4. 下次这类问题可以发到Discussion

好的，这边是专门处理bug的么？
我把宽度修改成功了，但是页面的其他一些元素发生不适配；
`&lt;`转义字符是 wordpress 自己改的，我改回好几次都不行；自定义html有样本吗？
已发到 Discussion，麻烦帮我看一下，感谢
https://github.com/mirai-mamori/Sakurairo/discussions/362#discussion-3660527
