### ISSUE TITLE
cover请求了一个奇怪的URL

### ISSUE THREAD

**Issue by THU-Pieris** [mirai-mamori/Sakurairo#367]
**大致范围：**

观察到一个奇怪的URL请求如下
![](https://raw.githubusercontent.com/THU-Pieris/Image/main/img/Snipaste_2021-11-05_13-01-31.png)
期望的请求是https://wp.pieris05.pw/wp-json/sakura/v1/image/cover
但实际是https://wp.pieris05.pw/url(%22https://wp.pieris05.pw/wp-json/sakura/v1/image/cover%22)

**具体行为描述：**

多次连续刷新，有时候有、有时候没有。很奇怪。

**尝试：**

\

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）https://wp.pieris05.pw/
- PHP 版本：8.0
- 数据库类型 / 版本：mysql 5.6.50
- WordPress 版本：5.8.1
- 主题版本：（Release 标注的版本号）2.2.12
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）All in One SEO, Comment Reply Email Notification, Email Subscribers & Newsletters, Jetpack, Link Manager, Subscribe to Comments Reloaded, WP Fastest Cache, WP Mail SMTP
- 浏览器：（浏览器名称及版本号）safari 版本15.1 (17612.2.9.1.20)

**截图（若有）**

已在相关位置给出

**补充信息：**

观察到其它站点有些存在该问题，比如

https://littlecu.cn

![Snipaste_2021-11-05_13-08-41](https://raw.githubusercontent.com/THU-Pieris/Image/main/img/Snipaste_2021-11-05_13-08-41.png)

https://www.anibullet.com

![image-20211105130925172](https://raw.githubusercontent.com/THU-Pieris/Image/main/img/image-20211105130925172.png)

有一些就没有。

**Comment by KotoriK** [comment]
草了 我都不知道之前测试怎么过的

**Comment by KotoriK** [comment]
Fuukei/Sakurairo-Script f782b39
