### ISSUE TITLE
Vaptcha验证的错误处理中类型转换失败的问题

### ISSUE THREAD

**Issue by wangwang5200** [mirai-mamori/Sakurairo#369]
我在使用这个Sakurairo的登录功能时，一点登录就弹出一个看不懂的东东
![image](https://user-images.githubusercontent.com/93471428/140774619-64b129b6-6e0b-4fbc-bb07-e21d0e105122.png)
我不知道该如何解决请你一点要帮我

**Comment by KotoriK** [comment]
@Aoyamakiri 看看
https://github.com/mirai-mamori/Sakurairo/blob/c3491ce5c7cae9fe1b095355efc0564cc8be1b4d/functions.php#L2056

**Comment by robert1chi** [comment]
#370 根据vaptcha[文档](https://www.vaptcha.com/document/install.html#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E4%BA%8C%E6%AC%A1%E9%AA%8C%E8%AF%81)修改

**Comment by robert1chi** [comment]
根据文档返回示例感觉2049行判断msg === 'success'有点问题
https://github.com/mirai-mamori/Sakurairo/blob/c3491ce5c7cae9fe1b095355efc0564cc8be1b4d/functions.php#L2049

**Comment by Aoyamakiri** [comment]
> 可知文档返回示例感觉2049行判断msg === '成功'有点
> 
> https://github.com/mirai-mamori/Sakurairo/blob/c3491ce5c7cae9fe1b095355efc0564cc8be1b4d/functions.php#L2049

@robert1chi 
他的文档有所更改，明天我进行修复

**Comment by wangwang5200** [comment]
所以我到底看谁发的，该如何去更改

**Comment by robert1chi** [comment]
> 所以我到底看谁发的，该如何去更改

可以先等pr被merge以后再用preview分支的functions.php进行更改
