### ISSUE TITLE
英文主题下有一些残留中文字符

### ISSUE THREAD

**Issue by Sprit-Fun** [mirai-mamori/Sakurairo#372]
切换到英文时，大部分文本都成功转换，但是在搜索以及登录还会显示中文；例如：登录，文章，页面，分类，评论。
我尝试找到对应的源码但是看了不少mo文件都找不到类似词。希望可以指导修复一下，谢谢！
![Capture1](https://user-images.githubusercontent.com/43423211/141085534-318619ca-7d76-4336-8503-dcb5606a44dd.PNG)
![Capture](https://user-images.githubusercontent.com/43423211/141085537-66eb902c-6928-403a-a240-faa7ace3b050.PNG)

**Comment by KotoriK** [comment]
好的 如果有发现其他没有翻译的地方也欢迎反馈

**Comment by Sprit-Fun** [comment]
英文主题下，如果未登录的话鼠标移到头像“登录”也会显示中文，这个也是在theme_plus.php里面大概457行的位置

**Comment by Sprit-Fun** [comment]
另外请问搜索页面的这些文本可以删除吗？这四个标题显示都是中文；谢谢！
![image](https://user-images.githubusercontent.com/43423211/141232813-751d39de-21f7-4e32-98fc-dc22debea5d7.png)

**Comment by KotoriK** [comment]
> 另外请问搜索页面的这些文本可以删除吗？这四个标题显示都是中文；谢谢！ ![image](https://user-images.githubusercontent.com/43423211/141232813-751d39de-21f7-4e32-98fc-dc22debea5d7.png)

好的 还请持续反馈

**Comment by Sprit-Fun** [comment]
这四个搜索页面的中文在app.js 和 app.js.map里面，修改为英文后就好了，希望可以增加dynamic功能来实现不同语言的搜索栏

**Comment by Sprit-Fun** [comment]
如果首页设置了视频播放会显示中文：正在载入视频；已暂停等。

**Comment by KotoriK** [comment]
> 如果首页设置了视频播放会显示中文：正在载入视频；已暂停等。

已经修复了 下个版本可以注意一下
