### ISSUE TITLE
如何解决Pjax与Mathjax渲染冲突的问题？

### ISSUE THREAD

**Issue by silentEAG** [mirai-mamori/Sakurairo#376]
**大致范围：**

文章内容

**具体行为描述：**

在Pjax动态加载下，Mathjax无法第一次加载时渲染。

**尝试：**

尝试搜索，添加事件委托，但仍然无法即时渲染。
```
<script>
.on('pjax:complete', function () {
    $.getScript("//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML", function() {
        MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
        
        var math = document.getElementsByClassName("entry-content")[0];
        MathJax.Hub.Queue(["Typeset",MathJax.Hub,math]);
    });
});
</script>
```
**配置与环境：**

- 问题页面：
- PHP 版本：7.3
- 数据库类型 / 版本：MySQL
- WordPress 版本：5.8.2
- 主题版本：2.2.12
- 使用的插件：Simple Mathjax,Akismet 反垃圾评论,你好多莉
- 浏览器：chrome

**Comment by KotoriK** [comment]
1.主题已经废弃jQuery，你贴的脚本片段使用了jQ，而由于它没有在加载所以不会工作
2.MathJAX不仅要加载脚本，还需要加载相关样式与字体资源
3.主题难以保证Pjax与其他插件的兼容性。如果一定要使用请关闭pjax
4.主题有内置的MathJAX，目前支持``` <math> ```HTML标签中的MathML，其他的格式比如LaTex由于不知道用什么markup好所以还没支持（你可以说明一下你用的mathjax插件使用什么markup）
https://github.com/Fuukei/Sakurairo_Scripts/blob/a0397d649535a2e5ef9a1d2ee469e59ee430bbc8/src/page/article_attach.ts#L77-L97

由于这个问题不会被尝试修复所以issue现在会被关闭
回复依然是可以的
