### ISSUE TITLE
在线音乐播放器出现的问题

### ISSUE THREAD

**Issue by lhc13145** [mirai-mamori/Sakurairo#385]
首先是上一版本的在线播放器的优化，非常棒，现在出现了一个问题就是在同一网站换到不同标签，页面重新加载，随之音乐播放器也重新加载，而上一个版本就会一直播放，这是目前体验来说不太好的地方，希望解决！

**Comment by KotoriK** [comment]
说实话没看懂

**Comment by lhc13145** [comment]
就是很简单一句话，在线音乐播放器正在播放，然后打开网站一个分类，就会停止，而上个版本的则不会

**Comment by KotoriK** [comment]
未能复现
请检查pjax是否打开 如果还不行请提供一下网址和导致播放停止的链接

**Comment by lhc13145** [comment]
ok了，小概率事件
