### ISSUE TITLE
Ver 2.2.6.1 该版本主页无法加载封面图了

### ISSUE THREAD

**Issue by wangsilei09** [mirai-mamori/Sakurairo#387]
**问题出处：**
尽早更新完Ver 2.2.6.1版本后，主页封面图加载不出来了
![image](https://user-images.githubusercontent.com/56724461/143803479-84bf700b-b858-4d03-8988-edaca98c64d8.png)

**Comment by KotoriK** [comment]
请提供网站地址

**Comment by wangsilei09** [comment]
www.yuetong.top


| |
wangsilei
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年11月29日 ***@***.***> 写道：

请提供网站地址

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangsilei09** [comment]
版本：2.3.1
网址为：www.yuetong.top

**Comment by wangsilei09** [comment]
> 请提供网站地址

版本：2.3.1
网址为：www.yuetong.top

**Comment by KotoriK** [comment]
你这个版本是2.3.1
参考#388
