### ISSUE TITLE
主页无法直接显示封面图

### ISSUE THREAD

**Issue by MoYoez** [mirai-mamori/Sakurairo#388]
**问题出处：**

主页上问题，具体表现为封面显示无法主动显示，需要手动刷新

**实际行为描述：**

进入主页后不会主动显示

**预期的行为：**

应该是直接显示，而不是需要手动pre/next

**复现步骤：**

直接访问页面即可

**配置与环境：**

- 问题页面：https://imagic.run
- PHP 版本：7.4
- 数据库类型 / 版本：5.6.50
- WordPress 版本：5.8.2
- 主题版本：2.3.1
- 使用的插件：Easy WP SMTP,External Media without Import,Rename wp-login.php,WP Statistics,wp super cache
- 浏览器：Microsoft Edge，96.0.1054.34

**截图（若有）**

https://i.loli.net/2021/11/29/fqGTJZopFXUbjEY.png

**补充信息：**

**Comment by KotoriK** [comment]
问题已修复
在下一个补丁发布前可以暂时使用这个链接的脚本文件替换主题目录下对应文件(```/js/app.js```)解决
https://github.com/mirai-mamori/Sakurairo/blob/eaacf97171ff61df253424d90603eec63f92b2ba/js/app.js
