### ISSUE TITLE
请教大文件加载是什么导致的

### ISSUE THREAD

**Issue by wangsilei09** [mirai-mamori/Sakurairo#389]
网址：www.yuetong.top
版本：2.3.1
我不知道开启什么导致的，加载页面是会有个请求，内容很大，想了解下他是设置哪里导致的或者怎么关闭？
![image](https://user-images.githubusercontent.com/56724461/143827741-225f1478-7ea9-4dfb-a47a-c402d6e70042.png)

**Comment by KotoriK** [comment]
是你开了APlayer
这个是音乐
