### ISSUE TITLE
说说界面控制台报错“Uncaught ReferenceError: $ is not defined","at www.dotnya.com/:672"

### ISSUE THREAD

**Issue by DotNya** [mirai-mamori/Sakurairo#39]
说说界面控制台报错：
Uncaught ReferenceError: $ is not defined
    at www.dotnya.com/:672

**Comment by mirai-mamori** [comment]
请更详细说明报错发生场景。

**Comment by DotNya** [comment]
Sakurairo版本：1.12.9
Wordpress版本：5.4.1
浏览器：chrome
通过主题内建模板新建说说页面后将其放置于导航菜单。
并发布一条说说用于测试。
点击进入说说页面后即可见该报错。

**Comment by mirai-mamori** [comment]
环境一致下暂不能复现。

**Comment by DotNya** [comment]
补充：
开启PJAX后由其他页面进入说说页面不会出现报错。
刷新或直接进入说说页面会出现改报错。

可见的表现为：左侧用户头像旋转动画丢失。

**Comment by mirai-mamori** [comment]
无论是否开启PJAX，何种方式进入，说说页面均无没有提示报错。
说说页面旋转动画丢失可以复现。这是因为外部链接引用的CSS未加载清楚的问题。
建议将说说的CSS整合至Style CSS 来解决此问题
