### ISSUE TITLE
文章页面图片无法放大

### ISSUE THREAD

**Issue by yn68** [mirai-mamori/Sakurairo#392]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**
文章页面图片无法放大
现有内容的优化 / 新增功能 / UI 界面 / 用户体验

**这个想法具体是要实现什么？**
实现图片灯箱类似效果

**这个想法实现后有什么帮助？**

**是否有具体的实现思路？**

**补充信息：**

**Comment by mirai-mamori** [comment]
自行查看使用说明、

**Comment by yn68** [comment]
设置保存后，文章页面无法打开图片
点击图片没有任何反应。


***@***.***
 
发件人： 染川 瞳
发送时间： 2021-12-04 13:37
收件人： mirai-mamori/Sakurairo
抄送： yuni; Author
主题： Re: [mirai-mamori/Sakurairo] 文章页面图片无法放大 (Issue #392)
自行查看使用说明、
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
