### ISSUE TITLE
修改style.css样式后 不起作用

### ISSUE THREAD

**Issue by wickedll** [mirai-mamori/Sakurairo#393]
![image](https://user-images.githubusercontent.com/29485174/144712006-baaf9971-df2a-4532-b3f7-5efef6d0aeb7.png)
修改了这个yaa但是index生成的还是原来的
![image](https://user-images.githubusercontent.com/29485174/144712026-322315fa-01f2-48b2-8210-b62d6c03a2ad.png)
这个阴影效果

**Comment by KotoriK** [comment]
看看右上角来源
你再想想

**Comment by wickedll** [comment]
我知道来源不同，但是我不知道在哪里修改这个index

**Comment by KotoriK** [comment]
> 我知道来源不同，但是我不知道在哪里修改这个index

善用代码搜索

**Comment by wickedll** [comment]
懂了 谢谢
