### ISSUE TITLE
2.3.2直接炸了=。=

### ISSUE THREAD

**Issue by sparkshou** [mirai-mamori/Sakurairo#395]
上午在Wordpress后台更新了2.3.2，然后突然弹

“出此站点遇到了致命错误。

了解有关对WordPress进行故障排除的更多信息。”

然后我去后台改掉themes 文件名努力进了后台，来GitHub重新下载了2.3.2的安装文件，依旧报错

“此站点遇到了致命错误。

了解有关对WordPress进行故障排除的更多信息。”

**Comment by KotoriK** [comment]
致命错误的内容呢

**Comment by sparkshou** [comment]
没有详细内容。。。。我也没收到邮件。蓝色链接 是 https://wordpress.org/support/article/faq-troubleshooting/

**Comment by sparkshou** [comment]
我现在进管理员后台把咱们的主题都删掉了，然后又重新上传2.3.2的程序安装完 依旧报错。。。。预览也会，启动也会

**Comment by zyfx-wzk** [comment]
具体报错信息
Fatal error: Uncaught Error: Function name must be a string in /var/www/html/wordpress/wp-content/themes/Sakurairo/inc/swicher.php:54 Stack trace: #0 /var/www/html/wordpress/wp-includes/class-wp-hook.php(303): font_end_js_control() #1 /var/www/html/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #2 /var/www/html/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action() #3 /var/www/html/wordpress/wp-includes/general-template.php(3015): do_action() #4 /var/www/html/wordpress/wp-content/themes/Sakurairo/header.php(67): wp_head() #5 /var/www/html/wordpress/wp-includes/template.php(770): require_once('/var/www/html/w...') #6 /var/www/html/wordpress/wp-includes/template.php(716): load_template() #7 /var/www/html/wordpress/wp-includes/general-template.php(48): locate_template() #8 /var/www/html/wordpress/wp-content/themes/Sakurairo/index.php(16): get_header() #9 /var/www/html/wordpress/wp-includes/template-loader.php(106): include('/var/www/html/w...') #10 /var/www/html/wordpress/wp-blog-header.php(19): in /var/www/html/wordpress/wp-content/themes/Sakurairo/inc/swicher.php on line 54

**Comment by zyfx-wzk** [comment]
确定是更新了2.3.2后出现的问题

**Comment by sparkshou** [comment]
> 确定是更新了2.3.2后出现的问题

那是等你们修复更新还是如何？

**Comment by CDdickey** [comment]
我尝试如果把php切换为7.4就正常了 @sparkshou

**Comment by sparkshou** [comment]
> 我尝试如果把php切换为7.4就正常了 @sparkshou
哎，我买的那个虚拟主机最高只支持7.3，脑壳痛

**Comment by KotoriK** [comment]
> 具体报错信息
> 
> ```
> Fatal error: Uncaught Error: Function name must be a string in /var/www/html/wordpress/wp-content/themes/Sakurairo/inc/swicher.php:54 
> Stack trace: #0 /var/www/html/wordpress/wp-includes/class-wp-hook.php(303): font_end_js_control() 
> #1 /var/www/html/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() 
> #2 /var/www/html/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action() 
> #3 /var/www/html/wordpress/wp-includes/general-template.php(3015): do_action() 
> #4 /var/www/html/wordpress/wp-content/themes/Sakurairo/header.php(67): wp_head() 
> #5 /var/www/html/wordpress/wp-includes/template.php(770): require_once('/var/www/html/w...') 
> #6 /var/www/html/wordpress/wp-includes/template.php(716): load_template() 
> #7 /var/www/html/wordpress/wp-includes/general-template.php(48): locate_template() 
> #8 /var/www/html/wordpress/wp-content/themes/Sakurairo/index.php(16): get_header()
> #9 /var/www/html/wordpress/wp-includes/template-loader.php(106): include('/var/www/html/w...') 
> #10 /var/www/html/wordpress/wp-blog-header.php(19): in /var/www/html/wordpress/wp-content/themes/Sakurairo/inc/swicher.php on line 54
> ```

确认是一个bug 已经修复
