### ISSUE TITLE
为何网站页面打开标签还是会重新刷新

### ISSUE THREAD

**Issue by gsclovezy1314** [mirai-mamori/Sakurairo#396]
PJAX局部刷新，我试了下关闭所有页面都会重新刷新打开，然后我打开该功能，网页在打开页面时还是会重新刷新打开，这种行为就是打开一个页面不会刷新，再打开第二个结果就重新刷新了，严重影响使用体验。之前的2.2没这个问题的，我的版本现在2.3.2

**Comment by bymoye** [comment]
未发现问题，请提供站点地址。

**Comment by gsclovezy1314** [comment]
gsclove.top

**Comment by bymoye** [comment]
我不好说。有点太慢了。但是既然您连主题页脚Theme Sakurairo by Fuukei都删了 那您一定可以自己解决的吧 那么这里不再提供后续支持。交给K宝了（ @KotoriK
