### ISSUE TITLE
webp随机优化图片库无法使用

### ISSUE THREAD

**Issue by yukizero7** [mirai-mamori/Sakurairo#4]
更新1.10.0版本后发现首页背景图被恢复为默认，进入后台重置为默认设置后，重新设置“封面图片库选项“为 webp优化随机图，并重新设置了 封面图片库URL 链接，保存设置后点击”封面图片库url“右侧的的**更新 manifest**后显示`{"code":"rest_no_route","message":"\u672a\u627e\u5230\u5339\u914dURL\u548c\u8bf7\u6c42\u65b9\u5f0f\u7684\u8def\u7531","data":{"status":404}}`
封面图片库url确认格式无误，也按照教程重新生成了一次manifest，再上传到cdn，依旧返回同样的错误

**Comment by mirai-mamori** [comment]
请提供更加详细的问题描述，暂时没有复现
