### ISSUE TITLE
语法高亮在第一次进入页面时无法正常加载

### ISSUE THREAD

**Issue by ikeDong** [mirai-mamori/Sakurairo#411]
**问题出处：**

代码高亮的js文件不会加载，刷新后才会出现

**实际行为描述：**

点击文章进去后不会有语法高亮效果

**预期的行为：**

页面正常显示

**复现步骤：**

首次登录页面

**配置与环境：**

- 问题页面：https://blog.ikedong.cn/archives/114
- PHP 版本：8.0
- 数据库类型 / 版本：mysql.7
- WordPress 版本：5.8.2
- 主题版本：（2.3.3
- 使用的插件：WP Githuber MD
- 浏览器：chrome:lastest

**问题截图**
首次加载页面
![Snipaste_2021-12-20_09-58-22](https://user-images.githubusercontent.com/91770427/146701472-14c9b35d-d646-4db7-9b99-4c921ea477c0.png)

刷新后的页面
![Snipaste_2021-12-20_09-59-50](https://user-images.githubusercontent.com/91770427/146701474-b1035360-ff0a-408f-a26b-b44a77b0ff99.png)

**Comment by KotoriK** [comment]
证实与#409一致 已修复

**Comment by ikeDong** [comment]
并没有，当我清除缓存重新进入的时候还是无法显示
![Snipaste_2021-12-20_10-36-10](https://user-images.githubusercontent.com/91770427/146703868-aea79be7-148c-4a6c-9564-ef34f7c34d71.png)
