### ISSUE TITLE
cdn是不是崩了

### ISSUE THREAD

**Issue by wickedll** [mirai-mamori/Sakurairo#412]
图标啥的都访问不了

**Comment by mirai-mamori** [comment]
或许吧2333

**Comment by AdeSpike** [comment]
> 或许吧2333

edge和chrome直接把jsdelivr拦了，cdn的加载直接被拦截了，显示不安全，直接不让访问了。
但如果挂梯子再访问，图片能正常加载。

**Comment by KotoriK** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18348#issuecomment-997777996
