### ISSUE TITLE
通过#409修正代码高亮后，会导致图片问题

### ISSUE THREAD

**Issue by ikeDong** [mirai-mamori/Sakurairo#413]
**问题出处：**

通过#409的方法修复代码高亮问题后，文章图片会一直处在加载或404

**实际行为描述：**

图片在第一次加载时会加载不出来，除非刷新一下

**预期的行为：**

图片正常加载

**复现步骤：**

第一次访问这个页面

**配置与环境：**

- 问题页面：https://blog.ikedong.cn/archives/104
- PHP 版本：8.0
- 数据库类型 / 版本：mysql5.7
- WordPress 版本：5.8.4
- 主题版本：2.3.3
- 使用的插件：WP Githuber MD
- 浏览器：chrome:lastest

**截图（若有）**
![Snipaste_2021-12-20_14-37-22](https://user-images.githubusercontent.com/91770427/146723111-f260ae3d-ce04-4abb-a222-1759921f6711.png)
![Snipaste_2021-12-20_14-37-13](https://user-images.githubusercontent.com/91770427/146723128-33cbb4d1-b365-410c-a7d9-2343793e1c93.png)
![Snipaste_2021-12-20_14-41-04](https://user-images.githubusercontent.com/91770427/146723137-c5b5ab8a-101a-4e58-9aa8-912ba5eb47cd.png)

**Comment by KotoriK** [comment]
你还需要下载新的js bundle
https://github.com/mirai-mamori/Sakurairo/commit/f0a4abfa1a0f4c62a74ee6b2c65f44b9d2ab4fe4

一般来说直接pull preview分支可能比自己应用更改要更加好 因为有时一个patch会分成多个commit提交
