### ISSUE TITLE
主页标题区域：文章摘要的对齐方式

### ISSUE THREAD

**Issue by VincentSHI1230** [mirai-mamori/Sakurairo#415]
**这是什么方面的想法？**
UI 界面

**这个想法具体是要实现什么？**
目前，主页文章摘要区域的对齐规则可能导致折行时由于英文单词或标点符号的影响显得参差不齐，尤其是当图片在左、摘要在右时。另外，在部分设备上，摘要的第四行字数不满，也影响了显示效果。因此，建议将摘要的对齐规则改为两端对齐。

**这个想法实现后有什么帮助？**
改善显示效果

**是否有具体的实现思路？**
.float-content p {
    text-align: justify;
}

**Comment by mirai-mamori** [comment]
不考虑该排版模式
