### ISSUE TITLE
无法更新 Manifest 路径（附带解决方案）

### ISSUE THREAD

**Issue by wekuchan** [mirai-mamori/Sakurairo#416]
**问题出处：**

主题自带设置-封面设置

**实际行为描述：**

提示找不到资源

**预期的行为：**

提示更新两个json文件

**复现步骤：**

新安装一次2.3.3版本主题，点击一次“更新 Manifest 路径”即可触发。

**解决方案：**

找到opt/options/theme-options.php，将
rest_url('sakura/v1/ database/update')
修改为
rest_url('sakura/v1/database/update')
保存文件，上传到主机即可。
（导致错误的原因就是因为这个空格）

我不会用github的pr，烦请作者大大改一下项目代码Orz

**Comment by KotoriK** [comment]
感谢🙏
