### ISSUE TITLE
手机端全屏显示未考虑浏览器地址栏宽度

### ISSUE THREAD

**Issue by DotNya** [mirai-mamori/Sakurairo#42]
手机端首页全屏显示未考虑浏览器地址栏宽度。
导致首页图片下端会有一部分内容需要下滑才能显示。
如果有开启波浪动效的话，波浪动效也需要下滑才能看见。
浏览器：Android Chrome 81.0.4044.117
具体情况：
Chrome浏览器在打开网页后默认地址栏是显示的，需要下拉网页才会自动隐藏地址栏。
在地址栏显示的情况下，首页会按照“地址栏未显示”的情况计算高度，导致图片底部及波浪需要下滑才能显示。

**Comment by mirai-mamori** [comment]
暂无好的解决办法。若您有好的解决方案，欢迎提交Pr
