### ISSUE TITLE
主页视频和音乐播放冲突

### ISSUE THREAD

**Issue by Sprit-Fun** [mirai-mamori/Sakurairo#421]
**问题出处：**

如果有音乐播放（比如使用主题自带的网易播放）和主页视频，并且播放主页视频，音乐播放器会被关闭并刷新页面来重新开启

**实际行为描述：**

如果播放了主页视频，音乐播放器则会消失 此时必须刷新页面来重新开启音乐播放器

**复现步骤：**

主题开启音乐播放以及主页视频功能，然后在主页点击播放视频，此时音乐播放器则会强制关闭

**Comment by mirai-mamori** [comment]
这算问题吗

**Comment by KotoriK** [comment]
> 这算问题吗

是旧版特性
