### ISSUE TITLE
使用懒加载后第二次进入相册模板图片会消失

### ISSUE THREAD

**Issue by Sprit-Fun** [mirai-mamori/Sakurairo#422]
**大致范围：**

相册模板

**具体行为描述：**

开启主题自带的懒加载后，第一次进入相册模板页面显示一切正常，但切换一个页面后重新返回相册模板页面后所有图片将消失，必须刷新来重新显示

**尝试：**

试过不同灯箱，没有解决问题

**补充信息：**

感觉是因为懒加载不知什么原因没有重新加载相册图片

**Comment by Sprit-Fun** [comment]
补充：发现了错误信息，貌似是因为app重新declare 会继续研究代码位置
![image](https://user-images.githubusercontent.com/43423211/148030340-3bde7f41-02a7-40ea-a7c3-0fa8dc16b013.png)

**Comment by KotoriK** [comment]
给下主题版本

**Comment by KotoriK** [comment]
已在 5eea1b16a468288a9adadd277e546b70b3700221 修复
