### ISSUE TITLE
建议新增摘要图片功能

### ISSUE THREAD

**Issue by VincentSHI1230** [mirai-mamori/Sakurairo#424]
**这是什么方面的想法？**
新增功能

**这个想法具体是要实现什么？**
使用户可以添加一张图片，在微信、QQ、知乎等卡片分享场景中指定为卡片的摘要图片。

**这个想法实现后有什么帮助？**
目前，大多数主流平台的卡片分享摘要图片均为自动抓取页面的第一张图片。由于各家算法不同，实测结果是，在不开启伪静态的情况下，无论分享的链接是否为博客主页，微信总会抓取到主页头像、QQ时好时坏，而知乎会抓取到主页社交区域的第一张图标 (大多数为左箭头或微信图标)。这些抓取程序在抓取不使用伪静态的url时访问到的是不含路径参数的index.php (即网站主页)，这使得WordPress博客的卡片分享能力较为尴尬。因此，如果能诱导第三方应用抓取到准备好的图片，可以提高使用本主题的博客在社交平台的分享能力，尤其是方便站长在知乎等平台分享引流。

**是否有具体的实现思路？**
在主页的body标签内最顶端添加一个display为none的img即可。

**补充信息：**
如果添加此功能，建议同时提醒用户，使用边长在300px左右的正方形图片，能获得最大的抓取成功率（该数据来自知乎）

**Comment by KotoriK** [comment]
我觉得这应该是由插件实现的功能
你可以先看看有没有现成的插件

**Comment by VincentSHI1230** [comment]
> 我觉得这应该是由插件实现的功能你可以先看看有没有现成的插件

事实上有使用过多款社会化分享插件。
确实存在一些社会化分享插件能够实现此功能，但其往往只能支持Twitter、Facebook等平台 (估计是有私有协议)，国内软件依然会在文档中自动抓取从而导致前述问题。
因此，最稳妥的办法依然是通过主题来支持 (目前我是靠修改主题文件实现的。另外，国内也有其他主题包含此功能)。

**Comment by KotoriK** [comment]
如果已经有了稳定成熟的实现可以直接pr
