### ISSUE TITLE
使用api随机图作为封面图片

### ISSUE THREAD

**Issue by likepoems** [mirai-mamori/Sakurairo#425]
浏览器报has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by xiqoqi** [comment]
‘封面随机背景图片缓存’ 是不是把这个选项打开了然后api还不能接受跨域请求
![image](https://user-images.githubusercontent.com/58991169/150376948-820bce94-6818-4e96-93fd-ea11af99b6fb.png)
关了或许就好了
