### ISSUE TITLE
希望可以自定义替换JsD的资源地址

### ISSUE THREAD

**Issue by xiqoqi** [mirai-mamori/Sakurairo#428]
如今JsD会使网站加载变慢，资源本地化也确实对小带宽机器不够友好；所以我把 Fuukei/Public_Repository 库里的资源都放到了腾讯云cos上并套上了cdn，然后把设置里的地址都改了一下，不过似乎还是有一些资源走的是JsD

希望可以出一个选项，可以选择走JsD资源 还是本地资源 还是自定义资源地址
比如选JsD的话资源地址就是https://cdn.jsdelivr.net/gh/Fuukei/Public_Repository@latest/xxx
选本地的话资源地址就是https://本地/xxx
选自定义的话资源地址就是https://自定义地址/xxx

**Comment by VincentSHI1230** [comment]
> 如今JsD会使网站加载变慢，资源本地化也确实对小带宽机器不够友好；所以我把 Fuukei/Public_Repository 库里的资源都放到了腾讯云cos上并套上了cdn，然后把设置里的地址都改了一下，不过似乎还是有一些资源走的是JsD
> 
> 希望可以出一个选项，可以选择走JsD资源 还是本地资源 还是自定义资源地址 比如选JsD的话资源地址就是https://cdn.jsdelivr.net/gh/Fuukei/Public_Repository@latest/xxx 选本地的话资源地址就是[https://本地/xxx](https://%E6%9C%AC%E5%9C%B0/xxx) 选自定义的话资源地址就是[https://自定义地址/xxx](https://%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9C%B0%E5%9D%80/xxx)

路过，提个小问题
使用对象存储的话，如何保证能够完美迁移静态资源到桶且文件的链接结构不会出现异常，如何应对静态资源版本更新的问题(～￣▽￣)～

**Comment by xiqoqi** [comment]
> > 如今JsD会使网站加载变慢，资源本地化也确实对小带宽机器不够友好；所以我把 Fuukei/Public_Repository 库里的资源都放到了腾讯云cos上并套上了cdn，然后把设置里的地址都改了一下，不过似乎还是有一些资源走的是JsD
> > 希望可以出一个选项，可以选择走JsD资源 还是本地资源 还是自定义资源地址 比如选JsD的话资源地址就是https://cdn.jsdelivr.net/gh/Fuukei/Public_Repository@latest/xxx 选本地的话资源地址就是[https://本地/xxx](https://%E6%9C%AC%E5%9C%B0/xxx) 选自定义的话资源地址就是[https://自定义地址/xxx](https://%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9C%B0%E5%9D%80/xxx)
> 
> 路过，提个小问题 使用对象存储的话，如何保证能够完美迁移静态资源到桶且文件的链接结构不会出现异常，如何应对静态资源版本更新的问题 (～￣▽￣)～

静态资源都放在github仓库了，我是直接下载然后解压上传到cos上的

如果有更新的话我是打算手动重新上传，不过如果有大佬的话大概能利用腾讯云提供的api自动更新吧

**Comment by mirai-mamori** [comment]
2.4即将实装
