### ISSUE TITLE
希望增加PJAX的MathJax的支持或教程

### ISSUE THREAD

**Issue by KDreamForest** [mirai-mamori/Sakurairo#430]
RT

**Comment by KotoriK** [comment]
新年快乐！感谢你对Sakurairo的支持。

目前，主题对mathjax的支持仅限于mathml，
主题会自动检测文章中的```\<math> ```标签并调用渲染。这一行为目前是不可以从主题设置自定的，未来会考虑将MathJax相关设置加入主题设置并支持LaTex。

关于如何深度自定义主题的教程，我们目前正在重构主题wiki，完成后会优先添加相关内容，敬请期待。
