### ISSUE TITLE
文章页面版权提示栏背景图片过大

### ISSUE THREAD

**Issue by VincentSHI1230** [mirai-mamori/Sakurairo#431]
**这是什么方面的想法？**
现有内容的优化

**这个想法具体是要实现什么？**
文章页面版权提示栏背景图片 (现为 https://cdn.jsdelivr.net/gh/Fuukei/Public_Repository@latest/vision/basic/creativecommons-light.png ) 过大 (28.7KB)，加载甚是折磨，有时候一整个文章页面就它半天出不来，建议替换

**这个想法实现后有什么帮助？**
解决该图片首次加载的恐惧

**是否有具体的实现思路？**
更换为更小的图片，这样能够提高加载速度。
考虑到图片特征，建议更换为svg格式，又小有高清，甚至能直接内嵌。
这里我已经用爆肝手搓+疯狂优化大法描好了，svg代码在下面，5KB多一点，请直接pr，好耶！
(～￣▽￣)～

**补充信息：**
![cce](https://user-images.githubusercontent.com/81342412/151203490-f50c0d5e-6d8e-4e5d-8a3b-9584614a13e7.svg)
`<svg width="4400" height="479" xmlns="http://www.w3.org/2000/svg" overflow="hidden"><defs><clipPath id="a"><path d="M0 997h4400v479H0z"/></clipPath><linearGradient x1="0" y1="1236.4" x2="4400" y2="1236.4" gradientUnits="userSpaceOnUse" spreadMethod="reflect" id="b"><stop offset="0" stop-color="#F2F2F2"/><stop offset=".2" stop-color="#F1F1F1"/><stop offset=".4" stop-color="#EEE"/><stop offset=".6" stop-color="#E8E8E8"/><stop offset=".8" stop-color="#E3E3E3"/><stop offset="1" stop-color="#DADADA"/></linearGradient></defs><g clip-path="url(#a)" transform="translate(0 -997)" fill-rule="evenodd"><path d="M0 998.4h4400v476H0v-476z" fill="url(#b)"/><path d="M238.2 997.4h104l1.9 1.7c3.7 5 6.6 10.7 8.5 17.2l-37 13.8a33.6 33.6 0 0 0-10.5-13.8c-2.5 2.1-6.4-14.5-37.6 6-8.2 9.6-14.8 41.5-.5 62.8 4.7 2.3 10.9 15.9 38.5 5.4 4.6-2.8 8.8-7.4 12.7-13.7l35.8 17c-17.7 37.9-83.7 53.2-122 17.5a84 84 0 0 1-4.8-102.8l11-11zM367 997.4h101l-5.7 22.7c-3.2-1.1-6.3-2-9.4-2.4-10.1-.7-17-3.2-31.4 10.2a47.7 47.7 0 0 0-8.6 30v71.5H367v-132zM490 997.4h99.4l12.2 22.1c2.9 9.7 4.4 20.9 4.4 33.8v13.5h-96.5c.7 9.5 4 17 10 22.7 10.5 2.5 6.1 14.6 39.4 4.1 4.8-3 9.2-7.2 13-13l33.6 19c-8.5 11-18 19-28.4 24-17.2 10.3-69 11-92.2-12.2-30-33-25-78.3-2.1-107.4l7.2-6.6zm55.6 10.8c-5.9-1.6-14.3-.7-26.7 8-5.3 5.8-8.6 13-9.7 21.7h54.5c0-10.2-2.1-17.8-6.4-22.8-2.3-1.2-5.8-5.3-11.7-6.9z" fill="#E6E6E6"/><path d="M622 997.4h107.2l8.8 14.3c2.7 8 4 17.1 4 27.8v88.5h-43.3v-16.6h-.6a55.6 55.6 0 0 1-76.8 8.6c-13.8-12-21-42-.6-65.3 8.8-8.9 21.7-14.3 38.8-16l39.4-4.3v-4.5c0-7.2-2.3-12.7-6.9-16.3-5-1.8-11.4-10.8-35.3-.7-5.2 3.2-10 8-14.2 14.2L612 1009l10-11.5zm77.1 64.9l-29.5 2.9c-6.9.8-11.9 2.7-15 5.7-4.6-3.1-13.6 46.9 36 19.5a30.7 30.7 0 0 0 8.5-22.5v-5.6zM746 997.4h104.6v16.4h-35.4v71.5c0 4.6 1 8.1 3 10.4 2.6.6-.6 4.2 14.7 2.4 2.2-.7 4.4-2.2 6.8-4.4l18.3 24.8c-12.5 13.5-51.6 22-75.8 2.5-8.2-7.8-12.2-19.6-12.2-35.2v-72h-24v-16.4zM866 997.4h46v131h-46v-131zM927 997.4h46.6l20.7 68.3c1 3.8 1.8 4 5.8 23h.5l2.8-11.3c.8-3.3 1.9-6.8 3.1-10.8l21.3-69.2h45.2l-48.3 131H973l-46-131zM1100 997.4h99.4l12.2 22.1c3 9.7 4.4 20.9 4.4 33.8v13.5h-96.5c.7 9.5 4 17 10 22.7 10.5 2.5 6.1 14.6 39.3 4.1 4.9-3 9.3-7.2 13.2-13l33.5 19c-8.5 11-18 19-28.4 24-17.2 10.3-69 11-92.2-12.2-30-33-25-78.3-2.1-107.4l7.2-6.6zm55.6 10.8c-5.9-1.6-14.3-.7-26.7 8-5.3 5.8-8.6 13-9.7 21.7h54.5c0-10.2-2.2-17.8-6.5-22.8-2.3-1.2-5.7-5.3-11.6-6.9zM354 1269.8a68.3 68.3 0 0 1-27.1 28.5c-22.2 12.7-68.7 14.8-94.8-11-54-64.7 8.4-169.3 98-125.4a50.6 50.6 0 0 1 22.4 30l-37 13.8c-2.9-6.3-6.4-11-10.5-13.9-2.5 2.2-6.4-14.5-37.6 6-8.2 9.7-14.8 41.8-.5 63.3 4.7 2.3 11 15.8 38.5 5.4 4.6-2.8 8.8-7.5 12.7-13.8l35.9 17.1z" fill="#E6E6E6"/><path d="M432.6 1307.4c-23.9 0-43.2-6.9-57.8-20.8-14.6-13.9-21.9-32.7-21.8-56.3a76.5 76.5 0 0 1 22.1-56.8c24.6-24.8 84-31.2 117.6 0 41.6 42.1 18.2 135.5-60.1 134zm1.5-35.6c11 0 19.5-4 25-12.2-.2-7.7 18.9-13.3-.1-61-4.7-1.3-15.8-24.7-50.7.8-.5 7.6-20 14-.4 60.6 5.8 7.8 14.6 11.8 26.2 11.8zM760.9 1302.4h-45.5v-85c0-10.2-2-17.6-5.9-22.7-3.6-1.6-13.6-17.4-36 1.9a38 38 0 0 0-7.2 23.4v82.3h-45.6v-84.8c0-10.2-2-17.7-5.8-22.8-3.6-2-13.4-17.1-36.2 1.4-4.7 6-7 14.1-7 24.4v81.8H526v-147.2h45.7v18.4h.6a50.7 50.7 0 0 1 19.9-15.9c7.9 0 12.4-14 53.2.3a40 40 0 0 1 16 16.7c6.6-7.8 14.1-13.6 22.7-17.4 10.3-5 43.5-11.9 63.5 9.3 8.9 10 13.4 24.8 13.4 44.1l-.1 91.8zM1014 1302.4h-45.3v-85c0-10.2-2-17.6-5.9-22.7-3.6-1.6-13.5-17.4-36 1.9a38 38 0 0 0-7.1 23.4v82.3h-45.5v-84.8c0-10.2-1.9-17.7-5.8-22.8-3.6-2-13.4-17.1-36.1 1.4-4.7 6-7 14.1-7 24.4v81.8H780v-147.2h45.5v18.4h.6a51.1 51.1 0 0 1 19.8-15.9c7.9 0 12.4-14 53.1.3a40.3 40.3 0 0 1 15.9 16.7 62.4 62.4 0 0 1 22.6-17.4c10.3-5 43.4-11.9 63.2 9.3 8.9 10 13.3 24.8 13.3 44.1v91.8zM1105.1 1307.4c-24 0-43.4-6.9-58.2-20.8-14.7-13.9-22-32.7-21.9-56.3a76.2 76.2 0 0 1 22.2-56.8c24.7-24.8 84.6-31.2 118.3 0 42 42.1 18.3 135.5-60.4 134zm1.5-35.6c11.2 0 19.6-4 25.2-12.2-.2-7.7 19.1-13.3 0-61-4.8-1.3-16-24.7-51 .8-.6 7.6-20.2 14-.5 60.6 5.8 7.8 14.6 11.8 26.3 11.8zM1340.9 1302.4h-45.2v-85c0-9.3-2-17-6-22.5-3.9-2.4-13.2-18-37.5.5-5.2 6-7.8 13.5-7.8 22.7v84.3H1199v-147.9h45.4v18.8h.6a51 51 0 0 1 20-16.3c11.8-6.6 44-11.2 63.2 9.5 8.5 10.4 12.8 25 12.8 44v92zM1350 1283.9l21.5-27.5c4.3 11.8 70.6 36.1 55.8-3.6a39.5 39.5 0 0 0-16.2-4.9c-19.7-2.9-33.7-8.2-42-16-13.7-13.7-19.6-42.3 2.8-65.6 18.5-10.5 25.5-19.4 71-9.7a64.4 64.4 0 0 1 23.8 13l-22 26.2c-5.7-4.1-11-7.2-16-9.2-6 .9.7-6.8-28.7.3 1.4 2.6-10.3.9 1 17.6a45 45 0 0 0 18.4 4.8c17.4 2 30.6 7 39.5 14.6a47.3 47.3 0 0 1-3.8 68.8c-24.3 9.3-44.5 32-105.1-8.8z" fill="#E6E6E6"/><path d="M3997 1407.4a68 68 0 0 1-27 28.3c-15.3 10-65.2 16.8-94.9-10.8-44.9-48.4-10.2-169.6 98-124.7a50.5 50.5 0 0 1 22.4 29.8l-37 13.8c-2.9-6.3-6.4-11-10.5-13.8-2 1.7-8.6-14-37.6 5.9-.5 6.6-20 15.7-.5 62.9 10.6 4 6.3 15.7 38.5 5.4 4.6-2.8 8.8-7.4 12.6-13.7l36 16.9z" fill="#D3D3D3"/><path d="M4138 1407.4a68 68 0 0 1-27 28.3c-15.3 10-65.2 16.8-94.9-10.8-44.9-48.4-10.2-169.6 98-124.7a50.5 50.5 0 0 1 22.4 29.8l-37 13.8c-2.9-6.3-6.4-11-10.5-13.8-2 1.7-8.6-14-37.6 5.9-.5 6.6-20 15.7-.5 62.9 10.6 4 6.3 15.7 38.5 5.4 4.6-2.8 8.8-7.4 12.7-13.7l35.9 16.9z" fill="#D0D0D0"/><path d="M3992.2 1128.4c173.7.6 278 177.2 215.6 325.3l-11.8 21.7h-46.6l3.3-4c82.3-124.7.3-283-139-297.8-170.8-16.3-264.8 171.6-178.8 297.8l3.3 4h-50l-11.7-21.7a234.5 234.5 0 0 1 215.7-325.3z" fill="#D4D4D4"/></g></svg>`

**Comment by KotoriK** [comment]
可以直接pr👏

**Comment by mirai-mamori** [comment]
不PR我就关啦？
