### ISSUE TITLE
弹广告

### ISSUE THREAD

**Issue by mengxin239** [mirai-mamori/Sakurairo#432]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：**

有广告

**具体行为描述：**

使用这个模板时会通过windows系统的提示框弹广告

**配置与环境：**

- 问题页面：https://blog.mengx.fun
- PHP 版本：7.3
- 数据库类型 / 版本：MySQL 5.5.62
- WordPress 版本：5.9
- 主题版本：（Release 标注的版本号）2.3.4
- 使用的插件：Live 2D，Telegram Bot & Channel，WP Mail SMTP，WP Telegram
- 浏览器：Chrome

**截图（若有）**

https://cdn.jsdelivr.net/gh/mengxin239/profile_photos/photo_2022-02-01_16-05-46.jpg

**补充信息：**

一般都是一些VPN啥的，如果不是这个模板带的广告我会自己继续查找原因，如果是麻烦告诉我在那个文件，我去自己修改
CloudFlare给我送了个新年大礼，现在我所有网站全都报废，加我TG发你ip@mengxin_2333

**Comment by mirai-mamori** [comment]
不是


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 萌新 ***@***.***>
发送时间: Tuesday, February 1, 2022 4:08:06 PM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mirai-mamori/Sakurairo] 弹广告 (Issue #432)


注意，在求助的时候请描述清楚你的问题，并保持耐心
在你阅读过这段文本之后，就可以删除这段引用文本

大致范围：

有广告

具体行为描述：

使用这个模板时会通过windows系统的提示框弹广告

配置与环境：

  *   问题页面：https://blog.mengx.fun
  *   PHP 版本：7.3
  *   数据库类型 / 版本：MySQL 5.5.62
  *   WordPress 版本：5.9
  *   主题版本：（Release 标注的版本号）
  *   使用的插件：Live 2D，Telegram Bot & Channel，WP Mail SMTP，WP Telegram
  *   浏览器：Chrome

截图（若有）

https://cdn.jsdelivr.net/gh/mengxin239/profile_photos/photo_2022-02-01_16-05-46.jpg

补充信息：

一般都是一些VPN啥的，如果不是这个模板带的广告我会自己继续查找原因，如果是麻烦告诉我在那个文件，我去自己修改

―

**Comment by mengxin239** [comment]
哦哦，好的好的，我重新安装一遍WordPress试试

**Comment by Hash070** [comment]
没有广告，建议重装并开启https，估计是被劫持了
