### ISSUE TITLE
JsDelivr源部分地区网络运营商会屏蔽，导致无法访问

### ISSUE THREAD

**Issue by axelwong** [mirai-mamori/Sakurairo#435]
主题版本：2.3.4

------

在我所在的地区，网络运营商会屏蔽JsDelivr源，导致网页部分文件无法访问

在尝试对项目部分可替换文件进行cdn链接替换后仍然有部分资源无法访问

然后尝试，在开启`本地化前端库`和`本地化 JS/CSS 文件`后部分文件仍然无法访问

![](https://inews.gtimg.com/newsapp_ls/0/14490857229/0.png)

**Comment by KotoriK** [comment]
重复#428 #426 #414
