### ISSUE TITLE
播放器问题

### ISSUE THREAD

**Issue by MomentQYC** [mirai-mamori/Sakurairo#436]
**问题出处：**

播放器问题

**实际行为描述：**

设置主题播放器开启，实际上却没有显示

**预期的行为：**

无法启用

**复现步骤：**

直接配置主题

**配置与环境：**

- PHP 版本：7.4
- 数据库类型 / 版本：MySQL5.7
- WordPress 版本：5.9
- 主题版本：2.2.6.1
- 使用的插件：已确认无关，因为之前同样这些插件未出现这种情况
- 浏览器：Edge 98.0.1108.43

**Comment by MomentQYC** [comment]
可能主题版本有点出入，反正是最新版本，群里的

**Comment by KotoriK** [comment]
先升版本

**Comment by MomentQYC** [comment]
> 

抱歉，版本看错了，确实是最新的，现在不知道为什么解决了，麻烦你们了
