### ISSUE TITLE
追番模板 点击next时报错Error: Error，Status：404

### ISSUE THREAD

**Issue by guhuanyuan** [mirai-mamori/Sakurairo#438]
**大致范围：**

追番模板
点击next时报错
Error: Error，Status：404

bangumi.js  24,28行

**具体行为描述：**

你的问题具体是什么？

**尝试：**

尝试更换blibli的cookie，未得到效果

**配置与环境：**
centos
Nginx 1.20.2

- 问题页面：http://guhuanyuan.top/?page_id=50
- PHP 版本：7.4
- 数据库类型 / 版本：mysql  5.6.50
- WordPress 版本：
- 主题版本：2.3.4
- 使用的插件：Hermit X ，Table of Contents Plus，Akismet 反垃圾评论
- 浏览器：遨游浏览器6.1.3.1001（64 位）0126

**截图（若有）**
![image](https://user-images.githubusercontent.com/47204511/153704848-4686549a-e8fb-450b-8cb4-9c6da68cc5f3.png)

**补充信息：**

求大佬指出错误原因

**Comment by KotoriK** [comment]
参考#156
