### ISSUE TITLE
随机图会对url的部分字符进行转义

### ISSUE THREAD

**Issue by keven1024** [mirai-mamori/Sakurairo#440]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

`主页设置 > 封面设置 > Webp优化/外部API桌面端随机图片地址`
`主页设置 > 封面设置 > 外部API手机端随机图片地址`

**实际行为描述：**

随机图api的url地址被部分转义，比如`&` => `&amp;`，导致随机图api无法正常工作

**复现步骤：**

添加带有&的随机图api地址并保存，然后打开你的首页，F12观察
`https://img.fudaoyuan.icu/api/1/random?scale_min=1.5&webp=true&md=false&format=302`
ps:如果不能访问就是我的nas关机或者断网了

**配置与环境：**

均为最新

**临时(偷懒)解决方法**

对被转义的字符再改回去
```
$imgurl = str_replace('&amp;','&',$imgurl);
```
添加于inc/classes/images.php

**补充信息：**

只是粗略看了下代码
个人猜测可能是iro_opt函数内有转义操作，由于我不熟悉代码就做了偷懒处理，抱歉没能pr

**Comment by KotoriK** [comment]
你的主题设置是怎么样的？直接在外部api地址粘贴了上述链接吗
