### ISSUE TITLE
报错Warning: strpos(): Empty needle in /usr/local/lighthouse/softwares/wordpress/wp-content/themes/Sakurairo-master/inc/theme_plus.php on line 542

### ISSUE THREAD

**Issue by SunchinSekian** [mirai-mamori/Sakurairo#443]
**问题出处：**

这个问题出在程序的哪一个具体功能？文章

**实际行为描述：**

报错
# 链接(URL)：http://124.222.132.159/
# 来源(Source)：SunchinSekian Blog

Warning: strpos(): Empty needle in /usr/local/lighthouse/softwares/wordpress/wp-content/themes/Sakurairo-master/inc/theme_plus.php on line 542

触发问题后造成了什么效果及影响？

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**打开特定的文章

怎样才能再次触发这个问题？

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：（Release 标注的版本号）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by SunchinSekian** [comment]
我搜索了issue，但我发现原问题并没有解决，于是又开了issue，希望作者多多包容

**Comment by SunchinSekian** [comment]
错误原因已经清楚了，是在文章里添加了超链接，请问该如何解决

**Comment by KotoriK** [comment]
原问题是哪个？ 使用的主题版本又是？

**Comment by SunchinSekian** [comment]
原版本：https://github.com/mirai-mamori/Sakurairo/issues/177
版本：iro 主题版本 / Theme Version 2.3.4 | [项目地址 / Project Address](https://github.com/mirai-mamori/Sakurairo)

**Comment by SunchinSekian** [comment]
> 原问题是哪个？ 使用的主题版本又是？
原版本：https://github.com/mirai-mamori/Sakurairo/issues/177
版本：iro 主题版本 / Theme Version 2.3.4 | [项目地址 / Project Address](https://github.com/mirai-mamori/Sakurairo)

**Comment by KotoriK** [comment]
请提供一个您添加的超链接的范例

**Comment by KotoriK** [comment]
这是你没有在```设置 > 常规```中设置站点名称。
这种情况下：
https://github.com/mirai-mamori/Sakurairo/blob/0f92fc07148c4036ccaa83b23f0847b2cef57316/inc/theme_plus.php#L523-L537
$srcUrl会为空，导致527行的strpos()报错
