### ISSUE TITLE
2.4测试版出现的一个问题

### ISSUE THREAD

**Issue by DARKN233** [mirai-mamori/Sakurairo#445]
**大致范围：**
现在发现的只有进入文章，点击编辑地方会出现
**具体行为描述：**
点击文章，有个“编辑”的按钮，点击进入文章编辑，会出现一个Http错误的提示，但是可以正常使用.
你的问题具体是什么
**尝试：**

你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了
我自己进入后台试了下编辑没发现没有这样的报错，注销以后，进入登录界面又出现这样的问题了
**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：Php 8.0
- 数据库类型 / 版本：Phpadmin 5.1
- WordPress 版本：5.9
- 主题版本：）Theme Version 2.3.24.RC
- 使用的插件：
- 浏览器：Microsoft Edge 98.0.1108.56  (64 位)

**截图（若有）**

![无标题](https://user-images.githubusercontent.com/62866031/155111174-7ff4a829-2a1e-4366-a476-bede0076b7ca.png)

**补充信息：**

**Comment by DARKN233** [comment]
我的网址：https://xenolies.xyz/

**Comment by DARKN233** [comment]
刚刚我试了下，登录页面（wp-login）又没这个问题了

**Comment by DARKN233** [comment]
![image](https://user-images.githubusercontent.com/62866031/155111810-801071f0-4b1b-4f1f-90b5-5634623a55f8.png)
又出现了。。。啊🤦‍♂️

**Comment by DARKN233** [comment]
使用的话没有其他的问题，只有这个提示。

**Comment by KotoriK** [comment]
打开f12查看一下到底报了啥错

**Comment by DARKN233** [comment]
![image](https://user-images.githubusercontent.com/62866031/155442182-930cacc3-a2e0-48de-90ce-e211ff3adcd0.png)
![image](https://user-images.githubusercontent.com/62866031/155442860-b29c6e36-ebed-4060-bf45-c323d075fdd1.png)
截到了这两张图，因为报错一闪而过没来得及打开

**Comment by DARKN233** [comment]
现在升级到了最新的测试版
iro 主题版本 / Theme Version 2.3.24.RC3
还是一样的问题

**Comment by DARKN233** [comment]
2.4更新了，发现还有一样的问题，还出现了新的问题
![image](https://user-images.githubusercontent.com/62866031/155489445-e612cbef-ce2c-4b9e-8801-fca41f23f854.png)
群里说了新问题，然后群友说的方法没用Orz

**Comment by mirai-mamori** [comment]
#450 请整理一下已知内容并前往2.4版本专区反馈
