### ISSUE TITLE
2.4.0 版本 问题反馈专区

### ISSUE THREAD

**Issue by mirai-mamori** [mirai-mamori/Sakurairo#450]

**Comment by Ukenn2112** [comment]
## 设置功能 Bug

- 开启 `封面视频` 使用外部链接视频时无法加载封面 
  - 视频链接：https://cdn.jsdelivr.net/gh/Ukenn2112/UkennWeb@7.1/00001.mp4
  - 控制台报错：![image](https://user-images.githubusercontent.com/60847880/155489383-87b9aeb8-ffc6-4d8c-b810-9af9ef50e16b.png)

- 开启 `音符触动特效` 后 pjax出现问题无法加载图片
   - 控制台报错：![image](https://user-images.githubusercontent.com/60847880/155488949-0a297fd5-517b-420d-83f5-d7a6e116ba6c.png)

**Comment by wangjiaqingll** [comment]
1. 手机浏览器封面图和文章特色图无法显示；
2. 手机浏览器侧边栏按钮点击无反应；
3. 评论提交按钮（BiuBiuBiu~）不居中，与评论框对比稍有错位就很难受！（不算bug）

**Comment by DARKN233** [comment]
![image](https://user-images.githubusercontent.com/62866031/155489572-a0f1c6ce-114d-452f-9a74-3bb3328d2d50.png)
这个问题按照群友说的”重新设置一遍“的方法没有作用，之前测试版有的莫名其妙的BUG正式版还存在
![image](https://user-images.githubusercontent.com/62866031/155489815-d3d824f3-cab7-441d-9c2d-eed6abca0b3e.png)

**Comment by xiaozhi-6** [comment]
前提：
单独下载的正式版Sakurairo 2.4.0，解压在了独立的文件夹中，并非覆盖版本
所有设置均重置并且测试没有问题（社交模块没有修改 图还是炸的）
已经清理了CDN缓存和其他可能影响的因素
问题：
1.粒子特效不能加载，疑似是资源问题，控制台报错为404
![image](https://user-images.githubusercontent.com/87865570/155489234-dd16a6e7-23f7-4bbc-af74-14acd1a4311a.png)
下面是控制台信息
![image](https://user-images.githubusercontent.com/87865570/155489422-7d3ab987-91fd-4ef3-b7c0-40259478f744.png)
2.谷歌统计报错，确认ID正确之后仍然不能加载（这个不一定是共性）
![image](https://user-images.githubusercontent.com/87865570/155489782-77c7d765-7bf7-4afb-9dda-b42b33e7e008.png)

**Comment by xiaozhi-6** [comment]
## 关于特色图片（api随机图片的问题请看这里）
### 如果出现不能加载特色图片，请尝试以下几步
#### 1.如果你开启了预加载，请关闭后在尝试
#### 2.如果你从未修改过api地址（原地址为：https://api.maho.cc/random-img/mobile.php）
#### 这个样子的，请尝试修改api地址，这里给出两个测试的api地址：
#### PC端：https://api.tonnai.com/pic-ecy/pc/rand.php
#### 移动端：https://api.tonnai.com/pic-ecy/mobile/rand.php
#### 3.请清理你的缓存和刷新CDN（如果你已经配置）
#### 4.不要忘了同时修改文章区域设置里面的“文章区域装饰特色图片外部API随机图片地址”（如果你已经设置）

**Comment by aquausora** [comment]
1. 替换鼠标光标的功能似乎失效了，即便填写了Cur鼠标文件链接但还是显示默认的光标
2. FancyBox灯箱无法正常加载，体现为点击图片后直接打开了图片的新标签页

**Comment by Sayyiku** [comment]
代码高亮失效
![image](https://user-images.githubusercontent.com/77047823/155499318-f637e09b-8548-4ca9-aae8-7b21c64e6624.png)

**Comment by VincentSHI1230** [comment]
主页社交区域 微信图片缺半边
![image](https://user-images.githubusercontent.com/81342412/155525815-7990bfe7-80fe-4e4f-b6ae-e49b27815eb9.png)
原因是公共CDN上的图片（ https://jscdn-x.panbaidu.cn/source/Sakurairo_Vision/@2.4/display_icon/sora/wechat.png ）出了问题
![image](https://user-images.githubusercontent.com/81342412/155525959-535824d7-88ea-4c7f-8b5b-f9b450265ca7.png)

**Comment by KotoriK** [comment]
> 1. 替换鼠标光标的功能似乎失效了，即便填写了Cur鼠标文件链接但还是显示默认的光标
> 2. FancyBox灯箱无法正常加载，体现为点击图片后直接打开了图片的新标签页

关于第二点，请确认一下上一个大版本是否有类似问题？

**Comment by KotoriK** [comment]
来自jscdn.panbaidu.cn的脚本资源无法加载，可能是cdnjs的资源url与jsdelivr有区别导致的
可以通过关闭```从公共 CDN 提供第三方库```来避免。此选项关闭时会使用主题中打包的第三方库
如果希望在关闭上述选项的同时，依然从公共CDN获取第三方库，可以尝试关闭```本地提供关键前端资源```

**Comment by aquausora** [comment]
> > 1. 替换鼠标光标的功能似乎失效了，即便填写了Cur鼠标文件链接但还是显示默认的光标
> > 2. FancyBox灯箱无法正常加载，体现为点击图片后直接打开了图片的新标签页
> 
> 关于第二点，请确认一下上一个大版本是否有类似问题？

经测试，使用2.3.4版本不会出现此问题。

**Comment by DARKN233** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/62866031/155726578-be81bf04-a61f-4550-9a07-268dcd85e3b1.png">
发现文章旁边的菜单无了

**Comment by KotoriK** [comment]
请诸位试一下更新到 https://github.com/mirai-mamori/Sakurairo/commit/cb446a74165b85be140d2b17b7660dbb25dca9c5 能否解决上述所有文章页出现的问题

**Comment by SunchinSekian** [comment]
正式版什么时候修复呢？

**Comment by KotoriK** [comment]
https://github.com/mirai-mamori/Sakurairo/commit/9408063f7ab49c89a28dbf35a11c1ebbb0665269
本次更改预计修复：
-  文章内图片无法右键
-  'HTTP undefined' 现在会显示更详细的报错
- 光标无法更换
- 开启```音符触动特效```后控制台报错并可能影响其他功能正常运行
- 开启```封面视频```后控制台报错并可能影响其他功能正常运行

上次更改预计修复的：
- 评论提交按钮（BiuBiuBiu~）不居中
- 代码高亮，fancybox，mathjax，折叠、文章目录等一切仅在非主页使用的功能
关于其他问题：
- 谷歌统计报错
    这个请求报的什么错？是被跨域拦截了，还是干脆404？
- 微信图标不完整
    请call爆 @mirai-mamori

**Comment by KotoriK** [comment]
覆盖不全的问题可以见#434

**Comment by xiaozhi-6** [comment]
# 2/27使用修正版遇到的问题
- ## 【严重！】网站加载卡顿，占用大量内存和CPU（甚至卡到打不开F12），视频如下

https://user-images.githubusercontent.com/87865570/155872825-f4f3c59f-87cc-4d4a-a501-93c629f497fb.mp4
### 我换了台设备也是这个情况，还望大佬们查明原因 
### <code>出现问题的网站</code> :   https://blog.chitudexiaozhi.com/
--- 
- ## 谷歌统计暂时没有报错了，（暂时）
--- 
- ## 其他问题
### 1.走第三方CDN库的时候依然不能加载jscdn.panbaidu的内容，显示为404   具体如图👇
![image](https://user-images.githubusercontent.com/87865570/155872956-fef1b1f7-f641-4a33-bf3b-bf0311fb7ce7.png)
### 后台设置情况：
![image](https://user-images.githubusercontent.com/87865570/155873236-329aa863-400c-47e2-8262-36f714672f8c.png)
### 2.当设置为如下情况时：
![image](https://user-images.githubusercontent.com/87865570/155873375-f13a29bb-96e9-49ab-bcbd-48d37d6a85bb.png)
### 会导致关键文件不能加载，如图👇
![image](https://user-images.githubusercontent.com/87865570/155873392-d8f03372-2008-4f3c-a0b3-eba0547f3ce8.png)
### 开启后虽然可以加载，但是网站会出现   <code>卡顿</code>
### 3.全部开启时网站可加载，但有   <code>卡顿</code>

**Comment by lucangshiyu1** [comment]
![image](https://user-images.githubusercontent.com/59046922/155941741-1cd35beb-1bb9-4952-9024-01bd43fabacb.png)
![image](https://user-images.githubusercontent.com/59046922/155941970-4523769a-c04e-4392-b1f4-d9214731e9c0.png)
![image](https://user-images.githubusercontent.com/59046922/155942046-5fafd5a6-6063-41c6-9f24-a2763de92f52.png)
图片跨域问题, 但图3证明跨域没问题

**Comment by KotoriK** [comment]
> ![image](https://user-images.githubusercontent.com/59046922/155941741-1cd35beb-1bb9-4952-9024-01bd43fabacb.png)
> 
> ![image](https://user-images.githubusercontent.com/59046922/155941970-4523769a-c04e-4392-b1f4-d9214731e9c0.png)
> 
> ![image](https://user-images.githubusercontent.com/59046922/155942046-5fafd5a6-6063-41c6-9f24-a2763de92f52.png)
> 
> 图片跨域问题, 但图3证明跨域没问题

是吗？你再想想

**Comment by VincentSHI1230** [comment]
2.4.0.1 bug 反馈
1. 导航栏二级菜单不居中 
![image](https://user-images.githubusercontent.com/81342412/156037897-72e2bddb-0041-41e2-9354-643e84f2599b.png)
1. 公共 CDN 资源 https://jscdn-x.panbaidu.cn/source/Sakurairo_Vision/@2.4/display_icon/sora/wechat.png 损坏的问题依然未解决，在此给瞳瞳磕一个求修复
![image](https://user-images.githubusercontent.com/81342412/156038515-7f4f527d-f2e4-4a4c-9b98-b7e3b97f1183.png)

**Comment by bymoye** [comment]
> 2.4.0.1 bug 反馈
> 
> 1. 导航栏二级菜单不居中
>    ![image](https://user-images.githubusercontent.com/81342412/156037897-72e2bddb-0041-41e2-9354-643e84f2599b.png)
> 2. 公共 CDN 资源 https://jscdn-x.panbaidu.cn/source/Sakurairo_Vision/@2.4/display_icon/sora/wechat.png 损坏的问题依然未解决，在此给瞳瞳磕一个求修复
>    ![image](https://user-images.githubusercontent.com/81342412/156038515-7f4f527d-f2e4-4a4c-9b98-b7e3b97f1183.png)

是的 但其实 这个事情 不是我们导致的（

**Comment by zhuzhehao1999** [comment]
菜单的分类好像有问题，点击主页面菜单进去出现404
![image](https://user-images.githubusercontent.com/68537574/156606489-53f1079b-cf34-4361-aa3b-fc5adede8f8e.png)
用2.3的时候不会的

**Comment by NyaDoo** [comment]
2.4.0.1
从首页进入登录页面时可见如下报错：
![K$X%}KK$ZI 59RLV2V H%WB](https://user-images.githubusercontent.com/65238336/157041880-38a8fb6d-006e-4db7-8c6a-ea67ba5fd651.png)
控制台无报错。

**Comment by NyaDoo** [comment]
2.4.0.1
从首页进入说说页面，说说页面头像旋转动画失效。

**Comment by tangyuanpro** [comment]
2.4.0.1版本bug反馈
站点使用的是wp6.0，在开启了多站点模式的情况下，子站点使用Sakurairo2.4.0.1会把图片往主站点媒体文件夹送，从而导致无法使用媒体库显示的链接打开图片（链接对应的是子站点文件夹的），图片没有使用cdn，在默认主题下未出现此种情况
在使用Sakurairo主题的子站点上传图片后媒体库显示链接如下（依然是子站点目录，见/site/5）：
http://blog.luololita.com/wp-content/uploads/sites/5/2022/03/1639805651384.jpg
图片实际链接如下（实际上传在主媒体文件夹了）：
https://blog.luololita.com/wp-content/uploads/2022/03/1639805651384.jpg
在使用默认主题的子站点上传图片后媒体库显示链接如下（一切正常）：
http://test.luololita.com/wp-content/uploads/sites/2/2022/03/1639805651384.jpg
在使用默认主题的子站点上传图片的实际链接未发生变动
最终导致在使用Sakurairo主题的子站点下在媒体库上传的图片全部无法显示，需手动将链接修改为主媒体文件夹的

**Comment by realJiaoKan** [comment]
更换字体后展示区域意外换行
![image](https://user-images.githubusercontent.com/37239817/158086419-a5920aaf-9368-4263-8ac6-f098c6ebe9ff.png)
![image](https://user-images.githubusercontent.com/37239817/158086455-4c8fd5ca-135e-4177-ae6a-b475ce149427.png)

**Comment by realJiaoKan** [comment]
> 更换字体后展示区域意外换行 ![image](https://user-images.githubusercontent.com/37239817/158086419-a5920aaf-9368-4263-8ac6-f098c6ebe9ff.png) ![image](https://user-images.githubusercontent.com/37239817/158086455-4c8fd5ca-135e-4177-ae6a-b475ce149427.png)

目前我的解决方式就是在自定义CSS中加入下面这几行:
```
.top-feature-row {
    white-space: nowrap;
}
```

**Comment by KotoriK** [comment]
> 2.4.0.1版本bug反馈 站点使用的是wp6.0，在开启了多站点模式的情况下，子站点使用Sakurairo2.4.0.1会把图片往主站点媒体文件夹送，从而导致无法使用媒体库显示的链接打开图片（链接对应的是子站点文件夹的），图片没有使用cdn，在默认主题下未出现此种情况 在使用Sakurairo主题的子站点上传图片后媒体库显示链接如下（依然是子站点目录，见/site/5）： http://blog.luololita.com/wp-content/uploads/sites/5/2022/03/1639805651384.jpg 图片实际链接如下（实际上传在主媒体文件夹了）： https://blog.luololita.com/wp-content/uploads/2022/03/1639805651384.jpg 在使用默认主题的子站点上传图片后媒体库显示链接如下（一切正常）： http://test.luololita.com/wp-content/uploads/sites/2/2022/03/1639805651384.jpg 在使用默认主题的子站点上传图片的实际链接未发生变动 最终导致在使用Sakurairo主题的子站点下在媒体库上传的图片全部无法显示，需手动将链接修改为主媒体文件夹的

有些疑惑
记忆中主题应该不会影响到媒体库上传

**Comment by tangyuanpro** [comment]
> > 2.4.0.1版本bug反馈 站点使用的是wp6.0，在开启了多站点模式的情况下，子站点使用Sakurairo2.4.0.1会把图片往主站点媒体文件夹送，从而导致无法使用媒体库显示的链接打开图片（链接对应的是子站点文件夹的），图片没有使用cdn，在默认主题下未出现此种情况 在使用Sakurairo主题的子站点上传图片后媒体库显示链接如下（依然是子站点目录，见/site/5）： http://blog.luololita.com/wp-content/uploads/sites/5/2022/03/1639805651384.jpg 图片实际链接如下（实际上传在主媒体文件夹了）： https://blog.luololita.com/wp-content/uploads/2022/03/1639805651384.jpg 在使用默认主题的子站点上传图片后媒体库显示链接如下（一切正常）： http://test.luololita.com/wp-content/uploads/sites/2/2022/03/1639805651384.jpg 在使用默认主题的子站点上传图片的实际链接未发生变动 最终导致在使用Sakurairo主题的子站点下在媒体库上传的图片全部无法显示，需手动将链接修改为主媒体文件夹的
> 
> 有些疑惑 记忆中主题应该不会影响到媒体库上传

可惜确实有这个问题，我有个也是用Sakurairo主题的朋友也复现了这个问题，要不你留个邮箱我给您开个超管账号你来复现一下，Thanks♪(･ω･)ﾉ

**Comment by Sprit-Fun** [comment]
新版本更新后出现图标404问题，更新前未出现此类问题。是否与服务器地点有关？
![0f01547d2494bc18a9bc0b95eac579c](https://user-images.githubusercontent.com/43423211/160062506-b730439e-6ad2-476e-b5f3-a40d63e67a0c.png)
![image](https://user-images.githubusercontent.com/43423211/160062494-51824ea8-f6a8-4572-aae2-21fbd79e5d3d.png)

**Comment by mirai-mamori** [comment]
> 新版本更新后出现图标404问题，更新前未出现此类问题。是否与服务器地点有关？ ![0f01547d2494bc18a9bc0b95eac579c](https://user-images.githubusercontent.com/43423211/160062506-b730439e-6ad2-476e-b5f3-a40d63e67a0c.png) ![image](https://user-images.githubusercontent.com/43423211/160062494-51824ea8-f6a8-4572-aae2-21fbd79e5d3d.png)

你都知道来这里反馈问题，那你为什么不看看上文呢

**Comment by Hash070** [comment]
在全局设置/额外设置/功能中，“下一页自动加载”选项，当选择“0秒”并保存设置后，刷新设置页面会发现该选项会被重置为“不自动加载”（选择大于0秒的选项则不会有问题）。
常试过重置主题设置，重新安装主题，禁用其他插件，都没有解决问题。
2.4.0和2.4.1中都有这个问题，在以前的版本中则没有这个问题

**Comment by VincentSHI1230** [comment]
> 在全局设置/额外设置/功能中，“下一页自动加载”选项，当选择“0秒”并保存设置后，刷新设置页面会发现该选项会被重置为“不自动加载”（选择大于0秒的选项则不会有问题）。 常试过重置主题设置，重新安装主题，禁用其他插件，都没有解决问题。 2.4.0和2.4.1中都有这个问题，在以前的版本中则没有这个问题

我也遇到了相同的bug

**Comment by bymoye** [comment]
> 在全局设置/额外设置/功能中，“下一页自动加载”选项，当选择“0秒”并保存设置后，刷新设置页面会发现该选项会被重置为“不自动加载”（选择大于2.4.0 和2秒4.1中有这个问题，在以前的版本中，则不会有 问题。则没有这个问题

推测为CSF框架将0判定为False并回到default

**Comment by Sprit-Fun** [comment]
请问一下如果CDN错误导致资源无法加载；设置了能访问的公共CDN也没用，这种情况该如何正确加载资源？主题现在很多资源无法正常加载：
https://github.com/mirai-mamori/Sakurairo/discussions/511#discussion-4045381
谢谢！

**Comment by mirai-mamori** [comment]
那你更新到2.5最新版啊

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: CLanNT ***@***.***>
发送时间: Monday, March 6, 2023 10:39:16 PM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: 染川瞳 ***@***.***>; State change ***@***.***>
主题: Re: [mirai-mamori/Sakurairo] 2.4.0 版本 问题反馈专区 (Issue #450)


音乐播放器不能正确加载歌单里的所有歌曲，只能加载出十首
[521$~`6A}967H{3BTKP{E}L]<https://user-images.githubusercontent.com/74392382/223141695-e5198eab-f624-4509-acc6-2518d60ffe67.png>

―
