### ISSUE TITLE
导航栏是否可以设置为文章分类

### ISSUE THREAD

**Issue by lutcraft** [mirai-mamori/Sakurairo#452]
我原本使用的是Sakura主题，此主题中导航栏被自动设置为文章的一级分类，但现在用到Sakurairo后，导航栏显示的是 页面 ，请问我如何切换回去，我在配置文件中寻找了很久也没有发现相关设置，谢谢

**Comment by KotoriK** [comment]
有没有可能```个性化 > 菜单```里头有选项

**Comment by lutcraft** [comment]
我在外观>菜单中找到了对应的设置，感谢解答
