### ISSUE TITLE
切换页面后菜单栏无法展开/收缩

### ISSUE THREAD

**Issue by handong-net** [mirai-mamori/Sakurairo#454]
选择设置菜单栏默认收缩后，进入站点首页，第一次菜单栏可以正常展开、收缩，切换至文章页后，则无法展开/收缩，再次返回首页后，菜单栏可以正常展开、收缩。当前页面刷新一次，菜单栏可以正常展开、收缩。

同样，若在文章页第一次点击菜单栏，可以正常展开、收缩，但切换至首页后，则无法展开/收缩，再次返回文章页面后，菜单栏可以正常展开、收缩。

复现步骤：
打开首页，点击菜单栏，可以正常展开、收缩，点击任意文章页面，此时点击菜单栏，无反应，返回或刷新当前页面，点击菜单栏，又可以正常展开、收缩。

另外提一个建议，在高分辨率访问时，首页封面有时候（图片分辨率不足时）会自动重复多张图片，后台能否增加设置选择平铺或者填充背景图。

- 问题页面：https://handong.net
- PHP 版本：74
- 数据库类型 / 版本：MySQL 5.7.34
- WordPress 版本：5.9.1
- 主题版本：2.4.0.1
- 使用的插件：CDN Enabler\WP Statistics\WP-China-Yes\Easy WP SMTP
- 浏览器：Microsoft Edge版本 98.0.1108.62

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
> 另外提一个建议，在高分辨率访问时，首页封面有时候（图片分辨率不足时）会自动重复多张图片，后台能否增加设置选择平
> 铺或者填充背景图。

主题设置里有的 你在```封面```那边找找

**Comment by handong-net** [comment]
> > 另外提一个建议，在高分辨率访问时，首页封面有时候（图片分辨率不足时）会自动重复多张图片，后台能否增加设置选择平
> > 铺或者填充背景图。
> 
> 主题设置里有的 你在`封面`那边找找

谢谢，找到了，在全局设置---样式菜单里面了，我以前也是光在封面找了，没找到选项。

另外我这个切换页面后菜单栏无法展开/收缩 是bug，还是我自己浏览器的兼容问题。

**Comment by KotoriK** [comment]
> > > 另外提一个建议，在高分辨率访问时，首页封面有时候（图片分辨率不足时）会自动重复多张图片，后台能否增加设置选择平
> > > 铺或者填充背景图。
> > 
> > 
> > 主题设置里有的 你在`封面`那边找找
> 
> 谢谢，找到了，在全局设置---样式菜单里面了，我以前也是光在封面找了，没找到选项。
> 
> 另外我这个切换页面后菜单栏无法展开/收缩 是bug，还是我自己浏览器的兼容问题。

逻辑问题 已经定位到了 现在在评估修改影响
