### ISSUE TITLE
封面签名栏打字特效消失

### ISSUE THREAD

**Issue by ycr10** [mirai-mamori/Sakurairo#455]
**问题出处：**

主页 封面 封面签名栏打字特效

**实际行为描述：**

封面签名栏打字特效无法使用，会直接显示。
F12会看到有两个js无法加载。

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL 5.5.62 
- WordPress 版本：5.9.1
- 主题版本：（Release 标注的版本号）2.4.0.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
![image](https://user-images.githubusercontent.com/62129032/156924717-62cbf5a4-db35-45d7-9dd8-3d535ace4211.png)
- 浏览器：（浏览器名称及版本号） Microsoft Edge 100.0.1183.0

**截图（若有）**
问题截图：
![image](https://user-images.githubusercontent.com/62129032/156924681-3f33294a-009d-4d22-9b32-3b2cbc60fcf9.png)

另附：签名栏以及社交媒体链接对移动端支持很差，能不能改进一下。特别是我这种签名长的人……
![image](https://user-images.githubusercontent.com/62129032/156924827-1b920e81-88e6-42ce-b6c4-89bc692709dc.png)

**Comment by KotoriK** [comment]
看F12 估计是typed.js没加载出来
#450 里边有个没加载出来的 可以看看是不是

**Comment by xiaozhi-6** [comment]
> **问题出处：**
> 
> 主页 封面 封面签名栏打字特效
> 
> **实际行为描述：**
> 
> 封面签名栏打字特效无法使用，会直接显示。 F12会看到有两个js无法加载。
> 
> **配置与环境：**
> 
> * 问题页面：（如果有，请提供一个触发此问题的页面链接）
> * PHP 版本：7.4
> * 数据库类型 / 版本：MySQL 5.5.62
> * WordPress 版本：5.9.1
> * 主题版本：（Release 标注的版本号）2.4.0.1
> * 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
>   ![image](https://user-images.githubusercontent.com/62129032/156924717-62cbf5a4-db35-45d7-9dd8-3d535ace4211.png)
> * 浏览器：（浏览器名称及版本号） Microsoft Edge 100.0.1183.0
> 
> **截图（若有）** 问题截图： ![image](https://user-images.githubusercontent.com/62129032/156924681-3f33294a-009d-4d22-9b32-3b2cbc60fcf9.png)
> 
> 另附：签名栏以及社交媒体链接对移动端支持很差，能不能改进一下。特别是我这种签名长的人…… ![image](https://user-images.githubusercontent.com/62129032/156924827-1b920e81-88e6-42ce-b6c4-89bc692709dc.png)

Sakurairo 2.4.0.1版本的打字特效需要在图示的位置设置，请大佬尝试一下
![image](https://user-images.githubusercontent.com/87865570/157452866-ce471636-67bd-47b4-852c-2d1adf0f470b.png)
