### ISSUE TITLE
希望增加本地随机图移动端和桌面端分离的功能

### ISSUE THREAD

**Issue by shiroa1** [mirai-mamori/Sakurairo#457]
在随机图设置中，若选择使用外部api，就可以有桌面端和移动端分离的功能，两端用不同的api从而得到适合两端的随机图。
但是如果将随机图设置改为本地，那么就没办法分离了，移动端和桌面端都是随机展示manifest文件夹中的图片。
希望可以增加本地随机图也可以像外部api那样分离移动端和桌面端的功能。
或许可以分为两个随机图文件夹，一个对应桌面端，一个对应移动端（？）

**Comment by bymoye** [comment]
#5b29d22e

**Comment by bymoye** [comment]
https://github.com/mirai-mamori/Sakurairo/commit/5b29d22efd4ecc3c185687e6d44a54dd031f166a 可能是你想要的
