### ISSUE TITLE
点击导航栏头像报错

### ISSUE THREAD

**Issue by klfd** [mirai-mamori/Sakurairo#460]
**问题出处：pc端，导航栏用户头像

这个问题出在程序的哪一个具体功能？

**实际行为描述：点击头像登录

触发问题后造成了什么效果及影响？

**预期的行为：点击头像后报错，且返回无法回到主页

这个功能应该有怎样的效果和影响？

**复现步骤：未登录状态下点击导航栏头像

怎样才能再次触发这个问题？

**配置与环境：wp版本5.9
- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.2/8.0
- 数据库类型 / 版本：mysql5.6.50
- WordPress 版本：5.9.2
- 主题版本：2.4.0.1
- 使用的插件：无
- 浏览器：微软edge

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：无
![Uploading E2615EAAE86027557E44895E2A4DEF48.png…]()

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
你这图根本没传上来啊

**Comment by mirai-mamori** [comment]
提供更多信息后再开启此issue
