### ISSUE TITLE
相册模板问题

### ISSUE THREAD

**Issue by bmegumi** [mirai-mamori/Sakurairo#461]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

相册模板

**实际行为描述：**

开启PJAX局部刷新时，第一次进入相册页面正常，第二次切换到相册页面时不显示照片，需手动刷新页面显示，或关闭pjax局部刷新

**预期的行为：**

开启PJAX局部刷新时，第一次进入相册页面正常，第二次切换到相册页面时不显示照片，需手动刷新页面显示，或关闭pjax局部刷新

**复现步骤：**

开启PJAX局部刷新 > 相册页面  > 切换页面 > 再次进入相册页面

**配置与环境：**

- 问题页面：https://maojinyan.cn/index.php/图库/
- PHP 版本：8.0
- 数据库类型 / 版本：mysql
- WordPress 版本：5.9
- 主题版本：2.4.1
- 使用的插件：
- 浏览器：

**截图（若有）**

**补充信息：**

**Comment by bymoye** [comment]
@KotoriK
