### ISSUE TITLE
纪念模式手机端随机封面图非黑白

### ISSUE THREAD

**Issue by YunDouYue** [mirai-mamori/Sakurairo#463]
**问题出处：**

- 纪念模式

**实际行为描述：**

- 手机端的随机图非黑白

**配置与环境：**

- 问题页面：
 - https://blog.tangbao.ltd/
- PHP 版本：
 - 80
- 数据库类型 / 版本：
 - MySQL5.6.5.0
- WordPress 版本：
 - 5.9.2
- 主题版本：
 - 2.4.1
- 使用的插件：
 - External Media without Import
 - Simple Local Avatars
- 浏览器：（浏览器名称及版本号）
 - Android Chrome 97.0.4692.98
**截图（若有）**
![7GI%%LLU8T(8_VMN)JIC`YD](https://user-images.githubusercontent.com/85783168/160266233-fdf4c929-0cd2-4298-9a5d-43c5e776ce0b.jpg)

**Comment by VincentSHI1230** [comment]
我也遇到了这种情况

**Comment by KotoriK** [comment]
很乐 
Chrome 100下```background-image```不会跟随施加在```html```和```body```上的filter
但是使用```background```属性就可以了

Safari 15.4下也是类似的情况，特殊的是可以用```-webkit-backdrop-filter```来达成目的 代价是不能和```filter```同时生效。
另外做了个小实验，给```body```加上```-webkit-backdrop-filter```会怎样，结果Safari的表现变得很不稳定，开关```background-image```和```-webkit-backdrop-filter```的时候会出现不能其中一个属性不及时生效的情况。

Firefox 96就更离谱一点 无论是background还是background-image filter都不会生效，甚至还会发生诡异的布局偏移

初步鉴定为是标准没有考虑到会这样玩的问题。
修改方案就是先换成```background```
