### ISSUE TITLE
登录页UI显示不完全

### ISSUE THREAD

**Issue by MomentQYC** [mirai-mamori/Sakurairo#464]
**问题出处：**

登录页

**实际行为描述：**

不完整的显示导致“注册”等选项无法被用户看见

**预期的行为：**

无

**复现步骤：**

只需要WordPress版本高一些+多语言版本

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL5.7
- WordPress 版本：5.9.2
- 主题版本：（Release 标注的版本号）2.4.1（所有版本其实都有这个问题）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）与插件无关
- 浏览器：（浏览器名称及版本号）与浏览器无关

**截图（若有）**

![image](https://user-images.githubusercontent.com/62551256/160273042-1faf6f65-bc48-4712-98e6-c29ef6422b3c.png)

**补充信息：**

无

**Comment by bymoye** [comment]
我的直觉告诉我是你自己设置的问题 ，而我实际看到的也是你自己设置的问题。请自己尝试解决

**Comment by MomentQYC** [comment]
然而并不是，只要是非单语言都有这个问题




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年4月5日(星期二) 凌晨0:44
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [mirai-mamori/Sakurairo] 登录页UI显示不完全 (Issue #464)





 
我的直觉告诉我是你自己设置的问题 ，而我实际看到的也是你自己设置的问题。请自己尝试解决

**Comment by bymoye** [comment]
> 然而，只要是非单有语言这个问题
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: 2022年4月5日(星期二) 凌晨0:44 To: ***@***.***&gt;; Cc: ***@***.***&gt;; ***@***.***&gt;; Subject: Re: [mirai-mamori/Sakurairo] 登录页UI显示不完全 (Issue #464) 我的直觉告诉我是你自己设置的问题 ，而我实际看到的也是你自己设置的问题。请自己尝试解决 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

非单语言是啥

**Comment by MomentQYC** [comment]
只要是WordPress某个版本之后，只要有不止一个语言包的WordPress都会显示这么个东西




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月5日(星期二) 上午10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mirai-mamori/Sakurairo] 登录页UI显示不完全 (Issue #464)





  
然而，只要是非单有语言这个问题
 …
 ------------------ Original ------------------ From: @.&gt;; Date: 2022年4月5日(星期二) 凌晨0:44 To: @.&gt;; Cc: @.&gt;; @.&gt;; Subject: Re: [mirai-mamori/Sakurairo] 登录页UI显示不完全 (Issue #464) 我的直觉告诉我是你自己设置的问题 ，而我实际看到的也是你自己设置的问题。请自己尝试解决 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
非单语言是啥
 
&mdash;

**Comment by bymoye** [comment]
![1](https://user-images.githubusercontent.com/27877470/161667039-a13ca631-e426-4545-af55-1ad9a08bf13c.png)
![2](https://user-images.githubusercontent.com/27877470/161667067-4a86cc14-ee2d-4a2e-9bb9-4eaa3ad1e3d8.png)
还是那句话 优先考虑自己的问题

**Comment by mirai-mamori** [comment]
新版会进行一点基础的优化，并且新增关闭多语言。不保证完全解决问题

**Comment by MomentQYC** [comment]
找到了，5.9.0开始的，但是有相当一部分人的屏幕是不适配的，这点我找人确认过




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月5日(星期二) 上午10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mirai-mamori/Sakurairo] 登录页UI显示不完全 (Issue #464)





 

 
 还是那句话 优先考虑自己的问题
 
&mdash;
