### ISSUE TITLE
希望添加获取文章首图作为封面的功能

### ISSUE THREAD

**Issue by whjysh** [mirai-mamori/Sakurairo#466]
1. 希望添加获取文章首图作为封面的功能
![image](https://user-images.githubusercontent.com/40263315/160313773-b0bc7265-4135-43ec-a88d-5ae6aa8eb573.png)
2. 希望添加更改分类页面下图片的自定义
![image](https://user-images.githubusercontent.com/40263315/160313855-a424915b-88f4-4e68-b2c7-c8425eab5bd4.png)

**Comment by weold957** [comment]
有同样的想法 ，获取首图或者是预览文章代码区

**Comment by zjgxcj** [comment]
wordpress本身就可以设置特色图片

**Comment by weold957** [comment]
> wordpress图片本身就可以设置特色

好的我已经找到了 非常感谢
