### ISSUE TITLE
如何全局设置文章字体的颜色

### ISSUE THREAD

**Issue by haozhihang123** [mirai-mamori/Sakurairo#467]
文章中字体的颜色容易和主题冲突。如果将透明度调成0，在白天模式下字体的颜色还行，但是如果在夜间模式，字体不是很亮，看着很别扭，请问图和更改字体显示的颜色。

**Comment by mirai-mamori** [comment]
夜间模式字体颜色会进行调整，目前暂不考虑开放设置内的自定义
