### ISSUE TITLE
封面签名栏打字特效占位语句失效

### ISSUE THREAD

**Issue by Offrande** [mirai-mamori/Sakurairo#468]
**问题出处：**

主页设置-封面设置-封面签名栏打字特效占位语句

**实际行为描述：**

封面签名栏打字特效占位语句失效

**预期的行为：**

显示封面签名栏打字特效占位语句

**复现步骤：**

所有设置均为默认，仅开启打字特效，无法显示封面签名栏打字特效占位语句

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：PHP-74
- 数据库类型 / 版本：MySQL 10.5.6-MariaDB
- WordPress 版本：5.9.2
- 主题版本：（Release 标注的版本号）2.4.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）无
- 浏览器：（浏览器名称及版本号）Safari 15.4

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by bymoye** [comment]
提供地址 / 优先考虑自己设置问题
