### ISSUE TITLE
封面签名栏打字特效占位语句的  字体颜色大小调整

### ISSUE THREAD

**Issue by aba3812** [mirai-mamori/Sakurairo#471]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**

 新增功能 / UI 界面 / 用户体验

**这个想法具体是要实现什么？**
### 封面签名栏打字特效占位语句的字体颜色大小调整

**这个想法实现后有什么帮助？**
### 
主页面美化
**是否有具体的实现思路？**

5
**补充信息：**
5

**Comment by KotoriK** [comment]
自己给签名栏加样式
