### ISSUE TITLE
建议 友情链接模板 可以选择特定分类链接展示

### ISSUE THREAD

**Issue by LYshiying** [mirai-mamori/Sakurairo#473]
**这是什么方面的想法？**

功能优化

**这个想法具体是要实现什么？**

`友情链接模板`页面可以设定**只显示**或**忽略**某分类的链接

在设定中可以对每个友情链接模板页面会展示的分类进行调整

**这个想法实现后有什么帮助？**

考虑到友情链接模板不一定用于友链，也可以用于如网页收藏夹等用途，展示各类不同的网页，或许可以用同一个模板制作不同页面分享不同类型的链接？

**Comment by bymoye** [comment]
欢迎提交pr
