### ISSUE TITLE
当登录弹出邮箱是否仍然正确的核对提醒时前端排版出现错误

### ISSUE THREAD

**Issue by VincentSHI1230** [mirai-mamori/Sakurairo#474]
**问题出处：**
登录页

**实际行为描述：**
当登录弹出邮箱是否仍然正确的核对提醒时，前端排版出现错误

**预期的行为：**
前端显示效果不理想，应该是登录页CSS只考虑了正常登录。

**复现步骤：**
当WordPress弹出该核对提醒时

**配置与环境：**
- PHP 版本：80
- 数据库类型 / 版本：不涉及
- WordPress 版本：5.9.3
- 主题版本：2.4.1
- 使用的插件：不涉及
- 浏览器：不涉及

**截图（若有）**
![image](https://user-images.githubusercontent.com/81342412/162098796-9ef5eef1-47c7-41fc-a3c6-2574fc796b3b.png)

**Comment by mirai-mamori** [comment]
确实是没适配
