### ISSUE TITLE
代码渲染出错

### ISSUE THREAD

**Issue by whjysh** [mirai-mamori/Sakurairo#476]
后台文章编辑截图：
![image](https://user-images.githubusercontent.com/40263315/162402191-3f000887-cdd0-4ccf-9e72-497e902aa5b2.png)

文章展示：
![image](https://user-images.githubusercontent.com/40263315/162402280-37018c5a-8e1c-41e6-8e66-d54afdefd83e.png)

-----

代码内容：
3. 建立mapper的xml文件，写具体的sql语句

   ```
   <?xml version="1.0" encoding="UTF-8" ?>
   <!DOCTYPE mapper
           PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
           "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
   <!--namespace ： UserMapper接口-->
   <mapper namespace="com.example.mapper.UserMapper">
       <!--resultType >> 实体类-->
       <select id="findAll" resultType="com.example.demo.UserInfo">
           select * from clock_system.user_info
       </select>
   </mapper>
   ```

------

代码渲染丢失

**Comment by KotoriK** [comment]
给个网址看看
另外不是很建议代码高亮不备注代码语言

**Comment by whjysh** [comment]
> 

https://blog.shaiol.cn/archives/154
已经添加了语言标记，没有解决
还有https://blog.shaiol.cn/archives/171    也是
![image](https://user-images.githubusercontent.com/40263315/163528133-8f64063b-6b31-4ffe-8726-e72aa8bc29e2.png)

![image](https://user-images.githubusercontent.com/40263315/163528075-710221c5-25c1-4075-8fda-7da45036956a.png)

**Comment by KotoriK** [comment]
<img width="249" alt="image" src="https://user-images.githubusercontent.com/52659125/163745905-8550f5ff-79ae-456f-b38c-de274de7536f.png">
很明显是您的md插件没有正确地转义xml格式
