### ISSUE TITLE
图片上传按钮错位

### ISSUE THREAD

**Issue by kurobaryo** [mirai-mamori/Sakurairo#48]
![20200604_005234](https://user-images.githubusercontent.com/30323316/83665427-fee5bf80-a5fd-11ea-8a6e-acd22ee20625.jpg)
大佬，我这边的上传图片的按钮错位了是怎么回事呢

**Comment by mirai-mamori** [comment]
还请说明移动端具体环境，并注明主题版本。

**Comment by leeeo-d** [comment]
移动端：Chrome, Android
主题版本为最新(v 1.13.6)

经测试，ios端(safari)及pc端(chrome)无此bug。

**Comment by mirai-mamori** [comment]
若能复现，请重新开启本Issue
