### ISSUE TITLE
主题前台背景切换夜间模式无法切换

### ISSUE THREAD

**Issue by NyaDoo** [mirai-mamori/Sakurairo#480]
主题前台背景切换点击夜间模式月亮图标后无法切换，需要点击图标偏右下角才可以正常切换。
下图图示中：点击红色部分无法切换，点击绿色部分可成功切换
![屏幕截图 2022-04-10 150431](https://user-images.githubusercontent.com/65238336/162606598-0ac62828-9d8c-4feb-8ce0-c6a48b8f4223.png)

**Comment by KotoriK** [comment]
乐
