### ISSUE TITLE
主题设置保存时出现问题

### ISSUE THREAD

**Issue by mashirotj** [mirai-mamori/Sakurairo#490]
**具体行为描述：**

保存时出现弹窗，只要点保存就会出现，具体见下图

**尝试：**

重装系统，宝塔，wordpress，问题依旧

**配置与环境：**

- 问题页面：
- PHP 版本：8.0
- 数据库类型 / 版本：mysql5.7
- WordPress 版本：5.9.3
- 主题版本：2.4.1
- 使用的插件：![Snipaste_2022-04-17_01-33-04.jpg](https://s2.loli.net/2022/04/17/5rbJqvGdnEDF6RB.jpg)
- 浏览器：chrome100&firefox100

**截图（若有）**

![Snipaste_2022-04-17_01-30-36.jpg](https://s2.loli.net/2022/04/17/c8Dfq3yjQ9xa6Yp.jpg)

**Comment by mashirotj** [comment]
已按照#136 尝试，问题依旧，关闭或是卸载nginx防火墙仍会出现此问题

**Comment by mirai-mamori** [comment]
参考 #355

**Comment by mashirotj** [comment]
> 参考 #355

![Snipaste_2022-04-17_09-42-39.jpg](https://s2.loli.net/2022/04/17/d5BiG7AzW1nUeF2.jpg)
他这个玄学就好了，我这不行啊

**Comment by KotoriK** [comment]
那为什么你的admin-ajax.php会报404呢

**Comment by xiaozhi-6** [comment]
> 那为什么你的admin-ajax.php会报404呢

## 奇怪 我这个报的是403
