### ISSUE TITLE
Font Awesome 无法加载

### ISSUE THREAD

**Issue by cocdeshijie** [mirai-mamori/Sakurairo#495]
**问题出处：**

使用Font Awesome图标的地方

**配置与环境：**

- PHP 版本：7.4和8.1都试过
- WordPress 版本：5.9.3
- 主题版本：2.4.5
- 浏览器: Chrome on Windows | 100.0.4896.88

**截图（若有）**

![](https://img.qwq.xyz/2022/2dde04d29909c.png)
![](https://img.qwq.xyz/2022/61a7a198839e5.png)

**Comment by SnowSwordScholar** [comment]
一样的问题，升到2.4.5后就这样了（应该，之前没注意，更新后检查了一遍发现的问题）
Chrome和Firefox都这样

**Comment by Sperte-sha** [comment]
我也遇到了。可在主题设置-关于主题-资源控制中将本地提供其他前端资源开启，可以解决。

**Comment by wdshine** [comment]
估计是cdn的原因，u-code的资源都用不了。除了右下角主题切换之外主页社交栏图标也加载不出来

**Comment by JMFANS** [comment]
要不本地化？然后走自己给网站套的cdn。
