### ISSUE TITLE
文章右侧目录不跟随

### ISSUE THREAD

**Issue by Sperte-s** [mirai-mamori/Sakurairo#497]
**问题出处：**

文章右侧目录

**实际行为描述：**

右侧目录不跟随文章一起下滑

**预期的行为：**

影响目录使用

**复现步骤：**

在https://www.timero.xyz/archives/40 界面向下滑

**配置与环境：**

- 问题页面：https://www.timero.xyz/archives/40
- PHP 版本：8.0
- 数据库类型 / 版本：MySQL/5.5.62
- WordPress 版本：5.9.3
- 主题版本：2.4.5
- 使用的插件：无
- 浏览器：Firefox 99.0.1(64位)

**截图（若有）**

![图片](https://user-images.githubusercontent.com/89120994/163832378-011f1e16-ad9e-4282-be45-a036a1e4dbb7.png)

**补充信息：**
文章无图片时不会触发，多图时会触发
在首页点进文章会触发这种情况，在全部文章界面点进文章不会触发，在阅读文章期间调整浏览器窗口大小会修复这种情况。

**Comment by Sperte-sha** [comment]
图片上传至站点时不会触发此问题，使用图床会触发此问题。

**Comment by KotoriK** [comment]
什么图床

**Comment by Sperte-s** [comment]
> 什么图床

基于onedirve自建的
刚刚把图片都改本地了，问题解决了。

**Comment by Sperte-s** [comment]
我看了看https://iro.tw/demo.html这里面的博客，用图床的也有这种情况，图片越多越明显。

**Comment by KotoriK** [comment]
这是因为：
1. 图片没有指定高度，浏览器没有为图片预留位置
2. 位于页面右侧的目录不会跟随页面resize

鉴于为图片指定高度是一个“最佳实践”，我推荐各位先试着把文章中的所有图片高度都指定了
