### ISSUE TITLE
视觉资源（除了Font Awesome以外的各种小图标）无法加载

### ISSUE THREAD

**Issue by XIAO-DOU-ZI** [mirai-mamori/Sakurairo#499]
**问题出处：**

图片资源服务器

**实际行为描述：**
图片资源服务器错误

触发问题后造成了什么效果及影响？
全站图片无法加载
**预期的行为：**
图片正常加载
这个功能应该有怎样的效果和影响？
全站图片无法加载
**复现步骤：**
https://x.jscdn.host/release/ucode-x/source/Sakurairo_Vision/@2.4/)/release/ucode-x/source/Sakurairo_Vision/@2.4/ 打开这个链接
怎样才能再次触发这个问题？
打开这个链接
**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.0
- 数据库类型 / 版本：MySQL 5.6.50
- WordPress 版本：5.9.3
- 主题版本：Theme Version 2.4.5

- 使用的插件：Yoast SEO
WP RSS Aggregator
WP Mail SMTP Pro
Simple Google reCAPTCHA
- 浏览器：Google crome 99.0.4844.74（正式版本） （64 位）

**截图（若有）**

**补充信息：**
无

**Comment by tang-guo-guo** [comment]
话说这就几个小图标不能改成本地加载吗，应该影响不大吧

**Comment by SnowSwordScholar** [comment]
一样的问题。国内部分地区加载不出来
发现每次像问问题总有人问过了。。。
`正在 Ping 4-2.hk.apigwtencent.com [119.28.201.187] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

119.28.201.187 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，`

**Comment by KotoriK** [comment]
可以暂时更改“视觉资源路径”到本地服务器或jsdelivr来解决问题
