### ISSUE TITLE
使用外部随机api时无法自动获取第一张图

### ISSUE THREAD

**Issue by kurobaryo** [mirai-mamori/Sakurairo#50]
无法自动获取第一张图的地址，单机下一张后正常获取。

**Comment by mirai-mamori** [comment]
请说明复现过程

**Comment by kurobaryo** [comment]
解决啦，是我自己的原因，用了webp格式ios不支持，当时用chrome的原因所以没法发现问题，不好意思啊。顺便一提很棒的主题，能有赞助通道吗

**Comment by Ukenn2112** [comment]
README的主题使用帮助下有赞助二维码通道,感谢你的支持😊

**Comment by kurobaryo** [comment]
刚刚赞助啦

Ukenn <notifications@github.com>于2020年6月9日 周二16:05写道：

**Comment by mirai-mamori** [comment]
谢谢🙏你对本项目的支持。
