### ISSUE TITLE
[bug report] 深色模式下封面显示过饱和

### ISSUE THREAD

**Issue by AstroNomen** [mirai-mamori/Sakurairo#501]
**问题出处，以及实际行为描述：**

深色模式下，封面图片饱和度会过高，严重影响阅读体验

**预期的行为：**

参考了一下主题作者的个人网站，夜间模式封面图片本应是套上一个减亮度的filter吧？或者说类似主题选项里的暗淡滤镜

**复现步骤：**

开启深色模式

**配置与环境：**

- 问题页面：封面
- PHP 版本：7.3.27
- 数据库类型 / 版本：MySQL 5.7.23
- WordPress 版本：5.9.3
- 主题版本：2.4.5
- 使用的插件：Akismet 反垃圾评论、Polylang、Jetpack、WP Mail SMTP、WPForms Lite
- 浏览器：Vivaldi 5.2.2623.39(Chrome/100.0.4896.133)、Edge 100.0.1185.50

**截图（若有）**

日间：
![image](https://user-images.githubusercontent.com/47104966/164974693-d7854263-043b-4d37-a30a-a2f44216f5b9.png)

深色模式：
![image](https://user-images.githubusercontent.com/47104966/164974668-38d766f8-cb86-4156-bf60-5d28dd34c13a.png)

使用暗淡滤镜(可以明显看出效果优于深色模式)：
![image](https://user-images.githubusercontent.com/47104966/164974797-d8626b5f-1376-4f39-922a-59f365bf6e64.png)

**补充信息：**

我所使用的深色模式的设置内容：
![image](https://user-images.githubusercontent.com/47104966/164974752-1d3ac16a-fe41-4b28-9a50-b5788615d814.png)

**Comment by KotoriK** [comment]
来个网址看看到底套的啥滤镜

**Comment by AstroNomen** [comment]
> 来个网址看看到底套的啥滤镜

https://autumnus.cn
并且其实是没有使用滤镜的状态，套暗淡滤镜只是想演示一下正常暗色模式封面应该呈现的效果
![image](https://user-images.githubusercontent.com/47104966/165006380-6ee7acdc-6368-4964-95d2-4b718068a979.png)

**Comment by mirai-mamori** [comment]
本质上就是套了降亮度的滤镜，参考iOS深色模式的调暗壁纸
