### ISSUE TITLE
资源404,并且主页背景设置异常

### ISSUE THREAD

**Issue by webyang-male** [mirai-mamori/Sakurairo#502]
**大致范围：**

前台背景相关设置

**具体行为描述：**

右下角背景设置工具箱不能显示

**尝试：**

重置选项并重新配置

**配置与环境：**

- 问题页面：https://www.bugjs.cn/
- PHP 版本：8.0
- 数据库类型 / 版本：MySQL 5.6.50
- WordPress 版本：5.9.3
- 主题版本：2.4.5
- 使用的插件：无
- 浏览器：谷歌 100.0.4896.60（正式版本） （64 位）

**截图（若有）**

![image](https://user-images.githubusercontent.com/52821367/164975711-4c3798bf-f05f-4d14-a964-489444881b2c.png)

![image](https://user-images.githubusercontent.com/52821367/164975740-4018f559-4183-43f8-a32a-838ebc76b070.png)

![image](https://user-images.githubusercontent.com/52821367/164975775-578a7297-3845-4662-8a0b-7beec9728a85.png)

**Comment by KotoriK** [comment]
[#499](https://github.com/mirai-mamori/Sakurairo/issues/499#issuecomment-1106020768)
