### ISSUE TITLE
呼叫 register_rest_route 的方式不正確。sakura/v1/image/upload 的 REST API route 定義缺少必要的 permission_callback 引數。如需公開 REST API route，請使用 __return_true 作為權限回呼。

### ISSUE THREAD

**Issue by tntapple219** [mirai-mamori/Sakurairo#503]
**问题出处：**

新增文章、頁面

**实际行为描述：**

無法新增文章、頁面

**预期的行为：**
無法新增文章、頁面
**复现步骤：**

**配置与环境：**

- 問題頁面：https://beizheng.cf/wp-admin/post-new.php
- PHP 版本：7.4
- 数据库类型 / 版本：
- WordPress 版本：5.9.3
- 主题版本：2.4.5
- 使用的插件：無
- 浏览器：Chrome 100

**截图（若有）**

![螢幕擷取畫面 2022-04-26 133237](https://user-images.githubusercontent.com/65000814/165228650-26cf1277-c0ea-4640-9a44-4fe8dc88cc00.png)

**补充信息：**

提供尽可能多的相关信息。

**Comment by bymoye** [comment]
Notice
