### ISSUE TITLE
仍然有大部分资源使用了jsdelivr，部分网络环境加载速度很慢，达到20多秒，严重拖累速度

### ISSUE THREAD

**Issue by whtrys** [mirai-mamori/Sakurairo#504]
rt，如何更改所有使用jsdelivr的资源的源，我已更改“视觉资源路径”为[https://jsdelivr.panbaidu.cn/gh/Fuukei/Sakurairo_Vision@2.4/](https://jsdelivr.panbaidu.cn/gh/Fuukei/Sakurairo_Vision@2.4/)，部分资源速度确实加快，但还是需要十多秒，若开启“从公共 CDN 提供第三方库”，页面将无法加载，排版会完全乱掉，请问有那些文件中调用了jsdelivr，可以通过手动更改cdn.jsdelivr.net为jsdelivr.panbaidu.cn来解决

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接） whtrys.space
- 主题版本：（Release 标注的版本号）2.4.5

**Comment by whtrys** [comment]
我已将所有设置中能改变jsdelivr的地方的链接全部改变，但还是会有资源从jsdelivr加载，我觉得大概率要从源文件下手了，请问在哪些文件中写死了jsdelivr

**Comment by mirai-mamori** [comment]
2.5统一进行修复
