### ISSUE TITLE
无法将网站cdn改为自建cdn

### ISSUE THREAD

**Issue by XIAO-DOU-ZI** [mirai-mamori/Sakurairo#505]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：**
无法将网站cdn改为自建cdn

**具体行为描述：**

无法将网站cdn改为自建cdn

**尝试：**

已经尝试过更改视觉资源路径，更改源文件，但其仍然无法通过cdn加载

**配置与环境：**

问题页面：（如果有，请提供一个触发此问题的页面链接）

PHP 版本：8.0

数据库类型 / 版本：MySQL 5.6.50

WordPress 版本：5.9.3

主题版本：Theme Version 2.4.5

使用的插件：Yoast SEO
WP RSS Aggregator
WP Mail SMTP Pro
Simple Google reCAPTCHA

浏览器：Google crome 99.0.4844.74（正式版本） （64 位）

**Comment by jipa233** [comment]
文件都写死了，用vscode搜一下改吧
