### ISSUE TITLE
有关登录跳转相关功能函数缺少引号导致其失效的问题

### ISSUE THREAD

**Issue by zhy201810576** [mirai-mamori/Sakurairo#506]
**问题出处：**

在项目下[ `inc/theme_plus.php` ](https://github.com/mirai-mamori/Sakurairo/blob/master/inc/theme_plus.php#L232)文件中(登录跳转相关功能函数)
第240行的`TYPE = <?php _e('dashboard','sakurairo')/*管理后台*/?>;`和第242行的`TYPE = <?php _e('home','sakurairo')/*主页*/?>;`缺少引号

**实际行为描述：**

登录跳转失效，无法完成倒计时5秒后跳转

**预期的行为：**

当完成登录后，用户跳转至主页，管理员跳转至后台

**复现步骤：**

登录时即可触发

**配置与环境：**

- 问题页面：登录页
- PHP 版本：7.4.28
- 数据库类型 / 版本：5.6.50
- WordPress 版本：5.9.3
- 主题版本：2.4.5
- 浏览器：Google Chrome 100.0.4896.127

**截图**
![登录跳转BUG](https://grayzhaohonyang.gitee.io/my-blog/img/%E7%99%BB%E5%BD%95%E8%B7%B3%E8%BD%ACBUG.png)

**Comment by KotoriK** [comment]
这咋不直接发个PR呢

**Comment by zhy201810576** [comment]
很抱歉作者，我不怎么会用Git，所以当时没想到发PR，很抱歉。我稍后将发起PR，您有空看一下。

您好，这里是GrayZ，请多关照(*^▽^*)

发件人: KotoriK
发送时间: 2022年5月1日 11:39
收件人: mirai-mamori/Sakurairo
抄送: 格雷Z洋洋; Author
主题: Re: [mirai-mamori/Sakurairo] 有关登录跳转相关功能函数缺少引号导致其失效的问题 (Issue #506)

这咋不直接发个PR呢

**Comment by KotoriK** [comment]
> 很抱歉作者，我不怎么会用Git，所以当时没想到发PR，很抱歉。我稍后将发起PR，您有空看一下。 您好，这里是GrayZ，请多关照(*^▽^*) 发件人: KotoriK 发送时间: 2022年5月1日 11:39 收件人: mirai-mamori/Sakurairo 抄送: 格雷Z洋洋; Author 主题: Re: [mirai-mamori/Sakurairo] 有关登录跳转相关功能函数缺少引号导致其失效的问题 (Issue #506) 这咋不直接发个PR呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

不必了 我已经改好了 等会你可以拉branch试试

**Comment by KotoriK** [comment]
笑死 晚了一步
