### ISSUE TITLE
登录界面 证明您的身份验证 样式错误

### ISSUE THREAD

**Issue by Wapriaily** [mirai-mamori/Sakurairo#507]
**问题出处：**

登录页面证明您的身份验证

**实际行为描述：**

CSS正常加载的情况下样式错误

**预期的行为：**

上下对齐，文本框能正常显示输入的数字

**复现步骤：**

登录界面多次密码错误后

**配置与环境：**

- 问题页面：登录页（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.0.17
- 数据库类型 / 版本：5.7.37
- WordPress 版本：5.9.3
- 主题版本：2.4.6（Release 标注的版本号）
- 浏览器：Google Chrome 100.0.4896.60（浏览器名称及版本号）

**截图**

![image](https://user-images.githubusercontent.com/52833112/165911851-723f530d-eee3-4aeb-b890-7e98f6b7cd8d.png)

**Comment by mirai-mamori** [comment]
俯瞰了一下，这应该是第三方插件的问题，不做兼容

**Comment by Wapriaily** [comment]
还真是，没注意到有个防爆破，以为是主题内置🧐
