### ISSUE TITLE
图标无法显示

### ISSUE THREAD

**Issue by linqihao2333** [mirai-mamori/Sakurairo#518]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/34388970/166853392-5b6762c3-9159-4391-9871-6ce6eaa7028f.png">

**Comment by Sprit-Fun** [comment]
此问题已有多次报告： #511 , #499 具体原因应该是CDN问题。尝试了更换视觉路径貌似没有修复；可以看下CDN走的是不是 x.cdn.host

**Comment by mirai-mamori** [comment]
合并至#495 一同处理
