### ISSUE TITLE
文章区域特色图片设置为外部API后 仍然调用封面随机图片的api地址

### ISSUE THREAD

**Issue by kirigirisan** [mirai-mamori/Sakurairo#519]
# **问题出处：**

首页的文章区域

# **实际行为描述：**

"文章区域装饰特色图片选项"设置为"外部API随机图片"并设置api地址后，仍然获取的是"封面随机图片"的api地址

# **预期的行为：**

从"文章区域装饰特色图片外部API随机图片地址"中获取图片

# **复现步骤：**

iro主题设置>>主页设置>>封面设置>>封面随机图片选项>>外部api>>多端分离>>填写外部API桌面端/移动端随机图片地址

iro主题设置>>主页设置>>文章区域设置>>文章区域装饰特色图片选项>>外部API随机图片>>填写文章区域装饰特色图片外部API随机图片地址

保存设置

已经提前关闭CDN服务，清理浏览器缓存，并使用无痕模式进入首页。

右击查看图片仍是封面随机图片api地址。使用f12查看源码发现src指向封面随即图片api地址，未能正确指向提前设置的文章区域装饰特色图片外部API随机图片地址

# **配置与环境：**

- 问题页面： https://gdufs2920.cloud
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL 5.6.50
- WordPress 版本：5.6
- 主题版本：2.4.5
- 使用的插件：偶尔启用WP Githuber MD撰写md格式文档作为博客文章，仅在撰写的时候启用，长期关闭
- 浏览器：Google Chrome  99.0.4844.84  /  Microsoft Edge 101.0.1210.32 

# **截图（若有）**
![封面设置](https://user-images.githubusercontent.com/43839744/166961051-b410a5f1-197a-4b8d-88cf-8fc5b8265e15.jpg)
![文章区域设置](https://user-images.githubusercontent.com/43839744/166961177-654d70fa-a020-4540-af35-f67a36141761.jpg)
![api不符](https://user-images.githubusercontent.com/43839744/166961207-ab073e20-4582-4cd2-989f-bad45d4942d6.jpg)

# **补充信息：**

查阅过issue #134 更换过api地址，仍然不行。

网站为80端口，已部署正规ca颁发的ssl证书，域名解析商为腾讯云

**Comment by kirigirisan** [comment]
# 问题解决状态
暂未解决
# 当前处理方法
考虑到服务器在境外 为了保证页面加载流畅 暂时将封面的api也设置为了文章区域图片的api（因为文章区域的图片为压缩过的webp类型图片 加载速度较快） 等待反馈ing~

**Comment by KotoriK** [comment]
这边打开您的网站看 封面图片是"https://gdufs2920.cloud/api/background/pc_webp.php" 这个地址

**Comment by kirigirisan** [comment]
> 这边打开您的网站看 封面图片是"https://gdufs2920.cloud/api/background/pc_webp.php" 这个地址

是的，已经在二楼进行了详情说明，因为这两天在建站需要经常进入网页，暂时将封面的图片api也设置为压缩过的图片的api地址↓



> # 问题解决状态
> 暂未解决
> 
> # 当前处理方法
> 考虑到服务器在境外 为了保证页面加载流畅 暂时将封面的api也设置为了文章区域图片的api（因为文章区域的图片为压缩过的webp类型图片 加载速度较快） 等待反馈ing~

现在已经重新设置了封面api和文章区域图片api，与issue保持一致。

**Comment by KotoriK** [comment]
你期望应该是哪个地址

**Comment by kirigirisan** [comment]
期望应该是封面图片和文章区域分开
封面是[background/pc.php](https://gdufs2920.cloud/api/background/pc.php)"
文章区域是[background/pc_webp.php](https://gdufs2920.cloud/api/background/pc_webp.php)

**Comment by mirai-mamori** [comment]
下个版本推
