### ISSUE TITLE
建议在视觉资源路径的提示文本中写上默认值

### ISSUE THREAD

**Issue by VincentSHI1230** [mirai-mamori/Sakurairo#523]
**这是什么方面的想法？**
设置内容优化

**这个想法具体是要实现什么？**
建议在 主题设置 - 关于主题 - 视觉资源路径 的提示文本中写上默认值 (例如当前版本的 `https://s.nmxc.ltd/sakurairo_vision/@2.5/`)，以免用户临时切换为其他路径想换回时忘了初始默认路径是什么。  
![image](https://user-images.githubusercontent.com/81342412/167533775-a5a43d18-9e9c-414c-9e65-669d95f4da2b.png)
╰(￣ω￣ｏ)

**这个想法实现后有什么帮助？**
同上

**是否有具体的实现思路？**
同上

**Comment by mirai-mamori** [comment]
你可以在wiki力屑


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 史文朔 ***@***.***>
发送时间: Tuesday, May 10, 2022 10:59:40 AM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mirai-mamori/Sakurairo] 建议在视觉资源路径的提示文本中写上默认值 (Issue #523)


这是什么方面的想法？
设置内容优化

这个想法具体是要实现什么？
建议在 主题设置 - 关于主题 - 视觉资源路径 的提示文本中写上默认值 (例如当前版本的 ***@***.***/)，以免用户临时切换为其他路径想换回时忘了初始默认路径是什么。
[image]<https://user-images.githubusercontent.com/81342412/167533775-a5a43d18-9e9c-414c-9e65-669d95f4da2b.png>
t(￣ω￣ｏ)

这个想法实现后有什么帮助？
同上

是否有具体的实现思路？
同上

―
