### ISSUE TITLE
主页封面图无法自动缩放

### ISSUE THREAD

**Issue by aquausora** [mirai-mamori/Sakurairo#524]
**问题出处：**

主页封面图

**实际行为描述：**

封面图无法自动缩放到合适的尺寸，在不同分辨率屏幕下显示效果不一，尤其是手机上，往往只能显示图片的一角（尽管采用多终端分离）。

**预期的行为：**

封面图应能自动缩放尺寸。

**复现步骤：**

更新主题到 2.5 版本即可复现，另，该问题在 2.5 版本之前从未出现。

无论选择 `外部API`  `Webp优化`  `本地` 何种方式都存在此问题。 

**配置与环境：**

- 问题页面：https://champhoon.xyz
- 主题版本：2.5
- 浏览器：Chrome 101.0.4951.54

**截图**

![](https://s2.loli.net/2022/05/10/zmE7vTtY358ydAq.jpg)

原图如下，可以看到明显只显示了一部分

![](https://cdn.jsdelivr.net/gh/aquausora/Picture-Repository@latest/wordpress/474UR-Kunikida-Hanamaru-Agh-I-can-t-get-up-Maru-in-Wonderland-IHOqpf-scaled.webp)

-----

手机端问题更加突出

![](https://s2.loli.net/2022/05/10/xCJjk4WdvZSXcY7.jpg)

原图如下

![](https://cdn.jsdelivr.net/gh/aquausora/Picture-Repository@latest/wordpress/87310264_p0.webp)

-----

目前已经尝试调整过主题设置中 `前台背景缩放方式` 无法解决此问题。

**Comment by KotoriK** [comment]
https://github.com/Fuukei/Sakurairo_Scripts/commit/c9598d1e14253903f4ee7f7ea81a8924f2a74673
