### ISSUE TITLE
对于现有的内容优化

### ISSUE THREAD

**Issue by HZ-TangBao** [mirai-mamori/Sakurairo#526]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**
- 现有内容的优化
现有内容的优化 / 新增功能 / UI 界面 / 用户体验

**这个想法具体是要实现什么？**

纪念模式可以定时开启，比如客户端的时间为512则自动开启纪念模式
页面剪切板版权提示可以自定义复制文本内容字节数量提示版权文本

**Comment by mirai-mamori** [comment]
版权提示是在js端写死的，如果不是很必要应该不考虑添加这个功能。
纪念模式定时开启能做但是意义不大，如果本地写死日期会不会出现不想要纪念的日子呢？因为每个人想要纪念的日子都不同。且如果是突发的事件又应该如何定时开启呢？如果我们不写死，改成在远程服务器判断，就需要专人去单独维护且大家依旧也不一定愿意纪念，这时候如果我们远程介入是否又欠妥呢
