### ISSUE TITLE
随机图中webp优化中的bug

### ISSUE THREAD

**Issue by lvtenghui** [mirai-mamori/Sakurairo#528]
**问题出处：**

随机图webp优化

**实际行为描述：**

随机图api返回500

**预期的行为：**

正常显示随机图

**复现步骤：**

按照文档使用命令生成webp文件后，将整个manifest上传至cdn，随后清空本地生成的文件，设置内填写cdn地址，最终导致500报错。

**临时解决方案：**

不要清空本地的生成的文件

**配置与环境：**

- PHP 版本：8.0.16
- 数据库类型 / 版本：MySQL 8.0.24
- WordPress 版本：5.9.3
- 主题版本：2.5.0.1
- 浏览器：Edge chrome内核

**Comment by lvtenghui** [comment]
复现过程是百分之百复现，临时解决方案也能解决，地址无法提供，影响我正常运行了...



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "染川 ***@***.***&gt;; 
发送时间: 2022年5月11日(星期三) 晚上9:56
收件人: ***@***.***&gt;; 
抄送: "Lv ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mirai-mamori/Sakurairo] 随机图中webp优化中的bug (Issue #528)





 
请提供地址

**Comment by bymoye** [comment]
> 复现过程是百复现，临时解决方案也能解决，地址无法提供，影响我正常运行了...
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "染川 ***@***.***&gt;; 发送时间: 2022年5月11日(星期三) 晚上9:56 收件人: ***@***.***&gt;; 抄送: "Lv ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mirai-mamori/Sakurairo] 随机图中webp优化中的bug (Issue #528) 请提供地址 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

无法提供那请自行解决 很遗憾无法复现
