### ISSUE TITLE
哔哩哔哩收藏模板php报错

### ISSUE THREAD

**Issue by lvtenghui** [mirai-mamori/Sakurairo#529]
**问题出处：**

模板页面

**实际行为描述：**

无法正常显示收藏模板

**复现步骤：**

填写完uid与cookies后，收藏模板报错

**配置与环境：**

- 问题页面：https://lvtenghui.com/136-2/
- PHP 版本：8.0
- 数据库类型 / 版本：MySQL 8.0.24
- WordPress 版本：5.9.3
- 主题版本：2.5.0.1
- 浏览器：Edge

**截图（若有）**

![image](https://user-images.githubusercontent.com/50571783/167709880-02a973fa-317e-4d70-9065-00834d95a22a.png)

**Comment by mirai-mamori** [comment]
有没有可能是因为你带端口呢

**Comment by mirai-mamori** [comment]
下个版本推送
