### ISSUE TITLE
搜索页面英文本地化：分类为中文

### ISSUE THREAD

**Issue by Sprit-Fun** [mirai-mamori/Sakurairo#530]
**问题出处：**

英文主题下，搜索页面的“分类”没有本地化

**实际行为描述：**

在英文主题下，进入搜索页面

**预期的行为：**

“分类”应为 'Category'

**复现步骤：**

用英文主题设置，其他标签都成功本地化，只有“分类”没有本地化。

**截图（若有）**

![image](https://user-images.githubusercontent.com/43423211/167981419-b8d7cec9-dd9e-4459-ad09-f7999dd6dee4.png)

**Comment by mirai-mamori** [comment]
欢迎pr👏

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Richard Lu ***@***.***>
发送时间: Thursday, May 12, 2022 10:43:21 AM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mirai-mamori/Sakurairo] 搜索页面英文本地化：分类为中文 (Issue #530)


问题出处：

英文主题下，搜索页面的“分类”没有本地化

实际行为描述：

在英文主题下，进入搜索页面

预期的行为：

“分类”应为 'Category'

复现步骤：

用英文主题设置，其他标签都成功本地化，只有“分类”没有本地化。

截图（若有）

[image]<https://user-images.githubusercontent.com/43423211/167981419-b8d7cec9-dd9e-4459-ad09-f7999dd6dee4.png>

**Comment by Sprit-Fun** [comment]
创PR了；如果有时间可以看一下
