### ISSUE TITLE
封面随机图片多终端分离 失效

### ISSUE THREAD

**Issue by Sualiu** [mirai-mamori/Sakurairo#532]
**问题出处：**
　　2.5.0.1版本  iro主题设置 → 主页设置 → 封面设置 → 封面随机图片多终端分离

**实际行为描述：**
　　关闭此选项以后，桌面端和移动端依旧会分别使用不同的随机图片地址。

**预期的行为：**
　　封面随机图片应当统一使用Webp优化/外部API桌面端随机图片地址。

**复现步骤：**
　　只需关闭此选项，选择不同图片测试即可。

**配置与环境：**

- 问题页面：无
- PHP 版本：ＰＨＰ８．１
- 数据库类型 / 版本：ＭＹＳＱＬ５．６
- WordPress 版本：５．９．３
- 主题版本：２．５．０．１
- 使用的插件：Easy WP SMTP
- 浏览器：Microsoft Edge 101.0.1210.39 (正式版本) (64 位)

**截图**
Webp优化/外部API桌面端测试图片：
![image](https://user-images.githubusercontent.com/42514208/168438995-538fed5b-06a8-4baf-9988-4893eb6bdd69.png)

外部API手机端测试图片：
![image](https://user-images.githubusercontent.com/42514208/168439022-5c85f2e8-706f-449e-97f2-eba230e37620.png)

具体设置如下，此时两端会显示不同图片：
![image](https://user-images.githubusercontent.com/42514208/168438943-e7414a67-8f86-4ef5-9743-6d0fe5f11c06.png)

**关闭设置**  并再次刷新页面（界面尺寸可能不正常，于浏览器F12中进行的测试并截图）：
PC端：
![image](https://user-images.githubusercontent.com/42514208/168439121-ddb6d31e-1084-4798-be95-5f006873a30a.png)
移动端：
![image](https://user-images.githubusercontent.com/42514208/168439145-483c1ef4-560a-4499-bc31-afb16171cc0c.png)

如图，关闭设置后并没有取到意料当中的效果。当然，也可能是我个人的理解有误。

**补充信息：**

无

**Comment by Sprit-Fun** [comment]
是不是开了cache？可以试试清除web cache然后试试是否用的不同API

**Comment by Sualiu** [comment]
> 是不是开了cache？可以试试清除web cache然后试试是否用的不同API

我试过启用全新的WordPress来验证此问题，它依旧会重复。所以，此问题应该是存在的。
当然，也可能是我的问题。

**Comment by mirai-mamori** [comment]
@KotoriK

**Comment by KotoriK** [comment]
需要注意的是当```封面随机背景图片缓存```打开时，可能要多刷新一次才会看到关闭```多终端分离```的效果
