### ISSUE TITLE
Author页面作者简介显示错误

### ISSUE THREAD

**Issue by Sprit-Fun** [mirai-mamori/Sakurairo#533]
**问题出处：**

作者页面-简介 显示错误

**实际行为描述：**

作者页面简介为‘1’

**预期的行为：**

显示作者的简介

**复现步骤：**

进入作者页面

**截图（若有）**

作者页面：
![image](https://user-images.githubusercontent.com/43423211/168447626-58726202-9e7f-4957-ae6a-39ae155623d7.png)
预期效果：
![image](https://user-images.githubusercontent.com/43423211/168447633-9438c833-84d8-438b-a5b2-67ebd6a84033.png)

**补充信息：**

发现应该是author.php 第12行：
`<div class="description"><?= get_the_author_meta('description') || iro_opt('signature_text', 'Carpe Diem and Do what I like'); ?></div>`
去除OR就可以显示作者简介了: `<div class="description"><?= get_the_author_meta('description') ; ?></div>`
但这个应该是无简介显示的信息？可以看一下这个问题。

**Comment by mirai-mamori** [comment]
欢迎pr

**Comment by KotoriK** [comment]
怪 那1是从哪来的

**Comment by zhy201810576** [comment]
作者页面简介显示为‘1’，是由于第12行代码直接将布尔运算的值输出造成的

**Comment by zhy201810576** [comment]
### 解决
将项目根目录下 [author.php](https://github.com/mirai-mamori/Sakurairo/blob/1b3979eec7b2133f913b36096210f5e0ae6fd0f3/author.php#L12) 第12行代码
`<?= get_the_author_meta('description') || iro_opt('signature_text', 'Carpe Diem and Do what I like'); ?>`
改为
`<?php echo get_the_author_meta('description') ? get_the_author_meta('description') : iro_opt('signature_text', 'Carpe Diem and Do what I like'); ?>`
即可解决。

**Comment by KotoriK** [comment]
> ### 解决
> 将项目根目录下 [author.php](https://github.com/mirai-mamori/Sakurairo/blob/1b3979eec7b2133f913b36096210f5e0ae6fd0f3/author.php#L12) 第12行代码 `<?= get_the_author_meta('description') || iro_opt('signature_text', 'Carpe Diem and Do what I like'); ?>` 改为 `<?php echo get_the_author_meta('description') ? get_the_author_meta('description') : iro_opt('signature_text', 'Carpe Diem and Do what I like'); ?>` 即可解决。

丈育了 原来PHP的逻辑运算符返回和JavaScript不一样的
