### ISSUE TITLE
Webp优化/外部API桌面端和手机端随机图片地址失效

### ISSUE THREAD

**Issue by zjgxcj** [mirai-mamori/Sakurairo#534]
**问题出处：**

iro主题设置——主页设置——封面设置——Webp优化/外部API桌面端随机图片地址&外部API手机端随机图片地址

**实际行为描述：**

封面图片和文章区域装饰特色图片在桌面端和手机端均无法显示

**预期的行为：**

影响使用体验

**复现步骤：**

于地址失效之后的新用户（本地未缓存）

**配置与环境：**

- 问题页面：[（如果有，请提供一个触发此问题的页面链接）](http://124.71.146.112/)
- PHP 版本：7.2
- 数据库类型 / 版本：mysql 5.6
- WordPress 版本：5.9.3
- 主题版本：（Release 标注的版本号）v2.5.0.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）Akismet 反垃圾评论
- 浏览器：（浏览器名称及版本号）Edge

**截图（若有）**
![Snipaste_2022-05-15_16-33-29](https://user-images.githubusercontent.com/70478063/168464169-f23d4547-2c4c-4635-a331-4b4e2c497f06.jpg)
![Snipaste_2022-05-15_16-33-50](https://user-images.githubusercontent.com/70478063/168464193-d8c2ca27-8810-410b-a5c0-c9610aa7efcb.jpg)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**
联系方式QQ:2864547910

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
合并至 #532
