### ISSUE TITLE
光标点击效果

### ISSUE THREAD

**Issue by zjgxcj** [mirai-mamori/Sakurairo#535]
**这是什么方面的想法？**

现有内容的优化 / 用户体验

**这个想法具体是要实现什么？**

光标点击效果

**这个想法实现后有什么帮助？**

更好的浏览体验

**是否有具体的实现思路？**

暂无

**补充信息：**

可参见https://solaking.com/

**Comment by mirai-mamori** [comment]
啥意思，就是点一下花里胡哨的特效？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zjgxcj ***@***.***>
发送时间: Sunday, May 15, 2022 10:54:26 PM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mirai-mamori/Sakurairo] 光标点击效果 (Issue #535)


这是什么方面的想法？

现有内容的优化 / 用户体验

这个想法具体是要实现什么？

光标点击效果

这个想法实现后有什么帮助？

更好的浏览体验

是否有具体的实现思路？

暂无

补充信息：

可参见https://solaking.com/

―

**Comment by zjgxcj** [comment]
对

**Comment by zjgxcj** [comment]
https://iro.tw/guide/about.html#额外设置
例子特效—>粒子特效
