### ISSUE TITLE
后台 iro 主题设置的资讯+无法正常显示

### ISSUE THREAD

**Issue by zhy201810576** [mirai-mamori/Sakurairo#537]
**问题出处：**

后台 iro 主题设置的资讯+无法正常显示

**实际行为描述：**

后台 iro 主题设置的资讯+无法正常显示

**预期的行为：**

后台 iro 主题设置的资讯+ 正常显示如下：

![news_plus](http://grayzhaohonyang.gitee.io/my-blog/img/news_plus.png)

**复现步骤：**

在后台 iro 主题设置，点击“你好！”选项卡

**配置与环境：**

- 问题页面：iro 主题设置，“你好！”选项卡
- PHP 版本：7.4.3
- 数据库类型 / 版本：5.6.50
- WordPress 版本：5.9.3
- 主题版本：2.5.0.1
- 浏览器：101.0.4951.64

**截图**

![news_plus error](http://grayzhaohonyang.gitee.io/my-blog/img/news_plus%20404%20error.png)

**补充信息：**

打开图片的链接 https://news.maho.cc/sakurairo.php ，无法正常显示报404错误

可将主题根目录下的 opt/options/theme-options.php 中的31行代码的链接，临时改为 https://s.nmxc.ltd/sakurairo_vision/news/v2.5.webp ，使其正常显示

**Comment by mirai-mamori** [comment]
已修复
