### ISSUE TITLE
快速下滑时左下角音乐播放器出现分离

### ISSUE THREAD

**Issue by zjgxcj** [mirai-mamori/Sakurairo#538]
**问题出处：**

ipad端safari浏览器（桌面端无此情况）页尾音乐播放器

**实际行为描述：**

分离

**预期的行为：**

影响使用体验

**复现步骤：**

试一试

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：（Release 标注的版本号）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

提供一个此问题触发的截图或报错信息。若没有，则留空。

[](url)

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
这边请你去问问苹果：https://www.apple.com.cn/cn/search/safari
