### ISSUE TITLE
ipad端safari浏览器评论识别为mac

### ISSUE THREAD

**Issue by zjgxcj** [mirai-mamori/Sakurairo#539]
**问题出处：**

评论功能

**实际行为描述：**

ipad端safari浏览器评论识别为mac

**预期的行为：**

影响使用体验

**复现步骤：**

怎样才能再次触发这个问题？
试一试

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：（Release 标注的版本号）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
这边请你去问问苹果：https://www.apple.com.cn/cn/search/safari

**Comment by KotoriK** [comment]
别问 问就是iPad的user agent和mac是一致的
