### ISSUE TITLE
请问如何关闭主题自带的代码高亮？

### ISSUE THREAD

**Issue by Sakuralovers** [mirai-mamori/Sakurairo#541]
![问题图片](https://s3.bmp.ovh/imgs/2022/05/16/3ba1fa7681675d04.png)
Markdown编辑器自带的代码高亮格式和主题自带的显示冲突了，在主题设置里没找到相关设置。
请问该怎么关闭主题的代码高亮呢？

尝试过删除sakura.css以及修改里面的内容，但是没起作用。。

**Comment by mirai-mamori** [comment]
来个链接

**Comment by Sakuralovers** [comment]
> 来个链接

[原文](https://wdshine.com/articles/uncategorized/131)
使用的编辑器插件是[WP Editor.md](https://github.com/LuRenJiasWorld/WP-Editor.md)

**Comment by KotoriK** [comment]
在主题设置中搜索“代码高亮程序”然后调到自定义

**Comment by Sakuralovers** [comment]
> 在主题设置中搜索“代码高亮程序”然后调到自定义

已经设置为自定义了，无效。然后发现字体背景色是style.css中这部分造成的
![图片](https://s3.bmp.ovh/imgs/2022/05/17/df79f8e64f19730f.png)

删除之后字体背景正常了，但还是没法高亮

**Comment by KotoriK** [comment]
如果开启了Pjax的话 [WP Editor.md](https://github.com/LuRenJiasWorld/WP-Editor.md)的代码高亮可能不会自动生效
鉴于WP Editor.md用的也是Prismjs 可以试试把代码高亮调到Prismjs

**Comment by KotoriK** [comment]
打开你的链接可以看到，代码高亮其实是已经正常运行了的 但是因为没有CSS样式所以高亮没显示出来

**Comment by Sakuralovers** [comment]
> 如果开启了Pjax的话 [WP Editor.md](https://github.com/LuRenJiasWorld/WP-Editor.md)的代码高亮可能不会自动生效 鉴于WP Editor.md用的也是Prismjs 可以试试把代码高亮调到Prismjs

我把WP Editor.md的代码高亮关了，然后对比了一下主题设置里的Prismjs和自定义。发现除了代码末尾的一键复制图标之外没有别的区别……

自定义高亮
![自定义高亮](https://s3.bmp.ovh/imgs/2022/05/20/9c59505ded72e0e1.png)

Prismjs
![Prismjs](https://s3.bmp.ovh/imgs/2022/05/20/a2fbdd4d8ed8bdb7.png)

Prismjs设置
![Prismjs设置](https://s3.bmp.ovh/imgs/2022/05/20/0f2f95db06f08e89.png)

**Comment by mirai-mamori** [comment]
只能建议你先关闭Pjax试试看

**Comment by Sakuralovers** [comment]
> 只能建议你先关闭Pjax试试看

也没用，我有时间再研究一下吧。感谢大佬解答^_^

**Comment by KotoriK** [comment]
所以说其实是prismjs的css因为某种原因没有加载上的问题 可以排查一下

**Comment by mirai-mamori** [comment]
应该是样式冲突，来个链接


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Sakuralovers ***@***.***>
发送时间: Monday, May 16, 2022 7:00:14 PM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mirai-mamori/Sakurairo] 请问如何关闭主题自带的代码高亮？ (Issue #541)


[问题图片]<https://camo.githubusercontent.com/391674bd04ac129b56b555c873b601ae38093952f36454616f114261a0bd01c9/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30352f31362f336261316661373638313637356430342e706e67>
Markdown编辑器自带的代码高亮格式和主题自带的显示冲突了，在主题设置里没找到相关设置。
请问该怎么关闭主题的代码高亮呢？

尝试过删除sakura.css以及修改里面的内容，但是没起作用。。

―
