### ISSUE TITLE
登录跳转失效，控制台报错

### ISSUE THREAD

**Issue by zhy201810576** [mirai-mamori/Sakurairo#542]
**问题出处：**

登录完成后的倒计时跳转失效，并且浏览器控制台报错

**实际行为描述：**

无法正常完成登录后倒计时跳转

**预期的行为：**

登录成功后应该倒计时5秒跳转页面，如下图：

![跳转成功](https://cdn.jsdelivr.net/gh/zhy201810576/picture-host/iro-2.5.0.1-login%20jump.png)

**复现步骤：**

登录后即可触发BUG

**配置与环境：**

- 问题页面：登录跳转页面
- PHP 版本：7.4.3
- 数据库类型 / 版本：5.6.50
- WordPress 版本：5.9.3
- 主题版本：2.5.0.1
- 浏览器：101.0.4951.64

**截图**

![登录跳转失效](https://cdn.jsdelivr.net/gh/zhy201810576/picture-host/iro-2.5.0.1-login%20jump-bug.png)

**补充信息：**

在项目 [inc/theme_plus.php](https://github.com/mirai-mamori/Sakurairo/blob/1b3979eec7b2133f913b36096210f5e0ae6fd0f3/inc/theme_plus.php#L239) 的第239行至第246行有关登录跳转功能代码中`setTimeout()`函数语法有误是造成登录跳转失效的主要原因，可将其修改为
```php+HTML
function gopage(url,descr) {
    function cb(sec) {
        document.getElementById('login-showtime').innerHTML = '<?= __("Login successful, ","sakurairo")/*空降成功*/?>'
        + sec + '<?= __("seconds later automatically transfer to","sakurairo")/*秒后自动转到*/?>' + descr;
        if (sec == 0) { window.location = url; } else { window.setTimeout(() => { cb(sec - 1); }, 1000); }
    }
    window.setTimeout(() => { cb(5); }, 1000); //倒计时秒数在这捏
}
```
进行解决

**Comment by KotoriK** [comment]
流汗.jpg

**Comment by KotoriK** [comment]
745ab45a5e946a1349b4678c2f1b40625d962563
