### ISSUE TITLE
登录后后台面板无法进入，显示当前主题不支持小工具功能

### ISSUE THREAD

**Issue by MK0727** [mirai-mamori/Sakurairo#547]
大致范围：未启用后台小工具项

具体行为描述：在启用该主题后选择了全新后台配色，第二次登录后台时便报错显示当前主题并不支持小工具功能

尝试：尝试按照WordPress帮助文档解决但未成功解决该问题

配置与环境：
- 问题页面：http://qtspa.ltd/wordpress
- PHP 版本：7.3.33
- 数据库类型 / 版本：MYSQL 4.9.10
- WordPress 版本：5.9.3
- 主题版本：2.5.0.2
- 使用的插件：未使用插件
- 浏览器：Chrome 96.0.4664.92

截图

![Screenshot_2022-05-21-09-24-23-261_com android chrome](https://user-images.githubusercontent.com/104549811/169629110-26858e7b-4495-427b-9a42-5165c1db25b0.jpg)

补充信息：无

**Comment by mirai-mamori** [comment]
其他的我不知道但是你的数据库版本是认真的吗

**Comment by MK0727** [comment]
未得到有效解决
