### ISSUE TITLE
开启了PJAX局部刷新报错Uncaught ReferenceError: pageURL is not defined

### ISSUE THREAD

**Issue by feko2018** [mirai-mamori/Sakurairo#549]
开启了PJAX局部刷新
![image](https://user-images.githubusercontent.com/38614242/169938292-c29c0e9d-d34a-4648-a927-1d71269546d4.png)

会出现下面报错：
![image](https://user-images.githubusercontent.com/38614242/169938114-d631a0f5-8027-4798-be02-b3c18bf35e99.png)

Uncaught ReferenceError: pageURL is not defined
    at HTMLDocument.<anonymous> (pjax.js:132)
    at A.fire (pjax.esm.min.js:25)
    at A.E [as switchDOM] (pjax.esm.min.js:13)
    at async A.k [as weakLoad] (pjax.esm.min.js:21)
    at async A.load (pjax.esm.min.js:25)
(匿名) @ pjax.js:132
fire @ pjax.esm.min.js:25
E @ pjax.esm.min.js:13
async function(异步)
E @ pjax.esm.min.js:11
k @ pjax.esm.min.js:21
load @ pjax.esm.min.js:25
load @ pjax.esm.min.js:6
onLinkOpen @ pjax.esm.min.js:7
(匿名) @ pjax.esm.min.js:8

**Comment by mirai-mamori** [comment]
什么版本


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Feko ***@***.***>
发送时间: Tuesday, May 24, 2022 10:46:55 AM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mirai-mamori/Sakurairo] 开启了PJAX局部刷新报错Uncaught ReferenceError: pageURL is not defined (Issue #549)


开启了PJAX局部刷新
[image]<https://user-images.githubusercontent.com/38614242/169938292-c29c0e9d-d34a-4648-a927-1d71269546d4.png>

会出现下面报错：
[image]<https://user-images.githubusercontent.com/38614242/169938114-d631a0f5-8027-4798-be02-b3c18bf35e99.png>

Uncaught ReferenceError: pageURL is not defined
at HTMLDocument. (pjax.js:132)
at A.fire (pjax.esm.min.js:25)
at A.E [as switchDOM] (pjax.esm.min.js:13)
at async A.k [as weakLoad] (pjax.esm.min.js:21)
at async A.load (pjax.esm.min.js:25)
(匿名) @ pjax.js:132
fire @ pjax.esm.min.js:25
E @ pjax.esm.min.js:13
async function(异步)
E @ pjax.esm.min.js:11
k @ pjax.esm.min.js:21
load @ pjax.esm.min.js:25
load @ pjax.esm.min.js:6
onLinkOpen @ pjax.esm.min.js:7
(匿名) @ pjax.esm.min.js:8

―

**Comment by feko2018** [comment]
主题版本：Sakurairo 主题版本 / Theme Version 2.5.0.3 | 内部版本 / Internal Version 17.0.3
php版本：php-7.4.3

**Comment by mirai-mamori** [comment]
插件列表


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Feko ***@***.***>
发送时间: Tuesday, May 24, 2022 10:59:15 AM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: 染川瞳 ***@***.***>; Comment ***@***.***>
主题: Re: [mirai-mamori/Sakurairo] 开启了PJAX局部刷新报错Uncaught ReferenceError: pageURL is not defined (Issue #549)


主题版本：Sakurairo 主题版本 / Theme Version 2.5.0.3 | 内部版本 / Internal Version 17.0.3
php版本：php-7.4.3

―

**Comment by feko2018** [comment]
![image](https://user-images.githubusercontent.com/38614242/169940030-471c0661-a47a-406a-9450-fa97bd4e0a0d.png)

**Comment by mirai-mamori** [comment]
缓存插件关了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Feko ***@***.***>
发送时间: Tuesday, May 24, 2022 11:01:09 AM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: 染川瞳 ***@***.***>; Comment ***@***.***>
主题: Re: [mirai-mamori/Sakurairo] 开启了PJAX局部刷新报错Uncaught ReferenceError: pageURL is not defined (Issue #549)


[image]<https://user-images.githubusercontent.com/38614242/169940030-471c0661-a47a-406a-9450-fa97bd4e0a0d.png>

―

**Comment by feko2018** [comment]
![image](https://user-images.githubusercontent.com/38614242/169940514-9255fc40-42e2-41bf-af09-2a5ebdac8668.png)
![image](https://user-images.githubusercontent.com/38614242/169940653-131cda56-f468-4b2d-ba18-60c6dd9d1a6d.png)
关了缓存，重启了php，清除了浏览器缓存和使用无痕模式来看，还是一样

**Comment by mirai-mamori** [comment]
来个链接


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Feko ***@***.***>
发送时间: Tuesday, May 24, 2022 11:07:14 AM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: 染川瞳 ***@***.***>; Comment ***@***.***>
主题: Re: [mirai-mamori/Sakurairo] 开启了PJAX局部刷新报错Uncaught ReferenceError: pageURL is not defined (Issue #549)


[image]<https://user-images.githubusercontent.com/38614242/169940514-9255fc40-42e2-41bf-af09-2a5ebdac8668.png>
[image]<https://user-images.githubusercontent.com/38614242/169940653-131cda56-f468-4b2d-ba18-60c6dd9d1a6d.png>
关了缓存，重启了php，清除了浏览器缓存和使用无痕模式来看，还是一样

―

**Comment by feko2018** [comment]
首页是正常https://www.88ops.com/     点击栏目才会出现这个

**Comment by mirai-mamori** [comment]
应该是你的某个插件没有和主题的pjax兼容，自行排查一下先

**Comment by KotoriK** [comment]
源站已更换主题 无法复现
