### ISSUE TITLE
夜间模式下评论区<a>标签对比度欠佳

### ISSUE THREAD

**Issue by kanodaisuki** [mirai-mamori/Sakurairo#551]
[![XaSV8U.png](https://s1.ax1x.com/2022/06/03/XaSV8U.png)](https://imgtu.com/i/XaSV8U)
如图
改成跟随主题颜色似乎比较合适

.comment .body p a {
  color: var(--theme-skin-matching,#ffe066);
  padding: 0 5px;
  text-decoration: underline;
}

**Comment by mirai-mamori** [comment]
下个版本修复

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: kanodaisuki ***@***.***>
发送时间: Friday, June 3, 2022 9:52:47 PM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mirai-mamori/Sakurairo] 夜间模式下评论区<a>标签对比度欠佳 (Issue #551)


[XaSV8U.png]<https://imgtu.com/i/XaSV8U>
如图
改成跟随主题颜色似乎比较合适

.comment .body p a {
color: var(--theme-skin-matching,#ffe066);
padding: 0 5px;
text-decoration: underline;
}

―
