### ISSUE TITLE
说说模板使用Hermit X插入音乐，刷新不出来播放器

### ISSUE THREAD

**Issue by wicecoffeey** [mirai-mamori/Sakurairo#552]
**问题出处：**
说说模板使用Hermit X插入音乐，第一次刷新不出来播放器，第二次就正常了

说说模板使用hermit X插入音乐有问题

pjax.js:132 
        
       Uncaught ReferenceError: pageURL is not defined
    at HTMLDocument.<anonymous> (pjax.js:132:42)
    at A.fire (pjax.esm.min.js:25:77)
    at A.E [as switchDOM] (pjax.esm.min.js:13:280)
    at async A.k [as weakLoad] (pjax.esm.min.js:21:394)
    at async A.load (pjax.esm.min.js:25:113)
(匿名) @ pjax.js:132
fire @ pjax.esm.min.js:25
E @ pjax.esm.min.js:13
await in E(异步)
k @ pjax.esm.min.js:21
load @ pjax.esm.min.js:25
load @ pjax.esm.min.js:6
onLinkOpen @ pjax.esm.min.js:7
(匿名) @ pjax.esm.min.js:8

第一次刷新不出来播放器，第二次就正常了

**配置与环境：**

- 问题页面：https://www.icecoffee.ltd/wyy/)
- PHP 版本：8.0
- 数据库类型 / 版本：MySQL
- WordPress 版本：6.0
- 主题版本：2.5.0.3
- 使用的插件：hermitX
- 浏览器：edge
![QQ截图20220605093419](https://user-images.githubusercontent.com/96828708/172031176-166cfa4c-c4d5-45ef-b38a-5dd2fc878da6.png)
![2](https://user-images.githubusercontent.com/96828708/172031178-007ff099-62e7-456e-be93-d1b332c818e0.png)

**补充信息：**
因为之前版本的主题没有问题的，所以想来求助一下

**Comment by KotoriK** [comment]
实测```从其他页面第一次进入wyy页面```播放器可能加载缓慢，但是最终能加载上
未遇到不能加载的问题

**Comment by wicecoffeey** [comment]
自己测试PC端的edge和google浏览器，以及手机端自带的夸克均不能一次性打开，防止半小时也不能加载
但是刷新网页之后立刻就能加载

**Comment by mirai-mamori** [comment]
关闭pjax把

**Comment by Doraemonsan** [comment]
翻看了一下 Hermit X 开发者的说明，需要在主题的 pjax 回调函数中加入"reloadHermit();"方法，该方法的作用是每次 pjax 刷新后，Hermit X 将停止播放，并重新加载该页面上的播放器（如果有）
