### ISSUE TITLE
请问最新版本主题是否移除了live2d功能？

### ISSUE THREAD

**Issue by kerroce** [mirai-mamori/Sakurairo#553]
# RT，在使用sakurairo v2.5.0.3时，发现live2d功能开关已消失，请问是由于什么原因？在接下来的版本里是否会重新添加？

## 大致范围：
主题配置类问题

## 具体行为描述：
设置页面中没有配置live2d的选项了

## 尝试：
1. 回退版本至2.5.0.1，开关出现，但使用默认设置还是无法正常显示live2d模型，
2. 尝试在2.5.0.1环境下将live2d仓库改为[stevenjoezhang/live2d-widget](https://github.com/stevenjoezhang/live2d-widget)，仍无法正常显示

## 配置与环境：
> 问题页面：略
>PHP 版本：7.4.29  x64
>数据库类型 / 版本：mysql 5.7
>WordPress 版本：6.0
>主题版本：2.5.0.3
>使用的插件：
>>Akismet Anti-Spam
>>Limit Login Attempts Reloaded
>>WP Githuber MD
>>WP Statistics

**Comment by mirai-mamori** [comment]
jsd已经无了，移不移除已经无所谓了
