### ISSUE TITLE
使用经典编辑器插件，发出来的文章的图片会很小很小

### ISSUE THREAD

**Issue by sxfinn** [mirai-mamori/Sakurairo#554]
使用默认的编辑器则不会出现此类情况

**Comment by robert1chi** [comment]
感谢你对Sakurairo的支持。
辛苦按照**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：（Release 标注的版本号）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**Comment by KotoriK** [comment]
我的建议是先看看你经典编辑器放图片的时候有没有设置样式

**Comment by sxfinn** [comment]
没有设置样式的
php是7.4
数据库版本5.6
主题版本是最新的发布版
浏览器chrome最新版本

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sxfinn** [comment]
另外我想问问建议的这些版本是多少

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sxfinn** [comment]
*   问题页面：http://1.15.98.101/2022/06/09/1221/PHP 版本：
  *   数据库类型 MySQL/ 版本：5.6
  *   WordPress 版本：5.9.3
  *   主题版本：2.0.5.3
  *   使用的插件：仅仅只有经典编辑器
浏览器：（浏览器名称及版本号）

发件人: PicoAoi ***@***.***>
发送时间: 2022年6月10日 14:25
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: sxfinn ***@***.***>; Author ***@***.***>
主题: Re: [mirai-mamori/Sakurairo] 使用经典编辑器插件，发出来的文章的图片会很小很小 (Issue #554)


感谢你对Sakurairo的支持。
辛苦按照配置与环境：

  *   问题页面：（如果有，请提供一个触发此问题的页面链接）
  *   PHP 版本：
  *   数据库类型 / 版本：
  *   WordPress 版本：
  *   主题版本：（Release 标注的版本号）
  *   使用的插件：（所有使用中的的插件，以便判断兼容性问题）
  *   浏览器：（浏览器名称及版本号）

**Comment by robert1chi** [comment]
命中了.entry-content span img 试试把span拿掉
