### ISSUE TITLE
主题设置无法保存 function(){return u(n),r.apply(this,arguments)}

### ISSUE THREAD

**Issue by NanMubai** [mirai-mamori/Sakurairo#557]
**问题出处：**
iro 主题设置 中的 保存功能

**问题描述：**
更改任何设置均无法保存，且提示 function(){return u(n),r.apply(this,arguments)}

**复现过程：**
更改 iro 主题设置 中的一项，点击「保存」后长时间无法保存，最后复现如上情况

**复现率：**
100%。

**配置与环境：**
宝塔: 7.9.2
PHP: 8.0
WordPress: 6.0
Nginx: 1.22.0
MySQL: 5.7.37
Theme: 2.5.0.3
Browser: Chrome 102.0.5005.115

**补充信息：**
尝试参照 #136 检查宝塔界面 Nginx 防火墙，但复现过程中此防火墙未开启
尝试参照 #355 ，但此 Issue 未描述解决方法，解决过程不可复制

**Comment by KotoriK** [comment]
但凡您搜索一下issue

**Comment by NanMubai** [comment]
> 

首先感谢您的耐心回复。

在提交此 issue 之前，尝试过在 issue 中搜索关键词“function(){return u(n),r.apply(this,arguments)}” 或 “保存”，但似乎有关 issues 都被关联到我在**补充信息**所提到的 #136 以及 #355 。对于 #136 中提到的防火墙问题，在尝试解决过程中宝塔界面中的防火墙并未开启； #355 中也并未提及如何解决，只是此 issue 提交者在之后的尝试中无法复现。

本人并未接触太多 Web 有关的开发，如果我尝试的搜索或者搜索关键词不够准确或全面，还请谅解并希望您指正检索错误或劳烦您指明可以解决的 issue 编号。

再次感谢您的回复。

**Comment by NanMubai** [comment]
> 但凡您搜索一下issue

首先感谢您的耐心回复。

在提交此 issue 之前，尝试过在 issue 中搜索关键词“function(){return u(n),r.apply(this,arguments)}” 或 “保存”，但似乎有关 issues 都被关联到我在补充信息所提到的 https://github.com/mirai-mamori/Sakurairo/issues/136 以及 https://github.com/mirai-mamori/Sakurairo/issues/355 。对于 https://github.com/mirai-mamori/Sakurairo/issues/136 中提到的防火墙问题，在尝试解决过程中宝塔界面中的防火墙并未开启； https://github.com/mirai-mamori/Sakurairo/issues/355 中也并未提及如何解决，只是此 issue 提交者在之后的尝试中无法复现。

本人并未接触太多 Web 有关的开发，如果我尝试的搜索或者搜索关键词不够准确或全面，还请谅解并希望您指正检索错误或劳烦您指明可以解决的 issue 编号。

再次感谢您的回复。

**Comment by KotoriK** [comment]
因为一个上游项目的问题，主题设置保存的背后操作（向admin-ajax.php发送POST请求）中发生的任何错误都会反映为内容为```function(){return u(n),r.apply(this,arguments)}```的弹窗。具体错误只能在开发工具中查看，多数会报HTTP 500，而这类错误中宝塔防火墙是我们碰到过最多的诱因（https://github.com/mirai-mamori/Sakurairo/issues/355#issuecomment-948414829 ），但也有像 https://github.com/mirai-mamori/Sakurairo/issues/490#issuecomment-1100784438_  报的是很诡异的404。

可能导致这一现象的问题有很多，所以，如果已有的解决方案无法解决你的问题，那你可以自行尝试排障（毕竟admin-ajax.php的权限不好开放嘛），然后欢迎你把你发现的问题，解决方案反馈给社区。

**Comment by robert1chi** [comment]
如果可以，请在执行这项操作时，打开浏览器的DevTools，保持在Network的监听状态，并提供http状态码，以便我们能更好的排除问题。
