### ISSUE TITLE
建议 封面图片切换时实现平滑过渡

### ISSUE THREAD

**Issue by qingchenling** [mirai-mamori/Sakurairo#561]
**这是什么方面的想法？**

UI 界面

**这个想法具体是要实现什么？**

封面图片切换时实现平滑过渡。现在切换图片时，如果时随机图api，会在切换的瞬间没有图片，显示出背景图（闪屏）。

**这个想法实现后有什么帮助？**

防止切换封面时有闪屏

**Comment by KotoriK** [comment]
目前实现这一想法需要比较大的重构，将封面背景图从background属性改为由一个\<image\>标签显示，有能力的话欢迎pr
