### ISSUE TITLE
普通页面（非模板页）评论区加载很慢

### ISSUE THREAD

**Issue by likepoems** [mirai-mamori/Sakurairo#564]
**大致范围：**

新建的一个普通页面

**具体行为描述：**

新建的一个普通页面用来当做留言板，评论加载很慢，时间10秒钟左右。留言也不多。不是报错的问题

**尝试：**

切换其他主题没这种情况，不到1秒钟加载完成

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：5.6
- WordPress 版本：最新版本
- 主题版本：最新版本
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：最新版Micrsoft Edge

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
你倒是把地址拿来啊

**Comment by likepoems** [comment]
不好意思，忘记提供地址了
https://likepoems.com/liuyan/

**Comment by likepoems** [comment]
这已经解决，是我配置的问题

**Comment by kingodragon** [comment]
> 这已经解决，是我配置的问题

我同样遇到了这个问题，请问你是怎么解决的
