### ISSUE TITLE
页面右下角设置切换Fronts问题

### ISSUE THREAD

**Issue by likepoems** [mirai-mamori/Sakurairo#565]
**问题出处：**

页面右下角设置齿轮点击切换问题

**实际行为描述：**

页面右下角齿轮点击后选择字体点击切换样式问题

**预期的行为：**

点击fonts下方按钮，切换后背景变暗，再次选择当前按钮背景变暗，另一个变回原样。

**复现步骤：**

博客主页设置按钮点击出现fonts选择字体就会出现这个问题

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL5.6
- WordPress 版本：最新版
- 主题版本：（Release 标注的版本号）最新版
- 使用的插件：
- 浏览器：最新版Mircsoft Edge

**截图（若有）**

![202207041503.gif](https://s2.loli.net/2022/07/04/Uzq6Dc9d4NG8Zjr.gif)

**补充信息：**

无

**Comment by mirai-mamori** [comment]
这个真的是bug嘛

**Comment by mirai-mamori** [comment]
倒是发现相同位置的另一个bug

**Comment by robert1chi** [comment]
感谢你对Sakurairo的支持。
我们在js中发现一个bug，目前已在处理，该问题预计在下个版本中修复。
