### ISSUE TITLE
如何设置页尾在线音乐播放器代理

### ISSUE THREAD

**Issue by gongliangjun** [mirai-mamori/Sakurairo#570]
**大致范围：**

页尾在线播放器设置

**具体行为描述：**

想设置页尾网易云音乐在线播放，请问如何设置页尾在线音乐播放器代理

**尝试：**

Sakurairo网站配置中页尾在线音乐播放器代理设置说明的文档打不开，文档链接：https://curl.se/libcurl/CURLOPT_PROXY.html 

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.1.31
- 数据库类型 / 版本：MySQL/5.6.37
- WordPress 版本：6.0
- 主题版本：Sakurairo2.5.1.1
- 使用的插件： quicklatex
- 浏览器：chrome 版本 103.0.5060.114

**截图（若有）**

**补充信息：**

**Comment by Davy-Chendy** [comment]
好像不设置代理也可以正常使用

**Comment by KotoriK** [comment]
因为curl换文档链接了
https://curl.se/libcurl/c/CURLOPT_PROXY.html
