### ISSUE TITLE
评论时间和文章发布时间

### ISSUE THREAD

**Issue by swRains** [mirai-mamori/Sakurairo#575]
**问题出处：**

时间显示

**实际行为描述：**

文章发布时间和评论时间显示相差7小时，哪怕是刚刚发布的文章显示也是七小时前，我看其他人似乎也有这个问题

**预期的行为：**

...分钟...小时前等

**复现步骤：**

怎样才能再次触发这个问题？

**配置与环境：**

- 问题页面：http://blog.cryzy.cn
- PHP 版本：7.3.4
- 数据库类型 / 版本：5.7.26
- WordPress 版本：6.0.1
- 主题版本：Sakurairo-2.5.1.1
- 使用的插件：Autoptimize  、 超级缓存
- 浏览器：Edge 103   Windows 10/11

**截图（若有）**

见网页
http://cryzy.cn:3440/?p=34

**Comment by robert1chi** [comment]
见issue #559

**Comment by Yish1** [comment]
同样遇到了这个问题，刚发的文章，再打开就是7个小时前

**Comment by VPSTP** [comment]
可以通过在wp-config.php中添加`date_default_timezone_set('Asia/Shanghai');`解决该问题
亲测有效
