### ISSUE TITLE
追番模板页面标题不支持中文

### ISSUE THREAD

**Issue by AdeSpike** [mirai-mamori/Sakurairo#576]
问题出处：Sakurairo 主题版本 / Theme Version 2.5.1.1 设置哔哩哔哩追番模板页面

这个问题出在程序的哪一个具体功能？
新建追番模板页面

实际行为描述：在主题设置中设置好哔哩哔哩的UID以及cookie后，新建模板页面，输入中文标题并发布。访问时显示404找不到页面。

触发问题后造成了什么效果及影响？
无法显示追番页面，弹出404找不到页面

预期的行为：获取到指定账号的追番列表

复现步骤：安装完成主题后，设置好哔哩哔哩的UID及其cookie后，新建页面，选择追番模板，填写中文标题，发布后访问。

**配置与环境：**

- 问题页面：https://example.blog.com/index.php/我的追番/
- PHP 版本：7.4
- 数据库类型 / 版本：5.6.51 - MySQL Community Server (GPL)
- WordPress 版本：6.0.1
- 主题版本：2.5.1.1
- 使用的插件：Akismet 反垃圾评论（4.2.5版本），All-in-One WP Migration（7.62版本），All-in-One WP Migration Unlimited Extension（2.46版本），Canvas-Nest.js（1.0.1版本），Hotlink File Prevention（2.0.0版本），UpdraftPlus-备份/恢复（1.22.14版本），Wordfence安全（7.5.5版本），WP Editor.md（10.2.1版本），WP SMTP（1.2.5版本），WP-China-Yes（3.5.3版本）
- 浏览器：Microsoft Edge版本 103.0.1264.62 (正式版本) (64 位)，Google Chrome版本 103.0.5060.114（正式版本） （64 位）

**截图（若有）**
中文标题报错

![zh](https://user-images.githubusercontent.com/46109115/179458835-d238cf6c-5588-463a-8e13-3490cd99953e.jpg)

英文标题正常显示
![en](https://user-images.githubusercontent.com/46109115/179459687-44dfd479-d944-40c2-b71b-46dd8f495221.jpg)

**补充信息：**

我这边自己测试发现只跟标题有关，uid及其cookie均保持一致。我需要把这个页面放在菜单栏里，英文的标题不太符合我博客整体文字风格，但中文的又会报错。此外，在早期的Sakurairo2.2.1版本中，中文是可以被访问到并且正常显示的，更新主题后就发现不支持中文了。希望团队验证这个问题。

**Comment by KotoriK** [comment]
这个可能与你的固定链接设置以及web服务器侧的重定向设置相关，请您自行排查
