### ISSUE TITLE
关于文章发布时间显示不一致的用户调查

### ISSUE THREAD

**Issue by robert1chi** [mirai-mamori/Sakurairo#583]
# 关于文章发布时间显示不一致的用户调查
我们观察到issue #559 以及issue #575 多次报告了主题存在文章发布时间与用户时间不一致的问题，为排查相关情况，现开启问卷调查。
点击 [腾讯问卷](https://wj.qq.com/s2/10588008/11f8) 前往问卷。
Sakurairo项目组不会主动保存您的敏感信息，与腾讯问卷隐私政策相关，请参阅[《腾讯问卷隐私保护指引》](https://wj.qq.com/xy/privacypolicy.html)  

We have observed that issue #559 and issue #575 have repeatedly reported the issue that the publication time of the article is inconsistent with the user's time. In order to investigate the relevant situation, a questionnaire is now opened.
Click [Tencent Questionnaire](https://wj.qq.com/s2/10588008/11f8) to go to the questionnaire.
The Sakurairo project team will not actively save your sensitive information, which is related to the Tencent Questionnaire Privacy Policy, please refer to [*Tencent Questionnaire Privacy Protection Guidelines*](https://wj.qq.com/xy/privacypolicy.html)

**Comment by VPSTP** [comment]
经测试，可以通过在wp-config.php中添加date_default_timezone_set('Asia/Shanghai');解决该问题

**Comment by ZJahon** [comment]
VPSTP的方法可以解决问题，困扰一天了，修改系统时间没有用。

**Comment by robert1chi** [comment]
PR #676将修复这个问题
PR #676 will fix this issue.
