### ISSUE TITLE
手机端文章列表、及时光轴

### ISSUE THREAD

**Issue by sathew** [mirai-mamori/Sakurairo#586]
**问题出处：**

1.首页文章列表页面
2手机端时光机页面！
**实际行为描述：**
1首页文章列表图文模式下，点击图片进入文章失败。
2手机端时光机页面，右上角全部展开/收缩，点击无效。

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**

一直存在。

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：2.5.1.1

另外建议：
 加入之前的github cards功能，大家的blog很多文章都引用了。[github repo=“xx/xx"]

**Comment by qingchenling** [comment]
本人也有相似的问题，并且是在PC端就点不开时光轴。另外首页的第一篇文章的lazzyload一直不出来图片，不清楚是不是bug

![image](https://user-images.githubusercontent.com/76830236/183625369-0685d30c-7386-4f19-a1dd-c806d21c8ddb.png)

**Comment by mirai-mamori** [comment]
来点地址

**Comment by qingchenling** [comment]
> 来点地址

qwq，自己查出错力，是自己写的 katex 加载直接重写了整个 `<aritcle>` 元素，导致把链接上的相关 js 写丢了，改了改重写的范围，所以没有那样的事了。

真是抱歉（唔
