### ISSUE TITLE
文章区域小图模式下，小特色图无法更换

### ISSUE THREAD

**Issue by uptiona** [mirai-mamori/Sakurairo#587]
**问题出处：**

这个问题出在程序的哪一个具体功能？

答：在Wordpress后台，iro主题设置——>主页设置——>文章区域设置——>文章区域装饰特色图片外部API随机图片地址

**实际行为描述：**

触发问题后造成了什么效果及影响？

答：输入外部API后没有显示自定义图片，而是仍然显示默认图片。此外，尝试在宝塔面板更换默认图片为自定义图片后仍然显示原来的默认图片。

**预期的行为：**

这个功能应该有怎样的效果和影响？

答：输入API地址后，应该显示自定义随机图片。

**复现步骤：**

怎样才能再次触发这个问题？

答：按照上述步骤即可复现。即在iro主题设置——>主页设置——>文章区域设置”中选择“显示样式”为小图模式（右边那个），然后在下面的API地址中填入自己的API，保存设置后，刷新博客首页即可看到。

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4.30
- 数据库类型 / 版本：MySQL 5.5.62
- WordPress 版本：6.0.1
- 主题版本：（Release 标注的版本号）2.5.1.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）Edge

**截图（若有）**https://s1.ax1x.com/2022/08/10/v3hajJ.png

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by uptiona** [comment]
补充一下：手机端是正常的，只有电脑端出了问题

**Comment by mirai-mamori** [comment]
随机图api暂不支持小图模式
