### ISSUE TITLE
网站后台开启音符触动特效后在移动端右下角样式菜单中任意前台背景不能一键切换

### ISSUE THREAD

**Issue by Aqua-Chen** [mirai-mamori/Sakurairo#588]
**问题出处：样式菜单**
![image](https://user-images.githubusercontent.com/65001321/183905122-1646c65f-413f-4fbd-b015-d9e03b4d64bf.png)

这个问题出在程序的哪一个具体功能：音符触动特效
![image](https://user-images.githubusercontent.com/65001321/183905330-b4ec412f-7b7c-4a1d-8a21-fc9fe3bcbf9d.png)

**实际行为描述：开启音符触动特效后在移动端右下角样式菜单中任意模式中切换**

触发问题后造成了什么效果及影响？
在移动端右下角样式菜单中前台背景不能一键切换

**预期的行为：**
点击后应该立即切换前台背景

这个功能应该有怎样的效果和影响？
应该与PC端一样一次点击即可切换，但移动端并未能达成预期效果

**复现步骤：**
开启音符触动特效后在移动端右下角样式菜单中任意模式中切换

怎样才能再次触发这个问题？
同上

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL 5.6.5.0
- WordPress 版本：6.0.1
- 主题版本：（Release 标注的版本号）2.5.1.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）未使用其他插件
- 浏览器：（浏览器名称及版本号） chrome 104 mobile

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。
![9ef32615-dab5-4f20-a114-3102e9e2454a](https://user-images.githubusercontent.com/65001321/183907691-64d3c561-27b3-42bf-b624-aad7516fbd6c.jpg)
![40e2ee3f-dcee-4b12-b2db-3c3a2cbc240f](https://user-images.githubusercontent.com/65001321/183907701-ba589a91-d7a1-4423-b0a2-6d8fdd678ac0.jpg)

**补充信息：**
none
提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
[Fuukei/Sakurairo_Scripts 9c96a8c](https://github.com/Fuukei/Sakurairo_Scripts/commit/9c96a8c9752dbbe28450a655446b704c68b140f8)
