### ISSUE TITLE
封面视频无法开启

### ISSUE THREAD

**Issue by suchacutesnake** [mirai-mamori/Sakurairo#589]
**大致范围：**

封面视频无法开启

**具体行为描述：**

封面视频按钮打开后，不显示视频

**尝试：**

尝试了从自己服务器上的视频和阿里云oss的视频，以及反复核对了url填写的方式

**配置与环境：**

- 问题页面：
![image](https://user-images.githubusercontent.com/63144725/183932494-def9430f-01af-4ee0-af3d-b3eca845801e.png)
- PHP 版本：7.4
- WordPress 版本：6.0.1
- 主题版本：2.5.1.1
- 使用的插件：关闭了所有插件，问题仍然存在
- 浏览器：Google Chrome Version 96.0.4664.110 (Official Build) (x86_64)

**补充信息：**

在远古版本（2.多）中同一个视频和填写方式是能播放视频的。
目前主页除了封面开关按钮和封面视频按钮开启外其他选项全部关闭。
https://secretbase.cutesnake.top/

**Comment by 1225702013** [comment]
我的也是这个问题，请问解决了吗？

**Comment by 1225702013** [comment]
我的点击首页右下角播放按钮就可以显示视频了

**Comment by suchacutesnake** [comment]
> 我的点击首页右下角播放按钮就可以显示视频了

感谢，原来是这样用的。不得不吐槽这个按钮藏得也太好了……要是能把按钮整大点，然后由我定义
