### ISSUE TITLE
关于网站主页文章置顶功能

### ISSUE THREAD

**Issue by Aqua-Chen** [mirai-mamori/Sakurairo#590]
**这是什么方面的想法？**
关于网站主页文章置顶功能
![image](https://user-images.githubusercontent.com/65001321/184054132-4c777411-74e8-41c6-bef8-f40edcd4dbb0.png)

现有内容的优化 / 新增功能 / UI 界面 / 用户体验

**这个想法具体是要实现什么？**
在现有的文章模块里添加单个文章置顶功能，使博客作者能够从所有文章里选出一篇文章进行置顶展示

**这个想法实现后有什么帮助？**
通过对单个文章置顶可将个人的一些介绍信息或其它想说的话最先展示在读者面前，而不必等读者一篇篇去翻，让读者能够快速了解这个博客是干什么的或博客的作者的一些请求等。

**是否有具体的实现思路？**
暂无

**补充信息：**
暂无

**Comment by mirai-mamori** [comment]
wp自带此功能
