### ISSUE TITLE
关于主题色与字体颜色的设置

### ISSUE THREAD

**Issue by uptiona** [mirai-mamori/Sakurairo#591]
**这是什么方面的想法？**

 用户体验

**这个想法具体是要实现什么？**

希望字体颜色与主题色分开配置，个人感觉还是黑色的字体看起来舒服，如果跟随主题色就容易看不清，但是如果把主题色设置为黑色，字体能看清了，其他配色却又显得阴沉。

**这个想法实现后有什么帮助？**

优化用户体验

**是否有具体的实现思路？**

无

**补充信息：**

**Comment by mirai-mamori** [comment]
后期可以考虑调整
