### ISSUE TITLE
说说页面加载时报错（刚进入时）

### ISSUE THREAD

**Issue by likepoems** [mirai-mamori/Sakurairo#592]
问题出处：

说说模板页面

实际行为描述：

说说页面刚加载时鼠标下滑报Uncaught TypeError: Cannot read property 'classList' of null at HTMLLIElement.<anonymous> ((index):1140)
一段时间后错误消失。

预期的行为：

说说页面刚加载时鼠标下滑和刷新后都能正常显示

复现步骤：

点击进入[说说页面](https://likepoems.com/shuoshuo/)，下滑页面，控制台报错，一段时间后错误消失

配置与环境：

问题页面：https://likepoems.com/shuoshuo/
PHP 版本：7.4
数据库类型 / 版本：MySQL5.6
WordPress 版本：最新版
主题版本：（Release 标注的版本号）最新版
使用的插件：
浏览器：最新版Mircsoft Edge

**Comment by mirai-mamori** [comment]
没看到报错

**Comment by likepoems** [comment]
> 没看到报错

我把page-word.php 40行这里添了一个if(e){},把鼠标的事件放在if语句里了，之前报找不到classList这个属性。在添加if后，第一次进入说说页面不会报错，但是鼠标移到头像上不会有动画，刷新页面后才会有。我把if去掉后（恢复到之前的代码），第一次进入页面鼠标移到头像上会有动画，但下滑上滑鼠标会报错

**Comment by KotoriK** [comment]
多半是和pjax的冲突
不过这个能用:hover做的动画扯javascript也有些
