### ISSUE TITLE
评论区报错，无法评论

### ISSUE THREAD

**Issue by yukie8848** [mirai-mamori/Sakurairo#593]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：评论区

这是哪一方面的问题？你是否知道问题所牵连到的文件以及在文件的哪一行？

**具体行为描述：评论区发出评论时提示错误

你的问题具体是什么？

**尝试：尝试过更换浏览器，更换主题版本，依旧失败

你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：5.6
- WordPress 版本：6.1
- 主题版本：（Release 标注的版本号）2.5.1.1
- 使用的插件：wordpress经典编辑器
- 浏览器：chrome 版本 104.0.5112.102（正式版本） （64 位）

[[**截图（若有] https://i.ibb.co/2dgMm1H/QQ-20220818223004.jpg

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
你报错呢

**Comment by bymoye** [comment]
请提供地址。
