### ISSUE TITLE
Sakura 主题如何迁移到本主题？

### ISSUE THREAD

**Issue by LinHeLurking** [mirai-mamori/Sakurairo#594]
我的博客目前在使用旧的 Sakura 主题，应该如何迁移到该主题呢？

**Comment by mirai-mamori** [comment]
暂时没有迁移工具。两套主题互相独立，可以手动进行配置迁移。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: github-actions[bot] ***@***.***>
发送时间: Monday, August 29, 2022 10:40:33 AM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [mirai-mamori/Sakurairo] Sakura 主题如何迁移到本主题？ (Issue #594)


任何人都可以处理此问题。
请务必在您的 pull request 中引用此问题。
感谢你的贡献! (obb)o☆

―
