### ISSUE TITLE
增加一个友链功能

### ISSUE THREAD

**Issue by kadlm** [mirai-mamori/Sakurairo#595]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**
增加
**这个想法具体是要实现什么？**
友链
**这个想法实现后有什么帮助？**
促进友谊（）
**是否有具体的实现思路？**
在页面底部或者右上角？
**补充信息：**

**Comment by KotoriK** [comment]
有没有可能已经有了

**Comment by kadlm** [comment]
> 有没有可能已经有了

可以指条路吗找不到
