### ISSUE TITLE
评论加验证码

### ISSUE THREAD

**Issue by cao-gift** [mirai-mamori/Sakurairo#601]
**这是什么方面的想法？**

新增功能 

**这个想法具体是要实现什么？**
评论加上Vaptcha（或者其他的），现在主题只有登录调用Vaptcha验证码

**这个想法实现后有什么帮助？**
防止垃圾评论

**是否有具体的实现思路？**
应该比较容易

**补充信息：**

**Comment by bymoye** [comment]
可以对简易人机验证进行修改。
