### ISSUE TITLE
目录实现 flex

### ISSUE THREAD

**Issue by qingchenling** [mirai-mamori/Sakurairo#603]
**这是什么方面的想法？**

现有内容的优化

**这个想法具体是要实现什么？**

文章的目录只有全屏（或者较宽）时才有显示，而半屏的时候就没有了，希望可以用 `flex` 属性实现浮动。

**这个想法实现后有什么帮助？**

可以更好的使用文章目录

**是否有具体的实现思路？**

**补充信息：**
![image](https://user-images.githubusercontent.com/76830236/192535589-2fcbacd0-e982-42c0-985f-f48f4f43d8f8.png)
![image](https://user-images.githubusercontent.com/76830236/192536009-ca778b0b-7775-45bd-8024-0198fc5e6a9b.png)

**Comment by KotoriK** [comment]
天国的移动端目录
