### ISSUE TITLE
主題設定無法使用

### ISSUE THREAD

**Issue by Arcelibs** [mirai-mamori/Sakurairo#607]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

WP控制台的主題設定

**实际行为描述：**

點主題設定的任何一個選項都沒有反應

**预期的行为：**

應該按了要出現設定頁

**配置与环境：**

- WordPress 版本：6.0
- 主题版本：Sakurairo-2.5.2
- 使用的插件：X
- 浏览器：chrome

**截图（若有）**
![主題設定無法使用](https://user-images.githubusercontent.com/49543451/193522040-719e2ec0-f8c2-4641-a25d-62874a7e0431.png)

**补充信息：**

點了儲存或者重設都沒用，剛新裝完的WP站台

**Comment by KotoriK** [comment]
看樣子是css沒有正確加載上
請打開開發人員工具檢查相關資源是否有完整加載

**Comment by Arcelibs** [comment]
重裝了一次可以了
