### ISSUE TITLE
使用【相册模板】创建的页面无法呈现内容

### ISSUE THREAD

**Issue by LonePheasantWarrior** [mirai-mamori/Sakurairo#608]
使用【相册模板】创建的页面无法呈现内容
打开创建好的目标页面，查看控制台发现有资源404：
``/wp-admin/admin-ajax.php?action=getPhoto&post=39``

查看对应的[admin-ajax.php](https://github.com/WordPress/WordPress/blob/master/wp-admin/admin-ajax.php)，发现其**根本没有**``getPhoto``这个action。
请检查是否使用了过时的功能

**Comment by KotoriK** [comment]
对应的代码其实在https://github.com/mirai-mamori/Sakurairo/blob/master/functions.php#L1857-L1898
目前[这个hook](https://developer.wordpress.org/reference/hooks/wp_ajax_action/)并没有deprecate，只要funcions.php正确加载应该不会有问题
请检查下有没有与之相关的PHP错误输出

**Comment by LonePheasantWarrior** [comment]
> 对应的代码其实在https://github.com/mirai-mamori/Sakurairo/blob/master/functions.php#L1857-L1898 目前[这个hook](https://developer.wordpress.org/reference/hooks/wp_ajax_action/)并没有deprecate，只要funcions.php正确加载应该不会有问题 请检查下有没有与之相关的PHP错误输出

找到原因了!
我的博客是部署在``主机域名/blog/``路径下
访问的路径应该是``https://{{主机域名}}/blog/wp-admin/admin-ajax.php?action=getPhoto&post=39``
但实际的是``https://{{主机域名}}/wp-admin/admin-ajax.php?action=getPhoto&post=39``

这两处的代码可能有问题:
https://github.com/mirai-mamori/Sakurairo/blob/master/js/page-photo.js
https://github.com/mirai-mamori/Sakurairo/blob/master/js/page-photo.js.map
