### ISSUE TITLE
使用“相册模板“产生的一个reload调用问题

### ISSUE THREAD

**Issue by sunling666** [mirai-mamori/Sakurairo#609]
首先，我不太确定 我遇到这个bug和Issue上一条提这个相册模板的是否是同一个问题

**问题出处：*相册模板*

**实际行为描述：*在wordpress 的页面管理我新增了一个“瞬间”（就是相册）页面，然后添加了图片，选择了相册模板，然后保存更新，然后进入博客页面，点击了导航，进入页面然后没有加载出来图片内容，但是刷新后则会加载出来，这个操作目前100%复现，但是很神奇的是同样的我测试了移动端会不会出现此问题，结果是没问题*

**预期的行为：*正常点击导航进入相册页面，直接加载出我的内容，正常查看，*

**复现步骤：*页面管理添加一个页面->上传图片->模板选择相册模板->然后更新去博客查看->点击导航进入页面->页面出现但是未加载任何内容->F5刷新页面就加载成功了*

**配置与环境：*我博客目前的地址可查看验证此问题   http://43.139.85.150/*

- 问题页面：（http://43.139.85.150/）
- PHP 版本：这个不清楚
- 数据库类型 / 版本：这个也不清楚
- WordPress 版本：最新的
- 主题版本：（下图的版本）
![image](https://user-images.githubusercontent.com/48114175/194032993-924cb02c-33ff-48ff-bab4-73b795408075.png)

- 使用的插件：（没用啥插件）
- 浏览器：（edge   105.0.1343.53 (正式版本) (64 位) ）

**截图（若有）**
进入页面的样子
![image](https://user-images.githubusercontent.com/48114175/194033114-cc59cec2-53a7-4794-b643-aa1df3e9d679.png)
刷新后的样子
![image](https://user-images.githubusercontent.com/48114175/194033189-0b577761-d101-442e-af08-2fb5215232bc.png)

**Comment by sunling666** [comment]
现在想问问怎么修改代码设置 pjax 跳过相册模版    再打开pjax

**Comment by xiaozhi-6** [comment]
> bug解决了 发现开了pjax的问题，现在想问问怎么修改代码设置 pjax 跳过相册模版，或者修改哪个文件 ，再打开pjax

我的建议是暂时不要开pjax了（好像和pjax相关的问题还有其他方面，暂时还都没处理）
