### ISSUE TITLE
网站证书过期图片资源都无法加载，请更新下～

### ISSUE THREAD

**Issue by NeverOvO** [mirai-mamori/Sakurairo#610]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

用户侧的QQ、微信等图标显示错误，管理后台关于https://s.nmxc.ltd的资源全部错误

**实际行为描述：**

触发问题后造成了什么效果及影响？

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**

打开网页即可复现

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：（Release 标注的版本号）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by Zhuanjier** [comment]
已经恢复了

**Comment by xiaozhi-6** [comment]
###  视觉资源除官方提供的外也可采用第三方（群友）的，经过官方检测后合格的视觉资源路径
### 链接如下：[iro文档-视觉资源路径](https://iro.tw/guide/about.html#视觉资源路径)
