### ISSUE TITLE
追番剧模板不能刷新了

### ISSUE THREAD

**Issue by WITCHES1949** [mirai-mamori/Sakurairo#614]
**问题出处：**
https://www.witches.top/comic/
这个问题出在程序的哪一个具体功能？
填写自己的B站UID后，显示的还是作者的B站追番信息，而且点击页面底部翻下一页报404错误
**实际行为描述：**

触发问题后造成了什么效果及影响？

**预期的行为：**

这个功能应该有怎样的效果和影响？

**复现步骤：**

怎样才能再次触发这个问题？

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：（Release 标注的版本号）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by WITCHES1949** [comment]
已解决，

**Comment by AiharaMahiru** [comment]
好像出了点问题，没有识别到账号的追番，其次点击刷新时出现Error: Error，Status：404，不知道有没有相同的情况/(ㄒoㄒ)/~~
