### ISSUE TITLE
wiki说明文档的链接访问失败

### ISSUE THREAD

**Issue by lgl1227** [mirai-mamori/Sakurairo#616]
wiki说明文档的链接访问失败

**Comment by beixibaobao** [comment]
细说wiki什么东西什么访问不了

**Comment by lgl1227** [comment]
就是首页的**支持文档** 没了。https://wiki.fuukei.org/

**Comment by beixibaobao** [comment]
> 就是首页的**支持文档** 没了。https://wiki.fuukei.org/

先看https://iro.tw 旧文档吧，新文档我也不知道。

**Comment by lgl1227** [comment]
ok




 
发件人： Hikurn_xi
发送时间： 2022-11-28 18:38
收件人： mirai-mamori/Sakurairo
抄送： Alex Valentine; Mention
主题： Re: [mirai-mamori/Sakurairo] wiki说明文档的链接访问失败 (Issue #616)
就是首页的支持文档 没了。https://wiki.fuukei.org/
先看https://iro.tw 旧文档吧，新文档我也不知道。
―
