### ISSUE TITLE
增加CC协议类型选择项

### ISSUE THREAD

**Issue by SungYinieh** [mirai-mamori/Sakurairo#618]
**这是什么方面的想法？**

新增CC协议自选显示功能，优化 UI 显示，提升用户体验。
![image](https://user-images.githubusercontent.com/115633657/201501995-c8d8b5e4-bcdb-44f8-a2cd-0289df76bbb8.png)

**这个想法具体是要实现什么？**
在现有的“页面设置”-“文章页面设置”-“文章页面版权提示和标签”的选项中，没有可选CC协议类型的可选项。比如某作者想使用CC NC-SA 4.0，则无法通过直接在设置中使用选择功能来直接展示。iro或许可以内置多种CC协议类型的选项，内嵌至版权提示内部，并在标签的前面显示。

**这个想法实现后有什么帮助？**
首先可以让主题使用者更加便捷地选择与展示自己的版权许可类型，其次是让读者与潜在的转载者快速了解作者对于转载的态度。这样一来将增强作者与读者之间的版权共识。

**是否有具体的实现思路？**
在开启“页面设置”-“文章页面设置”-“文章页面版权提示和标签”后，增加显示下拉选择项，如“NC”、“SA”、“NC-SA”、“BY-NC-SA”等CC协议类型，以供选择。

**补充信息：暂无**

**Comment by KotoriK** [comment]
欢迎pr

**Comment by mirai-mamori** [comment]
是好文明，以后有机会可以考虑
