### ISSUE TITLE
关于手机端音乐不显示和赞赏扫不出来和分类显示问题顺便加人夜间模式和日光模式可以自定义图片和分享社交媒体功能

### ISSUE THREAD

**Issue by mctiantian2501314** [mirai-mamori/Sakurairo#619]
1:我打开了音乐手机端不显示，只有电脑端显示
如图:电脑端:(https://postimg.cc/xqqg9Wrg)
[![20221116-063717.png](https://i.postimg.cc/2j7t7D0p/20221116-063717.png)](https://postimg.cc/xqqg9Wrg)
手机端:(https://postimg.cc/QV59gbch)
[![20221116-063634.png](https://i.postimg.cc/v82rs2Bg/20221116-063634.png)](https://postimg.cc/QV59gbch)
2:赞赏图片电脑端太小了手机端勉强正常这是赞赏扫不出来的原因。
3：分类跑出屏幕外了。如果分类能换行就好了。
4：希望夜间和日间模式可以自定义图片。
5：希望添加社交媒体分享功能
6：你以上就是我总结出来的问题和一些建议。

**Comment by mctiantian2501314** [comment]
我再补充一句:

**Comment by mirai-mamori** [comment]
手机端是设计成不显示音乐播放器的 赞赏这个功能下个版本会进行优化 手机端目前维持现状暂时无变更计划（要重构）目前自定义功能比较繁多需要理清楚再考虑细分 分享请使用第三方插件
