### ISSUE TITLE
作者Author页面Internal server error (500)

### ISSUE THREAD

**Issue by Sprit-Fun** [mirai-mamori/Sakurairo#620]
问题出处：

作者页面-简介 页面错误

实际行为描述：

当从thumbnail或者文章的entry-census 或者footer的author-profile 读取作者简介时，都会href进入到作者的页面。但是因为作者页面会造成500错误，将导致致命站点错误。现在只能修改href进入到主页

预期的行为：

显示作者的简介

复现步骤：

进入作者页面

截图（若有）

作者页面错误：
![image](https://user-images.githubusercontent.com/43423211/202372900-cfd9ef3b-d4aa-4dd0-9619-f6f0efb2d4b0.png)
具体API Call：
![image](https://user-images.githubusercontent.com/43423211/202373017-0c38188f-5630-4374-a4ac-8f39772ef41a.png)

补充信息：
感觉是author.php 的get_header(); 导致的错误。去掉header可以正常显示，但UI有错误。

**Comment by Sprit-Fun** [comment]
有可能是WP更新后导致的错误；使用其他主题好像也可以复现这个问题。

**Comment by KotoriK** [comment]
header是肯定不能去的
可以提供更详尽的PHP报错吗

**Comment by Sprit-Fun** [comment]
@KotoriK 更新了一下，此问题在新版本已经修复了。谢谢！
