### ISSUE TITLE
多次点击封面头像会导致下方打字机特效速度异常（鬼畜）

### ISSUE THREAD

**Issue by sakuraes** [mirai-mamori/Sakurairo#621]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

这个问题出在程序的哪一个具体功能？
主页设置-封面设置-Typed.js初始化选项

**实际行为描述：**
多次点击封面头像会导致下方打字机特效速度异常（鬼畜）

触发问题后造成了什么效果及影响？
多次点击封面头像会导致下方打字机特效速度异常（鬼畜）

**预期的行为：**
多次点击封面头像会导致下方打字机特效速度异常（鬼畜）

这个功能应该有怎样的效果和影响？
它不应当速度异常

**复现步骤：**

怎样才能再次触发这个问题？
原本配置下可复现（需要打开封面签名栏打字特效）

**配置与环境：**

- 问题页面：
- https://www.ylk.cool/
- https://blog.utopiaxc.cn/
- 以上2个均为https://iro.tw/demo.html中的展示网站
- （如果有，请提供一个触发此问题的页面链接）
- 本人配置
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL5.5.62
- WordPress 版本： 6.1.1（2022年11月15日）
- 主题版本：（Release 标注的版本号）
- Sakurairo 主题版本 / Theme Version 2.5.2 | 内部版本 / Internal Version 17.2.0 | [项目地址 / Project Address](https://github.com/mirai-mamori/Sakurairo)
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- none
- 浏览器：（浏览器名称及版本号）
Microsoft Edge
版本 107.0.1418.42 (正式版本) (64 位)Windows
IOS16.1.1下的safari
谷歌应用市场下的edge107.0.1418.35
**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

另外
https://s.nmxc.ltd/sakurairo/@2.5.2/js/smoothscroll.js?ver=2.5.2
似乎是平滑滚动js的404了

**Comment by KotoriK** [comment]
应该是因为点击头像会触发页面导航
挺乐的

**Comment by mirai-mamori** [comment]
暂时应该没有这方面的优化计划，毕竟这是古早遗留问题
