### ISSUE TITLE
纪念模式下，开启封面背景一体化之后封面图并不会变黑白

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [mirai-mamori/Sakurairo#625]
**问题出处：**

这个问题出在程序的哪一个具体功能？
纪念模式，封面背景一体化
**实际行为描述：**

触发问题后造成了什么效果及影响？
封面图并不会变黑白
**预期的行为：**

这个功能应该有怎样的效果和影响？
封面图和其他元素一起变黑白
**复现步骤：**

怎样才能再次触发这个问题？
开启纪念模式，开启封面背景一体化
**配置与环境：**

- 问题页面：https://cmu.bwmc.live
- PHP 版本：8.1.11
- 数据库类型 / 版本：MySQL 8.0.24
- WordPress 版本：6.1.1
- 主题版本：2.5.2
- 使用的插件：Akismet, WP Rocket
- 浏览器：Microsoft Edge 107.0.1418.62 (Official build) (x86_64) 

**截图（若有）**

![Screen Shot 2022-11-30 at 9 19 55 PM](https://user-images.githubusercontent.com/42903464/204813654-287cf5c6-0926-47e9-8821-e81359c349f5.png)

**补充信息：**

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
https://github.com/mirai-mamori/Sakurairo/issues/463#issuecomment-1094225752 #524 
要修复估计要把封面背景一体化的实现做大改了
