### ISSUE TITLE
Move theme function to Navbar

### ISSUE THREAD

**Issue by iamAliAhad** [mirai-mamori/Sakurairo#632]
Hi, Can anyone help me? I want to bring theme function in navigation menu. How can i do that?
![th](https://user-images.githubusercontent.com/90032081/206153293-33e562cf-cb76-4cc2-bc63-6e8721ab9112.PNG)

**Comment by KotoriK** [comment]
These layouts are defined in PHP files. And the client scripts are in [Fuukei/Sakurairo_Scripts](https://github.com/Fuukei/Sakurairo_Scripts). 
You may need some search on them to find a way.

Do it yourself and good luck!
