### ISSUE TITLE
在PHP8.1下，显示弃用函数

### ISSUE THREAD

**Issue by jstar0** [mirai-mamori/Sakurairo#636]
**大致范围：**

在PHP8.1下，显示弃用函数

**具体行为描述：**

在PHP8.1下，显示如下报错信息：
`Deprecated: Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/Wordpress/wp-includes/Requests/Cookie/Jar.php on line 63

Deprecated: Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/Wordpress/wp-includes/Requests/Cookie/Jar.php on line 73

Deprecated: Return type of Requests_Cookie_Jar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/Wordpress/wp-includes/Requests/Cookie/Jar.php on line 89

Deprecated: Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/Wordpress/wp-includes/Requests/Cookie/Jar.php on line 102

Deprecated: Return type of Requests_Cookie_Jar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/Wordpress/wp-includes/Requests/Cookie/Jar.php on line 111

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/Wordpress/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 40

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/Wordpress/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 51

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/Wordpress/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 68

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/Wordpress/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 82

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/Wordpress/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 91`

**尝试：**

更换PHP版本到7.4，不再显示弃用函数（半解决）

**配置与环境：**

- 问题页面：https://valley.jstar.vip
- PHP 版本：8.1.1
- 数据库类型 / 版本：MySQL5.7
- WordPress 版本：6.1.1_zh_CN
- 主题版本：2.5.5
- 使用的插件：未启动插件
- 浏览器：Chrome/108.0.0.0

**补充信息：**

只需更改php版本即可解决

**Comment by KotoriK** [comment]
看了一下报错的文件来源，基本都是来源于wp-includes，不是这个主题的文件。

WordPress迄今为止未有完整支持PHP 8.*，参见：
1. https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/ 
2. https://make.wordpress.org/core/2022/01/10/wordpress-5-9-and-php-8-0-8-1/#:~:text=WordPress%20is%20not%20fully%20compatible%20with%20PHP%208.0%20or%208.1.%20All%20remaining%20known%20PHP%208.1%20issues%20are%20deprecation%20notices.

deprecate都不是问题，只是PHP 9的时候会跑不了而已。如果实在在意就回退到7.*就可以了。
