### ISSUE TITLE
LightGallery灯箱 的左右切换按钮样式与主题默认样式冲突

### ISSUE THREAD

**Issue by WankkoRee** [mirai-mamori/Sakurairo#639]
**问题出处：**

LightGallery灯箱效果

**实际行为描述：**

显示效果异常

![image](https://user-images.githubusercontent.com/21287731/207495536-2abae07e-b9bb-4cf2-96e7-43abe2b62e0a.png)

**预期的行为：**

正常显示

![image](https://user-images.githubusercontent.com/21287731/207495688-ddcd6f53-762a-4e45-aa04-ca3364fa7d48.png)

**复现步骤：**

开启`LightGallery灯箱效果`并在文章中添加图片即可复现。

**配置与环境：**

- 问题页面：`https://wkr.moe/study/847.html`
- PHP 版本：`8.1`
- 数据库类型 / 版本：`MariaDB 10.9.3`
- WordPress 版本：`6.1.1`
- 主题版本：`2.5.6`
- 使用的插件：样式来自主题`style.css`，与插件无关
- 浏览器：`Edge 108.0.1462.46`

**截图（若有）**

> 已提供。

**补充信息：**

主题样式关于`button`的`box-shadow`会使得LightGallery灯箱左右按钮异常。

![image](https://user-images.githubusercontent.com/21287731/207496599-baf8d63c-716b-40d7-affc-25ff209531f0.png)

**Comment by WankkoRee** [comment]
！

**Comment by KotoriK** [comment]
姑且可以先自己写个样式覆盖解决
这全局样式太难改了

**Comment by WankkoRee** [comment]
反正不是什么主要的页面样式，就先不管了。后续修了的话踹我一脚就行。

----

另，说个和本 issue 无关的建议，可以在`文章页面设置`加个文章内图片自动居中的选项，实现起来只需要加个样式即可，我自己这边用了一阵子并没有发现什么 bug。

```css
main article div.entry-content p img {
    display: block;
    margin: 0 auto;
}
```

**Comment by KotoriK** [comment]
> 另，说个和本 issue 无关的建议，可以在`文章页面设置`加个文章内图片自动居中的选项，实现起来只需要加个样式即可，我自己这边用了一阵子并没有发现什么 bug。
> 
> ```css
> main article div.entry-content p img {
>     display: block;
>     margin: 0 auto;
> }
> ```
这个古腾堡编辑器可以自己设置来着

**Comment by WankkoRee** [comment]
一直用的`Githuber MD`来着，所以对于自带的编辑器反而不了解了。

虽然`<center>`标签可以，但是懒。😵

**Comment by WankkoRee** [comment]
111
