### ISSUE TITLE
要如何才可以使用主题提供的三种灯箱效果？

### ISSUE THREAD

**Issue by Lynnhs1n** [mirai-mamori/Sakurairo#645]
已经分别开启后，刷新页面，没有发现页面、文章内的图库里的图片弹出灯箱效果。
请问还需要加入代码或者满足什么条件，灯箱效果才可以调用吗
运行环境unraid wordpress docker+mariaDB

**Comment by zhy201810576** [comment]
我遇到了同样的问题😥，我使用的是FancyBox灯箱，在开启 `低使用设置 - 灯箱` 下的**FancyBox灯箱效果**后，按照FancyBox官方v3规范添加图片在文章中并没有展示其效果，表现为点击图片后在新标签页中打开图片。

目前的解决办法是在 `低使用设置 - 自定义插入 Header 代码` 填入：
```html
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css" />
```
引用外部资源，在文章中引用图片时使用FancyBox灯箱时按照官方格式书写：
```html
<a href="image_1.jpg" data-fancybox="gallery" data-caption="Caption #1">
	<img src="thumbnail_1.jpg" alt="" />
</a>
```
以实现其效果。
