### ISSUE TITLE
请问主题支持WP的相对路径插件吗？安装了该插件之后，主页部分的本地背景图无法显示，请问应该如何解决？

### ISSUE THREAD

**Issue by Lynnhs1n** [mirai-mamori/Sakurairo#646]
**具体行为描述：**

启用Ralative URL插件后，使用该主题时，主页的背景图片无法显示（背景图已经存入Gallary文件夹，关闭该插件可以正常显示）

**尝试：**

我有试过找出对应的PHP文件里面的程序，想通过改PHP源码的方式修正这一错误，可是失败了

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：PHP 7.4.27
- 数据库类型 / 版本：MariaDB-10.6.10
- WordPress 版本：6.1.1
- 主题版本：（Release 标注的版本号）2.5.6 
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）Relative URL 0.1.8版本 作者：[Tunghsiao Liu](https://sparanoid.com/)
- 浏览器：（浏览器名称及版本号）Chrome 最新

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。
启用Ralative URL插件后，主页的背景图片无法显示
![image](https://user-images.githubusercontent.com/109627967/209158559-ba59756a-5a07-47c3-888d-b6973245f604.png)

提供尽可能多的相关信息。

**Comment by Lynnhs1n** [comment]
麻烦了，谢谢主题的作者！

**Comment by KotoriK** [comment]
请你提供开启该插件后背景图的url
