### ISSUE TITLE
大佬们请问为什么分类页面403其他页面正常

### ISSUE THREAD

**Issue by HurricanMaple** [mirai-mamori/Sakurairo#650]
新建了一个分类，结果无法访问，显示403，尝试过解决把主题重新安装结果还是不行又换成了其他主题然后就可以访问了，希望作者大大能够修复这个问题
php版本：8.1
wordpress版本：最新版
不过标签页面都正常，就是分类异常
截图：
![2](https://cdn.fiee.tk/img/1029990_origin_Screenshot_20230112_133709_com.microsoft.emmx.jpg)
![1](https://cdn.fiee.tk/img/1029991_origin_Screenshot_20230112_133712_com.microsoft.emmx.jpg)

**Comment by KotoriK** [comment]
你自己的服务器防火墙问题吧
