### ISSUE TITLE
开启页面评论区域位置信息功能导致的wordpress部分崩溃

### ISSUE THREAD

**Issue by QiuYeDx** [mirai-mamori/Sakurairo#654]
**问题出处：**

在打开显示页面评论区域位置信息功能以后，打开已有评论的旧文章页面会出现大范围崩溃以及页面信息丢失。

**实际行为描述：**

崩溃表现有：

1. 文章首图不显示，表现为灰色
2. 背景图不显示，表现为浅灰色
3. 页面布局改变，宽度从基本排满页面变为非常狭窄的布局
4. 文章内容的各种样式丢失，代码块也丢失样式
5. 打赏按钮变为一个纯橙色的圆形，丢失icon，打赏的支付宝、微信截图不显示
6. Comment部分显示不全，用户头像丢失，评论内容丢失，代替的是“您的站点遇到了致命错误。”字样，评论框丢失
7. footer等内容丢失

**配置与环境：**

- 浏览器：Chrome、Safari、移动端Safari均有此表现

**截图**

<img width="1066" alt="截屏2023-01-14 19 03 43" src="https://user-images.githubusercontent.com/71062076/212468833-094b627b-d427-4c7d-b656-80d4257397a5.png">
<img width="1355" alt="截屏2023-01-14 19 03 58" src="https://user-images.githubusercontent.com/71062076/212468836-4c5497ce-baef-4125-8116-81cf926a2e0f.png">
<img width="1204" alt="截屏2023-01-14 19 04 01" src="https://user-images.githubusercontent.com/71062076/212468838-a8fa7b80-b3c2-4cb9-b702-3af61a1c5ccd.png">

**Comment by KotoriK** [comment]
找找有没有详细的PHP错误
不过位置信息功能这玩意我个人不大建议开，目前的实现每次渲染都要调接口
