### ISSUE TITLE
主题设置保存后倒退回保存前状态

### ISSUE THREAD

**Issue by xiaoluobo58** [mirai-mamori/Sakurairo#656]
**问题出处：*Sakurairo主题设置*

**影响：*Sakurairo主题设置被重置*

**复现步骤：*未知*

**配置与环境：**

- 问题页面：主题设置
- PHP 版本：7.3.33
- 数据库类型 / 版本：MySQL 5.6.51
- WordPress 版本：6.1.1
- 主题版本：2.5
- 使用的插件：Akismet、Jetpack、LiteSpeed缓存、Live 2D、Site Kit by Google、WPvivid备份插件
- 浏览器：Microsoft Edge 109.0.1518.61

**补充信息：**

在不手动重置设置的情况下，主题设置保存后自动退回到了若干分钟前的状态，触发方式与原因未知

**Comment by mirai-mamori** [comment]
优先检查插件，无果建议进群问或者视频演示一下

**Comment by KotoriK** [comment]
有可能是没有保存上？打开f12确认一下保存时发给```admin-ajax.php```的请求是否成功

**Comment by xiaoluobo58** [comment]
检查了一下，可能是由于缓存导致
