### ISSUE TITLE
续上次的文章版权说明样式建议

### ISSUE THREAD

**Issue by SungYinieh** [mirai-mamori/Sakurairo#658]
**这是什么方面的想法？**

对于现有文章版权说明样式的优化建议，仅供参考。

**补充信息：**
此处有图，静候加载：
![image](https://user-images.githubusercontent.com/115633657/216810259-5de3cb8e-bf07-4254-8af3-da191e9411a8.png)
 对应的Hexo主题：https://theme-cards.ichr.me/start/

**Comment by mirai-mamori** [comment]
即将在新版实装新的知识共享协议提示
