### ISSUE TITLE
无法加载后台主题设置页面

### ISSUE THREAD

**Issue by moelinmtf** [mirai-mamori/Sakurairo#660]
**大致范围：**

设置问题，无法加载主题设置页面
**具体行为描述：**

无法加载主题设置页面

**尝试：**
尝试过重新安装主题
**配置与环境：**

- PHP 版本：8.1
- 数据库类型 / 版本：MySQL
- WordPress 版本：6.1.1
- 主题版本：2.5.6
- 使用的插件：无
- 浏览器：Chrome101
**截图（若有）**
[https://s1.locimg.com/2023/02/17/9e41ca6d3eeea.png](url)

**补充信息：**

使用AWS Lightsail部署，为官方自动部署镜像

**Comment by KotoriK** [comment]
按F12打开开发人员工具看看有没有报错

**Comment by moelinmtf** [comment]
有
[https://s1.locimg.com/2023/02/17/028394a601e4e.png](url)

**Comment by KotoriK** [comment]
> 有 [https://s1.locimg.com/2023/02/17/028394a601e4e.png](url)

查一下为什么404
