### ISSUE TITLE
评论后的代码块样式问题(使用了markdown插件)

### ISSUE THREAD

**Issue by BingChunMoLi** [mirai-mamori/Sakurairo#663]
- 部署环境
  1. 使用插件 [WP Editor.md – The Perfect WordPress Markdown Editor]
  2. 官方docker环境 or oneinstack php7.3+wordpress6.1.1 or https://networkos.cluba
- 触发条件
 1. 使用markdown语法书写代码块
 2. 在代码块页面评论
 3. 不刷新页面情况下,代码块变为一行,刷新后正常

**Comment by KotoriK** [comment]
用的是hljs还是prismjs？

**Comment by BingChunMoLi** [comment]
> 用的是hljs还是prismjs？

highlight.js 默认值

**Comment by BingChunMoLi** [comment]
尝试了下prism.js 在开启行号的情况下评论会导致复制键乘二，而不是样式失效。

**Comment by BingChunMoLi** [comment]
hijs 评论前样式为table评论后为code span

**Comment by KotoriK** [comment]
确实现在在评论以后会重新应用代码样式
或许该去掉

https://github.com/Fuukei/Sakurairo_Scripts/blob/8be42228eedd945915fc7d5f8f0c5bdc691918eb/src/page/index.js#L461-L466

**Comment by KotoriK** [comment]
改动应该已经在新版体现，可以测试一下
