### ISSUE TITLE
使用prism代码高亮自定义主题不加载的问题

### ISSUE THREAD

**Issue by yblpoi** [mirai-mamori/Sakurairo#665]
**事先声明**
我已经清除过浏览器 / CDN 缓存
我没有修改过相关源代码
issue中没有类似问题

**问题出处：**
这个问题出在程序的哪一个具体功能？
代码高亮——prism

**实际行为描述：**
修改使用代码高亮为prism，并且在写文章时使用html代码。
代码高亮的功能是正常的，但是自定义的代码高亮主题没有正常使用。

调试网页发现：
    - 修改："Prism.js：自动加载地址" : 在刷新缓存后功能正常
    - 修改："Prism.js：代码高亮主题" 与"Prism.js：代码高亮主题（夜间模式）"  在进入网页后没有任何变化。

**配置与环境：**

- 问题页面：[点我跳转](https://fab-forest.cn/2023/02/%e5%be%ae%e8%bd%afsurfacepro7%e6%8a%98%e8%85%bearchwin%e5%8f%8c%e7%b3%bb%e7%bb%9f%e5%b9%b6%e5%ae%89%e5%85%a8%e5%90%af%e5%8a%a8/)
- PHP 版本：8.1
- 数据库类型 / 版本：Mariadb v10.6.12
- WordPress 版本：6.1.1
- 主题版本：v2.5.6
- 使用的插件：
   -  Akismet 反垃圾评论
   -  Jetpack
   -  One User Avatar
   -  WP Super Cache
- 浏览器：Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57

**截图**
![修改配置](https://user-images.githubusercontent.com/66136793/221403699-ebf23d39-9a7b-4f9a-8af3-830c58d2a85f.png)
![页面加载](https://user-images.githubusercontent.com/66136793/221403913-7d1036d0-a979-48b8-bf3a-628b1c61649a.png)

**对于截图的说明：**
为了避免不必要的影响，我修改配置后，清除了wp缓存、浏览器缓存，并刷新了CDN目录
进入博客后发现还是没有加载预期的高亮主题。

**Comment by KotoriK** [comment]
定位了一下问题，现在的行为应当是设置了深色模式后浅色模式的主题不会生效，而深色模式的主题应该能正常生效，请切换到深色模式确认一下。

**Comment by yblpoi** [comment]
很抱歉现在才回复。
刚刚测试了一下，的确是这个问题。深色模式下主题正常生效，关闭深色模式后，刷新CDN、浏览器缓存等，依然只加载了默认主题。

**Comment by KotoriK** [comment]
> 很抱歉现在才回复。 刚刚测试了一下，的确是这个问题。深色模式下主题正常生效，关闭深色模式后，刷新CDN、浏览器缓存等，依然只加载了默认主题。

OK, 那看来已经修复没有其他问题了
