### ISSUE TITLE
封面及背景图片无法自动缩放以适应屏幕大小

### ISSUE THREAD

**Issue by Grosser-Kurfuerst** [mirai-mamori/Sakurairo#666]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：**

背景

**具体行为描述：**

封面及背景图片无法自动缩放以适应屏幕大小
比如我使用一张2560*1440的图片作为背景，在浏览器里左右就会有空白

**尝试：**

主题设置里背景缩放的选项并不起作用

**配置与环境：**

- 问题页面：抱歉，域名还在备案
- PHP 版本：7.4.23
- 数据库类型 / 版本：
- WordPress 版本：6.1.1
- 主题版本：2.5.6
- 使用的插件：并未启用任何插件
- 浏览器：edge110.0.1587.50
**截图（若有）**
![image](https://user-images.githubusercontent.com/91124738/221487388-b3dd3cb3-9ba2-40cc-8883-cd3c30523f10.png)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
主题设置选项中有封面背景的填充方式

**Comment by Grosser-Kurfuerst** [comment]
> 主题设置选项中有封面背景的填充方式
设置为自动，但是并没有用

**Comment by KotoriK** [comment]
选项的含义可以在这里查询
https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

**Comment by Grosser-Kurfuerst** [comment]
三个选项都没有作用

**Comment by KotoriK** [comment]
相关选项仅针对```封面与前台背景一体化```也同时打开的情景，因为仅在该模式下相关选项才有意义。
对于没有开启```封面与前台背景一体化```的情况，可以通过附加额外的CSS样式对```.centerbg```添加你自己的样式
