### ISSUE TITLE
后台管理登录报错

### ISSUE THREAD

**Issue by Hdf20040108** [mirai-mamori/Sakurairo#667]
这个问题出在程序的哪一个具体功能？
-后台登录

触发问题后造成了什么效果及影响？
-无法登录后台

这个功能应该有怎样的效果和影响？
-登录至后台管理页面

怎样才能再次触发这个问题？
-进入后台登录页面

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）http://www.skyandsea.xyz/wp-login.php
- PHP 版本：PHP 8
- 数据库类型 / 版本：MySQL 8.0.32
- WordPress 版本：6.1.1-zh_CN
- 主题版本：（Release 标注的版本号）2.5.6
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）无
- 浏览器：（浏览器名称及版本号）Microsoft Edge 版本 110.0.1587.57 (正式版本) (64 位)

themes文件夹下的Sakurairo已经被我打包放在 http://www.skyandsea.xyz:8080/

**Comment by KotoriK** [comment]
PHP需要安装GD模块来使用验证码功能
