### ISSUE TITLE
希望能把这个主题的所有资源做一个本地版本用于下载(Make a local version of all the resources of this theme for download)

### ISSUE THREAD

**Issue by CRK1918** [mirai-mamori/Sakurairo#673]
虽然这个主题是非常高自定义的设计，包括非常多的图片，图标, 还有背景都可以自定义和这个主题在的关于本主题里面有一些本地元素的设置，但是关于图片, CSS, JavaScript等等的元素都不是原服务器的， 如果能做一个本地的版本将会更好地使用个人的代理而不是CDN，即使我原来的服务器没有连接到互联网。 当然还要保留现在的CDN版本。

**这个想法具体是要实现什么？**

这是为了方便使用和更新Sakurairo主题，并且把一些资源文件替换成本地版本。这样你就可以在本地和CDN之间切换，而不影响原来的主题使用。

**这个想法实现后有什么帮助？**

可以在没有网络连接的情况下使用和测试这个主题，不受CDN地址的限制。

可以更方便地修改和调试这个主题，不需要每次上传和下载资源文件。

可以更加方便用于云端部署的环境下使用, 例如使用云端的HA，更快地加载和显示这个主题，不需要等待CDN地址的响应和传输。

使用个人的代理而不是CDN可以提高网页的安全性，因为你可以控制和加密你的数据流量。

**是否有具体的实现思路？**

我建议你可以把Sakurairo主题的源码和我看到的[Sakurairo_Vision](https://github.com/Fuukei/Sakurairo_Vision) 还有其他可能需要的资源都下载到你的电脑上，并且修改一些资源文件的路径，让它们指向本地文件夹，而不是CDN地址。这样你就可以在本地运行和测试这个主题了。

**Comment by luinniuxx** [comment]
把它们包装起来做一个本地的版本所以可以在releases中下载还是可以的

**Comment by mirai-mamori** [comment]
Sakurairo开启本地化并且自行部署Vision资源的话可以实现99%的本地化。如果在本地环境调试可以修改host实现。你的想法是本地下载资源访问其他站点可以不用再加载，但单个页面所需要的流量远比你想的要少且对于一个网站来说没有实际必要，你的想法更像是APP的做法。
