### ISSUE TITLE
内容较少时，样式排版出错

### ISSUE THREAD

**Issue by baddate** [mirai-mamori/Sakurairo#677]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

样式排版

**实际行为描述：**
内容很短的时候，页尾信息会错位

**预期的行为：**

应该一直显示在浏览器最底部

**复现步骤：**

新建一个内容很短的页面

**配置与环境：**

- PHP 版本：7.4
- 数据库类型 / 版本：mysql
- WordPress 版本：6.2
- 主题版本：2.5.6
- 使用的插件：no
- 浏览器：firefox

**截图**
![image](https://user-images.githubusercontent.com/37013819/229052705-39ab75f8-1a47-44df-b394-c49a004f677d.png)

**Comment by mirai-mamori** [comment]
修这个要等重构了，目前暂无调整计划
