### ISSUE TITLE
修改代码块字体为等宽字体

### ISSUE THREAD

**Issue by CircleCrop** [mirai-mamori/Sakurairo#679]
**这是什么方面的想法？**
现有内容的优化，优化代码块字体为等宽并调用设备默认字体

**这个想法具体是要实现什么？**
修改代码块CSS font-family

**这个想法实现后有什么帮助？**
使得代码块更美观

**是否有具体的实现思路？**
font-family: monospace !important;

**补充信息：**
本人不是很懂CSS，可能改动了不必要的部分，具体修改后使用的字体在上一行
https://aiccrop.com/wp-content/themes/Sakurairo-preview/style.css?ver=2.5.15 这是我网站修改后当前使用的CSS
由于急需解决显示时间问题，所以先使用了Preview版本

**Comment by KotoriK** [comment]
目前代码块的样式是交由渲染插件做的，如果有自定需求可以自行添加CSS样式。按我所知，```prismjs```渲染代码时用的就是等宽字体。

目前我们并不打算直接加入```font-family: monospace```规则，因为monospace作为后备字体，在不同的操作系统/平台上会有不同的显示，难以控制

**Comment by CircleCrop** [comment]
.highlight-wrap code {
    font-family: monospace, sans-serif !important;
}

.hljs {
  font-family: monospace, sans-serif !important;
}
我在自定义CSS中添加了如下代码以解决问题。

**Comment by CircleCrop** [comment]
顺带一提，如果使用了pjax的话，从主页跳转至包含代码的文章，highlight.js（903.js）似乎不会被加载，因而导致使用WordPress的后备样式。

**Comment by mirai-mamori** [comment]
新测试版已经更改默认字体
