### ISSUE TITLE
子分类下的展示功能不全

### ISSUE THREAD

**Issue by zssssssk** [mirai-mamori/Sakurairo#681]
**问题出处：**

子分类下的展示功能

**实际行为描述：**

![image](https://user-images.githubusercontent.com/59335567/231340721-c8d28332-d199-491b-b3fc-c140cae141d8.png)

导进去了很多文章，但是easy子分类下的文章展示不全，就展示了十来篇，点”更早的文章“也加载不出
**预期的行为：**

应该能将该子分类下的文章展示全

**复现步骤：**

建一个父分类，子分类，并将大量文章导入该子分类下，在页面中进行查看子分类即可

**配置与环境：**

- 问题页面：[（问题的页面链接）](http://123.60.3.181/leetcode/easy/)
- PHP 版本：7.4
- 数据库类型 / 版本：7.9.8
- WordPress 版本：6.2
- 主题版本：（Release 标注的版本号）2.5.6
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
![image](https://user-images.githubusercontent.com/59335567/231342003-1455a66d-26a5-4480-a085-b8761cd743ea.png)

- 浏览器：（浏览器名称及版本号）：edge、112.0.1722.34

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by kanodaisuki** [comment]
@zssssssk hi，参照你的复现步骤，我没能复现你遇到的问题。请提供一下你的wordpress“固定链接”配置情况，以及关于nginx URL rewrite的配置，我怀疑是该项配置错误引起的问题。

**Comment by zssssssk** [comment]
十分感谢，我把固定链接里的自定义结构改成文章名就好了，后面那个nginx url都没用到，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mirai-mamori/Sakurairo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mirai-mamori/Sakurairo] 子分类下的展示功能不全 (Issue #681)





 
@zssssssk hi，参照你的复现步骤，我没能复现你遇到的问题。请提供一下你的wordpress“固定链接”配置情况，以及关于nginx URL rewrite的配置，我怀疑是该项配置错误引起的问题。
