### ISSUE TITLE
B站收藏页面报错

### ISSUE THREAD

**Issue by CircleCrop** [mirai-mamori/Sakurairo#683]
[https://aiccrop.com/bilibili-collections/](https://aiccrop.com/bilibili-collections/) 

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.2
- 数据库类型 / 版本：Maria Db 10.7
- WordPress 版本：6.2
- 主题版本：（Release 标注的版本号）2.5.15
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**
![da511836d115a9d](https://user-images.githubusercontent.com/54088075/231743569-ed0477f3-91f1-4f89-a260-7413c6cf81d9.jpg)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
报错修了，但是好像还是不能用，等其他人继续修

**Comment by CircleCrop** [comment]
感谢！

染川 瞳 ***@***.***> 于 2023年4月14日周五 13:59写道：

**Comment by mirai-mamori** [comment]
或许，应该，修了
