### ISSUE TITLE
B站追番模板在PHP8下提示弃用函数

### ISSUE THREAD

**Issue by CircleCrop** [mirai-mamori/Sakurairo#684]
虽然可以通过关闭 PHP 的 error 输出解决，不过如果能解决最好啦
![TX80($SRSFO9F QE@ODUSTF](https://user-images.githubusercontent.com/54088075/231787490-2b586852-91d5-4f25-b5fc-1c06c850edda.jpg)

**Comment by mirai-mamori** [comment]
修了

**Comment by CircleCrop** [comment]
感谢！

染川 瞳 ***@***.***> 于 2023年4月14日周五 13:59写道：
