### ISSUE TITLE
网页根目如像ua文件夹，评论等级文件夹没有自动被主题安装？还是说要自己建立文件夹和svg文件？

### ISSUE THREAD

**Issue by zsanjin-p** [mirai-mamori/Sakurairo#697]
**配置与环境：1核1g，centos7，

- PHP 版本：7.4
- 数据库类型 / 版本：5.5
- WordPress 版本：6.2
- 主题版本：Sakurairo-2.6.0
- 使用的插件：Google Analytics for WordPress by MonsterInsights  
Loginizer
Rank Math SEO
Simple Local Avatars
Smartideo
W3 Total Cache
Widget Options
WP Statistics
WPvivid备份插件
简易目录
经典编辑器
- 浏览器：Microsoft Edge版本 112.0.1722.48 (正式版本) (64 位)

    在网页f12的时候看见ua的svg文件和评论等级svg文件等都是404，我看了一下链接地址就是主页/ua/xx.svg出现404，主页/basic/wave1.png出现404，以及其他类似的问题，就像主页/basic/wave1.png这个我不知道这个文件目的是什么，可能还有一些类似问题没排查出来，后来我弄了相应的文件和文件夹，改了文件夹用户组和nginx为一个组的才能够正常读取ua文件和等级文件，像wave1.png我没有尝试，不过我猜测可能和首页的波浪效果有吧，因为我开启了首页大图底部的波浪和箭头设置，并没有起作用

**Comment by mirai-mamori** [comment]
检查主题设置视觉资源路径是否正确

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: github-actions[bot] ***@***.***>
发送时间: Friday, April 21, 2023 11:31:13 PM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [mirai-mamori/Sakurairo] 网页根目如像ua文件夹，评论等级文件夹没有自动被主题安装？还是说要自己建立文件夹和svg文件？ (Issue #697)


@zsanjin-p<https://github.com/zsanjin-p>，感谢你给 sakurairo 提出了 issue。d(RQ*)o
请根据 issue 模版确保背景信息的完善，我们将调查并尽快回复你。

―

**Comment by zsanjin-p** [comment]
是Sakurairo的主题设置吗，我好像没看到相关资源的路径选择

**Comment by CRK1918** [comment]
> 是Sakurairo的主题设置吗，我好像没看到相关资源的路径选择

在关于主题设置里面，你应该能找到资源路径。

**Comment by zsanjin-p** [comment]
我找到在git存着的视觉资源了，还有一个问题请教一下，主题的代码高亮有示范文档吗

**Comment by CRK1918** [comment]
> 我找到在git存着的视觉资源了，还有一个问题请教一下，主题的代码高亮有示范文档吗

在Wordpress直接插入代码block就行, 

Highlight.js： 这个主题的默认值，自动识别语言, 很多情况下都不正确需要手动调（如果修改wordpress需要你转换到经典的block）:

如

`<pre class="wp-block-code"><code>sudo apt-get install sl</code></pre>`

手动改bash:

```
<pre class="wp-block-code"><code class="language-bash">sudo apt-get install sl
</code></pre>
```

如果用 Prism.js就看一下： 
https://prismjs.com/#basic-usage
