### ISSUE TITLE
关于主题登陆界面

### ISSUE THREAD

**Issue by seyuk** [mirai-mamori/Sakurairo#698]
希望能有一个使用其他登陆页面的选项，比如我比较喜欢原本的登录界面；但每次更新都手动改主题文件，有点麻烦。（
所以刚才我使用了[Custom Login Page Customizer](https://wordpress.org/plugins/login-customizer/)，
但是这个也不能很好的干涉主题的登陆界面，并且使用之后无法正常显示“Simple Cloudflare Turnstile“插件的人机验证界面，禁用了之后也无法返回原本的登陆界面。

**Comment by mirai-mamori** [comment]
下个版本会加入开关
