### ISSUE TITLE
哔哩哔哩收藏模板报错

### ISSUE THREAD

**Issue by AiYuuki** [mirai-mamori/Sakurairo#699]
**问题出处：**

哔哩哔哩收藏模板

**实际行为描述：**

请求收藏页，`BilibiliFavlist.php` 的 `fetch_folder_item_api` 方法抛出类型传递错误

**预期的行为：**

应正常显示

**复现步骤：**

使用 `哔哩哔哩收藏模板` 模板页，并填写 UID 和 Cookie 后，使用模板的页面会抛出错误

**配置与环境：**

- 问题页面：[https://kira.cool/test](https://kira.cool/test)
- PHP 版本：7.4
- 数据库类型 / 版本：5.7.40
- WordPress 版本：6.2
- 主题版本：2.6
- 使用的插件：-
- 浏览器：Microsoft Edge 112.0.1722.48（x64）

**截图（若有）**

![KF 2YW({@ VXWCWH T77Q8M](https://user-images.githubusercontent.com/28827378/233763644-429e9bac-efe5-41f7-84ca-1054d1cc88e2.png)
![_2HAW%H13Z PE$F{D)()5VW](https://user-images.githubusercontent.com/28827378/233763645-bc4691fb-a665-4fd4-9b9f-d208d9fbc3e0.png)

**补充信息：**

埋点后发现收藏夹数据正常获取。

**抛出错误**：
```
  Fatal error: Uncaught TypeError: Return value of Sakura\API\BilibiliFavList::fetch_folder_item_api() must be an instance of 
  Sakura\API\mixed, array returned in /www/wwwroot/kira.cool/wp-content/themes/Sakurairo-2.6.0/inc/classes/BilibiliFavList.php:49 
  Stack trace: #0 /www/wwwroot/kira.cool/wp-content/themes/Sakurairo-2.6.0/inc/classes/BilibiliFavList.php(84): 
  Sakura\API\BilibiliFavList->fetch_folder_item_api() #1 /www/wwwroot/kira.cool/wp-content/themes/Sakurairo- 
  2.6.0/inc/classes/BilibiliFavList.php(69): Sakura\API\BilibiliFavList->folder_display() #2 /www/wwwroot/kira.cool/wp- 
  content/themes/Sakurairo-2.6.0/user/page-bilibiliFavList.php(28): Sakura\API\BilibiliFavList->get_folders() #3 
  /www/wwwroot/kira.cool/wp-includes/template-loader.php(106): include('/www/wwwroot/ki...') #4 /www/wwwroot/kira.cool/wp- 
  blog-header.php(19): require_once('/www/wwwroot/ki...') #5 /www/wwwroot/kira.cool/index.php(17): require('/www/wwwroot/ki...') 
  #6 {main} thrown in /www/wwwroot/kira.cool/wp-content/themes/Sakurairo-2.6.0/inc/classes/BilibiliFavList.php on line 49
```

即期望返回 Sakura\API\mixed 类型，但实际返回了数组。
 
做错误排查时，删除 mixed 数据类型约束后，此时无报错，且页面正常渲染：
![image](https://user-images.githubusercontent.com/28827378/233763760-ab1ebde4-c27b-4361-9bec-37968c331127.png)
![image](https://user-images.githubusercontent.com/28827378/233763774-2b964e6c-6c24-4d8e-8804-be2e37fd87c0.png)

**Comment by KotoriK** [comment]
没有想到mixed是一个php 8特性...https://php.watch/versions/8.0/mixed-type
当初加这个类型好像是php 8下会报类型错误，抽空看看有没有什么办法解决
