### ISSUE TITLE
说说板块中评论提示文字与其他元素重合

### ISSUE THREAD

**Issue by Will-ChenYW** [mirai-mamori/Sakurairo#70]
**问题出处：**

主题的说说功能

**实际行为描述：**

“Comments off”提示文字与图片的重叠

**预期的行为：**

建议此处从"Comments off on xxx"改为"Comments off"

**复现步骤：**

当说说的名字超过某个特定长度

**配置与环境：**

与环境无关

**截图（若有）**

![image](https://user-images.githubusercontent.com/44114934/88478186-a5a06980-cf78-11ea-9b5a-d4a41554e884.png)

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
已收到，下个版本修正。谢谢你的支持！
