### ISSUE TITLE
Translation enhance

### ISSUE THREAD

**Issue by Techssh** [mirai-mamori/Sakurairo#704]
--现有内容的优化 / 新增功能 / UI 界面 / 用户体验--

我现在使用英文版的, 但是有一些翻译不够齐全

折叠信息块:
展开 / 收缩 →( expand / collapse )

评论版块:
上车请刷卡。→(删除)

![translation enhance](https://user-images.githubusercontent.com/127261267/234064416-ea54cb63-e369-4c31-9d19-82a07c344da6.JPG)

**Comment by kanodaisuki** [comment]
确实存在这个问题，预计下个版本修复

**Comment by mirai-mamori** [comment]
上车请刷卡已经有双语提示了，不是完全不能用。短代码翻译已经更改

**Comment by mirai-mamori** [comment]
下个版本实装
