### ISSUE TITLE
文章标题导航栏即使没有小标题，也依旧存在

### ISSUE THREAD

**Issue by Yish1** [mirai-mamori/Sakurairo#708]
**问题出处：任意页面

**实际行为描述：文章标题导航栏即使没有小标题，也依旧存在

**预期的行为：没有小标题的文章不应该存在导航栏

- 问题页面：(https://classone.top/friends/)
- PHP 版本：7.4
- 数据库类型 / 版本：
- WordPress 版本：6.2
- 主题版本：2.6.0
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**
![4d715a82b40ce4793dee025e8174254](https://user-images.githubusercontent.com/101796381/235342498-2d793c73-7def-42ee-8d58-3e23296bd5b4.png)

**Comment by KotoriK** [comment]
如果指的是文章目录，文章目录仅在满足指定要求时才会出现。可以看看是不是页面的什么内容错误地满足了要求
https://github.com/Fuukei/Sakurairo_Scripts/blob/735a979d2b3e2a3853f165490c3831322b456b1a/src/page/index.js#L316-L354
