### ISSUE TITLE
php8.0兼容性问题

### ISSUE THREAD

**Issue by Yish1** [mirai-mamori/Sakurairo#709]
**问题出处：升级php时遇到

**实际行为描述：升级php后，有评论的文章或页面都会提示“服务器内部错误”，没评论的文章发送评论后显示“服务器内部错误”，并且刷新后也无法打开了，与前者一样

**预期的行为：无法访问

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.0.2
- 数据库类型 / 版本：
- WordPress 版本：6.2
- 主题版本：2.6.0
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）

**截图（若有）**
![c6611612e9caa67a7507cfa3157dda3](https://user-images.githubusercontent.com/101796381/235342678-5a3d07e1-87e1-4444-9cb1-caad74e6b3e3.jpg)
![c552ed90d286f1e6b08d5622169d57a](https://user-images.githubusercontent.com/101796381/235342680-ee9d6065-ff30-4585-8d59-675b5315d226.jpg)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：wordpress自带主题没有任何问题，即便是最新的PHP8.2也没任何问题，所以可以确定时本主题的兼容性问题，但debug.log没有记录这段报错内容

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
信息不足，无法判断

**Comment by bymoye** [comment]
无法复现。
