### ISSUE TITLE
希望增加说说特色图片与评论选项

### ISSUE THREAD

**Issue by wojiaoyishang** [mirai-mamori/Sakurairo#712]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**

使用贵主题后，博客访问 /shuoshuo 默认是说说文章的归档页面（所有说说的集合页面）。在此页面中的说说特色图片默认采用了“没有特色图片采用随机壁纸api”的方法，有点强迫症，我想要自定义说说的特色图片。同时，此页面的每个说说会显示“评论关闭”的字样。扣一下字眼，“评论关闭”和“没有评论功能”是两回事儿，我更倾向去打开评论的功能（因为QQ空间的说说不也是可以评论的吗(^▽^)）。

**这个想法具体是要实现什么？**

增加说说特色图片与评论选项

**这个想法实现后有什么帮助？**

便于用户更好地自定义主题

**是否有具体的实现思路？**

请看 PR（ #711 ）：feat: 说说增加启用特色图片与评论选项

**Comment by mirai-mamori** [comment]
已实现
