### ISSUE TITLE
不知道为什么开启导航栏搜索后，首页无法显示？ 会出现一个小框框，但是不显示搜索的图标。

### ISSUE THREAD

**Issue by qunlovehe** [mirai-mamori/Sakurairo#717]
在后台开启了导航栏搜索后，右上角的 搜索 图标不显示，会出现一个小框子，如果单击的话会出现搜索界面。只是图片单纯的不正常显示，这是因为我设置了某些东西导致遮盖了吗？
[www.249249.xyz ](url)

貌似不能上传图片，还麻烦大佬帮忙看一下。

**Comment by mirai-mamori** [comment]
应该是视觉资源路径的问题，可以检查一下相关设置
