### ISSUE TITLE
请增加对QQ音乐上传cookie的支持

### ISSUE THREAD

**Issue by WaterApple09** [mirai-mamori/Sakurairo#721]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**

现有内容的优化

**这个想法具体是要实现什么？**

QQ音乐可播放会员音乐

**这个想法实现后有什么帮助？**

网易云音乐因版权问题有太多歌曲无法播放了，以及QQ音乐的用户数量也不小，只有网易云可以上传cookie对qq音乐用户来说有亿点难受

**是否有具体的实现思路？**

与网易云同理，请增加对qq音乐cookie上传的支持

**Comment by mirai-mamori** [comment]
暂无计划
