### ISSUE TITLE
Highlight.js 显示异常

### ISSUE THREAD

**Issue by Techssh** [mirai-mamori/Sakurairo#722]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**
Highlight.js

**实际行为描述：**
升级到最新的版本之后就出现了这个问题

**复现步骤：**

怎样才能再次触发这个问题？

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.2.5
- 数据库类型 / 版本：10.5.18 MariaDB
- WordPress 版本：6.2
- 主题版本：（Release 标注的版本号） 2.6.1 update (1)
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）N/A
- 浏览器：（浏览器名称及版本号）chrome 112.0.5615.121

**截图（若有）**
![Highlight js](https://github.com/mirai-mamori/Sakurairo/assets/127261267/bc1d298c-7349-4a04-8208-74e673cfc5a0)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**
视觉资源路径是使用最新的:
https://github.com/Fuukei/Sakurairo_Vision

**Comment by kanodaisuki** [comment]
行内代码与代码块的样式优先级出现了一些问题，在修了
