### ISSUE TITLE
首页进入后顶部出现php警告

### ISSUE THREAD

**Issue by zsanjin-p** [mirai-mamori/Sakurairo#724]
**问题出处：**

用了主题后进入首页上方有一行报错：Warning:  mysqli_num_fields() expects parameter 1 to be mysqli_result, bool given in /www/wwwroot/www.域名/wp-includes/class-wpdb.php on line 3819＂ while reading response header from upstream, client: 172.73.223.8, server: www.域名, request: ＂GET /tags/development/ HTTP/2.0＂, upstream: ＂fastcgi://unix:/tmp/php-cgi-74.sock:＂, host: ＂www.域名＂

**实际行为描述：**

没什么影响，影响美观吧，一进去就弹出来这个字，然后才是动画浮现网页

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：5.7
- WordPress 版本：6.2
- 主题版本：（Release 标注的版本号）2.6

**Comment by kanodaisuki** [comment]
hi，从你给出的信息中，不足以确定出现错误的原因。请问你是否有使用数据库缓存相关的插件？如果可以，请列出你正在使用的插件，以帮助定位问题。

**Comment by robert1chi** [comment]
有可能是数据库缓存插件的问题，关闭这类插件试试警告是否会消失。
It may be the issue of the database cache plugin, turn it off first and try to see if the warning disappears.

**Comment by G-Sea** [comment]
我也一样的问题，刚刚安装的WordPress版本，没有改变如何WordPress配置，没使用插件，一样的问题：


Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 117

Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 118

Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 119

Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 121

**Comment by robert1chi** [comment]
> 我也一样的问题，刚刚安装的WordPress版本，没有改变如何WordPress配置，没使用插件，一样的问题：
> 
> Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 117
> 
> Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 118
> 
> Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 119
> 
> Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 121

你这问题不太一样，你是没有配置导航栏的logo。

**Comment by G-Sea** [comment]
> 

感谢，现在正常了

**Comment by zsanjin-p** [comment]
> @zsanjin-p，感谢你给 sakurairo 提出了 issue。ヾ(≧▽≦*)o 请根据 issue 模版确保背景信息的完善，我们将调查并尽快回复你。



> hi，从你给出的信息中，不足以确定出现错误的原因。请问你是否有使用数据库缓存相关的插件？如果可以，请列出你正在使用的插件，以帮助定位问题。



> 有可能是数据库缓存插件的问题，关闭这类插件试试警告是否会消失。 It may be the issue of the database cache plugin, turn it off first and try to see if the warning disappears.



> 我也一样的问题，刚刚安装的WordPress版本，没有改变如何WordPress配置，没使用插件，一样的问题：
> 
> Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 117
> 
> Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 118
> 
> Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 119
> 
> Warning: Trying to access array offset on value of type null in /www/wwwroot/域名/wp-content/themes/Sakurairo-2.6.1.1/header.php on line 121

破案，是W3 Total Cache插件问题，换其他的缓存插件就行了
