### ISSUE TITLE
注册界面人机验证

### ISSUE THREAD

**Issue by tangpoya** [mirai-mamori/Sakurairo#733]
现有内容的优化 ：
给注册页面加个人机验证码

我现在使用Vaptcha验证码，但只有登录界面有，注册界面没有，导致一大堆注册机注册

**Comment by tangpoya** [comment]
![image](https://github.com/mirai-mamori/Sakurairo/assets/88241889/e5c833f4-3dba-4530-9270-c452e35798da)

**Comment by WaterApple09** [comment]
可以先试试cloudflare turnstile，reCAPTCHA，极验这种插件作为一个临时的替代
毕竟作者需要一段时间才能回复嘛

**Comment by tangpoya** [comment]
不删倒还好，但把这堆删了后又冒出一大堆

**Comment by tangpoya** [comment]
现在还好，起码这些注册机登不进去

**Comment by CRK1918** [comment]
我觉得用WAF应用或者CloudFlare Proxy的URL过滤也可以
