### ISSUE TITLE
友情链接页面出现error

### ISSUE THREAD

**Issue by zoujunyi2127** [mirai-mamori/Sakurairo#734]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：**
/www/wwwroot/zjydiary.top/wp-content/themes/Sakurairo-2.6.0/functions.php on line 1176

**具体行为描述：**

友情链接页面出现error

**尝试：**

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.0
- 数据库类型 / 版本：mysql
- WordPress 版本：6.2.2
- 主题版本：（Release 标注的版本号）2.6.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**
<img width="951" alt="截屏2023-05-21 18 56 02" src="https://github.com/mirai-mamori/Sakurairo/assets/113773870/1a2b564f-9990-4fc7-aa81-57b8d35dfb29">

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
优先更新到最新版先

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: github-actions[bot] ***@***.***>
发送时间: Sunday, May 21, 2023 6:59:04 PM
收件人: mirai-mamori/Sakurairo ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [mirai-mamori/Sakurairo] 友情链接页面出现error (Issue #734)


任何人都可以处理此问题。
请务必在您的 pull request 中引用此问题。
感谢你的贡献! (obb)o☆

―

**Comment by zoujunyi2127** [comment]
修改文件1176行为
`    if(!empty($content)) {
    @$dom->loadHTML($content);
} else {
    // 可能记录一个错误或者以不同的方式处理这个情况
}`
就好了

**Comment by kanodaisuki** [comment]
此问题已在[2.6.1.1](https://github.com/mirai-mamori/Sakurairo/releases/tag/2.6.1.1)中得到修复，请及时更新主题。
