### ISSUE TITLE
代码高亮还是有问题 highlight.js

### ISSUE THREAD

**Issue by waangcy** [mirai-mamori/Sakurairo#736]
首次打开网页正常，但是F5刷新该网页后显示不正常。通过F12排查，提示出现截图错误
![a](https://img.mjj.today/2023/05/21/c07b87c2a16c92941b7c6a882ecbe416.png)

- 问题页面：任意显示代码高亮页面
- PHP 版本：7.4
- 数据库类型 / 版本：mysql5.6
- WordPress 版本：最新
- 主题版本：2611
- 浏览器：chrome113

**Comment by kanodaisuki** [comment]
这是一个因未转义代码段里的HTML代码而带来的错误，比如说“>”，此问题可能会导致网站受到“XSS攻击”，详见[https://github.com/highlightjs/highlight.js/wiki/security](https://github.com/highlightjs/highlight.js/wiki/security)

值得注意的是，这不是主题自身原因。

而是你所使用的编辑器插件“wp-editormd”未对代码里的特殊字符做转义导致的。另外一个原因是，你同时使用了两种代码高亮方法：Highlight.js与Prism.js。

现在你有两个解决此问题的方法：

一是将主题的代码高亮功能关闭，在设置选项中将`代码高亮程序`设置为`自定义`；另外一个方法是禁用wp-editormd编辑器的代码高亮功能，转而使用主题自带的代码高亮功能。

应该明确的一件事情是，不要同时使用两种代码高亮程序。我的建议是使用第一个方法。

**Comment by waangcy** [comment]
> 
已解决，感谢。通过禁用wp-editormd编辑器的代码高亮功能，已正常显示且刷新正常
