### ISSUE TITLE
fontawesome图标无法正常显示

### ISSUE THREAD

**Issue by LuckyPuppy514** [mirai-mamori/Sakurairo#737]
**问题出处：**

有使用fontawesome图标的地方，如菜单栏，文章列表等

**实际行为描述：**

fontawesome图标无法正常显示

**预期的行为：**

fontawesome图标正常显示

**复现步骤：**

浏览器访问问题页面，即可看到菜单栏图标显示异常，在 [官方站点展示中也有不少站点存在同类问题](https://github.com/Fuukei/docs_site/discussions/1#discussioncomment-4559264)

**配置与环境：**

- 问题页面：[LuckyPuppyのBlog](https://www.lckp.top)
- PHP 版本：8.0.28
- 数据库类型 / 版本：mysql / 5.7.41
- WordPress 版本：6.1.3
- 主题版本：2.6.0
- 使用的插件：Autoptimize, Yoast SEO, WP Githuber MD, WP Statistics, Wordfence安全, Easy WP SMTP, Attachment Pages Redirect
- 浏览器：Edge / Chrome

**截图（若有）**

![image](https://github.com/mirai-mamori/Sakurairo/assets/53246532/20c63be6-56dd-4a57-8cd8-b3fbfe080207)

**补充信息：**

无

**Comment by mirai-mamori** [comment]
请更新到最新版

**Comment by WaterApple09** [comment]
跨域问题，我是等会就好了
或者自己把资源本地化也可以

**Comment by LuckyPuppy514** [comment]
> 跨域问题，我是等会就好了 或者自己把资源本地化也可以

是的，没找到改本地化的地方，但是升级到最新版就好了 😂
