### ISSUE TITLE
时间轴页面底部未全覆盖

### ISSUE THREAD

**Issue by tudou-OuO** [mirai-mamori/Sakurairo#740]
- PHP 版本：7.4
- WordPress 版本：6.2
- 主题版本：2.6.1.1
- 使用的插件：这和插件没啥关系罢（）
- 浏览器：microsoft edge 115.0.1866.1

问题出处：时间轴页面
实际行为描述：时间轴页面的白色亚克力效果背景未全覆盖，底部有大量未覆盖区域...说着有点抽象，看图就知道了
![image](https://github.com/mirai-mamori/Sakurairo/assets/120903437/25c08025-118d-4972-abbd-5a60c3ce43a8)
复现步骤：打开时间轴页面（https://blog.tudououo.top/timeline/），拉到底部即可

**Comment by CRK1918** [comment]
这与 issue #677 相似， 多增加一些内容就可以了。

**Comment by tudou-OuO** [comment]
但是一时间我更新不出这么多文章qaq

> 这与 issue #677 相似， 多增加一些内容就可以了。
