### ISSUE TITLE
字体资源加载不出

### ISSUE THREAD

**Issue by waangcy** [mirai-mamori/Sakurairo#749]
**问题出处：**
具体链接：https://cdn4.tianli0.top/fonts/css?family=Noto+Serif|Noto+Serif+SC|Noto+Sans+SC|Dela+Gothic+One|Fira+Code&display=swap

返回结果：{"code":"40310002","msg":"region is forbidden"}

貌似是IP被限制了？

或者请提供自建该服务的修改入口

**Comment by mirai-mamori** [comment]
字体服务只在中国大陆运营

**Comment by waangcy** [comment]
> 字体服务只在中国大陆运营

请问怎么替换为自己的地址
