### ISSUE TITLE
无法拉取本地数据库的随机图片

### ISSUE THREAD

**Issue by wjqalan** [mirai-mamori/Sakurairo#750]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：**

这是哪一方面的问题？你是否知道问题所牵连到的文件以及在文件的哪一行？

**具体行为描述：无法拉取本地随机图片和网易云音乐，局域网也不行

你的问题具体是什么？

 #**尝试：需要开放额外端口吗？

你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了

**配置与环境：Windows 10 Pro 宝塔面板

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：74
- 数据库类型 / 版本：MySQL 57
- WordPress 版本：6.1
- 主题版本：（Release 标注的版本号）2.6.2
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）无启用插件
- 浏览器：（浏览器名称及版本号）edge，edge can，Chrome，Firefox，Safire

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：如果需要网站链接的话叫我一下，再提供

提供尽可能多的相关信息。

**Comment by wjqalan** [comment]
现在更加严重，使用edge浏览器自动跳转https会失去UI主题

**Comment by mirai-mamori** [comment]
链接

**Comment by wjqalan** [comment]
> 链接

UI主题问题在edge上偶发，移动客户端无法访问网易云音乐

**Comment by wjqalan** [comment]
www.wjqserver.xyz

**Comment by wjqalan** [comment]
www.wjqserver.xyz

**Comment by mirai-mamori** [comment]
先把证书正确配置后再说 移动端不显示音乐播放器

**Comment by wjqalan** [comment]
> 先把证书正确配置后再说 移动端不显示音乐播放器

![Screenshot_2023-06-17-14-13-28-666_com android chrome](https://github.com/mirai-mamori/Sakurairo/assets/114663932/0ca9899e-61b7-4a19-a0c2-ba0afa6453f4)
只要加上 ssl证书，就没UI

**Comment by wjqalan** [comment]
在？

**Comment by kanodaisuki** [comment]
https与http混合内容无法在浏览器中加载，这是一个常识。

请把你的`WordPress地址（URL）`改成https协议地址。

为了确保安全，你应该始终使用https。如果你不知道如何操作，请在网络上查阅相关资料。一些基础性的问题，在这里你可能无法得到更多的支持。

感谢你使用Sakurairo主题。
