### ISSUE TITLE
頁面封面圓角異常

### ISSUE THREAD

**Issue by moekira** [mirai-mamori/Sakurairo#754]
問題：頁面(文章、分類等)頂部封面pattern-center的圓角不能正常運作？
<img width="192" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/125431448/133b0673-caee-4af2-8ee8-40c4ee406694">
這是設置中的截圖，我實際已經選擇了圓角樣式(page_style=sakurairo)
<img width="599" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/125431448/38130b64-8f74-4038-8c7b-83b4216dfad4">
可能是由於2.6.0版本style.css中刪除了border-radius樣式，但我無法確認這是否是一個細節問題。
<img width="320" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/125431448/1b86cf5a-9977-446a-a961-ca6916fba09c">
感謝解答。

**Comment by kanodaisuki** [comment]
补充：关联Commit [a14ac17](https://github.com/mirai-mamori/Sakurairo/commit/a14ac1743a29aec197bb2edad5e86145d4a6eef5)

**Comment by mirai-mamori** [comment]
确实已经移除了 后面更新一下提示图
