### ISSUE TITLE
AI摘要选择不需要生成，出现BUG

### ISSUE THREAD

**Issue by zoujunyi2127** [mirai-mamori/Sakurairo#755]
**问题出处：**

这个问题出在程序的哪一个具体功能？

ChatGPT生成AI摘要

实际行为描述：

将即将发布的文章的ID填入不需要生成框中

触发问题后造成了什么效果及影响？

仍然有与文章搭不着边的AI摘要生成

**预期的行为：**

这个功能应该有怎样的效果和影响？

生成空白AI摘要

**复现步骤：**

怎样才能再次触发这个问题？

将即将发布的文章的ID填入不需要生成框中

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）https://www.zjydiary.top/?p=299
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL 5.7.39
- WordPress 版本：6.2.2
- 主题版本：Sakurairo 主题版本 2.6.2 | 内部版本 18.2.0 |
- 使用的插件：Big File Uploads、Easy WP SMTP、IP2Location Country Blocker、Login Lockdown、Show IDs、Simple Local Avatars、Wechat Social、Wordfence安全、WP Statistics、注册IP (Register IPs)
- 浏览器：Chrome 114.0.5735.133（正式版本） (arm64)

**截图（若有）**

<img width="1125" alt="截屏2023-06-26 16 33 23" src="https://github.com/mirai-mamori/Sakurairo/assets/113773870/1cb8f12d-ebca-4901-b127-43fb04c675dc">
<img width="905" alt="截屏2023-06-26 16 33 35" src="https://github.com/mirai-mamori/Sakurairo/assets/113773870/0ad25f85-2e65-40ea-adec-1ea5b974180c">

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
先看得懂选项意思再说

**Comment by zoujunyi2127** [comment]
> 先看得懂选项意思再说

请你具体解释一下

**Comment by zoujunyi2127** [comment]
hooks.php34行后面加上
```
 }elseif (!empty(get_post_meta($post_id, POST_METADATA_KEY, true))) {
                    delete_post_meta($post_id,POST_METADATA_KEY);
                
```
有效解决
