### ISSUE TITLE
移动端显示时，正文字体大小锁死在 16

### ISSUE THREAD

**Issue by Eterance** [mirai-mamori/Sakurairo#756]
**问题出处：**

全局设置 -> 字体设置 -> 文本字体大小

**实际行为描述：**

移动端显示时，正文字体大小锁死在 16。

当在设置中设置字体不等于 16（这里设置为 10），并且将浏览器窗口拉小以触发移动端布局时，正文字体锁死在16；

![image](https://github.com/mirai-mamori/Sakurairo/assets/25473156/ca094792-8d58-429d-bf3d-f6388dabe937)

提示块字体正常，为 10：

![image](https://github.com/mirai-mamori/Sakurairo/assets/25473156/fb8b9550-0d1f-4722-9708-da0ebcb269c3)

**预期的行为：**

移动端正文字体大小也跟着设置走。

（能不能添加个移动端和桌面端的字体大小分开设置的 feature，我设置 18 在电脑上觉得合适但是手机看起来觉得太大了 QAQ）

（好像手机锁死 16 挺合适的，那反过来不就是提示块没锁死 16 是 bug）

**复现步骤：**

设置中设置字体大小为不等于 16，并且将浏览器窗口拉小以触发移动端布局或者用手机查看即可。

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.1
- 数据库类型 / 版本：MySQL 5.7.40
- WordPress 版本：6.2.2
- 主题版本：（Release 标注的版本号）2.6.2
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）Code Snippets, Meow Lightbox, Simple User Avatar, ThumbPress - Stop Generating Unnecessary Thumbnails, WP SuperCache （禁用所有插件后，现象仍存在）
- 浏览器：（浏览器名称及版本号）Microsoft Edge 版本 115.0.1901.14 (正式版本) beta (64 位)

**截图（若有）**

截图已在正文添加

**补充信息：**

无

**Comment by mirai-mamori** [comment]
下个版本把提示框锁死吧
