### ISSUE TITLE
深色模式/夜间模式 背景透明度过低

### ISSUE THREAD

**Issue by Eterance** [mirai-mamori/Sakurairo#757]
**问题出处：**

UI……？

**实际行为描述：**

浅色模式下，透明度是正常（符合预期）的，能看得见背景图：

![image](https://github.com/mirai-mamori/Sakurairo/assets/25473156/c5a7aeec-6fa9-4a24-aeb9-8a204fceb163)

但是深色模式下，背景图几乎不可见：

![image](https://github.com/mirai-mamori/Sakurairo/assets/25473156/601d8bd7-05c0-4081-b2be-ea193c7de0cf)

**预期的行为：**

如果删除掉 `body.dark #main-container`，背景图片透明度就看起来正常多了：

![image](https://github.com/mirai-mamori/Sakurairo/assets/25473156/6b63f5e4-eae8-4321-946f-903759ad5bc1)

**复现步骤：**

开启背景图深色模式即可复现

**配置与环境：**

与 https://github.com/mirai-mamori/Sakurairo/issues/756 相同。

**截图（若有）**

无

**补充信息：**

无

**Comment by beixibaobao** [comment]
深色模式背景透明度 有单独的这个选项啊，你在这个对应的选项去修改一下看看？

**Comment by Eterance** [comment]
> 深色模式背景透明度 有单独的这个选项啊，你在这个对应的选项去修改一下看看？

找到了，感谢。不过我还是觉得深色模式下background叠加了两次有点奇怪，不知道是失误还是有意为之ㄟ( ▔, ▔ )ㄏ
