### ISSUE TITLE
目录显示问题

### ISSUE THREAD

**Issue by sinkers-lan** [mirai-mamori/Sakurairo#758]
**这是什么方面的想法？**

现有内容的优化

**这个想法具体是要实现什么？**

![image](https://github.com/mirai-mamori/Sakurairo/assets/100743317/eaacdb13-0610-4390-98f9-17758da462bf)
侧边的目录在目录太长的时候显示不完全，希望目录可以跟随进度向下滚动

**这个想法实现后有什么帮助？**

提升用户体验

**是否有具体的实现思路？**

无。（或许可以先加入一个目录字体大小的调解设置，我把字体设小点也许可以放下更多（不是

**补充信息：**

感谢！现在的UI已经比以前的好看多了多了多了，已经解决了我心里90%的美观问题

**Comment by mirai-mamori** [comment]
暂时还没有 重做目录的计划 后续会考虑进行优化
