### ISSUE TITLE
（1.15.0）文章页标题字体大小设置

### ISSUE THREAD

**Issue by railzy** [mirai-mamori/Sakurairo#76]
**这是什么方面的想法？**

添加文章页标题字体大小设置

**这个想法具体是要实现什么？**

添加文章页标题字体大小设置

**这个想法实现后有什么帮助？**

自由设置标题字体大小，更加美观

**是否有具体的实现思路？**

无。只知道控制标题字体大小的CSS代码如下。
```
h1.entry-title {
    font-size: 40px;
}
```

**补充信息：**

**Comment by mirai-mamori** [comment]
1.15.0中将添加
