### ISSUE TITLE
[PHP Deprecated]: function.php弃用错误

### ISSUE THREAD

**Issue by SkyYyds001** [mirai-mamori/Sakurairo#760]
版本：2.6.2

我就是在我的wordpress安装主题安装完成之后，就出现了，不知道是什么原因

![YL92RS6)_1}INQNQ7B~KWWP](https://github.com/mirai-mamori/Sakurairo/assets/137469609/a83d335d-fb56-464d-9a41-e300e814b3d0)

**Comment by KotoriK** [comment]
deprecate 不是错误，相关提示可以关闭，并且不会有别的影响
