### ISSUE TITLE
文章特色图片是否可以来自文章内的图片

### ISSUE THREAD

**Issue by AnWangzi** [mirai-mamori/Sakurairo#761]
我在自己的网站上发布文章之后在首页发现文章特色图片需要加载后才能显示，而且是媒体库中随机的图片，但是我想让他显示文章内的图片，可以让人在点进去前有一个预览，但是设置里没有这个选项，所以我只能给每个文章单独设定特色图像，比较麻烦，所以能不能在设置中添加一个选项让主页显示的文章特色图像跟随文章内图片呢，下面附上我的网站地址，感谢。
https://wz2m.cn

**Comment by kanodaisuki** [comment]
首页文章封面图片的逻辑是，如果未设置特色图片，则显示与首页背景图片来源一致的随机图片。
将缺失的特色图片设置为文章内的第一张图片，这不符合大多数人的需求。原因如下：
* 不一定每一篇文章都拥有图片
* 文章内的第一张图片或许与内容无关
* 文章内的第一张图片的宽高比例不适合用于展示

为每篇文章设置一张特色图片，是常见且必要的做法。使用[Featured Image from URL](https://wordpress.org/plugins/featured-image-from-url/)插件，或许能简化上传图片的流程，只需填入图片的URL即可。
