### ISSUE TITLE
アイドル(IDOL)　Update(2)版本iro主题设置无法使用

### ISSUE THREAD

**Issue by AyaneAI** [mirai-mamori/Sakurairo#764]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**
在使用iro主题设置时出现502
这个问题出在程序的哪一个具体功能？
iro主题设置
**实际行为描述：**
点击iro主题设置后，出现502报错
触发问题后造成了什么效果及影响？
设置功能无法使用
**预期的行为：**
设置功能可以使用
这个功能应该有怎样的效果和影响？

**复现步骤：**

怎样才能再次触发这个问题？

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：（Release 标注的版本号）
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**截图（若有）**
![image](https://github.com/mirai-mamori/Sakurairo/assets/48854072/e241bdaf-8b00-4168-9405-02f4045638a9)
![image](https://github.com/mirai-mamori/Sakurairo/assets/48854072/34381ae7-3403-4665-a214-088f5ca502bf)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by beixibaobao** [comment]
你的 配置与环境 还真空.....可能是PHP的问题，你尝试调配一下PHP，或者是临时换个PHP看看（73 74）

**Comment by Shiroiame-Kusu** [comment]
如果可以的话，请提供你的php日志以及nginx的日志

**Comment by AyaneAI** [comment]
尝试了一下，发现安装老版本以后，再使用新版本，问题解决

**Comment by Weixiaojun666** [comment]
相同问题 附上报错
`FastCGI sent in stderr: "PHP message: PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/wordpress/wp-content/themes/Sakurairo/functions.php on line 1360; PHP message: PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/wordpress/wp-content/themes/Sakurairo/functions.php on line 1361; PHP message: PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/wordpress/wp-content/themes/Sakurairo/functions.php on line 1362; PHP message: PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/wordpress/wp-content/themes/Sakurairo/functions.php on line 1363" while reading response header from upstream`
