### ISSUE TITLE
从2.5升级到2.6后文章无法正常显示

### ISSUE THREAD

**Issue by tsgsha** [mirai-mamori/Sakurairo#765]
**问题出处：**

主题从2.5.x自动升级到2.6.x，文章无法正常打开。

**实际行为描述：**

文章无法正常打开。

**预期的行为：**

文章无法正常打开。

**复现步骤：**

之前使用主题v2.5.2，一切正常；手动安装主题v2.5.5, v2.5.6文章页面也一切正常；但手动安装了主题v2.6.0, v2.6.2，文章均无法正常打开。

**配置与环境：**

- 问题页面：
     正常页面（使用主题v2.5.2）: https://gapdh.com/bcytj/introduction/
     问题页面（使用主题v2.6.2）: https://ceshi.gapdh.com/bcytj/introduction/
- PHP 版本：PHP7.4
- 数据库类型 / 版本：mysql8.0
- WordPress 版本：6.2.2
- 主题版本：v2.6.2
- 使用的插件：beaver-builder-lite-version, ninja-beaver-lite-addons-for-beaver-builder, 
- 浏览器：chrome 114.0.5735.199; firefox115.0.1

**截图（若有）**

**Comment by KotoriK** [comment]
可能关联#746
确认问题页面中```main.site-main```没有内容

**Comment by tsgsha** [comment]
您好，我确实通过F12关注到了页面中没有内容。但同样的站点切换回sakurairo v2.5主题就一切正常，使用v2.6主题就出了类似的问题。此外，当撰写新文章时无论是进入预览页面还是直接发布在v2.6主题中都无法正常打开。请问类似有相应的解决办法或可供参考的文档吗？多谢！

**Comment by tsgsha** [comment]
> 可能关联#746 确认问题页面中`main.site-main`没有内容

您好，我确实通过F12关注到了页面中没有内容。但同样的站点切换回sakurairo v2.5主题就一切正常，使用v2.6主题就出了类似的问题。此外，当撰写新文章时无论是进入预览页面还是直接发布在v2.6主题中都无法正常打开。请问类似有相应的解决办法或可供参考的文档吗？多谢！

**Comment by tsgsha** [comment]
> 最好可以查一下PHP日志

不好意思我对PHP还不是特别熟悉。
在网站的日志中我发现如下语句：
2023/07/11 23:15:28 [error] 23908#23908: *2706 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/ceshi/wp-content/themes/Sakurairo-2.6.2/functions.php:1209
在php-fpm日志中一直是以下语句的重复：
[11-Jul-2023 16:36:46] NOTICE: Terminating ...
[11-Jul-2023 16:36:46] NOTICE: exiting, bye-bye!
[11-Jul-2023 16:36:46] NOTICE: fpm is running, pid 18529
[11-Jul-2023 16:36:46] NOTICE: ready to handle connections
[11-Jul-2023 16:36:46] NOTICE: systemd monitor interval set to 10000ms
在php的error_log目录中暂未产生文件。
不知以上能否有助于发现问题。
再次感谢！

**Comment by KotoriK** [comment]
原因是2.5->2.6间的一次变更引入了```DOMDocument```，这个类需要引入PHP扩展```dom```才能使用。
如何安装扩展请参考https://stackoverflow.com/questions/14395239/class-domdocument-not-found
5d271011dda06cf51c7a510f110536511f4a99ca

**Comment by tsgsha** [comment]
> 原因是2.5->2.6间的一次变更引入了`DOMDocument`，这个类需要引入PHP扩展`dom`才能使用。 如何安装扩展请参考https://stackoverflow.com/questions/14395239/class-domdocument-not-found [5d27101](https://github.com/mirai-mamori/Sakurairo/commit/5d271011dda06cf51c7a510f110536511f4a99ca)

非常感谢您的耐心解答，我学习一下

**Comment by tsgsha** [comment]
> 原因是2.5->2.6间的一次变更引入了`DOMDocument`，这个类需要引入PHP扩展`dom`才能使用。 如何安装扩展请参考https://stackoverflow.com/questions/14395239/class-domdocument-not-found [5d27101](https://github.com/mirai-mamori/Sakurairo/commit/5d271011dda06cf51c7a510f110536511f4a99ca)

安装php-xml后成功打开了文章，非常感谢您的帮助！
