### ISSUE TITLE
应用主题，页面无法正常显示，报错 Deprecated

### ISSUE THREAD

**Issue by Zhonjc2** [mirai-mamori/Sakurairo#766]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：**

似乎是PHP部分语法或函数已被弃用。例如
Deprecated: Creation of dynamic property CSF_Field_color::$unique is deprecated in /usr/local/nginx/html/blog/wp-content/themes/Sakurairo/opt/classes/fields.class.php on line 16

**具体行为描述：**

主题预览、应用后都出现了页面无法显示的问题，PHP 提示一大堆错

**尝试：**

尝试删除一些插件，依旧无法解决；
还尝试通过 SSH 上传主题，依旧无法解决

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.2.8
- 数据库类型 / 版本：MySQL 8.0.33
- WordPress 版本：6.2.2
- 主题版本：2.6.2
- 使用的插件：Social Icons Widget & Block by WPZOOM
- 浏览器：Safari 17.0

**截图（若有）**
<img width="1373" alt="截屏2023-07-13 15 57 33" src="https://github.com/mirai-mamori/Sakurairo/assets/41794800/073ce3e6-a3e3-409b-8c65-c9636c086924">

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

其他主题都是正常使用的。在一堆报错（真的很多）下面，有正常显示的文章。

**Comment by kanodaisuki** [comment]
同 #751 #760

**Comment by Shiroiame-Kusu** [comment]
你可以选择关闭php设置中的display_error

**Comment by Tyler913** [comment]
> 你可以选择关闭php设置中的display_error

我后台看到wp-confing.php 中我的DEBUG 已经是false了但是还是会显示这个，这个是什么问题

**Comment by KotoriK** [comment]
> > 你可以选择关闭php设置中的display_error
> 
> 我后台看到wp-confing.php 中我的DEBUG 已经是false了但是还是会显示这个，这个是什么问题

说是关闭PHP设置中的```display_error```，这个错误是PHP报的不是WordPress报的
