### ISSUE TITLE
全新Wordpress无插件主题默认设置头像（标题）处显示Warning并且无法正确加载背景图片

### ISSUE THREAD

**Issue by Bi2Nb9O3-Studio** [mirai-mamori/Sakurairo#768]
**问题出处：主页**

这个问题出在程序的哪一个具体功能？

**实际行为描述：**无法正确显示主页背景图片和标题（如头像之类的）

触发问题后造成了什么效果及影响？

**预期的行为**：显示为正常的主页

这个功能应该有怎样的效果和影响？

**复现步骤**：全新wordpress安装主题之后就有问题

怎样才能再次触发这个问题？

**配置与环境：**

- 问题页面：bi2nb9o3.xyz
- PHP 版本：8.0
- 数据库类型 / 版本：MySQL 8.0.24
- WordPress 版本：6.2.2
- 主题版本：2.6.2
- 使用的插件：无，全新
- 浏览器：Firefox1 115.0.2

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

头像/标题（我也不知道算哪一部分）处显示的是：Warning: Trying to access array offset on value of type null in /www/wwwroot/main/wp-content/themes/Sakurairo-2.6.2/header.php on line 117 (这部分的XPath路径是：/html/body/header/div/div[1]/span/span/a/ruby/span[1])

浏览器开发者工具Network一栏显示的请求：
https://netcut.cn/p/6e6855ca2d281bbb

**Comment by Bi2Nb9O3-Studio** [comment]
已解决问题，复现步骤：删除自定义步骤

**Comment by Eterance** [comment]
> > 已解决问题，复现步骤：删除自定义步骤
> 
> 我也遇到了这个问题，经过检查所有 8.X 的 php 都会出现这种情况： ![image](https://user-images.githubusercontent.com/25473156/260785112-27f9c615-1f61-4f76-9205-84dd8f08b201.png)
> 
> 而切换到 7.X 就没有这个问题。可否告知你是怎么解决的？

已解决：
https://github.com/mirai-mamori/Sakurairo/issues/724#issuecomment-1566180758

https://github.com/mirai-mamori/Sakurairo/issues/778
