### ISSUE TITLE
新版本（2.6.2）出现【全局设置】-【导航菜单设置】-【白猫样式Logo】的bug

### ISSUE THREAD

**Issue by T-ironman** [mirai-mamori/Sakurairo#769]
**问题出处：**

【全局设置】-【导航菜单设置】-【白猫样式Logo】

**实际行为描述：**

文本B 不再旋转

**预期的行为：**

文本B 应该旋转

**复现步骤：**

使用2.6.2版本，已经找人复刻，切换2.5.1.1即可正常旋转

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：MariaDB 10.5.6
- WordPress 版本：6.1.1
- 主题版本：2.6.2
- 使用的插件：NO
- 浏览器：Chrome

**截图（若有）**

线下已经补充

**补充信息：**

无

**Comment by mirai-mamori** [comment]
后续版本会进行补齐

**Comment by EriTang** [comment]
版本 2.6.3.1中仍然不旋转
