### ISSUE TITLE
希望能选择看板娘的模型

### ISSUE THREAD

**Issue by GavinIves** [mirai-mamori/Sakurairo#77]
**这是什么方面的想法？**

现有内容的优化 、新增功能、用户体验

**这个想法具体是要实现什么？**
能像live2d插件那样直接选择模型编号 衣服编号

**这个想法实现后有什么帮助？**

不用费事自己搭建live2d 那东西我搞了一天没搞出来 
**是否有具体的实现思路？**

**补充信息：**

**Comment by mirai-mamori** [comment]
因为本主题自带看板娘使用的是云端（JsDeliver CDN）服务，因此在本地暂时无法实现模型切换等功能，您可以Fork一份本主题使用的看板娘进行自定义。并创建您自己的发行版后。可在主题后台设置可以方便的自定义看板娘地址。
