### ISSUE TITLE
希望作者大大能把主题内置的网页音乐播放器改善一下并适用到pc-

### ISSUE THREAD

**Issue by XDML-QM** [mirai-mamori/Sakurairo#771]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**

现有内容的优化 / 新增功能 / UI 界面 / 用户体验

**这个想法具体是要实现什么？**

**这个想法实现后有什么帮助？**

**是否有具体的实现思路？**

**补充信息：**

**Comment by mirai-mamori** [comment]
什么意思捏

**Comment by mirai-mamori** [comment]
没有手机端听歌的必要

**Comment by nicocatxzc** [comment]
> 大致的意思就是希望主题的网页播放器能适应到手机显示，这样的话访客在通过手机访问博客网站的时候能点击侧栏音乐播放器听歌，不然音乐播放器只能在电脑上才能显示
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mirai-mamori/Sakurairo" ***@***.***&gt;; 发送时间:&nbsp;2023年8月2日(星期三) 下午3:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [mirai-mamori/Sakurairo] 希望作者大大能把主题内置的网页音乐播放器改善一下并适用到pc- (Issue #771) 什么意思捏 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

在主题设置的footer引入这段代码：
`
(function() {
    if (window.innerWidth < 860) {
        console.log("加载移动端播放器")
        const scripts = [
            'aplayer的js路径',
            'meting的js路径'
        ];
        const stylesheets = [
            'aplayer的css路径'
        ];

        const customHTML = `
<meting-js
fixed="true"
server="指定音乐服务器，比如netease"
type="playlist"
id="歌单id"
preload="none">
</meting-js>
        `;
        // 向body末尾添加自定义HTML代码
        document.addEventListener("DOMContentLoaded", () => {
            const customElement = document.createElement('div');
            customElement.innerHTML = customHTML;
            document.body.appendChild(customElement);
        // 动态加载CSS样式
        stylesheets.forEach(href => {
            const link = document.createElement('link');
            link.rel = 'stylesheet';
            link.href = href;
            document.head.appendChild(link);
        // 动态加载JS脚本
        scripts.forEach(src => {
            const script = document.createElement('script');
            script.src = src;
            script.async = true; // 可选，异步加载脚本
            document.head.appendChild(script);
        });
        });
        });
    }
})();
`
然后下载aplayer的css和js引入:https://github.com/DIYgod/APlayer/tree/master/dist
同样下载meting.js引入:https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js
上面的路径填这两个文件的路径即可
要播放器能缩进侧边可以在css末尾加上
`
.aplayer.aplayer-narrow .aplayer-body {
    left: -66px !important;
}
.aplayer-body:hover {
    left: 0px !important
}
`
没找到主题是怎么设置窄屏幕不显示的，只试出来是像素>860px才显示播放器，用这个方法可以在窄屏幕自己手动引入播放器
