### ISSUE TITLE
wordpress更新到6.3引起的问题

### ISSUE THREAD

**Issue by qanderer** [mirai-mamori/Sakurairo#774]
**大致范围：**

wordpress更新引起的问题

**具体行为描述：**

我将我的wordpress由6.2更新到了刚刚发布的6.3
然后问题就出现了

**尝试：**

我启动了wordpress的debug模式想要尝试修复
得知以下错误信息
```
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/wordpress/wp-content/themes/Sakurairo/functions.php on line 1564

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/wordpress/wp-content/themes/Sakurairo/functions.php on line 1565

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/wordpress/wp-content/themes/Sakurairo/functions.php on line 1566

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/wordpress/wp-content/themes/Sakurairo/functions.php on line 1567
```

**配置与环境：**

- 问题页面：[acgurl.link](https://acgurl.link/)
- PHP 版本：8.1.2-1ubuntu2.13 (cli) (built: Jun 28 2023 14:01:49) (NTS)
- 数据库类型 / 版本：MySql 8.0.33-0ubuntu0.22.04.4 (Ubuntu)
- WordPress 版本：6.3
- 主题版本：[2.6.2](https://github.com/mirai-mamori/Sakurairo/tree/2.6.2)
- 使用的插件：无
- 浏览器：Cent Browser 版本 5.0.1002.354（正式版本） （32 位） (Chromium 102.0.5005.167)

**截图**
![{2S4P7_7X2CC~QX1Q 5E`_T](https://github.com/mirai-mamori/Sakurairo/assets/139052986/f4e23389-9d18-48a7-83eb-4066676c7d70)

**补充信息：**

无

**Comment by KotoriK** [comment]
与WordPress版本无关
```dash_scheme()```函数的deprecated已在 cb817208780ddd863ef084c99ceb366bee6c5fe6 修复
