### ISSUE TITLE
保存主题修改时罕见地清空设置 [maybe wont fix]

### ISSUE THREAD

**Issue by FrostleafChan** [mirai-mamori/Sakurairo#775]
**问题出处：**

iro主题设置  保存更改按钮

**实际行为描述：**

主题设置被清空，~~数据库内可见iro_options字段为空。~~

**预期的行为：**

已修改设置应成功保存进数据库。

**复现步骤：**

此Issue复现随机性极大，重复刚才的操作亦无法重现此Issue。但在我的记忆里，在最近一两年的时间里，这种情况已经在不同的LNMP平台和缓存策略（含无缓存）上出现至少4次。

**配置与环境：**

- 问题页面：无
- PHP 版本：7.4
- 数据库类型 / 版本：MySQL 8.0.24
- WordPress 版本：6.3
- 主题版本：アイドル(IDOL)　Update(2)  Sakurairo 主题版本 2.6.2 | 内部版本 18.2.0
- 使用的插件：你好多莉、WP Super Cache
- 浏览器：Google Chrome 版本 115.0.5790.110（正式版本） （64 位）

**截图（若有）**

**补充信息：**

**Comment by kanodaisuki** [comment]
可能确实很罕见，我从未遇到过。如果你找出了稳定复现的步骤，请补充更多信息。
