### ISSUE TITLE
使用 PHP 8.x 版本且保留初始的“世界你好”文章会导致首页界面不正常

### ISSUE THREAD

**Issue by Eterance** [mirai-mamori/Sakurairo#778]
**问题出处：**

使用 PHP 8.x 版本且保留初始的“世界你好”文章会导致首页界面不正常

**实际行为描述：**

封面大图、个人头像、页脚全没了，背景消失。
![image](https://github.com/mirai-mamori/Sakurairo/assets/25473156/a4ee79b3-d165-4edf-8a39-cb324839afa6)

**预期的行为：**

正常的首页

**复现步骤：**

php8.x 下，新建一个站点并且安装主题并且设置后即可观察到。

将初始的文章移入回收站即可恢复正常；从回收站中恢复又会不正常。

降级到 php 7.x 首页不会有问题。

**配置与环境：**

- 问题页面：无
- PHP 版本：8.x
- 数据库类型 / 版本：MySQL 5.7.40
- WordPress 版本：6.3
- 主题版本：2.6.2
- 使用的插件：无
- 浏览器：Microsoft Edge 版本 116.0.1938.36 (正式版本) beta (64 位)

**补充信息：**

定位问题的全过程：https://blog.baldcoder.top/articles/solving-the-mysterious-bug-of-homepage-layout-disorder-on-sakurairo-php-8-x-environment/

虽然删掉第一篇文章就能解决这个问题，但是如果不知道还是很折腾人的

**Comment by bymoye** [comment]
并没有遇到过，可否提供一下错误信息？

**Comment by Eterance** [comment]
> 并没有遇到过，可否提供一下错误信息？

第一张图里的报错：

```
Fatal error :  Uncaught TypeError: number_format(): Argument #1 ($num) must be of type float, string given in /www/wwwroot/192.168.1.109/wp-content/themes/Sakurairo-main/functions.php:454
Stack trace:
#0 /www/wwwroot/192.168.1.109/wp-content/themes/Sakurairo-main/functions.php(454): number_format()
#1 /www/wwwroot/192.168.1.109/wp-content/themes/Sakurairo-main/functions.php(496): restyle_text()
#2 /www/wwwroot/192.168.1.109/wp-content/themes/Sakurairo-main/tpl/content-thumb.php(91): get_post_views()
#3 /www/wwwroot/192.168.1.109/wp-includes/template.php(787): require('...')
#4 /www/wwwroot/192.168.1.109/wp-includes/template.php(720): load_template()
#5 /www/wwwroot/192.168.1.109/wp-includes/general-template.php(206): locate_template()
#6 /www/wwwroot/192.168.1.109/wp-content/themes/Sakurairo-main/index.php(67): get_template_part()
#7 /www/wwwroot/192.168.1.109/wp-includes/template-loader.php(106): include('...')
#8 /www/wwwroot/192.168.1.109/wp-blog-header.php(19): require_once('...')
#9 /www/wwwroot/192.168.1.109/index.php(17): require('...')
#10 {main}
  thrown in 
```

好诡异，现在自己从头新建网站又复现不出来了；报错的 WP 跑在局域网的虚拟机上，想把它的整个文件夹和数据库复制到服务器上让大伙瞅瞅，结果在服务器上又变成好的了，人麻了毫无头猪

要是实在找不出来原因就算了吧，反正删掉自带的第一个post也能修复
