### ISSUE TITLE
使用主题搜索功能排除Categories/pages的方块

### ISSUE THREAD

**Issue by Techssh** [mirai-mamori/Sakurairo#786]
**这是什么方面的想法？**

主题搜索功能

现有内容的优化 / 新增功能 / UI 界面 / 用户体验
**这个想法具体是要实现什么？**

当搜索的时候应该搜索帖子的内容, 包括贴子的标题或者其他的说说内容。而不要显示"类别"还有没有评论显示的功能（如图）

**这个想法实现后有什么帮助？**

更好的搜索显示

**是否有具体的实现思路？**

去掉未分类还有没有评论的显示，或者排除Categories。如果一定要搜索类别可以加上一个开关选项

**补充信息：**
![image](https://github.com/mirai-mamori/Sakurairo/assets/127261267/bd470234-4ec5-4c6f-8aca-82528fafe704)

**Comment by bymoye** [comment]
没理解，但是可以试着提pull requests
