### ISSUE TITLE
pc文本框文字溢出

### ISSUE THREAD

**Issue by huaizhu1** [mirai-mamori/Sakurairo#789]
- 问题页面：（如果有，请提供一个触发此问题的页面链接)  https://i.miksz.cc
- 系统：Ubuntu 22.04 64 Bit
- nginx版本：1.22
- PHP 版本：7.4
- 数据库类型 / 版本：mysql5.7
- WordPress 版本：最新
- 主题版本：（Release 标注的版本号）最新
- 使用的插件：（所
![屏幕截图 2023-09-13 102925](https://github.com/mirai-mamori/Sakurairo/assets/103626680/c8d8acba-eb3f-47cd-885a-265a4b76eb0b)
有使用中的的插件，以便判断兼容性问题）
- 
- 浏览器：（浏览器名称及版本号）edge chrome

**截图（若有）**

![QQ图片20230913102700](https://github.com/mirai-mamori/Sakurairo/assets/103626680/63042b47-ea54-4456-954f-7f1b3a66851c)

![QQ图片20230913102705](https://github.com/mirai-mamori/Sakurairo/assets/103626680/71f836b8-4691-4190-abe3-4461638f0af3)

**Comment by huaizhu1** [comment]
溢出并非全部文章溢出而是出现在某些文章（我也觉得很怪
![网页捕获_13-9-2023_103551_i miksz cc](https://github.com/mirai-mamori/Sakurairo/assets/103626680/06674774-cbc6-4bfa-aa70-2b35fab5cd47)

**Comment by kanodaisuki** [comment]
关于这个问题，你可以参文章：[Better Line Breaks for Long URLs](https://css-tricks.com/better-line-breaks-for-long-urls/)

是否会溢出，取决于你的URL里面有没有“换行符”，所以有些看起来正常，有些则是溢出。

解决方法是，不要在摘要里面放URL。关于如何自定义摘要，请参考：https://codex.wordpress.org/Customizing_the_Read_More
