### ISSUE TITLE
【帮助】Vaptcha验证类型加载不出来，一直提示 Vaptcha Initializing

### ISSUE THREAD

**Issue by Moxiner** [mirai-mamori/Sakurairo#790]
**大致范围：**
验证方式
Vaptcha验证
后台登录

**具体行为描述：**
我开启了 ```Vaptcha验证``` 类型，可能是我疏忽了什么，现在一旦遇到验证码就会  ```Vaptcha验证```  ，这很正常
但不正常的就是 ```Vaptcha验证``` 用不了，一直会提示 ```Vaptcha Initializing```，我现在甚至登录不了 ```WordPress后台``` 重新设置验证码类型，
```Log```也没有报错 

**问题：**
- [ ] 无法正常的使用 ```Vaptcha验证```
- [ ] 无法登录 ```WordPress``` 后台

**尝试：**
1. 更换网络
2. 更换浏览器
3. 更换设备
4. 使用海外代理
这些都无法解决问题

**配置与环境：**
- 问题页面：[您可以直接点击此链接以了解问题](http://blog.moxiner.fun/wp-login.php)
- PHP 版本：不太清楚
- OpenResty版本:  1.21.4.2
- 数据库类型 / 版本：mysql 8.1.0
- WordPress 版本：3.6.1
- 主题版本：2.6.2
- 使用的插件：初始的两个插件，并没有安装新的插件
- 浏览器：Microsoft Edge版本 118.0.2088.2 (正式版本) dev (64 位)

**截图（若有）**
[![Vaptcha Initializing](https://z1.ax1x.com/2023/09/14/pPRcfoV.png)](https://imgse.com/i/pPRcfoV)

**补充信息：**
可能是因为我没有填写```Vaptcha Key```之类的东西？（如果有的话）
我觉得可以访问数据库修改某个键关闭Vaptcha验证，临时解决无法登录后台的问题，但我不确定修改哪个键

**Comment by bymoye** [comment]
是的，你可以通过数据库直接修改该项，在wp的配置键，具体是哪个键我也忘了，需要翻找一下数据库。

**Comment by SakuraTao2007** [comment]
> 是的，你可以通过数据库直接修改该项，在wp的配置键，具体是哪个键我也忘了，需要翻找一下数据库。

hello我也是这个问题，找到相关options了但是不知道该如何修改，可以给一些指点嘛？
![image](https://github.com/mirai-mamori/Sakurairo/assets/59493751/8a5c89e6-702a-4821-a879-41d08a50e6fe)

**Comment by Moxiner** [comment]
我直接回滚了，QWQ

**Comment by SakuraTao2007** [comment]
> 我直接回滚了，QWQ

![image](https://github.com/mirai-mamori/Sakurairo/assets/59493751/17fb93df-cc05-4796-a60e-f0a7e81ebaa8)
找到了但是不知道咋改

**Comment by Moxiner** [comment]
我想应该更改``` option name`: vaptcha``但是我知道具体的键值，www
>⚠️ 操作时，请备份您的数据库

**Comment by SakuraTao2007** [comment]
> 我想应该更改` option name: vaptcha`但是我不知道具体的键值，www
> 
> > ⚠️ 操作时，请备份您的数据库

![image](https://github.com/mirai-mamori/Sakurairo/assets/59493751/450a5119-63f7-4e30-ac21-b880bcc67167)
我改成这个能进后台了，但是似乎有一些设置被充值了

**Comment by Moxiner** [comment]
应该是验证码相关的设置被重置了吧...我也不太清楚数据库相关的知识，www
或者是WP检测到数据库参数有问题，引发了自修复（

**Comment by SakuraTao2007** [comment]
> vaptcha

也算是修好了, pap

**Comment by bymoye** [comment]
82b22b5 将会是如果不填写key和vid将无法使用Vaptcha，避免该问题出现。
