### ISSUE TITLE
说说功能列表页长文本字行间距过小导致字重叠。

### ISSUE THREAD

**Issue by Constantine-Harris** [mirai-mamori/Sakurairo#799]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

说说功能

**实际行为描述：**

文本框文字重叠

**预期的行为：**

行间距正确

**复现步骤：**

疑似长文本

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4.33
- 数据库类型 / 版本：5.7.40
- WordPress 版本：6.3.1
- 主题版本：2.6.3
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 
![image](https://github.com/mirai-mamori/Sakurairo/assets/44835063/e762d893-91ce-4c79-8dab-43ef0d78f309)

- 浏览器：Chrome  116.0.5845.190
Nginx 1.22.1
**截图（若有）**
![image](https://github.com/mirai-mamori/Sakurairo/assets/44835063/bff21b95-f70c-4b92-bebd-9e770d41ee32)
![image](https://github.com/mirai-mamori/Sakurairo/assets/44835063/584be02c-5da4-4876-b866-2e8020ae7b20)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by mirai-mamori** [comment]
已知问题 下个版本修复
