### ISSUE TITLE
手机端logo位置

### ISSUE THREAD

**Issue by kfyidrig** [mirai-mamori/Sakurairo#80]
**问题出处：**

手机端文章页面

**实际行为描述：**

手机端网页图片logo位置一直不变，即使顶部栏已经上移

**预期的行为：**

logo随顶部栏一起消失

**复现步骤：**

手机端访问https://blog.ieleven.xyz/pat/，向下滑动网页，观察网站logo

**Comment by Ukenn2112** [comment]
这功能本来就是这样做的，默认移动端logo不跟随导航栏消失而消失
