### ISSUE TITLE
Trying to access array offset on value of type null in header.php on line 117,118,119

### ISSUE THREAD

**Issue by sukaps** [mirai-mamori/Sakurairo#801]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：**

header.php的117,118,119行

**具体行为描述：**

启用主题后首页报错

**尝试：**

百度后尝试修改，没搞明白

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.0.62
- 数据库类型 / 版本：MySQL 5.7.40
- WordPress 版本：6.3.2
- 主题版本：（Release 标注的版本号）2.6.3
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）无
- 浏览器：（浏览器名称及版本号）Chrome 118.0.5993.89

**截图（若有）**

<img width="1280" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/71579708/82f14e11-c80c-468c-945c-7bf466d94659">
<img width="706" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/71579708/7e930a9d-04f3-4448-b26f-b0b4cb404156">

**补充信息：**

提供尽可能多的相关信息。

**Comment by moneypiaorui** [comment]
我也遇到了这个问题，而且安装Sakura主题也会出现这个情况

**Comment by moneypiaorui** [comment]
我在尝试将PHP版本降到7.4解决了WARNING的情况，但是首页功能仍然显示不全

**Comment by sukaps** [comment]
> 我也遇到了这个问题，而且安装Sakura主题也会出现这个情况

在主题设置中设置相关信息后报错消失恢复正常

**Comment by moneypiaorui** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
