### ISSUE TITLE
GitHub 仓库信息块无法显示

### ISSUE THREAD

**Issue by zzzhxxx** [mirai-mamori/Sakurairo#802]
**问题出处：**

短代码

GitHub 仓库信息块

**实际行为描述：**

使用短代码引入GitHub 仓库信息块，在文章中无法显示仓库信息

**预期的行为：**

正常显示有关仓库信息

**复现步骤：**

在文章中使用GitHub仓库信息块短代码

**配置与环境：**

- 问题页面：[页面](https://zzzhxxx.top/rao-guo-dan-xiang-li-api-de-referer-yan-zheng/)
- PHP 版本：8.0
- 数据库类型 / 版本：mariadb
- WordPress 版本：6.3.2
- 主题版本：2.6.3 
- 使用的插件：无
- 浏览器：Chrome 118.0.5993.89

**截图（若有）**

<img width="437" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/63891505/e354e69b-3e05-418a-a315-26fa067f5bab">
<img width="407" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/63891505/b173de7a-9908-496c-8bf0-039da230ce9c">

**补充信息：**

貌似是提供服务的[项目](https://github-profile-summary-cards.vercel.app/api/pin/?username=zzzhxxx&repo=calendar_api)不再支持生成仓库卡片，是否能够更换一个生成仓库卡片的项目?

**Comment by KotoriK** [comment]
可以 或许可以做个主题配置，允许用户使用自己的构建

**Comment by KotoriK** [comment]
检查了一下官方构建好像还在，可以看看是不是api地址换了

**Comment by zzzhxxx** [comment]
> 检查了一下官方构建好像还在，可以看看是不是api地址换了

看了下readme,api好像没换，只是现在没有对于repo卡片的支持，只剩下了个人信息数据的卡片

**Comment by zzzhxxx** [comment]
也许可以参考一下[argon](https://github.com/solstice23/argon-theme)在主题内构建一个？

**Comment by mirai-mamori** [comment]
感觉没太多必要 如果有更好的项目源可以更换最好

**Comment by zzzhxxx** [comment]
[GitHub Readme Stats](https://github.com/anuraghazra/github-readme-stats)，这个我觉得应该可以替换

**Comment by CKylinMC** [comment]
抱歉打扰，但想问一下这个自定设置项现在已经有了吗？我没有找到...
