### ISSUE TITLE
在从公共 CDN 提供第三方库的情况下，Typed.js不生效

### ISSUE THREAD

**Issue by kanodaisuki** [mirai-mamori/Sakurairo#803]
## 复现
开启`封面签名栏打字特效`并启用`从公共 CDN 提供第三方库`
主题版本：2.6.3

## 描述

Typed.js资源能加载成功，但是没有打字效果，控制台无报错。控制台手动执行
```js
new Typed('.element', {
    strings: ["给时光以生命，给岁月以文明", ]
})
```
打字效果正常出现。

在不启用从从公共 CDN 提供第三方库的情况下，打字效果正常出现。

已排除Typed.js版本问题，推测可能和这个[commit](https://github.com/Fuukei/Sakurairo_Scripts/commit/f013059370a70c7fbf684c2dfad4e9e24045d17a)有关。

**Comment by KotoriK** [comment]
来个网址看看

**Comment by kanodaisuki** [comment]
> 来个网址看看

[t.kanochan.net](https://t.kanochan.net/)，一个临时的测试站点，会在这个问题关闭后删除。

![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/b8cbc921-a340-4694-a03c-b28dae864af1)
![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/afa51422-8f49-4ff3-8af1-1d2e6082f961)

**Comment by KotoriK** [comment]
笑死写成() => resolve了
等会修
