### ISSUE TITLE
奇奇怪怪的多条错误

### ISSUE THREAD

**Issue by JsaRut** [mirai-mamori/Sakurairo#806]
**大致范围：**

主题设置页面

**具体行为描述：**

去后台主题设置页面，进行配置

**尝试：**

没有，不会

**配置与环境：**

- 问题页面：后台/主题设置
- PHP 版本：8.2.6
- 数据库类型 / 版本：MySQL 5.7.34
- WordPress 版本：6.3.2
- 主题版本：3.1
- 使用的插件：没有启用任何插件
- 浏览器：Edge 118.0.2088.76 (正式版本) (64 位)

**截图（若有）**

首页和后台的截图
![网页捕获_2-11-2023_201853_192 168 0 112](https://github.com/mirai-mamori/Sakurairo/assets/89496854/bbf55464-5966-4fd8-bbf8-4ce03c74397b)
![网页捕获_2-11-2023_201934_192 168 0 112](https://github.com/mirai-mamori/Sakurairo/assets/89496854/b4123eb7-cc76-4ec8-abff-ed07e90b0feb)

**补充信息：**

奇奇怪怪的多条错误

**Comment by mirai-mamori** [comment]
设置框架方面使用了部分弃用函数，上游还未更新，没有安全问题不用太过担心
