### ISSUE TITLE
现阶段有修复使用了弃用函数的框架问题吗？

### ISSUE THREAD

**Issue by JsaRut** [mirai-mamori/Sakurairo#807]
**大致范围：**

主题设置页面和首页

**具体行为描述：**

去后台主题设置页面进行配置

**尝试：**

没有

**配置与环境：**

- 问题页面：后台/主题设置
- PHP 版本：8.2.6
- 数据库类型 / 版本：MySQL 5.7.34
- WordPress 版本：6.3.2
- 主题版本：3.1
- 使用的插件：没有使用任何插件
- 浏览器：Edge 118.0.2088.76 (正式版本) (64 位)

**截图（若有）**

首页和后台截图
![首页截图](https://user-images.githubusercontent.com/89496854/279978421-bbf55464-5966-4fd8-bbf8-4ce03c74397b.jpeg)
![后台截图](https://user-images.githubusercontent.com/89496854/279979379-b4123eb7-cc76-4ec8-abff-ed07e90b0feb.jpeg)

**补充信息：**

现阶段有修复该问题的方法吗？太影响观感了

**Comment by KotoriK** [comment]
降级到PHP 7或者关闭deprecated提示

**Comment by JsaRut** [comment]
能提供详细的文档吗？
