### ISSUE TITLE
以后的版本有可能支持CloudFlare Turnstile验证码吗？

### ISSUE THREAD

**Issue by JsaRut** [mirai-mamori/Sakurairo#809]
**这是什么方面的想法？**

更多的验证码提供商

**这个想法具体是要实现什么？**

接入CloudFlare Turnstile验证码，在登录、注册页面或评论中可以使用CloudFlare Turnstile验证码

**这个想法实现后有什么帮助？**

更快速方便地通过人机验证，并且保护隐私

**是否有具体的实现思路？**

调用CloudFlare提供的Turnstile API？

**补充信息：**

Vaptcha验证码不是那么的方便，用插件实现CloudFlare Turnstile接入后太难看

**Comment by kanodaisuki** [comment]
我看了一下，CloudFlare Turnstile插件已经足够好用，我认为没有集成的必要。
只需要做的是表单CSS优化的问题，[Snippets](https://wordpress.org/plugins/code-snippets/)插件可以帮助你做这个事情。

**Comment by JsaRut** [comment]
> 我看了一下，CloudFlare Turnstile插件已经足够好用，我认为没有集成的必要。 只需要做的是表单CSS优化的问题，[Snippets](https://wordpress.org/plugins/code-snippets/)插件可以帮助你做这个事情。

谢谢
