### ISSUE TITLE
启用pjax加载在从首页跳转到首页的情况下，Typed.js重复加载

### ISSUE THREAD

**Issue by kanodaisuki** [mirai-mamori/Sakurairo#810]
**问题出处：**

首页封面签名栏打字特效

**实际行为描述：**

首页跳转到首页时，Typed.js对象在未销毁的情况下重载

**预期的行为：**

[Sakurairo_Scripts](https://github.com/Fuukei/Sakurairo_Scripts/blob/d7bd40122418e3333a5c34c4df3dcbab8b22ed8f/src/app/pjax.js#L43)此处，或许应该销毁后重新添加？

**复现步骤：**

1. 开启pjax加载
2. 开启首页封面签名栏打字特效
3. 在首页点击网站logo，从首页跳转到首页

**配置与环境：**

- 主题版本：2.6.3.1

**截图（若有）**

![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/c37ec553-75ed-479b-a6a0-79147529f782)

**Comment by KotoriK** [comment]
或许在```initTypedJs()```执行前添加```disableTypedJsIfExist()```？

**Comment by kanodaisuki** [comment]
> 或许在`initTypedJs()`执行前添加`disableTypedJsIfExist()`？

或者在initTypedJs()里判断是否已经存在typed对象？防止二次加载。
这样的话，在首页原地跳转时，或许会丝滑一些
