### ISSUE TITLE
或许应该重新启用评论完成后刷新代码高亮的功能

### ISSUE THREAD

**Issue by kanodaisuki** [mirai-mamori/Sakurairo#812]
之前关闭该功能是因为#663，现在该问题在https://github.com/Fuukei/Sakurairo_Scripts/commit/30148284e1b4b3aa2e807ed7c012e0ff1d2f5956  中已得到解决。

**Comment by KotoriK** [comment]
重新启用以后会带来什么好处嘛

**Comment by kanodaisuki** [comment]
目前如果评论包含代码块，不手动刷新页面的话，样式很丑。

![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/f95cd9ad-f13c-468e-95f5-1210f075c7ba)

如果评论完成后能刷新代码高亮，就挺好的。

![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/96a404d2-9786-4804-beca-cf452359cfc4)

**Comment by kanodaisuki** [comment]
> 试试 可以的话就pr呗

OK

**Comment by mirai-mamori** [comment]
@kanodaisuki

**Comment by kanodaisuki** [comment]
> @kanodaisuki

先mark一下，等等牌就来
