### ISSUE TITLE
font-awesome-animation无法运行

### ISSUE THREAD

**Issue by TJsr0015** [mirai-mamori/Sakurairo#816]
font-awesome-animation无法运行

我按照https://blog.ukenn.top/sakura1/的教程源代码反复实验，图标有出现，但是动画一直没用效果

我也尝试过font-awesome-animation下的其他动画以及图标，都是图标可以动画不行

- 问题页面：我域名还没申请下来…………
- PHP 版本：8.2.4
- 数据库类型 / 版本：8.0.24
- WordPress 版本：wordpress-6.4.1-zh_CN
- 主题版本：3.1
- 使用的插件：One User Avatar
- 浏览器：edge和chrome最新版本

![屏幕截图 2023-11-11 023127](https://github.com/mirai-mamori/Sakurairo/assets/150474246/3fab402b-f1b9-4f80-92b2-cb01f0236f4b)
![屏幕截图 2023-11-11 023213](https://github.com/mirai-mamori/Sakurairo/assets/150474246/66f6a365-6f8e-43f0-9daf-c1e08f2ce5c8)
![屏幕截图 2023-11-11 023157](https://github.com/mirai-mamori/Sakurairo/assets/150474246/10369ea8-a8f9-40a8-808b-3b4836332f5c)

**Comment by TJsr0015** [comment]
> font-awesome-animation无法运行
> 
> 我按照[https://blog.ukenn.top/sakura1/的教程源代码反复实验，图标有出现，但是动画一直没用效果](https://blog.ukenn.top/sakura1/%E7%9A%84%E6%95%99%E7%A8%8B%E6%BA%90%E4%BB%A3%E7%A0%81%E5%8F%8D%E5%A4%8D%E5%AE%9E%E9%AA%8C%EF%BC%8C%E5%9B%BE%E6%A0%87%E6%9C%89%E5%87%BA%E7%8E%B0%EF%BC%8C%E4%BD%86%E6%98%AF%E5%8A%A8%E7%94%BB%E4%B8%80%E7%9B%B4%E6%B2%A1%E7%94%A8%E6%95%88%E6%9E%9C)
> 
> 我也尝试过font-awesome-animation下的其他动画以及图标，都是图标可以动画不行
> 
> * 问题页面：我域名还没申请下来…………
> * PHP 版本：8.2.4
> * 数据库类型 / 版本：8.0.24
> * WordPress 版本：wordpress-6.4.1-zh_CN
> * 主题版本：3.1
> * 使用的插件：One User Avatar
> * 浏览器：edge和chrome最新版本
>

**Comment by mirai-mamori** [comment]
2.6系列已经放弃fa4相关的资源加载

**Comment by TJsr0015** [comment]
> 2.6系列已经放弃fa4相关的资源加载

老哥能帮忙引个路吗？好心告知下有哪些平替？我顺着自己去学就成（刚刚学习怎么搞网站，感谢老哥回复）

**Comment by TJsr0015** [comment]
> 2.6系列已经放弃fa4相关的资源加载

那鼠标悬停时图标变换是否有便捷的内置平替呢？有的话麻烦和我说下，辛苦老哥了（前两天才开始玩这个，感谢！！）
