### ISSUE TITLE
我的网站无法正常加载Vaptcha，现在无法进入后台，如何关闭这个验证？

### ISSUE THREAD

**Issue by CwCuMolly** [mirai-mamori/Sakurairo#817]
![image](https://github.com/mirai-mamori/Sakurairo/assets/145273157/58896b18-36c0-43a9-a45a-91f9fe47983f)
我的网站无法正常加载Vaptcha，现在无法进入后台，如何关闭这个验证？

**Comment by KotoriK** [comment]
进数据库直接改iro_option?

**Comment by kanodaisuki** [comment]
有两种方式可以解决这个问题

### 1、通过修改数据库实现

主题的设置存放在表`wp_options`中，字段名称`iro_options`，里面包含主题所有的设置，你需要在字段值里面找到`vaptcha`，并将其修改为`off`并保存，此举将关闭主题的登录验证码功能。由于`iro_options`的值非常复杂，因此构建一个SQL命令是很困难的，我建议你使用可视化的SQL管理工具进行操作。

### 2、通过修改主题代码实现（推荐！）

在`\Sakurairo\functions.php`文件中使用`//`注释掉以下代码：

```php
//add_filter('authenticate', 'checkVaptchaAction', 20, 3);
```
此举会禁用Vaptcha后端验证，但前台的Vaptcha组件仍会加载，这个不影响，输入用户名密码登录即可。登入成功后，别忘了修改后台设置以禁用Vaptcha登录验证，并编辑`\Sakurairo\functions.php`文件取消上述的代码注释。
