### ISSUE TITLE
特定 SQL 语句导致大量报错

### ISSUE THREAD

**Issue by drsanwujiang** [mirai-mamori/Sakurairo#818]
[functions.php#L2063](https://github.com/mirai-mamori/Sakurairo/blob/main/functions.php#L2063) 在检查数据表时指定了数据库引擎 MyISAM。

MySQL、MariaDB 的默认引擎是 InnoDB，同时 PlanetScale 等数据库托管服务干脆取消了对 MyISAM 的支持，这会导致大量报错：

![Screenshot](https://github.com/mirai-mamori/Sakurairo/assets/41151854/118b925c-fa6c-460b-ad65-fe20ab4a0708)

可以考虑删掉对数据库引擎的指定？

**Comment by KotoriK** [comment]
或许可以考虑在不支持MyISAM的环境自动fallback? @mirai-mamori

**Comment by drsanwujiang** [comment]
> 或许可以考虑在不支持MyISAM的环境自动fallback? @mirai-mamori

有特别需要 MyISAM 的地方吗？

**Comment by KotoriK** [comment]
> > 或许可以考虑在不支持MyISAM的环境自动fallback? @mirai-mamori
> 
> 有特别需要 MyISAM 的地方吗？

查了下MyISAM适合少写多读的场合，这个表是用于随机图的，应该会更适合
