### ISSUE TITLE
127.0.0.1 FRP访问网站会造成位置显示报错

### ISSUE THREAD

**Issue by Sun-xiaoqiu** [mirai-mamori/Sakurairo#820]
本人环境：
PHP-8.1
Nginx-1.22.1
未修改过网站的源代码

在测试网站评论功能能时发现评论出现Warning,如下：
![TH}T$V6NJ@PDM(QC 4ORR{S](https://github.com/mirai-mamori/Sakurairo/assets/48948778/9defb7d7-6e6f-4ee1-8cb0-87033e8ff943)
经过检查报错所指的文件functions.php的报错代码所在区域，发现该区域所实现的是IP地址判断用户位置的功能，怀疑是用户位置显示造成的报错。
解决：关闭了显示用户所在位置，报错消失。

由于我没有公网ip，使用了FRP穿透到公网，服务器端看到访问请求来源都是127.0.0.1。

**Comment by KotoriK** [comment]
IP地址需要代理服务器使用一些约定传到WordPress服务器上，例如采用```X-Forward-IP```头。
但这些功能应该不属于也不该属于这个主题的功能范围。
