### ISSUE TITLE
代码块不能复制了

### ISSUE THREAD

**Issue by zsanjin-p** [mirai-mamori/Sakurairo#826]
主题版本2.6.3.1

文章编辑方式为文本，内容：
<pre><code class="shell">bash &lt;(wget -qO- https://raw.githubusercontent.com/sing-web/x-ui/main/install_CN.sh)</code></pre>
![image](https://github.com/mirai-mamori/Sakurairo/assets/76470776/ff24e305-cca9-4e98-b1ac-433e4d95cba0)

显示如图，右边的复制不见了

![屏幕截图_20231226_002154](https://github.com/mirai-mamori/Sakurairo/assets/76470776/f9f7742d-4f7f-4a5f-9f80-e99d8040cb57)

**Comment by KotoriK** [comment]
来个地址瞧瞧

**Comment by pdl0x0lbq** [comment]
> 来个地址瞧瞧

https://magways.cn/index.php/2023/12/22/stm32%e7%bc%96%e8%af%91micro-ros%e9%9d%99%e6%80%81%e5%ba%93/
大佬我的也是

**Comment by KotoriK** [comment]
与#811 重复，会尽快释出更新
