### ISSUE TITLE
音乐播放器优化

### ISSUE THREAD

**Issue by Xuanzheng0901** [mirai-mamori/Sakurairo#827]
**这是什么方面的想法？**

现有内容的优化

**这个想法具体是要实现什么？**
1.音乐播放器常驻，不再通过左下角按钮呼出
2.音乐播放器大小增大
3.手机端开启音乐播放器
**这个想法实现后有什么帮助？**
给网站加bgm！

**是否有具体的实现思路？**
否（

**补充信息：**

**Comment by mirai-mamori** [comment]
没有相关计划
