### ISSUE TITLE
如何将视频作为主页背景，直接播放。

### ISSUE THREAD

**Issue by MyToolMan** [mirai-mamori/Sakurairo#828]
想要在网站主页添加视频，只能通过点击播放按钮来实现视频播放
![image](https://github.com/mirai-mamori/Sakurairo/assets/69788470/f8800466-1eb9-4333-b282-7952ad9425ce)
这样设计是为了减少进入网站时的等待时间，但在视频压制得当再有一个好的托管服务其实可以做到秒加载的。
我想做到[拿拿酱](https://mtpa.live/)这样的效果，进入主页直接就播放视频。并且主页的一些控件不会受到影响。

**Comment by KotoriK** [comment]
目前主题没有提供相关的配置，可以PR一个

**Comment by mirai-mamori** [comment]
可以问问他本人

**Comment by suchacutesnake** [comment]
这个功能可以实现的。不过这样做的话，按主流浏览器的要求，就不能播放声音了
