### ISSUE TITLE
ChatGPT生成AI摘要

### ISSUE THREAD

**Issue by EriTang** [mirai-mamori/Sakurairo#829]
请问如何在设置里使用官方的ChatGPT访问地址 可以给个链接吗
目前使用http://sxy.gay/无法显示AI摘要
WordPress版本6.4.2
主题版本2.6.3.1

**Comment by KotoriK** [comment]
应当直接替换对应选项即可

**Comment by EriTang** [comment]
请问可以告诉我官方的地址吗 我不知道 谢谢你

**Comment by KotoriK** [comment]
您好，这是Bing。很高兴为您服务。😊

[ChatGPT API是一个由OpenAI开发的API，可以让您使用ChatGPT模型来生成自然语言对话。ChatGPT模型是一个基于GPT-3.5系列的强化学习模型，可以根据用户的输入和上下文来回答问题、承认错误、挑战错误的前提或拒绝不合适的请求](https://openai.com/blog/chatgpt/)¹。

要使用ChatGPT API，您需要先注册一个OpenAI账户，然后获取一个API密钥，最后支付一定的费用。您可以在[这里](^[1](https://openai.com/blog/chatgpt/)^)找到详细的使用教程²。您也可以在[[这里](https://openai.com/blog/chatgpt/)](^3^)和[这里](^4^)看到一些ChatGPT API的介绍和活用事例³⁴。

我希望这些信息对您有帮助。如果您有其他问题，欢迎随时向我提问。👋

源: 与必应的对话， [2](https://qiita.com/kenichiro_ayaki/items/afff43e78e75b0ae8d8a)024/1/[3](https://aismiley.co.jp/ai_news/what-is-the-chatgpt-api/)
(1) Introducing ChatGPT - OpenAI. https://openai.com/blog/chatgpt/.
(2) Introducing ChatGPT - OpenAI. https://openai.com/blog/chatgpt/.
(3) ChatGPT API を使うための手順 #API - Qiita. https://qiita.com/kenichiro_ayaki/items/afff[4](https://app-liv.jp/ai/articles/7/)3e78e75b0ae8d8a.
(4) ChatGPT APIとは？始め方や使用時の注意点、活用事例を紹介. https://aismiley.co.jp/ai_news/what-is-the-chatgpt-api/.
(5) 「ChatGPT API」とは？ 使い方・設定方法・できることなどを解説. https://app-liv.jp/ai/articles/7/.
(6) ChatGPT APIとは？始め方や使用時の注意点、活用事例を紹介. https://aismiley.co.jp/ai_news/what-is-the-chatgpt-api/.
(7) 「ChatGPT API」とは？ 使い方・設定方法・できることなどを解説. https://app-liv.jp/ai/articles/7/.
(8) undefined. https://openai.com/.
(9) undefined. https://api.openai.com/v1/chat/completions.
