### ISSUE TITLE
Aplayer无法播放(Solved)

### ISSUE THREAD

**Issue by Alex-Return-oriented** [mirai-mamori/Sakurairo#830]
已解决

**Comment by KotoriK** [comment]
给个链接

**Comment by Alex-Return-oriented** [comment]
aHR0cDovLzYwLjIwNC4xMzUuMTM0OjgwMDgv

**Comment by KotoriK** [comment]
你可以看一下音频文件有没有正常下载

**Comment by Alex-Return-oriented** [comment]
请问怎么才能实现下载呢，访问 http://60.204.135.134:8008/wp-json/sakura/v1/meting/aplayer?server=netease&type=pic&id=109951166067466889&meting_nonce=59d2ce8f85 是可以看到封面的

**Comment by Alex-Return-oriented** [comment]
感谢大佬，刚刚用Google v120.0.6099.109测试版能成功播放，应该是我浏览器的插件的问题
