### ISSUE TITLE
Highlight.js语言识别错误

### ISSUE THREAD

**Issue by zzzhxxx** [mirai-mamori/Sakurairo#832]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

代码块高亮

**实际行为描述：**

使用Markdown插入代码块时标注html语言却识别为Markup语言，并且控制台报错并没有Markup语言

**预期的行为：**

应正常显示html的高亮格式

**复现步骤：**

在文章中插入html代码块

**配置与环境：**

- 问题页面：https://zzzhxxx.top/mit-iap-2021-day-1-html-css-lecture/
- PHP 版本：8.0
- 数据库类型 / 版本：
- WordPress 版本：6.4.2
- 主题版本：3.1
- 使用的插件：WP Editor.md

**截图（若有）**

<img width="508" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/63891505/82ca697b-1967-4d2d-90e1-df3716668113">
<img width="761" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/63891505/ba3687e6-392b-49a1-8a33-72761230b974">
<img width="271" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/63891505/848d9345-62cf-41d2-a151-26adefe38b34">

**Comment by KotoriK** [comment]
先检查一下md转代码块的输出中是否有加入语言代码

**Comment by zzzhxxx** [comment]
> 先检查一下md转代码块的输出中是否有加入语言代码

加入了，在编辑器内的高亮是正常的
<img width="1433" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/63891505/50b3ca2e-772c-493a-9a8a-6566f6a75921">

**Comment by KotoriK** [comment]
> > 先检查一下md转代码块的输出中是否有加入语言代码
> 
> 加入了，在编辑器内的高亮是正常的 <img alt="image" width="1433" src="https://private-user-images.githubusercontent.com/63891505/296924071-50b3ca2e-772c-493a-9a8a-6566f6a75921.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzYzMDcsIm5iZiI6MTcwNTM3NjAwNywicGF0aCI6Ii82Mzg5MTUwNS8yOTY5MjQwNzEtNTBiM2NhMmUtNzcyYy00OTNhLTlhOGEtNjU2NmY2YTc1OTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMzMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZDkxNDJjYWE2MGU0NTQ5OGRmNzY1YTk5NWZiYWFlNWM4ZmM5MDEzYmExODhhM2ZiNTkyYmNkZGZjNzk0ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gvq9Owe7sANG9Tv9GeSpcZ4HNy1K5SxraTvssteIuf0">

检查一下你编辑器输出的HTML源代码，```<pre><code>```部分

**Comment by zzzhxxx** [comment]
<img width="1198" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/63891505/74fe01d6-d247-406b-ac9c-91c6693d92f9">

**Comment by KotoriK** [comment]
那就很怪 因为你目前博客前端展示的HTML结构是和你现在给的编辑器的结构是不一致的

**Comment by zzzhxxx** [comment]
> 那就很怪 因为你目前博客前端展示的HTML结构是和你现在给的编辑器的结构是不一致的

编辑器似乎用的是primjs的高亮，这是否会是highlight.js自己的bug？或者说highlight.js的自动识别是忽略在md里已经标注过的语言类型的？

**Comment by KotoriK** [comment]
> > 那就很怪 因为你目前博客前端展示的HTML结构是和你现在给的编辑器的结构是不一致的
> 
> 编辑器似乎用的是primjs的高亮，这是否会是highlight.js自己的bug？或者说highlight.js的自动识别是忽略在md里已经标注过的语言类型的？

hljs有自动识别，prismjs没有，但是他们都共用同一套markup

**Comment by KotoriK** [comment]
现在的问题是前端输出的markup里边就把代码块标记为markup

**Comment by KotoriK** [comment]
我快速检查了下主题自带的markdown parser仅作用于评论，博文的md转换应该是由你的插件决定的。我现在倾向于认为这个是插件的问题。当然，如果真的是哪处屎山导致的请积极反馈，请你先做下测试看看吧

**Comment by zzzhxxx** [comment]
> 我快速检查了下主题自带的markdown parser仅作用于评论，博文的md转换应该是由你的插件决定的。我现在倾向于认为这个是插件的问题。当然，如果真的是哪处屎山导致的请积极反馈，请你先做下测试看看吧

好的，我换一个md插件试试

**Comment by KotoriK** [comment]
嗯 我记忆中直接写html markup的话是没有问题的

**Comment by zzzhxxx** [comment]
> 嗯 我记忆中直接写html markup的话是没有问题的

现在换用了WP Githuber MD插件，高亮功能恢复正常了，看来应该是插件的问题
