### ISSUE TITLE
图片说明文字居中无法正常显示

### ISSUE THREAD

**Issue by YazawaSunrise** [mirai-mamori/Sakurairo#836]
![PixPin_2024-01-22_19-56-59](https://github.com/mirai-mamori/Sakurairo/assets/114328572/2ed4a1ac-3787-497d-a1a6-d4c26320c57c)
wordpress的编辑界面，将说明文字设为居中
![PixPin_2024-01-22_19-57-14](https://github.com/mirai-mamori/Sakurairo/assets/114328572/a2f911b0-b52b-477b-9233-a8113c8a1b1a)
实际显示页面，居中失败
![PixPin_2024-01-22_19-57-51](https://github.com/mirai-mamori/Sakurairo/assets/114328572/859d425e-103b-4eae-bad6-12a496679c19)
默认主题的显示

**Comment by kanodaisuki** [comment]
你的`页面排版样式`选择的是什么呢，在主题设置里面

**Comment by YazawaSunrise** [comment]
> 你的`页面排版样式`选择的是什么呢，在主题设置里面

默认样式

**Comment by kanodaisuki** [comment]
问题原因在于默认主题与第三方主题（不仅仅限于Sakurairo）渲染出来的HTML结构不同，导致无法匹配区块编辑器的样式。

### 默认主题渲染出来的HTML

```html
<figure class="wp-block-image aligncenter size-full">
  <img
    decoding="async"
    loading="lazy"
    width="340"
    height="342"
    src="http://sakurairo-dev.kanochan.net/wp-content/uploads/2022/04/login.png"
    alt=""
    class="wp-image-1186"
    srcset="
      https://sakurairo-dev.kanochan.net/wp-content/uploads/2022/04/login.png         340w,
      https://sakurairo-dev.kanochan.net/wp-content/uploads/2022/04/login-298x300.png 298w,
      https://sakurairo-dev.kanochan.net/wp-content/uploads/2022/04/login-150x150.png 150w
    "
    sizes="(max-width: 340px) 100vw, 340px"
  />
  <figcaption class="wp-element-caption">这是说明文字</figcaption>
</figure>
```

### 第三方主题渲染出来的HTML

```html
<div class="wp-block-image">
  <figure class="aligncenter size-full">
    <img
      decoding="async"
      width="340"
      height="342"
      src="http://sakurairo-dev.kanochan.net/wp-content/uploads/2022/04/login.png"
      alt=""
      class="wp-image-1186"
      srcset="
        https://sakurairo-dev.kanochan.net/wp-content/uploads/2022/04/login.png         340w,
        https://sakurairo-dev.kanochan.net/wp-content/uploads/2022/04/login-298x300.png 298w,
        https://sakurairo-dev.kanochan.net/wp-content/uploads/2022/04/login-150x150.png 150w
      "
      sizes="(max-width: 340px) 100vw, 340px"
    />
    <figcaption class="wp-element-caption">这是说明文字</figcaption>
  </figure>
</div>
```

### 区块编辑器样式库

关于图片说明居中的样式可以在`/wp-includes/css/dist/block-library/style.css`的第1014行找到，对于WordPress6.2.2版本：

```css
.wp-block-image.aligncenter{
  text-align:center;
}
```
这里文字居中样式的选择器只会匹配默认主题渲染出来的HTML，第三方主题不生效也是合情合理。

目前不清楚是WordPress有意为之或是BUG。看了一下其他主题，似乎都是在主题里集成
```css
.wp-block-image .aligncenter{
  text-align:center;
}
```
样式以解决此问题。

如果想要临时解决这个问题，你可以在主题设置中，将上面的样式添加到主题的自定义CSS里面。

**Comment by kanodaisuki** [comment]
对于为什么同一个区块下，默认主题与第三方主题渲染出来的HTML结构不同，或许应该详细考究一下，走过路过的大佬们，请帮忙看看~

**Comment by KotoriK** [comment]
感谢Copilot找到了[一篇2022年5月的文章](https://make.wordpress.org/core/2022/05/03/block-markup-updates-for-image-quote-list-and-group-blocks/)，自WordPress 6.0始，区块的HTML标记结构发生了变化
我们可能要针对相关情况做特别处理
