### ISSUE TITLE
灯箱只有lightgellery可以用了

### ISSUE THREAD

**Issue by Yish1** [mirai-mamori/Sakurairo#837]
BaguetteBox灯箱效果
开启之后将使用BaguetteBox作为图片灯箱效果
FancyBox灯箱效果
开启之后将使用FancyBox作为图片灯箱效果，将会额外加载JQ库
LightGallery灯箱效果
开启之后将使用LightGallery作为图片灯箱效果

只有最后一个可以用.

**Comment by Yish1** [comment]
v2.6.3.1

**Comment by KotoriK** [comment]
三种库使用的是不同的markup，可以先检查下呢

**Comment by Yish1** [comment]
没事了，我的问题/doge
