### ISSUE TITLE
安装主题后主页报错

### ISSUE THREAD

**Issue by huailo** [mirai-mamori/Sakurairo#845]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

这个问题出在程序的哪一个具体功能？
主页，不正常报错
**实际行为描述：**
array_search() expects parameter 2 to be array
**复现步骤：**
-
怎样才能再次触发这个问题？
-
**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4.33
- 数据库类型 / 版本：8.0.34
- WordPress 版本：6.4.3
- 主题版本：（Release 标注的版本号）2.6.3.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）无
- 浏览器：（浏览器名称及版本号）edge版本 121.0.2277.83 (正式版本) (64 位)

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。
![image](https://github.com/mirai-mamori/Sakurairo/assets/82349739/b7439655-8be3-41f6-8ff2-f0e2e2424236)
网站主页面
**补充信息：**
已经降级php并且对word press进行了干净的重新安装，无效
提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
这个错误其实是主题设置初始值还没写入导致的

你安装完再刷新下试试呢？或者进去主题设置保存一下再看看还有没有这个问题
