### ISSUE TITLE
深色模式下背景图出现异常

### ISSUE THREAD

**Issue by HiderX** [mirai-mamori/Sakurairo#847]
**问题出处：**
深色模式；前台背景

**实际行为描述：**

浅色模式前台背景正常显示、深色模式下前台背景会在y轴上重复，并随着滚动滚动

**预期的行为：**

修复此bug，或者帮忙给出前台背景的选择器，使用 .body.dark 尝试设置背景为fixed和no- repeat无效

**复现步骤：**

**配置与环境：**

- 问题页面：bilibili.work（开启深色模式，chrome访问）（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8
- 数据库类型 / 版本： mysql
- WordPress 版本：latest
- 主题版本：latest（Release 标注的版本号）
- 使用的插件：UpdraftPlus WP Githuber MD  超级缓存（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：chrome 版本 121.0.6167.139（正式版本） (arm64)（浏览器名称及版本号）

**截图（若有）**
<img width="1624" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/60884197/8fd3b9e2-3b99-4ada-aedf-882f444ecd0c">

**补充信息：**

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
Firefox没有这个问题。Chrome这边还不一定每次都会触发，但是只要没有```.dark```类就一定不会触发，并且老版本的Chrome也有这个问题。

很神秘

**Comment by HiderX** [comment]
那我怎么解决（ 
safari访问一卡一卡的， 浅色模式还是正常的 ，深色模式就bug
能不能通过selector 给他固定一下呀

**Comment by HiderX** [comment]
尝试了.body.dark 选择器，使用stylebot在前台有效，但是写到主题设置里的css不起作用

**Comment by KotoriK** [comment]
Safari也有类似的bug嘛？
这个目前怀疑是特殊的CSS规则导致特定浏览器呈现出了问题（也就是符合标准但违背了浏览器内部的工作方式导致异常，换句话来说就是比较难搞）

**Comment by HiderX** [comment]
有，而且我写css还不起效果，写成none倒是可以
