### ISSUE TITLE
文章页面装饰图片不显示，单独页面显示正常

### ISSUE THREAD

**Issue by light-ly** [mirai-mamori/Sakurairo#848]
**问题：**
在设置中设置了特色图片使用外部链接，在主页文章区域显示正常，但打开文章页面装饰图片不显示。
外部链接使用的是 https://api.maho.cc/random-img/pc.php

**尝试：**

关闭预加载，清理缓存，删除并重新发布文章，都没有改变这个现象

**配置与环境：**

- 问题页面：blog.light-liuyi.top
- PHP 版本：7.4.23
- 数据库类型 / 版本：MariaDB 10.5.6
- WordPress 版本：6.3
- 主题版本：2.6.3.1
- 使用的插件：Akismet 反垃圾邮件：垃圾邮件保护
- 浏览器：Microsoft Edge 121.0.2277.112 

这是在主页的文章区域，显示是正常的

<img width="707" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/57036763/1b23e326-4de2-4730-96e8-0a6301da4388">

这是在文章打开的页面，没有显示图片

<img width="1015" alt="image" src="https://github.com/mirai-mamori/Sakurairo/assets/57036763/a5076a31-60de-40f4-822f-c3efb255cd3f">

**Comment by kanodaisuki** [comment]
如果你需要在文章页面的顶部显示图片，你需要在文章编辑页面配置`特色图片`。WordPress并不直接支持填写外部链接作为特色图片，需要使用第三方插件，如`Featured Image from URL (FIFU)`，你也可以选择本地媒体库上的图片作为特色图片。

当文章缺少特色图片时，为了保证首页样式的统一，会自动从随机图来源里获取一张图片作为首页里文章的封面。而文章页面不会这样做，你需要自行配置文章的特色图片。

**Comment by light-ly** [comment]
OK 十分感谢，可以显示图片了。对 WordPress 不是很熟悉导致对特色图片的设置理解有误。麻烦了，再次感谢。
