### ISSUE TITLE
评论邮件通知无法正常发出邮件

### ISSUE THREAD

**Issue by MyGodKnow** [mirai-mamori/Sakurairo#849]
**问题出处：**

评论邮件通知

**实际行为描述：**

评论的时候在勾选了"邮件通知"和“我不是机器人”后成功发送了评论，后台也能看到，但是在回复该评论后评论的人无法收到邮件。

**复现步骤：**

后台勾选相关选项，然后评论一下，并回复该评论。

**配置与环境：**

- 问题页面：www.wgzdy.top的所有文章
- PHP 版本：8.0.26 
- 数据库类型 / 版本：MySQL 5.6.50
- WordPress 版本：6.4.3
- 主题版本：2.6.3.1
- 使用的插件：果果推送（版本：0.0.5）、WP Fastest Cache（版本：1.2.3）、WP Fastest Cache Premium（版本：1.6.8）、Smart SEO Tool-WordPress SEO优化插件（版本4.0.4）
- 浏览器：Google Chrome（版本 109.0.5414.120（正式版本） （64 位））

**补充信息：**

我在functions.php中添加了如下代码：
`add_action('phpmailer_init', 'mail_smtp');
function mail_smtp( $phpmailer ) {
    $phpmailer->FromName = '我鬼知道の机器人';
    $phpmailer->Host = 'smtp-mail.outlook.com';
    $phpmailer->Port = 587;
    $phpmailer->Username = 'robots@wgzdy.top';
    $phpmailer->Password = '****';
    $phpmailer->From = 'robots@wgzdy.top';
    $phpmailer->SMTPAuth = true;  
    $phpmailer->SMTPSecure = 'STARTTLS';
    $phpmailer->IsSMTP();
}
`
经测试，可以正常发出邮件
![20240217162940](https://github.com/mirai-mamori/Sakurairo/assets/95115184/2e3b02cc-9d30-4cc5-a39e-39d77be2d880)

（好像只有我有这个BUG？？这玩意持续在我网站上有半年了）

**Comment by kanodaisuki** [comment]
> 我在functions.php中添加了如下代码：
add_action('phpmailer_init', 'mail_smtp'); function mail_smtp( $phpmailer ) { $phpmailer->FromName = '我鬼知道の机器人'; $phpmailer->Host = 'smtp-mail.outlook.com'; $phpmailer->Port = 587; $phpmailer->Username = 'robots@wgzdy.top'; $phpmailer->Password = '****'; $phpmailer->From = 'robots@wgzdy.top'; $phpmailer->SMTPAuth = true;   $phpmailer->SMTPSecure = 'STARTTLS'; $phpmailer->IsSMTP(); } 
经测试，可以正常发出邮件

邮件通知能力依赖于WordPress的邮件插件，请先安装并配置一个你喜欢的邮件插件。

**Comment by MyGodKnow** [comment]
> > 我在functions.php中添加了如下代码：
> > add_action('phpmailer_init', 'mail_smtp'); function mail_smtp( $phpmailer ) { $phpmailer->FromName = '我鬼知道の机器人'; $phpmailer->Host = 'smtp-mail.outlook.com'; $phpmailer->Port = 587; $phpmailer->Username = '[robots@wgzdy.top](mailto:robots@wgzdy.top)'; $phpmailer->Password = '****'; $phpmailer->From = '[robots@wgzdy.top](mailto:robots@wgzdy.top)'; $phpmailer->SMTPAuth = true;   $phpmailer->SMTPSecure = 'STARTTLS'; $phpmailer->IsSMTP(); }
> > 经测试，可以正常发出邮件
> 
> 邮件通知能力依赖于WordPress的邮件插件，请先安装并配置一个你喜欢的邮件插件。

安装了WP Mail SMTP插件后解决了，谢谢大佬
