### ISSUE TITLE
手机端的登陆问题

### ISSUE THREAD

**Issue by NBzhouzihan** [mirai-mamori/Sakurairo#852]
**具体行为描述：**

在基于此主题的网站 https://kiseki.blog/ 中，手机端评论是强制登录的，同时配套有一套含验证码的注册页面。而在我编写的网站 http://www.icpc-westlake.cn/ 中，电脑端含有登录界面，但是手机端并没有登录入口。

**尝试：**

在选择了允许所有人注册之后，电脑端已经有了注册入口，但是手机端依旧没有登录入口。

**配置与环境：**

- PHP 版本：7.4.33
- 数据库类型 / 版本：mysql5.6.51
- WordPress 版本：6.4.3
- 主题版本：（Release 标注的版本号）2.6.3.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

![8bffb5a6e867e1f944a23b76e3d6dbe](https://github.com/mirai-mamori/Sakurairo/assets/93895266/8692d7ef-f7a9-4cd8-82b1-7b2c3a646a34)

**Comment by kanodaisuki** [comment]
或许应该增加移动端的登录/注册入口
