### ISSUE TITLE
看板娘左侧四个按钮没有紧靠侧边

### ISSUE THREAD

**Issue by Frank-Pai** [mirai-mamori/Sakurairo#855]
**大致范围：**
博客左下角看板娘左侧四个按钮没有紧靠侧边。

**具体行为描述：**
我从网上找到了一篇博客（原文链接：https://yremp.live/live2d/），讲如何在Sakura主题添加Live2D看板娘。我在Sakura主题上试验成功了，见下图。

![image](https://github.com/mirai-mamori/Sakurairo/assets/161006809/4780a807-70d3-4f9e-bd16-5e4535d0dc86)

但在Sakurairo主题上试验却出现了bug，看板娘左侧四个按钮没有紧靠侧边。

![image](https://github.com/mirai-mamori/Sakurairo/assets/161006809/98de5627-b093-40ec-b1f5-4535313fd63a)

**尝试：**
我是一个纯小白，只会复制粘贴，我自己不知道哪里出问题了。

**配置与环境：**
- 问题页面：http://www.franksbackgarden.top/
- PHP 版本：7.4.33
- 数据库类型 / 版本：MySQL 5.6.50
- WordPress 版本：6.4.3
- 主题版本：Sakurairo 2.6.3.1
- 使用的插件：Autoptimize 3.1.10 ；WP Statistics 14.5；超级缓存 1.11.0
- 浏览器：Microsoft Edge  122.0.2365.59 

**补充信息：**
我是一个纯小白，只会复制粘贴。还请各位大佬给出的解决步骤细一些。

**Comment by Yish1** [comment]
waifu.css第396行   left: -11px; 自己改一下就好
![image](https://github.com/mirai-mamori/Sakurairo/assets/101796381/8c9b8148-1402-4948-b077-ab67c62dd536)

**Comment by ahui-atong** [comment]
> waifu.css第396行 left: -11px; 自己改一下就好 ![image](https://private-user-images.githubusercontent.com/101796381/309528523-8c9b8148-1402-4948-b077-ab67c62dd536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDI2MzIsIm5iZiI6MTcxMTU0MjMzMiwicGF0aCI6Ii8xMDE3OTYzODEvMzA5NTI4NTIzLThjOWI4MTQ4LTE0MDItNDk0OC1iMDc3LWFiNjdjNjJkZDUzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMjI1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzRjOTgyMjY4OWMyMjFjOTE2YTliZTJhNDg2OWE4OTgyODBiZjUzYjg4ZTg1MmI4ZmM1ZDcxMjNiMWM5YzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8vGnmRotpmTmltQvlfw9X1Ra5QtR2F3Ggsl5Wo3oMQE)

我也遇到了相同的问题，请问waifu.css文件在哪里

**Comment by ahui-atong** [comment]
> waifu.css第396行 left: -11px; 自己改一下就好 ![image](https://private-user-images.githubusercontent.com/101796381/309528523-8c9b8148-1402-4948-b077-ab67c62dd536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTY3NTcsIm5iZiI6MTcxMTYxNjQ1NywicGF0aCI6Ii8xMDE3OTYzODEvMzA5NTI4NTIzLThjOWI4MTQ4LTE0MDItNDk0OC1iMDc3LWFiNjdjNjJkZDUzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwOTAwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODdlOGMxMjZiYmY0N2NhZjJjNWVkNTgyNzJkZGFiYTkyYjM0YTMxNjRlZmRiNjJmZmM1NTRkZGY1MmZiMzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zWUuDQlV7R4vCX_Mye7hvOzciDEGwGBtCMQXQ6QBRAw)

我找到位置了，改了咋没有效果
