### ISSUE TITLE
QQ头像加密问题

### ISSUE THREAD

**Issue by Yish1** [mirai-mamori/Sakurairo#856]
**问题出处：在最新的priview路线中，开启评论QQ头像加密( “重定向” 以及 “后端获取头像数据” )会导致评论区报错

![image](https://github.com/mirai-mamori/Sakurairo/assets/101796381/fdd8059d-cd43-481d-9ff7-0fbfb75b5402)

发现导致此问题与[Function.php](https://github.com/mirai-mamori/Sakurairo/commit/6c087196ca8666e04c9f6a36577be6c5173c137a)的修改有关，此次修改注释掉了$sakura_privkey，导致与之相关的$iv与$encrypted出错

**截图（若有）*
<img width="998" alt="e9135c7970152050d9e5fe6a33a6c88a" src="https://github.com/mirai-mamori/Sakurairo/assets/101796381/eaf9a881-9643-48da-bc21-c44e125c370b">
*

**补充信息：**
后端解析图像接口(高安全性，慢速) 似乎无法获取图像
例[https://ptlogin2.qq.com/getface?appid=1006102&imgtype=3&uin=10001](https://ptlogin2.qq.com/getface?appid=1006102&imgtype=3&uin=10001)
![image](https://github.com/mirai-mamori/Sakurairo/assets/101796381/3de10f89-5b99-4e89-ab03-e4fe55e6cdad)

**Comment by bymoye** [comment]
qq从去年开始就需要鉴权了，相对来说很麻烦。

**Comment by Yish1** [comment]
qq空间这个接口也能返回json，不知能否替代https://users.qzone.qq.com/fcg-bin/cgi_get_portrait.fcg?uins=100001

**Comment by bymoye** [comment]
> qq空间这个接口也能返回json，不知能否替代https://users.qzone.qq.com/fcg-bin/cgi_get_portrait.fcg?uins=100001

并不能，这个回来的头像是明文，包含qq号的。

**Comment by Yish1** [comment]
这个似乎可以，在inc/qq.php里找到的 https://api.qjqq.cn/api/qqinfo?qq=
![image](https://github.com/mirai-mamori/Sakurairo/assets/101796381/1d68d472-e847-4fcc-8042-1ed3a4e8e36c)

**Comment by mirai-mamori** [comment]
@KotoriK

**Comment by robert1chi** [comment]
Deprecated, 未来版本计划移除
