### ISSUE TITLE
最新的chromium内核评论区无法上传图片

### ISSUE THREAD

**Issue by W912022884** [mirai-mamori/Sakurairo#858]
**问题出处：**

评论区上传图片功能

**实际行为描述：**

没有跳出资源管理器，手机电脑都有，点击无反应
但95和99版本内核测试可以上传
大概100以上版本出现该问题

**预期的行为：**

弹出资源管理器选择图片后上传

**复现步骤：**

点击评论区上传图片功能

**配置与环境：**

- 问题页面：https://wxweb.xyz/?page_id=10
- PHP 版本：8.0
- 数据库类型 / 版本：5.2
- WordPress 版本：6.4.3
- 主题版本：2.6.3.1
- 使用的插件：无
- 浏览器：100版本以上

**截图（若有）**
无
**补充信息：**
无

**Comment by Yish1** [comment]
一样的问题😂我分支里试着修了一下https://github.com/Yish1/Sakurairo/commit/b002dec6bda6a0551ac88bb2858dbba1d70ef027

**Comment by KotoriK** [comment]
现在还有这个问题吗？未能复现

**Comment by mirai-mamori** [comment]
可以pr
