### ISSUE TITLE
用户头像在后台、菜单栏、文末博主描述三部分显示不正确的问题

### ISSUE THREAD

**Issue by Quanfita** [mirai-mamori/Sakurairo#86]
您好，我想请教一个问题，用户头像后台的“资料图片”、菜单栏的头像和文末博主描述的头像显示好像有问题，文末博主头像只能显示主题设置的头像而不是文章作者的头像，菜单栏头像一直显示的是默认头像无法修改，后台的头像我通过simple-local-avatars修改后对上述两个没有任何影响。上述问题楼主是否有好的解决办法，wp新人还在学习，还请指教。

**背景**：我想要打造一个多用户的网站，有作者、管理员、游客三种身份，作者和管理员可以发文章。
**问题描述**：目前出现的问题是：1.菜单栏头像无法修改。后台用户信息我借助simple-local-avatars可以进行修改了，但是只能后台显示；2.文末博主头像只能显示管理员的，即在主题设置中设置的头像。我希望文末博主头像可以显示文章作者的头像。

下图给出了从作者角度观察的这三部分显示的头像：
[后端用户信息](http://101.200.38.17/wp-content/uploads/2020/08/TIM截图20200808133213.png)
[文末博主描述](http://101.200.38.17/wp-content/uploads/2020/08/TIM截图20200808133251.png)
[菜单栏头像](http://101.200.38.17/wp-content/uploads/2020/08/TIM截图20200808133236.png)

- PHP 版本：5.6
- 数据库类型 / 版本：Mysql 5.7
- Worldpress 版本：4.8.1
- 主题版本：1.14.1
- 使用的插件：simple-local-avatars，wp-members
- 浏览器：chrome 79.0.3945.130

希望能够得到您的帮助，谢谢~！

**Comment by Ukenn2112** [comment]
首先感谢您发来的issue:
我先讲解一下本主题目前设计各方面头像是如何设置以及具体有什么作用

1.菜单栏头像:是根据用户使用自己的邮箱在gravatar上所设置的头像

2.文末博主头像:是根据博客博主在主题后台所设置的头像

3.后端用户信息所设置的头像:也只是后台才能看到然而并没有什么实际效果。

当初主题设计的时候只考虑了满足单个用户也就是单个博主需求，所以并没有做多用户的设计与优化。可能后续版本考虑会支持。但是目前主题并不适合做多用户博客来选用，为此没能满足你的需求，在此我感到非常抱歉。
