### ISSUE TITLE
主页出现问题

### ISSUE THREAD

**Issue by usariapro** [mirai-mamori/Sakurairo#860]
**大致范围：**

这是哪一方面的问题？你是否知道问题所牵连到的文件以及在文件的哪一行？

答：不知道

**具体行为描述：**

你的问题具体是什么？

我能大概感觉到是和我当时编辑了主题的文件有关，虽然我没有动里面的代码，我只是想寻找下session_start这串代码，但没有找到就关闭了，然后就出现了这个问题。主页一直出现代码，但是一直往下拉能看到正常主页。

**尝试：

你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了

答：恢复了备份的主题文件和数据库文件，但还是像那样。

**配置与环境：

- 问题页面：www.kerbin.icu
- PHP 版本：8.2.3
- 数据库类型 / 版本：mysqlnd 8.2.3
- WordPress 版本：6.4.3
- 主题版本：3.1
- 使用的插件：健康检查和故障排除
- 浏览器：chrome 版本 122.0.6261.112

**截图（若有）**
![QQ截图20240308225508](https://github.com/mirai-mamori/Sakurairo/assets/59077002/0b596081-089f-4462-956a-1e527473b7f9)
![QQ截图20240308225917](https://github.com/mirai-mamori/Sakurairo/assets/59077002/a8cc1883-6698-41f9-965a-b763db7f079a)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by usariapro** [comment]
# 商业转载请联系作者获得授权，非商业转载请注明出处。
# For commercial use, please contact the author for authorization. For non-commercial use, please indicate the source.
# 协议(License)：署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)
# 作者(Author)：Aruruu
# 链接(URL)：https://www.kerbin.icu/?customize_changeset_uuid=05e73599-cce1-4d50-938f-b4996723663a&customize_theme=Sakurairo-2.6.3.1&customize_messenger_channel=preview-0
# 来源(Source)：Kerbin!

Deprecated: Creation of dynamic property CSF_Field_image_select::$field is deprecated in /home/ftp/s/s9564313/wwwroot/wp-content/themes/Sakurairo-2.6.3.1/opt/classes/fields.class.php on line 14

Deprecated: Creation of dynamic property CSF_Field_image_select::$value is deprecated in /home/ftp/s/s9564313/wwwroot/wp-content/themes/Sakurairo-2.6.3.1/opt/classes/fields.class.php on line 15

Deprecated: Creation of dynamic property CSF_Field_image_select::$unique is deprecated in /home/ftp/s/s9564313/wwwroot/wp-content/themes/Sakurairo-2.6.3.1/opt/classes/fields.class.php on line 16

Deprecated: Creation of dynamic property CSF_Field_image_select::$where is deprecated in /home/ftp/s/s9564313/wwwroot/wp-content/themes/Sakurairo-2.6.3.1/opt/classes/fields.class.php on line 17

Deprecated: Creation of dynamic property CSF_Field_image_select::$parent is deprecated in /home/ftp/s/s9564313/wwwroot/wp-content/themes/Sakurairo-2.6.3.1/opt/classes/fields.class.php on line 18

Deprecated: Creation of dynamic property CSF_Field_slider::$field is deprecated in /home/ftp/s/s9564313/wwwroot/wp-content/themes/Sakurairo-2.6.3.1/opt/classes/fields.class.php on line 14


**### 我尝试将主页出现的代码复制进chatGPT里，以下是GPT的回答**




这些警告信息是由于使用了过时的代码和函数导致的。在你提供的信息中，这些警告是关于一个名为"Sakurairo-2.6.3.1"的WordPress主题的问题。

警告中提到的"Deprecated"意味着相关代码或函数已被弃用，不再推荐使用。这意味着在将来的版本中，这些代码可能会被移除或不再正常工作。

如果你是该主题的开发者或管理员，你可以考虑更新主题，以避免这些警告。更新主题通常会修复过时的代码，并提供更好的兼容性和功能。

如果你只是网站的使用者，你可以尝试联系主题的开发者或作者，向他们报告这些警告信息。他们可能会提供更新的版本或修复的补丁来解决这些问题。

总之，这些警告信息不会导致网站无法正常运行，但如果你希望保持网站的最佳状态，最好采取相应的行动来解决这些警告。

**Comment by KotoriK** [comment]
https://github.com/mirai-mamori/Sakurairo/issues/807#issuecomment-1791801814
