### ISSUE TITLE
评论无法发出,提示"错误：请输入您的评论文本" admin-ajax.php 500

### ISSUE THREAD

**Issue by wanyulaowang** [mirai-mamori/Sakurairo#861]
**问题出处：**

文章评论

**实际行为描述：**

正常输入评论内容,点击"BiuBiuBiu~"发送显示报错

**预期的行为：**

应该正常发送并保存评论

**复现步骤：**

重新评论即可

**配置与环境：**

- 问题页面：
- PHP 版本：8.1
- 数据库类型 / 版本：MySQL 5.7.44
- WordPress 版本：6.4.3
- 主题版本：2.6.3.1
- 使用的插件：
Antispam Bee; 
Basic User Avatars; 
 Post SMTP;
Wordfence安全
WP Extended Search
WP Statistics
WP-Optimize - Clean, Compress, Cache

- 浏览器：（浏览器名称及版本号）
Microsoft Edge
版本 122.0.2365.80 (正式版本) (64 位)
**截图（若有）**
![](https://imgs.run/i/2024/03/12/65efe32243965.png)
![](https://imgs.run/i/2024/03/12/65efe36ecb06c.png)

**补充信息：**

尝试切换其他主题,例如LoliMeow正常发送评论

![](https://imgs.run/i/2024/03/12/65efe547191f6.png)

**Comment by KotoriK** [comment]
```/wp-admin/admin-ajax.php```的返回是什么？

**Comment by wanyulaowang** [comment]
![](https://imgs.run/i/2024/03/16/65f550564cce7.png)
![](https://imgs.run/i/2024/03/16/65f55151e5476.png)

**Comment by wanyulaowang** [comment]
排查到原因了,主题可能与"Antispam Bee"插件冲突,只要启用Antispam Bee插件,评论就会发生该异常,目前不清楚具体冲突原因

**Comment by KotoriK** [comment]
需要检查下是评论触发了插件的哪条规则（
