### ISSUE TITLE
随机图片设置 增加API调用模式

### ISSUE THREAD

**Issue by chinoKwi** [mirai-mamori/Sakurairo#865]
**这是什么方面的想法？**
新增功能

**这个想法具体是要实现什么？**
随机图片设置外部API增加 API接口调用模式

**这个想法实现后有什么帮助？**
更灵活的使用随机图片API

**是否有具体的实现思路？**

前端 页面增加：
1. 接口地址输入框（例如：`https://example.com`）
2. 请求方式下拉框 (例如：`POST`)
3. 图片地址取值输入框 （例如：`data.url`）

**补充信息：**
接口调用在后端完成，待接口返回数据后 依据用户输入的 `图片地址取值` 字段，将图片渲染至页面

**Comment by kanodaisuki** [comment]
没太看明白。你的意思是让浏览网页的游客可以自定义随机图来源？

按照你的想法，我认为你的服务器会变成一台由匿名用户控制，可以向任何地址发送HTTP请求的机器。这是绝对不合理的。

**Comment by chinoKwi** [comment]
并不是让浏览网页的游客自定义随机图来源。
前端页面是指 后台管理的主题设置里。目前有 Webp优化/外部API桌面端随机图片地址、外部API手机端随机图片地址，希望可以在目前的功能上按照上述方案增强。

目前填入的地址是直接被放到图片src里的。主要想法是不想直接暴露填写的随机图片地址，对于部分随机图片接口 地址中可能包含token等字段。

**Comment by KotoriK** [comment]
你这个问题是随机图片接口的问题而不是主题的问题，主题是不管随机图接口是直接返回图片还是redirect到图片真实地址上的。
