### ISSUE TITLE
nginx php报告出现错误日志：php depreciated 不影响正常功能

### ISSUE THREAD

**Issue by Rick-Cooper** [mirai-mamori/Sakurairo#866]
**问题出处：**
nginx php 报错：
*369 FastCGI sent in stderr: PHP message: PHP Deprecated: Creation of dynamic property CSF_Field_color::$where is deprecated in /var/www/wordpress/wp-content/themes/Sakurairo/opt/classes/fields.class.php on line 17;
PHP message: PHP Deprecated: Creation of dynamic property CSF_Field_image_select::$unique is deprecated in /var/www/wordpress/wp-content/themes/Sakurairo/opt/classes/fields.class.php on line 16;

有很多行报错，php是最新8.2版本

**实际行为描述：**

php报错

**预期的行为：**

no log

**复现步骤：**

正常浏览网页

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：PHP Version 8.2.7

可能是主题里面一些素材php以后不支持了？

**Comment by KotoriK** [comment]
deprecated warning 的issue迄今为止已经有10条了
#636 #640 #751 #760 #764 #766 #774 #807 #860 #866

1. deprecate不是报错，而是预告的是下个大版本才会不支持的功能，非开发者可以安全关掉。现在PHP 9还没有消息，在那之前fix掉就平安无事
2. 这是来自外部依赖的问题，我们也在等上游修复。([v2.3.1](https://github.com/Codestar/codestar-framework/releases/tag/2.3.1)终于修了，下个版本应该会更新上)

**Comment by Rick-Cooper** [comment]
好的，感谢🥰

**Comment by Rick-Cooper** [comment]
好的，感谢🥰
