### ISSUE TITLE
一个新的光标样式

### ISSUE THREAD

**Issue by ImKK666** [mirai-mamori/Sakurairo#867]
**这是什么方面的想法？**
看到 https://docs.fuukei.org/ 的鼠标特效非常棒 感觉更符合主题

**这个想法具体是要实现什么？**
应该可以增加一个 调用鼠标特效的js接口 直接覆盖原有的光标样式图片选项
有更高的自由度

**这个想法实现后有什么帮助？**
一个更符合主题审美的鼠标特效？

**是否有具体的实现思路？**
加个开关 选择默认的 或者 自定义的js实现
或者干脆全部调用js实现 光标特效 这样就可以 自己修改特效

**补充信息：**
最好默认的光标特效以后就使用 https://docs.fuukei.org/的 [滑稽][狗头保命]

**Comment by kanodaisuki** [comment]
@Shiroiame-Kusu 劳劳烦贴一下鼠标代码，或者指个路。

理论上让用户直接把js代码放主题里面就行了，无需要额外接口。开关的话，应该不会加，因为把主题设置里的光标清空，也能达到同样的目的。

**Comment by Shiroiame-Kusu** [comment]
> @Shiroiame-Kusu 劳劳烦贴一下鼠标代码，或者指个路。
> 
> 理论上让用户直接把js代码放主题里面就行了，无需要额外接口。开关的话，应该不会加，因为把主题设置里的光标清空，也能达到同样的目的。

你要不先去翻翻wiki的代码，我博客最近是爆炸状态拿不到最纯真的js
