### ISSUE TITLE
Prism.js代码高亮组件 添加 复制代码 按钮抛出异常

### ISSUE THREAD

**Issue by ImKK666** [mirai-mamori/Sakurairo#868]
**问题出处：**
https://92.run/2024/03/30/league-of-legendslolriot-servers-bypass-inline-hook/

**实际行为描述：**
使用 Prism.js 代码高亮组件
缺失了 复制代码 的按钮 及其 功能

**预期的行为：**
正确的添加 复制代码按钮 及其功能

**复现步骤：**
如图设置:
![image](https://github.com/mirai-mamori/Sakurairo/assets/100894732/4d3e4a6c-211f-4d6a-b755-f887cb1e77ca)

然后 新建文章 添加一个HTML内容 键入
```html
<pre><code class="language-cpp">
printf("test");
</code></pre>
```
发布 打开就可以 观察到

**配置与环境：**

- 问题页面：https://92.run/2024/03/30/league-of-legendslolriot-servers-bypass-inline-hook/
- PHP 版本：8.0.26
- 数据库类型 / 版本：5.7.44
- WordPress 版本：6.4.3
- 主题版本：2.6.3.1 | 内部版本 18.3.1
- 使用的插件：WP Rocket 3.15.10
- 浏览器：Microsoft Edge 版本 120.0.2210.61 (正式版本) (64 位)

**截图（若有）**
![image](https://github.com/mirai-mamori/Sakurairo/assets/100894732/04599d62-5c59-496a-a84c-2a8cbc84ad8b)
![image](https://github.com/mirai-mamori/Sakurairo/assets/100894732/34da2239-3388-41ec-b121-78a4ebb2a926)

**补充信息：**
测试 发现 Highlightjs.js 也会 出现这个问题 有待各位复现

**Comment by kanodaisuki** [comment]
嗯，这个问题其实已经修了，但是还没有发布新版，等待版本更新吧
