### ISSUE TITLE
wordpress导航栏图标没有动态效果

### ISSUE THREAD

**Issue by ahui-atong** [mirai-mamori/Sakurairo#869]
**Sakurairo 版本 2.6 **

原本wordpress主题安装的Sakura主题，导航栏图标设置了动态效果，切换Sakurairo主题后，导航栏设置基本和原来一样，但是动态效果却不显示了，不知道啥原因

**Comment by KotoriK** [comment]
Sakurairo与Sakura的配置并不是一对一的关系，也**可能存在**Sakura的特性Sakurairo未有实装的情况，请检查主题是否有相关配置

**Comment by mirai-mamori** [comment]
新版本使用的是fa6 并非fa4
