### ISSUE TITLE
关于加强机器人评论拦截的建议

### ISSUE THREAD

**Issue by kanodaisuki** [mirai-mamori/Sakurairo#870]
### 发生了什么？
![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/242e827d-0f15-49d9-9ae9-4f1480153f48)

如上图所见，是机器人发布的垃圾评论。主题已经开启了【页面评论区域机器人验证】，但似乎未能起到有效的阻挡作用。

### 原因分析

![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/e63e6b68-595a-49e5-a037-ed3a5f3b467c)

上图是一张iro的评论表单，结合后台评论的内容上看，可以确定一点：机器人填写（勾选）了全部表单内容，并将表单发送到了后台。

![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/59eb9c76-5afa-47a0-b56d-6225d0e8d576)

关于【页面评论区域机器人验证】的功能实现，可以看代码[theme_plus.php](https://github.com/mirai-mamori/Sakurairo/blob/c94fec3f13384fb0f5fe2164456f6626ec363739/inc/theme_plus.php#L145)，代码仅验证了POST请求中是否含有【no-robot】字段，对于填写全部表单内容这种机器人来说，无法起到拦截作用。

### 改进建议

或许可以复用后台登录的验证码来进行机器人拦截。

**Comment by ImKK666** [comment]
上个CF盾 一般的机器人肯定是不行了 毕竟一条信息1毛钱 可不是啥机器人都用得起的

**Comment by KotoriK** [comment]
那我们反过来 no-robot为off的时候才允许通过

**Comment by kanodaisuki** [comment]
改了一版，如果觉得还OK的话，我把它推上来。
复用了主题内建的验证码功能。
![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/6726dc67-70e2-473a-8c68-8268afd77ead)

![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/c121999e-58ce-4138-84ad-5f7dee08e20f)
