### ISSUE TITLE
【Preview】意外的在空值上调用方法

### ISSUE THREAD

**Issue by kanodaisuki** [mirai-mamori/Sakurairo#873]
![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/e7cd3a3c-e381-4d06-bcb6-b5b2e46575e2)

### 复现

对于preview版本，关闭评论区后，就会出现。

### 相关代码

https://github.com/Fuukei/Sakurairo_Scripts/blob/796d0560e69f4a67527c35e6ae13f4de61e7619a/src/page/emoji.ts#L26

**Comment by KotoriK** [comment]
确实应该捕获一下，晚点改
