### ISSUE TITLE
代码复制

### ISSUE THREAD

**Issue by zhang-zhonggui** [mirai-mamori/Sakurairo#874]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。
**这是什么方面的想法？**

现有内容的优化 / 新增功能 / UI 界面 / 用户体验

**这个想法具体是要实现什么？**
希望在代码展示框中添加个一键复制按钮
![image](https://github.com/mirai-mamori/Sakurairo/assets/89518224/dd659882-4e51-42fb-9964-254d1363be80)
lei类似这种

**这个想法实现后有什么帮助？**

**是否有具体的实现思路？**

**补充信息：**

**Comment by zhang-zhonggui** [comment]
![image](https://github.com/mirai-mamori/Sakurairo/assets/89518224/73c428a8-f823-4f16-a92f-d2f4c47e5880)
目前我的是没有的 Sakurairo 主题版本 2.6.3.1

**Comment by kanodaisuki** [comment]
> ![image](https://private-user-images.githubusercontent.com/89518224/323444823-73c428a8-f823-4f16-a92f-d2f4c47e5880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTc3OTYsIm5iZiI6MTcxNDA1NzQ5NiwicGF0aCI6Ii84OTUxODIyNC8zMjM0NDQ4MjMtNzNjNDI4YTgtZjgyMy00ZjE2LWE5MmYtZDJmNGM0N2U1ODgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1MDQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzOTkzZGQzYjk2MTU3OTIwNWJjZmJlY2M5OTBmNWY2ZWE4NDI5ODFkM2ExYzJiNTg0NzkyYWI5MDMyZDc4YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cJM_47ekV46BLPfEHv46umzC--CEp9Jc1SjcTvL_1e8) 目前我的是没有的 Sakurairo 主题版本 2.6.3.1

看看#811，新版本会解决这个问题，但目前还没发布。请等待更新。
