### ISSUE TITLE
跑马灯样式公告

### ISSUE THREAD

**Issue by WLTGH** [mirai-mamori/Sakurairo#880]
**这是什么方面的想法？**

UI 界面

**这个想法具体是要实现什么？**
给公告栏添加跑马灯效果

**这个想法实现后有什么帮助？**
公告栏可显示文本太少了，很多东西会被隐藏起来

**是否有具体的实现思路？**

**补充信息：**

**Comment by kanodaisuki** [comment]
赞同，加一个吧

**Comment by kanodaisuki** [comment]
看了一下代码

https://github.com/mirai-mamori/Sakurairo/blob/c94fec3f13384fb0f5fe2164456f6626ec363739/index.php#L28

大于142字节长度的字符会启用跑马灯效果，对桌面端来说刚刚好。但对于移动端来说，142字节之前的字符已经大大超出了显示区域，会被隐藏。

而且`<marquee>`标签已经被[弃用](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/marquee)了，或许应该使用CSS动画代替。
