### ISSUE TITLE
手机404页面按键显示问题

### ISSUE THREAD

**Issue by zachb3123** [mirai-mamori/Sakurairo#882]
**问题出处：**
如下图，手机版本（小屏幕）404页面没有完全自动回车显示，英文的比较长，所以就比较明显些。

**实际行为描述：**

触发问题后造成了什么效果及影响？
不美观

**复现步骤：**

怎样才能再次触发这个问题？
404 page

**配置与环境：**

- 问题页面：N/A
- PHP 版本：8.2
- 数据库类型 / 版本：Maria DB 10.11
- WordPress 版本：6.5.2
- 主题版本：latest release
- 使用的插件 N/A
- 浏览器：手机浏览器

**截图（若有）**
![image](https://github.com/mirai-mamori/Sakurairo/assets/168796576/7502ef8e-0aff-4353-8c93-03d4919dbee7)

![image](https://github.com/mirai-mamori/Sakurairo/assets/168796576/5c205225-0bc0-44bd-ae84-5b634835116b)

**Comment by kanodaisuki** [comment]
确实有这个问题，改用flex布局吧
