### ISSUE TITLE
追番模版源请求添加Anilist 

### ISSUE THREAD

**Issue by MareDevi** [mirai-mamori/Sakurairo#885]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**

现有内容的优化 / 新增功能 

**这个想法具体是要实现什么？**
追番模版源请求添加Anilist 

**这个想法实现后有什么帮助？**
丰富数据来源

**是否有具体的实现思路？**
官方提供Api借口

**补充信息：**
https://anilist.co

**Comment by KotoriK** [comment]
这个平台不是很熟悉欸，可以请你简要地介绍下嘛

**Comment by MareDevi** [comment]
> 这个平台不是很熟悉欸，可以请你简要地介绍下嘛

唔……整体上跟mal差不多，用的人也挺多的，不过以老外居多，我当初选它是因为它ui好看来着💦💦
Anilist官方提供了借口所以接入起来应该还是挺方便的

**Comment by meng-luo** [comment]
我觉得Bangumi也可以，国内还是有很多人在用的，并且也有官方的api文档[https://bangumi.github.io/api/](https://bangumi.github.io/api/)
