### ISSUE TITLE
文章没展示目录

### ISSUE THREAD

**Issue by Leard-K** [mirai-mamori/Sakurairo#887]
**问题出处：**

文章页的目录没展示

**配置与环境：**

- 问题页面：文章页
- PHP 版本：8.2.19
- 数据库类型 / 版本：MySQL8.2
- WordPress 版本：6.5.3
- 主题版本：不知道什么版本，main分支拉的

**截图（若有）**
![image](https://github.com/mirai-mamori/Sakurairo/assets/73871922/5238b1ff-a5de-476f-94e4-2ab700a79b38)
**补充信息：**
还有个问题，樱花飘落的那个效果，就展示了一会，不知道咋回事，飘了一会，页面刷新后就没了。

**Comment by MuQY1818** [comment]
你好，我的文章也不显示目录了，请问是怎么解决的呢

**Comment by Leard-K** [comment]
> 你好，我的文章也不显示目录了，请问是怎么解决的呢

![image](https://github.com/user-attachments/assets/e105fc36-10cd-4067-b0e6-342485206901)
过去个把月了，记不得了，注意一下插件啥的，可以先禁用全部插件，然后看看效果
