### ISSUE TITLE
手机端时光轴页面右上角全部展开/收缩，点击无效。

### ISSUE THREAD

**Issue by zachb3123** [mirai-mamori/Sakurairo#889]
**问题出处：**
如标题, 电脑版没有问题。 #586 有提及过

这个问题出在程序的哪一个具体功能？
时光轴页面

**实际行为描述：**

触发问题后造成了什么效果及影响？
用户功能影响

**复现步骤：**

怎样才能再次触发这个问题？
任意一个网站带有手机端时光轴的页面 全部展开/收缩，点击无效

**配置与环境：**

- 问题页面：时光轴页面
- PHP 版本：8.2
- 数据库类型 / 版本：10.11.7-MariaDB
- WordPress 版本：6.5.3
- 主题版本：latest
- 浏览器：N.A

**截图（若有）**
![image](https://github.com/mirai-mamori/Sakurairo/assets/168796576/9f21def2-c791-4980-b1ee-c37debec02ed)

**Comment by kanodaisuki** [comment]
展开/收缩点击仅在桌面端生效：https://github.com/Fuukei/Sakurairo_Scripts/blob/d2b54cc0455e76f4816072ea2ddbc8f7ae815579/src/app/func.js#L111-L145

这是为啥咧 @KotoriK

**Comment by KotoriK** [comment]
> 展开/收缩点击仅在桌面端生效：https://github.com/Fuukei/Sakurairo_Scripts/blob/d2b54cc0455e76f4816072ea2ddbc8f7ae815579/src/app/func.js#L111-L145
> 
> 这是为啥咧 @KotoriK

应该是抄的这一段https://github.com/mirai-mamori/Sakurairo/blob/7decb0a1660a7a319417b12a76c747d83f05861b/js/sakura-app.js#L541C1-L552C14
看起来应该是去jQuery的时候改写大括号套多了
