### ISSUE TITLE
使用文章页面自动显示菜单 会导致文章显示不出来

### ISSUE THREAD

**Issue by SuoLuo1** [mirai-mamori/Sakurairo#895]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：**

这是哪一方面的问题？你是否知道问题所牵连到的文件以及在文件的哪一行？

**具体行为描述：**

你的问题具体是什么？

**尝试：**

你有试过自己解决吗？如果有，请描述你解决的方法和过程，即使它失败了

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.0.30
- 数据库类型 / 版本：8.0.37
- WordPress 版本：6.5.2
- 主题版本：（Release 标注的版本号）3.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）无
- 浏览器：（浏览器名称及版本号）chrome 125.0.6422.142

**截图（若有）**

![image](https://github.com/mirai-mamori/Sakurairo/assets/91360119/f5556349-36b5-41ed-88cc-5c6743cca9a8)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**
尝试安装yum install php-xml 报错
Last metadata expiration check: 4:00:15 ago on Sat 08 Jun 2024 06:44:24 PM CST.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides libgcrypt.so.11()(64bit) needed by php-xml-8.0.30-6.el7.remi.x86_64 from remi-php80
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

提供尽可能多的相关信息。

**Comment by kanodaisuki** [comment]
`文章页面自动显示菜单`功能依赖于PHP DOM扩展，如果你的php没有自动安装，你需要手动安装该扩展。

[dom.installation.php](https://www.php.net/manual/zh/dom.installation.php)

如果你的扩展已经正确安装，可能是别的原因导致了错误，你需要提供发生问题时的PHP日志以便分析。
