### ISSUE TITLE
本地[封面随机图片选项] 手机端适配问题

### ISSUE THREAD

**Issue by LonePheasantWarrior** [mirai-mamori/Sakurairo#896]
我的`主页设置`/`封面设置`/`封面随即图片选项`设置为`本地`
此时横屏访问场景下一切OK，但是到了竖屏场景下画面就怪怪的

我尝试在`/wp-content/themes/Sakurairo-2.6.3.1/manifest/gallary/`下创建了个`mobile`文件夹，在其下放了一些竖屏的图片，但并没有被使用。
随后将竖屏图片和横屏图片一起放在了`/wp-content/themes/Sakurairo-2.6.3.1/manifest/gallary/`，期望站点可以根据图片的横竖比例来自适应当前访问场景，不过并没有这样。

目前我没有找到一个合适的在`本地`设置场景下有一个桌面端和移动端都能兼顾的设置方案，烦请大佬指点一下！
当然我也有看文档[Theme-Sakurairo](https://docs.fuukei.org/Sakurairo/Homepage/#%E9%9A%8F%E6%9C%BA%E5%9B%BE%E8%AE%BE%E7%BD%AE)，不过并没有找到有效的内容

**Comment by xiaozhi-6** [comment]
> 我的`主页设置`/`封面设置`/`封面随即图片选项`设置为`本地` 此时横屏访问场景下一切OK，但是到了竖屏场景下画面就怪怪的
> 
> 我尝试在`/wp-content/themes/Sakurairo-2.6.3.1/manifest/gallary/`下创建了个`mobile`文件夹，在其下放了一些竖屏的图片，但并没有被使用。 随后将竖屏图片和横屏图片一起放在了`/wp-content/themes/Sakurairo-2.6.3.1/manifest/gallary/`，期望站点可以根据图片的横竖比例来自适应当前访问场景，不过并没有这样。
> 
> 目前我没有找到一个合适的在`本地`设置场景下有一个桌面端和移动端都能兼顾的设置方案，烦请大佬指点一下！ 当然我也有看文档[Theme-Sakurairo](https://docs.fuukei.org/Sakurairo/Homepage/#%E9%9A%8F%E6%9C%BA%E5%9B%BE%E8%AE%BE%E7%BD%AE)，不过并没有找到有效的内容

### Reply：请检查以下开关是否打开：
![image](https://github.com/mirai-mamori/Sakurairo/assets/87865570/d625396a-e376-431f-89de-bac7c74d0fb6)
#### 如果该方案无效建议在服务端自建简易api服务以应用多端分离效果，或者可以使用[Sakurairo主题文档推荐的API接口](https://docs.fuukei.org/Sakurairo/Homepage/#%E9%9A%8F%E6%9C%BA%E5%9B%BE%E8%AE%BE%E7%BD%AE)~

**Comment by LonePheasantWarrior** [comment]
> > 我的`主页设置`/`封面设置`/`封面随即图片选项`设置为`本地` 此时横屏访问场景下一切OK，但是到了竖屏场景下画面就怪怪的
> > 我尝试在`/wp-content/themes/Sakurairo-2.6.3.1/manifest/gallary/`下创建了个`mobile`文件夹，在其下放了一些竖屏的图片，但并没有被使用。 随后将竖屏图片和横屏图片一起放在了`/wp-content/themes/Sakurairo-2.6.3.1/manifest/gallary/`，期望站点可以根据图片的横竖比例来自适应当前访问场景，不过并没有这样。
> > 目前我没有找到一个合适的在`本地`设置场景下有一个桌面端和移动端都能兼顾的设置方案，烦请大佬指点一下！ 当然我也有看文档[Theme-Sakurairo](https://docs.fuukei.org/Sakurairo/Homepage/#%E9%9A%8F%E6%9C%BA%E5%9B%BE%E8%AE%BE%E7%BD%AE)，不过并没有找到有效的内容
> 
> ### Reply：请检查以下开关是否打开：
> ![image](https://private-user-images.githubusercontent.com/87865570/346317376-d625396a-e376-431f-89de-bac7c74d0fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTI0NDgsIm5iZiI6MTcyMzAxMjE0OCwicGF0aCI6Ii84Nzg2NTU3MC8zNDYzMTczNzYtZDYyNTM5NmEtZTM3Ni00MzFmLTg5ZGUtYmFjN2M3NGQwZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA2MjkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZTM2YTA5N2Q2N2Y3NTNhMDZjZjVhNTNhYTJmOTg0NmQ1ODU3NGU4ZGIyMDcyMWIxOGE2MDg2NGM3NmZiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0oXhBx2qnS071_-f3AKWuhQPDp4k0NPWch7E_vfuOLs)
> 
> #### 如果该方案无效建议在服务端自建简易api服务以应用多端分离效果，或者可以使用[Sakurairo主题文档推荐的API接口](https://docs.fuukei.org/Sakurairo/Homepage/#%E9%9A%8F%E6%9C%BA%E5%9B%BE%E8%AE%BE%E7%BD%AE)~

我注意到`封面随机图片多终端分离`开关仅能作用于外部API封面图场景,不适用`本地`封面图场景
