### ISSUE TITLE
去除已经生成的AI摘要

### ISSUE THREAD

**Issue by mlmk6698** [mirai-mamori/Sakurairo#898]
我需要去除历史文章已经生成的AI文章摘要(我使用排除文章功能并不起效),故请求帮助

**Comment by KotoriK** [comment]
如果您需要自己编写文章摘要，可以直接编写，自己编写的摘要会自动替换AI摘要。
https://github.com/mirai-mamori/Sakurairo/blob/c94fec3f13384fb0f5fe2164456f6626ec363739/tpl/content-thumb.php#L115
如果你要删除已经生成的AI摘要，你需要清空post_meta中```ai_summon_excerpt```这个key的值
https://github.com/mirai-mamori/Sakurairo/blob/c94fec3f13384fb0f5fe2164456f6626ec363739/inc/chatgpt/hooks.php#L14

**Comment by mlmk6698** [comment]
感谢，目前已经解决了这个问题
