### ISSUE TITLE
代码高亮控制台打印warn信息：Uncaught (in promise)  code-highlight.js:216

### ISSUE THREAD

**Issue by BigdataZjk** [mirai-mamori/Sakurairo#900]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

![042d74fad75798e746c32534ab0395e9](https://github.com/mirai-mamori/Sakurairo/assets/77384483/a879557f-aa56-4473-b14a-c9724527e2cb)

**实际行为描述：**

没有直接影响

**预期的行为：**

不出现这个warn提示

**复现步骤：**

新建一个有代码块的文章，打开文章，进入浏览器控制台

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4
- 数据库类型 / 版本：Mysql 8.0
- WordPress 版本：6.5.4
- 主题版本：2.6.3.1 
- 使用的插件：WP Fastest Cache
- 浏览器：Microsoft Edge 版本 125.0.2535.67 (正式版本) (x86_64)
**截图（若有）**

![c9eca8496c8a8995116c7d52163b3123](https://github.com/mirai-mamori/Sakurairo/assets/77384483/bcc8ef52-3f02-4f3c-b227-8d74949f594c)

**补充信息：**

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
这个已经修过了 https://github.com/Fuukei/Sakurairo_Scripts/commit/8e8571eb8dc95c614887278900918e89e3d70d37
可以等新更新
