### ISSUE TITLE
文章封面随机图重复刷新

### ISSUE THREAD

**Issue by Yish1** [mirai-mamori/Sakurairo#902]
**问题出处：**

当点击“更早的文章”按钮后，之前已加载的文章封面随机图会重复刷新

**配置与环境：**

- 问题页面：https://cmxz.top
- PHP top：8.2
- WordPress 版本：6.5.4
- 主题版本：当前最新preview分支
- 浏览器：Edge Beta 127.0.2651.5

**截图（若有）**
群里发了视频，或者cmxz.top首页能复现

**补充信息：**

提供尽可能多的相关信息。

**Comment by kanodaisuki** [comment]
在主题的图片懒加载实现中，当图片从可视窗口外重新回到可视窗口内时，都会触发一次doLoad 方法，重新设置图片的src属性，详见：
https://github.com/KotoriK/lazyload/blob/efc7a1b081d4b865788600a7403126564247dfbd/src/lazyload.ts#L89-L92

重新设置src属性，意味着浏览器会再次请求图片资源，从你的API响应头上看，你没有给图片资源设置缓存，缓存头被设置成了`Cache-Control: no-cache, no-store, must-revalidate`，这会导致浏览器忽略缓存，重新请求图片资源。

![image](https://github.com/mirai-mamori/Sakurairo/assets/79365334/f8d2dcfa-14d8-4a7f-b746-1273149e7f13)

对于同一个URL，你的图片API会返回不同的图片，所以从视觉上看，已经加载的文章封面随机图会重新加载，即封面图片发生了改变。

总的来说，出现这个问题的主要原因可能是doLoad 方法不够完善，在设置src之前，或许应检查图片是否已经完成了lazyload：

```js
if (tagName === 'video') {
    if (src && element.src !== src) {
        element.src = src;
    }
} else if (tagName === 'img') {
    if (src && element.src !== src) {
        element.src = src;
    }
    if (srcset && element.srcset !== srcset) {
        element.srcset = srcset;
    }
}
```

@KotoriK

**Comment by Yish1** [comment]
感谢！在启用api缓存后，确实不会重复加载了
![image](https://github.com/mirai-mamori/Sakurairo/assets/101796381/b5a9cfb1-08a2-4c02-9fea-dd9062ca9922)

**Comment by KotoriK** [comment]
> 在主题的图片懒加载实现中，当图片从可视窗口外重新回到可视窗口内时，都会触发一次doLoad 方法，重新设置图片的src属性，详见： https://github.com/KotoriK/lazyload/blob/efc7a1b081d4b865788600a7403126564247dfbd/src/lazyload.ts#L89-L92
> 
> 重新设置src属性，意味着浏览器会再次请求图片资源，从你的API响应头上看，你没有给图片资源设置缓存，缓存头被设置成了`Cache-Control: no-cache, no-store, must-revalidate`，这会导致浏览器忽略缓存，重新请求图片资源。
> 
> ![image](https://private-user-images.githubusercontent.com/79365334/342007778-f8d2dcfa-14d8-4a7f-b746-1273149e7f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTY3MTMsIm5iZiI6MTcxOTE5NjQxMywicGF0aCI6Ii83OTM2NTMzNC8zNDIwMDc3NzgtZjhkMmRjZmEtMTRkOC00YTdmLWI3NDYtMTI3MzE0OWU3ZjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyMzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZGM3MjRiY2ZiOGIzMzY2ZTFhN2YwZjI1NTA3MDUwNTY2M2IwYmQ3MjE0YmEzMWY3MTc2MTU5NzA5MzdjYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GDH1VOdO5iGOrghhlmQ9jA59AiOSEjY5EXm0ln318Go)
> 
> 对于同一个URL，你的图片API会返回不同的图片，所以从视觉上看，已经加载的文章封面随机图会重新加载，即封面图片发生了改变。
> 
> 总的来说，出现这个问题的主要原因可能是doLoad 方法不够完善，在设置src之前，或许应检查图片是否已经完成了lazyload：
> 
> ```js
> if (tagName === 'video') {
>     if (src && element.src !== src) {
>         element.src = src;
>     }
> } else if (tagName === 'img') {
>     if (src && element.src !== src) {
>         element.src = src;
>     }
>     if (srcset && element.srcset !== srcset) {
>         element.srcset = srcset;
>     }
> }
> ```
> 
> @KotoriK

确实 这段代码是直接抄upstream的没看，现在才发现他这个删除根本没删

**Comment by Yish1** [comment]
请问在Sakurairo_Scripts中的修改是需要webpack打包之后再替换Sakurairo里面的js文件吗？

**Comment by kanodaisuki** [comment]
> 请问在Sakurairo_Scripts中的修改是需要webpack打包之后再替换Sakurairo里面的js文件吗？

是的
