### ISSUE TITLE
是否可以加入Cloudflare Turnstile支持

### ISSUE THREAD

**Issue by sciencekiller** [mirai-mamori/Sakurairo#906]
目前只支持自建验证码和Vaptcha，但是Cloudflare Turnstile是一个很好的选择，并且我相信已经有插件实现了这个功能，Simple Cloudflare Turnstile，但是当它与本主题同时使用时，貌似会被页面重写掉，能否加一个机制，引入Cloudflare Turnstile进行机器人验证，官方的文档很齐全，应该不存在太大的问题

**Comment by KotoriK** [comment]
欢迎pr！
