### ISSUE TITLE
应用主题后无法写文章

### ISSUE THREAD

**Issue by LCXlichengxuan** [mirai-mamori/Sakurairo#907]
应用主题后，无法进入后台的写文章页面（https://url/wp-admin/post-new.php）
有时提示502，有时提示404，有时干脆无法访问...

使用主题时有此问题，更改为wp默认主题后问题消失。

- PHP 版本：7.4
- 数据库类型 / 版本：mysql
- WordPress 版本：6.5.5
- 主题版本：2.6.3.1
- 使用的插件：Pinyin Slugs，取消也没用
- 浏览器：edge，chrome等都试过了

**Comment by LCXlichengxuan** [comment]
111

**Comment by KotoriK** [comment]
你需要提供具体的报错信息

**Comment by LCXlichengxuan** [comment]
![image](https://github.com/mirai-mamori/Sakurairo/assets/138630227/a44fd432-1b08-493e-b011-c7430cf9a03e)

**Comment by KotoriK** [comment]
ERR_CONNECTION_RESET都还没到HTTP这层呢，检查下两边的网络先

**Comment by Sualiu** [comment]
可以看一下服务器那边的错误日志或者提供一下更具体完整的操作过程描述，这样很难判断原因，不利于解决问题。

**Comment by LCXlichengxuan** [comment]
location /
{
	 try_files $uri $uri/ /index.php?$args;
}

rewrite /wp-admin$ $scheme://$host$uri/ permanent;

**Comment by KotoriK** [comment]
> 我也遇到了，其他什么页面都能打开，就写文章打不开

试一下上述解决方案
