### ISSUE TITLE
在加入Markdown插件后，代码块和Katex无法共存的问题

### ISSUE THREAD

**Issue by WUYINAN-666** [mirai-mamori/Sakurairo#908]
**问题出处：**

文章中的代码块以及Katex公式

**实际行为描述：**

第一次加载时，代码块显示正常，Katex不渲染。刷新后，Katex渲染，代码块不正常。
触发问题后造成了什么效果及影响？

**预期的行为：**

均正常显示

**复现步骤：**

网址：https://jcjr.cloudns.ch/2024/07/07/%e9%a2%98%e8%a7%a3%ef%bc%9a%e7%ac%a6%e5%8d%a1%e5%88%b6%e4%bd%9c/
插件：WP Editor.md

**配置与环境：**

- 问题页面：[（如果有，请提供一个触发此问题的页面链接）](https://jcjr.cloudns.ch/2024/07/07/%e9%a2%98%e8%a7%a3%ef%bc%9a%e7%ac%a6%e5%8d%a1%e5%88%b6%e4%bd%9c/)
PHP 版本 | 8.1.29 （支持 64 位数值）
- 数据库类型 / 版本：mysql 8.0.35
- WordPress 版本：6.5.5
- 主题版本：（Release 标注的版本号）2.6.31
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）WP Editor.md
- 浏览器：（浏览器名称及版本号）Chrome

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
现在好像没问题？

**Comment by WUYINAN-666** [comment]
> 现在好像没问题？

咦，我那个链接还是有问题的呀
代码块被显示成一行了

**Comment by KotoriK** [comment]
it works on my machine
![image](https://github.com/user-attachments/assets/d119c68a-5858-4c53-aa07-985ac92c90b7)

**Comment by KotoriK** [comment]
你提到的Katex不渲染是因为开启了PJAX，而Katex渲染所需的JS插件没有在PJAX完成后渲染导致的
解决方案：
1. Katex转为服务端渲染
2. 关闭PJAX
3. 主题目前自带[MathML](https://developer.mozilla.org/en-US/docs/Web/MathML)支持，可以将Katex转换成MathML

不过MathML挺长的效率不高，如果有合适的HTML markup可以主题这边统一做渲染支持

**Comment by KotoriK** [comment]
代码块变成一行的原因没有解明，猜测可能是关键CSS缺失导致的，多刷新就好了

**Comment by WUYINAN-666** [comment]
> 你提到的Katex不渲染是因为开启了PJAX，而Katex渲染所需的JS插件没有在PJAX完成后渲染导致的 解决方案：
> 
> 1. Katex转为服务端渲染
> 2. 关闭PJAX
> 3. 主题目前自带[MathML](https://developer.mozilla.org/en-US/docs/Web/MathML)支持，可以将Katex转换成MathML
> 
> 不过MathML挺长的效率不高，如果有合适的HTML markup可以主题这边统一做渲染支持
> 代码块变成一行的原因没有解明，猜测可能是关键CSS缺失导致的，多刷新就好了

其实Katex渲染刷新一下就好的，问题不大
主要是代码块在我这边怎么刷新显示都是异常的
![image](https://github.com/user-attachments/assets/6aa136ee-747a-4c55-909b-27f99c97cded)
如图所示

也许是些玄学问题，不过还是谢谢大佬，抽空回复我的issue

**Comment by WUYINAN-666** [comment]
> 代码块变成一行的原因没有解明，猜测可能是关键CSS缺失导致的，多刷新就好了

我发现，在markdown中编写代码块时将
` ```cpp `
改为只有
` ``` `
就可以解决该问题
![image](https://github.com/user-attachments/assets/320c0cfa-b896-4679-9e60-5f7f27257276)
->
![image](https://github.com/user-attachments/assets/6718d680-479b-4695-b9ad-1e0bddb98cfd)
但是这样一来，一是我的markdown编辑器没法正确识别代码块
二是文章中显示的代码块无法正确识别语言

![image](https://github.com/user-attachments/assets/0844707b-4991-4af9-a2c0-4d886bb87d3d)
