### ISSUE TITLE
aplayer的优化

### ISSUE THREAD

**Issue by GavinIves** [mirai-mamori/Sakurairo#91]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**

现有内容的优化 ， 用户体验

**这个想法具体是要实现什么？**
在后台管理增加aplayer自动播放和显示歌词的开关（我改了自动播放后需要打开aplayer界面才会有歌词，否则只会播放歌曲不会放歌词）

**这个想法实现后有什么帮助？**
有些人可能想要自动播放音乐，比如我哈哈哈哈哈哈哈，每次需要去js里面改，更新主题后又需要重新改，挺麻烦的

**是否有具体的实现思路？**
通过php更改属性 这个你肯定比我在行 歌词修改js里面的hide变成show就行

**补充信息：**

**Comment by mirai-mamori** [comment]
现代浏览器基本都已经禁止了网页自动播放的行为，因此不考虑添加此功能。
