### ISSUE TITLE
启用主题后 提示Deprecated: Creation of dynamic property CSF_Field_slider::$unique is deprecated

### ISSUE THREAD

**Issue by xingyunlee12138** [mirai-mamori/Sakurairo#910]
PHP 8.2 MSQL8.0 ,ARM64架构服务器，
具体如下
Deprecated: Creation of dynamic property CSF_Field_slider::$value is deprecated in www/wwwroot/kanna.best/wp-content/themes/Sakurairo/opt/classes/fields.class.php on line 16
![1](https://github.com/user-attachments/assets/6a2fd9d8-bc60-4a62-98b3-b6f272b25a81)

**Comment by Sualiu** [comment]
当前正式发布版本[2.6.3.1](https://github.com/mirai-mamori/Sakurairo/releases/tag/2.6.3.1) 不支持PHP8.0及以上版本，推荐使用的是PHP7.4。此问题已在开发预览版本当中修复。

**Comment by KotoriK** [comment]
https://github.com/mirai-mamori/Sakurairo/issues/866#issuecomment-2026450451
