### ISSUE TITLE
博客的首页文章排版问题

### ISSUE THREAD

**Issue by yumo509** [mirai-mamori/Sakurairo#913]
![QQ截图20240804021417](https://github.com/user-attachments/assets/3a9e636d-8623-4918-9965-5f8aca4494b1)
如图所示，首页的文章排版会出现这样的随机图片+文章+摘要遮挡了其他内容，并且从菜单的分类目录进入查看当前分类目录的文章时也会遇到一样的情况，遮挡的位置大致上跟首页的位置差不多。

**Comment by kanodaisuki** [comment]
对于摘要，或许应该加个过滤器去除所有HTML标签。

**Comment by KotoriK** [comment]
> 对于摘要，或许应该加个过滤器去除所有HTML标签。

什么情况下摘要会被塞HTML标签啊

**Comment by kanodaisuki** [comment]
> > 对于摘要，或许应该加个过滤器去除所有HTML标签。
> 
> 什么情况下摘要会被塞HTML标签啊

@yumo509 你的文章是怎么排版的，贴一下编辑器的截图

**Comment by mirai-mamori** [comment]
可以看看新版会不会这样
