### ISSUE TITLE
code-highlight.js:228报错“__ is not defined”

### ISSUE THREAD

**Issue by letao9370** [mirai-mamori/Sakurairo#915]
①问题出处：code-highlight.js:228报错“__ is not defined”，文件来源“webpack://sakurairo-scripts/src/common/code-highlight.js”

②这个问题出在程序的哪一个具体功能？

    实际行为描述：代码格式化显示模块，应该用于实现复制代码功能但是“复制”按钮消失

③触发问题后造成了什么效果及影响？

    预期的行为：“复制”按钮出现，点击即可复制代码

④这个功能应该有怎样的效果和影响？

    复现步骤：安装Sakurairo主题，使用code-highlight.js并插入任何代码即可

    怎样才能再次触发这个问题？安装Sakurairo主题，使用code-highlight.js并插入任何代码即可

⑤配置与环境：

    - 问题页面：（如果有，请提供一个触发此问题的页面链接）
    - PHP 版本：PHP 8.0
    - 数据库类型 / 版本：MySQL 5.7
    - WordPress 版本： 6.6.1
    - 主题版本：2.6.3.1
    - 使用的插件：Limit Login Attempts Reloaded, Smush, WP Super Cache
    - 浏览器：Chrome 127.0.6533.120

⑥截图（若有）

![image](https://github.com/user-attachments/assets/62d36297-4352-4faa-aaf0-36f1f6cec91a)

![image](https://github.com/user-attachments/assets/6f66c4ed-33fa-415e-83c0-52951fe534da)

⑦补充信息：与“https://github.com/mirai-mamori/Sakurairo/issues/900”问题类似但错误位置不同

**Comment by kanodaisuki** [comment]
你给的信息很详细，这是值得肯定的。但是在提出问题前，你应该先搜索以下有没有类似的问题已经被提出。

#874 #868 #811 

这个问题已经被修复，只是还没有推送到正式版，等待更新即可。或者你可以尝试测试版：https://github.com/mirai-mamori/Sakurairo/tree/preview
