### ISSUE TITLE
请问安装主题后，预览主题就一屏 Deprecated: Creation of dynamic property CSF_Field_slider::$value is deprecated 报错

### ISSUE THREAD

**Issue by kinaito** [mirai-mamori/Sakurairo#917]
已确认过issue，同样安装的其他主题只有sakura出现一样的问题，

**问题出处：**

主题-主题预览

**实际行为描述：**

启动预览就出现
![image](https://github.com/user-attachments/assets/a70f441e-08f8-4646-85ed-5ac50e15511e)

**预期的行为：**
正常预览、设置主题

**复现步骤：**

每次在主题页面预览都会

**配置与环境：**

- 问题页面：由于在本地无法提供
- PHP 版本：8.2.12
- 数据库类型 / 版本：MariaDB 10.4.32
- WordPress 版本：6.61
- 主题版本：2.6.3.1
- 使用的插件：无
- 浏览器：Chrome

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by kinaito** [comment]
补充：sakura主题也是启动时会报错
![image](https://github.com/user-attachments/assets/bba64fc5-a22d-4d35-9aee-15656b731318)

**Comment by KotoriK** [comment]
https://github.com/mirai-mamori/Sakurairo/issues/866#issuecomment-2026450451

**Comment by KotoriK** [comment]
> 补充：sakura主题也是启动时会报错 ![image](https://private-user-images.githubusercontent.com/27257553/363490424-bba64fc5-a22d-4d35-9aee-15656b731318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTMyNzUsIm5iZiI6MTcyNTI1Mjk3NSwicGF0aCI6Ii8yNzI1NzU1My8zNjM0OTA0MjQtYmJhNjRmYzUtYTIyZC00ZDM1LTlhZWUtMTU2NTZiNzMxMzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA0NTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxN2E5ZDU3MGQyYmFjMzBlOTFkY2RjMzI0NTVhYWYzZjczNWU1Y2ZmMTc0MDJhZWZhOGRlN2IxMTBkODE0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.agORxwrpI0MMrm_TfJ296o7KwxbQaybCBLzyECm6WkI)

Sakura这段报错和Sakurairo的成因并不一致，影响程度也不一样。一般而言 Deprecation 消息可以忽略
