### ISSUE TITLE
首页文章区域的『自定义展示内容』想法

### ISSUE THREAD

**Issue by CGangel** [mirai-mamori/Sakurairo#918]
目前为止的版本，主题设置--主页--文章区域设置中，能自定义展示的似乎只有『作者信息』。（如下图）
![image](https://github.com/user-attachments/assets/9c6764ca-2854-4931-996a-0d6e5fb13ee3)

加上『作者信息』后，从主页看，文章标题下方，从左到右展示的信息依次为『作者信息』『热度』『评论』『分类』（如下图）
![image](https://github.com/user-attachments/assets/83c8118a-edce-4154-8274-7c2891d6c903)

不可否认的是，这样的风格确实很美观，但是个人感觉，还可以更细致一点。『热度』『评论』这些信息……说实话，作用有限。相反的是，方便读者快速查询文章的『标签』却无法展示，只有点进文章后，才能在文章末尾查看到，岂不是本末倒置？

————以下是个人想法————

1. 支持在主页的文章区域中新增『标签』的展示。 

2. 支持在主题设置中调整文章区域的『自定义展示内容』，比如上文提到的『作者信息』『热度』『标签』......之类的，可以单独选择是否展示它们中的每一个，并自定义展示的顺序。至于可能很长的『标签』，为了不影响显示效果，可以放在底部展示。具体实现效果，可以参考隔壁的某主题（如下图）
![image](https://github.com/user-attachments/assets/401dc4c5-768f-4341-96ab-fdc17e3c9a4d)
![image](https://github.com/user-attachments/assets/9b4c0791-7825-46a4-9327-097648d34061)

咱就一电脑小白，代码写不了一点，靠自己实现上面的功能是不可能的，还望大佬细细地把饭喂到嘴里吃（bushi）

**Comment by KotoriK** [comment]
LGTM
TODO: 
- [ ] 增加选项，在文章列表显示文章标签
- [ ] 支持文章元数据显示顺序更改

**Comment by KotoriK** [comment]
方便问一下相关主题是哪个主题嘛？可以看看文章元数据部分能不能无缝对接

**Comment by CGangel** [comment]
> 方便问一下相关主题是哪个主题嘛？可以看看文章元数据部分能不能无缝对接

是指issue里的“隔壁某主题”吗？主题名叫“Argon”，小有名气
