### ISSUE TITLE
请求添加 LaTeX 渲染功能

### ISSUE THREAD

**Issue by d0j1a1701** [mirai-mamori/Sakurairo#919]
**这是什么方面的想法？**

新增功能

**这个想法具体是要实现什么？**

使用 KaTeX/MathJax 实现 $\LaTeX$ 公式渲染

**这个想法实现后有什么帮助？**

可以在博客中显示公式

**是否有具体的实现思路？**

引入 katex.js / Mathjax.js 即可

**补充信息：**

可使用以下格式标记公式：

行内：$E=mc^2$

块级：
$$E = mc^2$$

**Comment by KotoriK** [comment]
https://github.com/Fuukei/Sakurairo_Scripts/commit/2a0d0e34e0350f9955eda3a2c251d2dca5b85366
