### ISSUE TITLE
有关文章协议与页面剪切板版权提示方面不一致的问题

### ISSUE THREAD

**Issue by ChiyoYuki** [mirai-mamori/Sakurairo#934]
**大致范围：**

文章协议与页面剪切板版权提示方面的问题

我不知道问题所牵连到的文件或是在文件的哪一行

**具体行为描述：**

在主题设置`文章主题设置->页面设置->文章页面设置->文章扩展区->文章协议选项`中选择其他 **非** `CC BY-NC-SA 4.0`的选项并保存后，开启`文章主题设置->页面设置->综合设置->页面剪切板版权提示`开关，在文章界面复制超过30字节的文字，剪切板中仍会出现

```
# 商业转载请联系作者获得授权，非商业转载请注明出处。
# For commercial use, please contact the author for authorization. For non-commercial use, please indicate the source.
# 协议(License)：署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)
# 作者(Author)：千代有希
# 链接(URL)：https://chiyoyuki.uk/wordpress/index.php/2024-10-09_00:23:01/330/
# 来源(Source)：空と海
```

字样。即协议一栏仍保持为`CC BY-NC-SA 4.0`。

**尝试：**

尝试在主题设置界面寻找页面剪切板版权提示的自定义文本选项，但没有找到

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8.2.20
- 数据库类型 / 版本：类型：MariaDB 服务端版本：10.11.6-MariaDB-0+deb12u1 客户端版本：mysqlnd 8.2.20
- WordPress 版本：6.6.2
- 主题版本：2.7.0
- 使用的插件：Simple Local Avatars，WordPress 导入工具，WP Fastest Cache，WP Githuber MD，WP Mail SMTP，你好多莉
- 浏览器：Chrome 129.0.6668.100（正式版本） （64 位）

**截图（若有）**

**补充信息：**

无

**Comment by KotoriK** [comment]
还真是 忘了这茬了

**Comment by KotoriK** [comment]
我建议是剪切板提示里面以后就放以下内容：

1. 复制的内容
2. 作者名
3. 网站名
4. 永久链接
也许还可以加上访问日期和发表日期？
上述内容也可以参考论文引文的格式附注。首先语言中立，不必再写双语的标语，另外也更简洁一些（删的时候比较好删
然后版权提示可以考虑移除掉，毕竟文章页的函数栏已经有了明确提示
不知道大家怎么看

**Comment by mirai-mamori** [comment]
我没意见
