### ISSUE TITLE
主题页面一直有do的声音，这是为什么？？？？？

### ISSUE THREAD

**Issue by mmjon** [mirai-mamori/Sakurairo#938]
主题页面一直有do的声音，这是为什么？？？？？

**Comment by mirai-mamori** [comment]
链接

Outlook for iOS<https://aka.ms/o0ukef> を入手
________________________________
差出人: github-actions[bot] ***@***.***>
送信日r: Thursday, October 17, 2024 10:55:13 AM
宛先: mirai-mamori/Sakurairo ***@***.***>
CC: Subscribed ***@***.***>
件名: Re: [mirai-mamori/Sakurairo] 主题页面一直有do的声音，这是为什么？？？？？ (Issue #938)


任何人都可以处理此问题。
请务必在您的 pull request 中引用此问题。
感谢你的贡献! (obb)o☆

―

**Comment by mmjon** [comment]
找到了，好像是这玩意的问题，把这个关了就行了
![image](https://github.com/user-attachments/assets/d974ee40-30f8-473a-920a-6b2255ca15f3)

**Comment by mirai-mamori** [comment]
那你自己关issue吧

Outlook for iOS<https://aka.ms/o0ukef> を入手
________________________________
差出人: mmjon ***@***.***>
送信日r: Thursday, October 17, 2024 11:03:34 AM
宛先: mirai-mamori/Sakurairo ***@***.***>
CC: 染川瞳 ***@***.***>; Comment ***@***.***>
件名: Re: [mirai-mamori/Sakurairo] 主题页面一直有do的声音，这是为什么？？？？？ (Issue #938)


找到了，好像是这玩意的问题，把这个关了就行了
image.png (view on web)<https://github.com/user-attachments/assets/d974ee40-30f8-473a-920a-6b2255ca15f3>

―
