### ISSUE TITLE
追剧列表后续加载提示 404

### ISSUE THREAD

**Issue by SiberiaHusky** [mirai-mamori/Sakurairo#940]
**问题出处：**

追剧列表模板

**实际行为描述：**

点击_NEXT_按钮后提示 ERROR 404

**预期的行为：**

与追番列表一样加载后续的节目

**复现步骤：**

点击_NEXT_按钮

**配置与环境：**

- 问题页面：[追剧列表](http://log.hooskai.top/drama/)
- PHP 版本：8.2.11
- 数据库类型 / 版本：MariaDB 10.3.27
- WordPress 版本：6.6.2
- 主题版本：（Release 标注的版本号）：2.7.0
- 使用的插件：无
- 浏览器：Microsoft Edge 130.0.2849.46

**Comment by mirai-mamori** [comment]
已修复
