### ISSUE TITLE
表情包无法加载的问题

### ISSUE THREAD

**Issue by TheShy-Dream** [mirai-mamori/Sakurairo#950]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：**

涉及表情包加载的问题，可能在functions.php文件里

**具体行为描述：**

bilibili和贴吧的相关表情包无法加载

**尝试：**

目前的解决方案是copy其他页面的emoji文件转化为webp放到指定路径，但是不是长久之计，还是希望跟版本统一，从指定url加载

**配置与环境：**

- 问题页面：可以点击[此页面](http://sunshychen.top/2024/10/20/%e6%b4%97%e8%84%91%e4%b8%8e%e6%95%99%e8%82%b2%e7%9a%84%e5%8c%ba%e5%88%ab%e6%98%af%e4%bb%80%e4%b9%88%ef%bc%9f/)进入评论区表情的页面获取具体情况，
- PHP 版本：7.4.15
- 数据库类型 / 版本：
- WordPress 版本：
- 主题版本：2.7.1
- 使用的插件：已经禁用了所有
- 浏览器：chrome 129.0.6668.101（正式版本） （64 位）

**截图（若有）**

![image](https://github.com/user-attachments/assets/b549cf91-90fc-41bf-80d5-8050f844f3c2)

**补充信息：**
我看到了functions.php中从制定url加载相关代码，但是我这个还是静态的从服务器路径加载，不知道什么原因或者如何修改，然后在服务器对应路径没有找到这里的webp文件。
提供尽可能多的相关信息。

**Comment by TheShy-Dream** [comment]
可以点击[此页面](http://sunshychen.top/2024/10/20/%e6%b4%97%e8%84%91%e4%b8%8e%e6%95%99%e8%82%b2%e7%9a%84%e5%8c%ba%e5%88%ab%e6%98%af%e4%bb%80%e4%b9%88%ef%bc%9f/)进入评论区表情的页面获取具体情况，

**Comment by mirai-mamori** [comment]
表情包根据在视觉资源路径中填写的地址加载 如果想要添加表情包请使用对应的相关功能
如果自定义了视觉资源请自己确保相关目录格式及文件是否存在
