### ISSUE TITLE
在更新主题后，gallary目录下所有图片被清空

### ISSUE THREAD

**Issue by IamXuWu** [mirai-mamori/Sakurairo#956]
**问题出处：**

这个问题出在程序的哪一个具体功能？
 iro 主题设置->主页设置->封面设置

**实际行为描述：**

触发问题后造成了什么效果及影响？
在更新主题后，gallary目录下所有图片被清空

**预期的行为：**

这个功能应该有怎样的效果和影响？
不应该被清空

**复现步骤：**

怎样才能再次触发这个问题？
放图片到gallary目录中，然后由旧版本更新到新版本。
**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- kyomu.me（我的博客，之后会把图片加上去所以应该不算问题了）
- PHP 版本：7.4.33
- 数据库类型 / 版本：mysql 5.7.44-cll-lve
- WordPress 版本：6.6.2
- 主题版本：（Release 标注的版本号）2.7.1.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
Akismet 反垃圾评论：垃圾评论保护
Autoptimize
EWWW Image Optimizer
Limit Login Attempts Reloaded
Rank Math SEO
WP Mail SMTP
WP Statistics
超级缓存
- 浏览器：（浏览器名称及版本号）
Google Chrome 117.0.5938.149

**截图（若有）**

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。
我从2.6.3.1更新到2.7.0出现了这个问题，然后从2.7.0更新到2.7.1.1也出现了这个问题。不知道是不是主题的bug？

**Comment by mirai-mamori** [comment]
这就是应该被清空的 如果想要不被清空 请找WP官方反馈或者手动覆盖升级
