### ISSUE TITLE
票券风格的摘要无法加载

### ISSUE THREAD

**Issue by xiaoka520** [mirai-mamori/Sakurairo#958]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**文章区域设置-卡片风格

这个问题出在程序的哪一个具体功能？

**实际行为描述：**无法加载摘要（wp自动摘取文章开头文字生成的摘要），但ai摘要可以加载

触发问题后造成了什么效果及影响？

**预期的行为：**正常加载摘要

这个功能应该有怎样的效果和影响？

**复现步骤：**

怎样才能再次触发这个问题？

**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）[https://listfx.top](https://listfx.top)
- PHP 版本：7.4.33
- 数据库类型 / 版本：8.2.0
- WordPress 版本：6.6.2
- 主题版本：（Release 标注的版本号）2.7.1.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）无
- 浏览器：（浏览器名称及版本号）Safari 15.8.2

**截图（若有）**
![E5178948-8DDD-4E84-8D62-77CFA23677B4](https://github.com/user-attachments/assets/04703da9-32d7-4e22-80cf-d90c61f5883d)
![1242D84D-6790-4992-A603-3AC808C4661E](https://github.com/user-attachments/assets/3326ac69-3773-40df-aa8a-51d755cddf66)

提供一个此问题触发的截图或报错信息。若没有，则留空。

**补充信息：**

提供尽可能多的相关信息。

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by mirai-mamori** [comment]
在贵站未发现问题

**Comment by xiaoka520** [comment]
> 在贵站未发现问题

我似乎忘记附上问题页面了：https://listfx.top  
但iOS上的Safari确实是有这问题
![7BBD89BE-26BF-4163-9033-CB7A4DC4FFDF](https://github.com/user-attachments/assets/6b7d5125-2f5b-416e-bd75-fdef010fb96e)

**Comment by mirai-mamori** [comment]
理论上已经修好了 可以等新版本发布以后看看 仍有问题可再次开启
