### ISSUE TITLE
追番模版源请求添加 Bangumi 番组计划

### ISSUE THREAD

**Issue by KyomuDesu** [mirai-mamori/Sakurairo#959]
**这是什么方面的想法？**

现有内容的优化

**这个想法具体是要实现什么？**
追番模版源请求添加 Bangumi 番组计划

**这个想法实现后有什么帮助？**
可以优化体验+国内挺多人用Bangumi的

**是否有具体的实现思路？**
有官方的API https://bangumi.github.io/api/

**补充信息：**
官网 bangumi.tv / bgm.tv

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by mirai-mamori** [comment]
无相关计划

**Comment by nicocatxzc** [comment]
https://github.com/mirai-mamori/Sakurairo/pull/1031

**Comment by KyomuDesu** [comment]
> #1031 @KyomuDesu

感谢
