### ISSUE TITLE
粒子特效开启后未显示

### ISSUE THREAD

**Issue by RainMz** [mirai-mamori/Sakurairo#964]
**问题出处：**

主题设置-全局设置-额外设置-粒子特效

**实际行为描述：**

开启后粒子特效不显示（已经按照教程开启了：封面与前台背景一体化选项；并且前台背景缩放方式改为了覆盖）

**预期的行为：**

网站正常显示粒子特效

**复现步骤：**

开启粒子特效即可复现

**配置与环境：**

- 问题页面：
- PHP 版本：8.2
- 数据库类型 / 版本：phpMyAdmin 版本信息： 5.2.0
- WordPress 版本：6.6.2
- 主题版本：2.7.1.1
- 使用的插件：Simple Custom CSS and JS
- 浏览器：chrome 129.0.6668.70

**截图（若有）**
无
**补充信息：**
无

**Comment by mirai-mamori** [comment]
已修复
