### ISSUE TITLE
文章目录显示优化

### ISSUE THREAD

**Issue by luinniuxx** [mirai-mamori/Sakurairo#967]
**这是什么方面的想法？**

文章目录比较紧凑, 看能不能优化或美观一下?

Sakurairo:
![image](https://github.com/user-attachments/assets/13778541-7cd4-431c-8341-f00b75586733)

下面是我参考其他一些主题文章目录的例子：

![image](https://github.com/user-attachments/assets/5b0a5199-f56c-4f86-8f2c-ab5465e17dd2)

![image](https://github.com/user-attachments/assets/f9d58637-a254-4fe4-99c4-7e3aec7eab3f)

**Comment by mirai-mamori** [comment]
稍微优化了一下
