### ISSUE TITLE
关于外部字体引用失败，但是又没完全失败

### ISSUE THREAD

**Issue by ShowUNow** [mirai-mamori/Sakurairo#972]
**大致范围：**
外部字体引用的问题

**具体行为描述：**
我已将我我下载的字体文件.ttf格式通过 [网站](https://transfonter.org/) 转换成了.woff2格式并生成了对应的css文件
（关于为何不用参考文档给出的网站：一个月48好贵消费不起qwq）

**你的问题具体是什么？**
使用的是这部分的功能
![image](https://github.com/user-attachments/assets/1a5b00f9-5c09-42f1-a301-521967d39f46)

[字体链接](https://cdn.tingyun.top/zt2/Showdex.woff2)
[字体对应的css链接](https://cdn.tingyun.top/zt2/stylesheet.css)

**尝试：**
在填写完对应的字体名称和链接之后，并且在
![image](https://github.com/user-attachments/assets/da57394f-f0d2-4f21-a992-3fbf2641ad3e)
这一部分使用该字体
在**Windows**、**Android**、**HarmonyOS**系统上均无法显示出指定的字体，如
![image](https://github.com/user-attachments/assets/b04d5a6a-e586-47e6-ba5c-527f768e9461)

但是在**iOS**系统上的浏览器就可以正常显示，已测试iPhone和iPad均可
![image](https://github.com/user-attachments/assets/3b4b3fb6-4565-48c4-93e9-f5711e0d2ac3)

**配置与环境：**

- 问题页面：[主页](https://tingyun.top/)
- PHP 版本：7.4
- 数据库类型 / 版本：mysql:5.7
- WordPress 版本：6.6.2
- 主题版本：2.7.2
- 使用的插件：Canvas-Nest.js、Google Analytics for WordPress by MonsterInsights、WordPress 导入工具、WP Statistics（逐一禁用后未发现是插件原因）
- 浏览器：Chrome（已尝试在除iOS设备上无痕模式下和我朋友电脑上均无法正确加载字体）

**补充信息：**
我已查阅了[参考文档](https://docs.fuukei.org/Sakurairo/Global/#%E5%AD%97%E4%BD%93%E8%AE%BE%E7%BD%AE)
我没太看明白引用的链接到底应该写https://cdn.tingyun.top/zt2/Showdex.woff2
还是https://cdn.tingyun.top/zt2/stylesheet.css
如果是写成第一种，那就是我上述所说的只有在iOS的设备上的浏览器可以正确加载字体
如果是写成第二种（我看参考文档好像是这个意思），那么所有设备都无法正确加载字体

也许我引用的不对，希望有大佬能够为我指点迷津，感激不尽！

**Comment by nicocatxzc** [comment]
![image](https://github.com/user-attachments/assets/732689b0-3056-4ef4-8743-cd71e35b2e30)
跨域资源调用问题，安卓、windows和华为的系统浏览器大多基于chromium，会严格遵守跨域资源调用的规则，

如果你使用的是nginx或者openrestry，
使用了cdn请自行在cdn提供商进行配置
请在静态资源服务器配置加上add_header Access-Control-Allow-Origin '*' always;以允许所有外部访问，具体限制访问请自行查找网络教程

**Comment by nicocatxzc** [comment]
如果不熟悉相关配置，把文件放到pages服务（比如github pages、cloudflare pages、netlify pages）或者您的wordpress的本站目录并引用也是一种选择

**Comment by ShowUNow** [comment]
> ![image](https://private-user-images.githubusercontent.com/114812330/382668172-732689b0-3056-4ef4-8743-cd71e35b2e30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDU1NDksIm5iZiI6MTczMDcwNTI0OSwicGF0aCI6Ii8xMTQ4MTIzMzAvMzgyNjY4MTcyLTczMjY4OWIwLTMwNTYtNGVmNC04NzQzLWNkNzFlMzViMmUzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNzI3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDkzODc3MjIwNGFkOThjY2VmOGZkM2E3MTdkMjhmMmQ1ZmNjMDNmZGE5OGJlMzMyYTRiMTQ0ZTc5NDQ0ZWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z5KeJ5pgLLXf1FighleMrx-x8s9TCYXOTrGJIAuA-p8) 跨域资源调用问题，安卓、windows和华为的系统浏览器大多基于chromium，会严格遵守跨域资源调用的规则，
> 
> 如果你使用的是nginx或者openresty， 请在静态资源服务器配置加上 add_header Access-Control-Allow-Origin '*' always; 以允许所有外部访问，具体限制域名访问请自行查找网络教程 示范： <img alt="屏幕截图 2024-11-04 152204" width="412" src="https://private-user-images.githubusercontent.com/114812330/382670793-bd86caf3-5188-4a6f-b0ea-1aae527ff7a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDU1NDksIm5iZiI6MTczMDcwNTI0OSwicGF0aCI6Ii8xMTQ4MTIzMzAvMzgyNjcwNzkzLWJkODZjYWYzLTUxODgtNGE2Zi1iMGVhLTFhYWU1MjdmZjdhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNzI3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGQ5MmM3ZjViM2NiMzBmNmVhMjlkNGExZmM4OGVhYTYyNDg5ZGZiNTcwMWZlNjI1YjM2ODgzNDQ3MjA4MDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Twr9hxUU3SF6hSrlobHXB1zq2k1l3wNuiOysIl177s0"> 使用了cdn请自行在cdn提供商进行配置


成功了！太感谢您了，这个问题困扰了我很久，查阅了很多资料和询问ai都无果。但是按照您说的在nginx配置中添加了
`add_header Access-Control-Allow-Origin '*' always;`
问题成功得以解决！

我还有一个小问题，如果您有空的话，能不能帮我查看一下我主页封面图的话的切换功能是否正常，图片的切换感觉并不丝滑。但是我调用的外部随机图库中的图片均为webp格式，每个图片文件的大小至少90%都在1MB以内，极少数会在2到3MB，并且已在nginx的配置中开启了接受跨域请求
```
 # 添加 CORS 头
        add_header Access-Control-Allow-Origin '*' always;
        add_header 'Access-Control-Allow-Origin' '*';  # 允许所有域访问
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';  # 允许的请求方法
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept';  # 允许的请求头

        # 处理 OPTIONS 请求
        if ($request_method = OPTIONS) {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept';
            add_header 'Content-Length' 0;
            return 204;  # 不返回内容
        }
```
并且提供图库的服务器为阿里云香港服务器，带宽1000Mbps，三网平均延迟都在50ms左右（如果您也不太清楚的话也无所谓，反正无伤大雅 :-)

**Comment by nicocatxzc** [comment]
![image](https://github.com/user-attachments/assets/c1957eb0-f9de-49a5-9096-572ec942dad4)
![image](https://github.com/user-attachments/assets/9ee770f2-10a4-4769-bab5-9b8d1f26d0f6)
这几个资源也标红了，你注意一下

**Comment by ShowUNow** [comment]
> ![image](https://private-user-images.githubusercontent.com/114812330/382977837-c1957eb0-f9de-49a5-9096-572ec942dad4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzIxNjQsIm5iZiI6MTczMDc3MTg2NCwicGF0aCI6Ii8xMTQ4MTIzMzAvMzgyOTc3ODM3LWMxOTU3ZWIwLWY5ZGUtNDlhNS05MDk2LTU3MmVjOTQyZGFkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQwMTU3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmM4ZTFkNWMxZGViYjM1NDI0MDk2MDc2NzA4MTFhNzBlNmQ2Yzc2ZmIxZTAxNTJhZDMwYmM4MGY0MGJjNjQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rJLRac0oPA_b4c3RdmjYqzKhQ3BKSdWOOsV_ylelsVY) ![image](https://private-user-images.githubusercontent.com/114812330/382977907-9ee770f2-10a4-4769-bab5-9b8d1f26d0f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzIxNjQsIm5iZiI6MTczMDc3MTg2NCwicGF0aCI6Ii8xMTQ4MTIzMzAvMzgyOTc3OTA3LTllZTc3MGYyLTEwYTQtNDc2OS1iYWI1LTliOGQxZjI2ZDBmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQwMTU3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTkxYWJkYmIwZmVmMjUyZGRjOWI4NTFiYWE5OTI1MzNmZTM5ZjAwZTZjNzRjYTRjMzQ4OTllNmJlN2QxZDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ITC0usw1HbcxFjZKsPk7J-PRcLV2IN4uWozvvjpVm7k) 这几个资源也标红了，你注意一下

谢谢解决了！原因是必须使用单独的域名而不能加路径，我通过手机端和桌面端使用两个不同的新域名成功地解决了这个问题。
不好意思计算机知识学艺不精，麻烦你了，谢谢 :-)
