### ISSUE TITLE
粒子特效开启后，鼠标和粒子特效的交互未生效

### ISSUE THREAD

**Issue by RainMz** [mirai-mamori/Sakurairo#973]
**问题出处：**

主题设置-全局设置-额外设置-粒子特效

**实际行为描述：**

开启粒子特效后，粒子特效和鼠标相关的交互不生效

**预期的行为：**

鼠标移动会和粒子特效进行交互

**复现步骤：**

使用带鼠标交互的粒子特效

**配置与环境：**

问题页面：
PHP 版本：8.2
数据库类型 / 版本：phpMyAdmin 版本信息： 5.2.0
WordPress 版本：6.6.2
主题版本：2.7.2
使用的插件：Simple Custom CSS and JS
浏览器：chrome 129.0.6668.70

**截图（若有）**

无

**补充信息：**

无

**Comment by mirai-mamori** [comment]
例子特效的层级在背景下方 没有交互是正常表现
