### ISSUE TITLE
文章评论区添加图片的按钮是不是错位了？以及评论框里里面的预设文字该怎么修改？

### ISSUE THREAD

**Issue by ShowUNow** [mirai-mamori/Sakurairo#976]
评论区开启了添加图片的功能，接口为https://sm.ms
**截图（若有）**
![image](https://github.com/user-attachments/assets/02a159ab-c069-49b8-9475-294be8473c72)
![image](https://github.com/user-attachments/assets/2d67a6d6-f5d6-478f-8cc4-8112408ee506)

**补充信息：**

使用的是最新版本的主题和wordpress，本人没有修改过评论区的源代码。经测试在Windows和手机（iOS)上均有错位情况。
[博客地址](https://tingyun.top)

**另外**
还想再问一下
![image](https://github.com/user-attachments/assets/c0948133-93b3-4e97-994b-afaf54c410ae)
评论框里里面的预设文字该怎么修改？是在comments.php文件里吗，没找到对应位置，求告知🙏

**Comment by nicocatxzc** [comment]
抱歉，经过测试没有在你的博客发现按钮和图片有错位的情况，可以提供一下具体复现过程吗，比如视频？

这个占位符确实太尬了，预计下个版本允许自定义

**Comment by ShowUNow** [comment]
> 抱歉，经过测试没有在你的博客发现按钮和图片有错位的情况，可以提供一下具体复现过程吗，比如视频？
> 
> 这个占位符确实太尬了，预计下个版本允许自定义


https://github.com/user-attachments/assets/49eda6b6-9f5a-4293-abd8-cd96c0225df7

可能是我描述的不够准确，我的意思是点击上传图片的图标并不能成功唤起该功能，而是需要点击这个图标右侧的空白区域才可以。并且这个现象在手机端也是如此

**Comment by nicocatxzc** [comment]
https://github.com/user-attachments/assets/b6c2d80f-045b-4f92-8ae1-87ba0539246f

经过测试貌似不存在问题，也许您需要提供更详细的复现方法
测试环境：<html>
<body>

Google Chrome | 130.0.6723.117 (正式版本) （64 位） (cohort: Stable)
-- | --
修订版本 | 37382504fe66965a688029d08706ddadca7ceb46-refs/branch-heads/6723@{#1765}
操作系统 | Windows 11 Version 23H2 (Build 22631.4391)
JavaScript | V8 13.0.245.18
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
命令行 | "C:\Program Files\Google\Chrome\Application\chrome.exe" --restart --flag-switches-begin --enable-features=BlockInsecurePrivateNetworkRequests --flag-switches-end
可执行文件路径 | C:\Program Files\Google\Chrome\Application\chrome.exe


</body>
</html>

**Comment by ShowUNow** [comment]
https://github.com/user-attachments/assets/70d9b07d-d9cc-42b5-b2f1-c481bee9c7b9


https://github.com/user-attachments/assets/f0a6f30a-51c3-43ca-ac0e-1714762c1920

https://github.com/user-attachments/assets/cf2f3737-2b7f-4c71-b9ea-20f2e831c086


@nicocatxzc 
**第一个视频中的浏览器为：**
Windows Chrome 已是最新版本
版本 130.0.6723.117（正式版本） （64 位）
Windows Microsoft Edge
版本 127.0.2651.105 (正式版本) (64 位)
iOS Chrome 版本为130.0.6723.90
iOS Safari版本号不会看（iOS 17.6.1）

**第二个视频中的浏览器为：**
Android 百度浏览器

**第三个视频中的浏览器为：**
微信内置浏览器

以及还测试了我朋友的vivo自带浏览器，也是图标错位。（未录视频）

以上情况均可在多个不同设备的同一操作系统的浏览器中复现。
**但是！**刚刚拿朋友的鸿蒙系统自带的浏览器测试，图标位置是正确的（_这下真的遥遥领先了_）
补充：
![屏幕截图1](https://github.com/user-attachments/assets/0fbb8ed4-e428-4a29-9051-d551416f5e7b)
![屏幕截图2](https://github.com/user-attachments/assets/0c8dbd1f-3c5a-449b-9cc6-0e697030abf8)
