### ISSUE TITLE
主页设置中 展示区域设置中 的链接部分要如何填写

### ISSUE THREAD

**Issue by 1nmyway** [mirai-mamori/Sakurairo#989]
> 注意，在求助的时候请描述清楚你的问题，并保持耐心
> 在你阅读过这段文本之后，就可以删除这段引用文本

**大致范围：**

关于主页设置中 展示区域设置中 的链接部分要如何填写，我试图将链接导向一个新页面，但是在wordpress添加页面时我发现页面直接添加在了主页面，我想要达到文章部分那样的效果，点击文章跳转另一个网页。

感激不尽。

**Comment by kanodaisuki** [comment]
> 关于主页设置中 展示区域设置中 的链接部分要如何填写

填写目标页面的浏览器地址栏中的地址就行。

> 我试图将链接导向一个新页面，但是在wordpress添加页面时我发现页面直接添加在了主页面

不是很明白你描述的内容。如果你的主页变成了页面而不是文章列表，这个可以在wordpress`设置` -> `阅读` -> `您的主页显示` 中调整。

**Comment by 1nmyway** [comment]
我在使用页面添加页面时，比如my_Introduction，我其实想让他显示在display展示区域里，通过点进展示区域进入到我的my_Introduction，就像文章一样，在wordpress里添加文章可以直接在主页面中点进对应文章进入，但是我发现他直接添加在了主页。关于目标页面的地址填写我不知道应该如何做，使用我的公网ip/my_Introduction没法访问
![屏幕截图 2024-11-17 114405](https://github.com/user-attachments/assets/6dce559e-5a20-42d7-a248-9c63f9506214)
/
[屏幕截图 2024-11-17 114454](https://github.com/user-attachments/assets/247a1831-92dd-4bef-b9ad-4b6a3837cb26)

![屏幕截图 2024-11-17 114604](https://github.com/user-attachments/assets/93d6eab8-1b00-4694-a8cf-7040d26b433c)

**Comment by 1nmyway** [comment]
![Uploading 屏幕截图 2024-11-17 114508.png…]()

**Comment by KotoriK** [comment]
> 使用我的公网ip/my_Introduction没法访问

这个问题你查一下WordPress如何配置固定链接（和你正在使用的服务器软件也有关系）
如果不懂的话还可以问问GPT
