### ISSUE TITLE
可不可以添加这样的二级菜单

### ISSUE THREAD

**Issue by WLTGH** [mirai-mamori/Sakurairo#990]
https://github.com/user-attachments/assets/718b3d24-ba68-46ba-8fba-51dfa6dd9c86

**Comment by nicocatxzc** [comment]
![image](https://github.com/user-attachments/assets/5d2dab5c-2c7d-4532-98da-fc17d36ca61b)
https://docs.fuukei.org/Sakurairo/Short-Code/#%E6%8A%98%E5%8F%A0%E4%BF%A1%E6%81%AF%E5%9D%97

文章、页面内可以使用内置短代码功能，导航菜单没必要
