### ISSUE TITLE
社交网络图标的webp文件在访问时返回404

### ISSUE THREAD

**Issue by Evil0ctal** [mirai-mamori/Sakurairo#992]
你好，在设置完社交网络后，打开主页时发现原本的图标文件无法显示，目前发现下面几个文件链接是返回404的：

- https://s.nmxc.ltd/sakurairo_vision/@2.7//github.webp
- https://s.nmxc.ltd/sakurairo_vision/@2.7//st.webp
- https://s.nmxc.ltd/sakurairo_vision/@2.7//tw.webp
- https://s.nmxc.ltd/sakurairo_vision/@2.7//mail.webp

截图：

![image](https://github.com/user-attachments/assets/b003d445-5a1d-4909-8455-b35e37328d50)

主题版本信息：

Sakurairo 主题版本 2.7.2 | 内部版本 19.2.0 |

**Comment by mirai-mamori** [comment]
自行重新设置图标包
