### ISSUE TITLE
评论区UA显示报错

### ISSUE THREAD

**Issue by Mtoly** [mirai-mamori/Sakurairo#994]
**问题出处：**

评论区评论显示UA部分

**实际行为描述：**

在ipad os 18.2下，使用Chrome，via，Safari最新版本进行评论，显示UA部分会报错
报错内容如下
Warning: Undefined array key 1 in /www/wwwroot/website/wp-content/themes/Sakurairo/inc/theme_plus.php on line 826   (  Safari 604   macOS XCheetah ) Warning: Undefined array key 1 in /www/wwwroot/website/wp-content/themes/Sakurairo/inc/theme_plus.php on line 826 

**配置与环境：**

- PHP 版本：8.2
- 数据库类型 / 版本：mysql8
- WordPress 版本：6.7.1
- 主题版本：2.7.2（Release 标注的版本号）
- 使用的插件：WP Githuber MD
WP Mail SMTP
经典编辑器（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：Chrome via Safari

**Comment by mirai-mamori** [comment]
请更换ip源为ipapi即可
