### ISSUE TITLE
我无法导入存放在本地目录内的自定义表情

### ISSUE THREAD

**Issue by Deepsea-CN** [mirai-mamori/Sakurairo#995]
> 注意，在报告之前请先确认：**你已经清除过浏览器 / CDN 缓存；你没有修改过相关源代码；你已经在本仓库的issue中搜索确认了没有其他人提过了类似的问题。**
> 在确定这的确是原项目中的问题之后，请删除这段文本，并继续报告。

**问题出处：**

添加自定义表情模块

**实际行为描述：**

按照文档输入目录地址后导入不了表情，扫描到0个图片

**预期的行为：**

正常添加表情

**复现步骤：**

仅测试本机无法添加

**配置与环境：**

略

**截图（若有）**

略

**补充信息：**
我把表情（.png后缀，权限www:www:777）放到uploads/emotion文件夹下，表情地址设置为../.././uploads/emotion，点击这里按钮提示导入0个表情

**Comment by kanodaisuki** [comment]
@Deepsea-CN 主题文档的描述与实际有一些出入，文件在`uploads/emotion`文件夹下的话，路径填写`/emotion`就可以了，详情可以先参考一下[这里](https://kanochan.net/archives/3449.html)，后面我们会更正文档。

**Comment by kanodaisuki** [comment]
> @kanodaisuki 有空看看
> 
> 可能`$custom_smilies_path`没读到文件夹时应该提供一些更详细的错误提示？

确实需要提示一下，放到列表刷新的输出里面好了

**Comment by Deepsea-CN** [comment]
> uploads/emotion

试了一下还是有问题，再确认了一下图片确实是能被访问的https://silverisky.com/wp-content/uploads/emotion/%E8%8A%B1.png
只填/emotion也是更新0个表情，尝试了../前后路径也不太行

**Comment by nicocatxzc** [comment]
经过测试，在preview版本中，默认起始目录就是/wp-content/uploads/
表情目录设置: /2024/10
会读取：/wp-content/uploads/2024/10

我编写文档使用的测试环境是windows+xampp（apache+php8.2+mysql8）
实际测试该方案可行的测试环境是linux+1panel+docker（openresty+php8.2+mysql8）

很抱歉对您造成了困扰，要不您先试试这个解决方法是否可行？

**Comment by Deepsea-CN** [comment]
看了调试信息终于发现问题了，是我理解问题，输入路径之后得先保存设置再点导入才能正确指向目录，因为我习惯几个栏目的设置全调好了一次保存，所以一直没注意这个问题，直接当他是动态识别的了...不好意思
正确路径确实如您所说，是在uploads下的目录名
调试信息：
- 表情目录设置为: /emotion
- 实际读取的路径为: /home/wwwroot/silverisky.com/wp-content/uploads/emotion
自定义表情列表更新完成！总共有15个表情。
